export type GeographicalIndicationEntry = {
  serial: string
  name: string
  type: string
  year: string
}

export type GeographicalIndicationStateGroup = {
  state: string
  items: readonly GeographicalIndicationEntry[]
}

export const geographicalIndicationByState: readonly GeographicalIndicationStateGroup[] = [
  {
    state: 'Andaman and Nicobar Islands',
    items: [
      {
        serial: '1',
        name: 'Andaman Karen Musley rice',
        type: 'Agricultural',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Andhra Pradesh',
    items: [
      {
        serial: '1',
        name: 'Srikalahasthi Kalamkari',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '2',
        name: 'Kondapalli bommallu',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '3',
        name: 'Machilipatnam Kalamkari',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '4',
        name: 'Budithi Bell and Brass Craft',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '5',
        name: 'Andhra Pradesh leather puppetry',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '6',
        name: 'Uppada Jamdani sarees',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '7',
        name: 'Tirupathi Laddu',
        type: 'Food stuff',
        year: '2009–10',
      },
      {
        serial: '8',
        name: 'Guntur Sannam Chilli',
        type: 'Agricultural',
        year: '2010–11',
      },
      {
        serial: '9',
        name: 'Venkatagiri Sarees',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '10',
        name: 'Bobbili Veena',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '11',
        name: 'Mangalagiri sarees and fabrics',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '12',
        name: 'Dharmavaram handloom pattu sarees and paavadas',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '13',
        name: 'Bandar Laddu',
        type: 'Food stuff',
        year: '2016–17',
      },
      {
        serial: '14',
        name: 'Udayagiri Wooden Cutlery',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '15',
        name: 'Durgi Stone Carvings',
        type: 'Handicrafts',
        year: '2017–18',
      },
      {
        serial: '16',
        name: 'Etikoppaka Toys',
        type: 'Handicrafts',
        year: '2017–18',
      },
      {
        serial: '17',
        name: 'Allagadda Stone Carving',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '18',
        name: 'Atreyapuram Pootharekulu',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '19',
        name: 'Narasapur Crochet Lace Products',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '20',
        name: 'Ponduru Khadi',
        type: 'Textiles',
        year: '2024-25',
      },
    ],
  },
  {
    state: 'Andhra Pradesh, Odisha',
    items: [
      {
        serial: '1',
        name: 'Araku Valley Arabica Coffee',
        type: 'Agricultural',
        year: '2018–19',
      },
    ],
  },
  {
    state: 'Arunachal Pradesh',
    items: [
      {
        serial: '1',
        name: 'Arunachal Orange',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '2',
        name: 'Idu Mishmi Textiles',
        type: 'Handicraft',
        year: '2019–20',
      },
      {
        serial: '3',
        name: 'Arunachal Pradesh Khaw Tai',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '4',
        name: 'Arunachal Pradesh Yak Churpi',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '5',
        name: 'Arunachal Pradesh Tangsa Textile Product',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '6',
        name: 'Arunachal Pradesh Handmade Carpet',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '7',
        name: 'Arunachal Pradesh Wancho Wooden Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '8',
        name: 'Arunachal Pradesh Adi Kekir',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '9',
        name: 'Arunachal Pradesh Apatani Textile',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '10',
        name: 'Arunachal Pradesh Monpa Textile',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '11',
        name: 'Arunachal Pradesh Nyishi Textile',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '12',
        name: 'Arunachal Pradesh Monpa Handmade Paper',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '13',
        name: 'Arunachal Pradesh Adi Textile',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '14',
        name: 'Arunachal Pradesh Galo Textile',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '15',
        name: 'Arunachal Pradesh Adi Apong',
        type: 'Manufactured',
        year: '2023–24',
      },
      {
        serial: '16',
        name: 'Arunachal Pradesh Dao',
        type: 'Manufactured',
        year: '2023–24',
      },
      {
        serial: '17',
        name: 'Arunachal Pradesh Angnyat Millet',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '18',
        name: 'Arunachal Pradesh Marua Apo',
        type: 'Manufactured',
        year: '2023–24',
      },
      {
        serial: '19',
        name: 'Arunachal Pradesh Tai Khamti Textile',
        type: 'Handicraft',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Arunachal Pradesh, Assam',
    items: [
      {
        serial: '1',
        name: 'Arunachal Pradesh Singpho Phalap',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '2',
        name: 'Assam Mishing Handloom Products',
        type: 'Handicraft',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Assam',
    items: [
      {
        serial: '1',
        name: 'Muga silk of Assam',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '2',
        name: 'Assam (orthodox)',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '3',
        name: 'Muga Silk of Assam (Logo)',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '4',
        name: 'Assam Karbi Anglong Ginger',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '5',
        name: 'Tezpur Litchi',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '6',
        name: 'Joha rice of Assam',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '7',
        name: 'Boka Chaul',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '8',
        name: 'Kaji Nemu',
        type: 'Agricultural',
        year: '2019–20',
      },
      {
        serial: '9',
        name: 'Chokuwa rice of Assam',
        type: 'Agricultural',
        year: '2019–20',
      },
      {
        serial: '10',
        name: 'Judima',
        type: 'Manufactured',
        year: '2021–22',
      },
      {
        serial: '11',
        name: 'Gamosa of Assam',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '12',
        name: 'Majuli Mask of Assam',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '13',
        name: 'Assam Majuli Manuscript Painting',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '14',
        name: 'Bodo Dokhona',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '15',
        name: 'Bodo Eri Silk',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '16',
        name: 'Bodo Jwmgra',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '17',
        name: 'Bodo Gamsa',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '18',
        name: 'Bodo Keradapini',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '19',
        name: 'Bodo Thorkha',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '20',
        name: 'Bodo Gongar Dunjia',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '21',
        name: 'Bodo Kham',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '22',
        name: 'Bodo Serja',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '23',
        name: 'Bodo Sifung',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '24',
        name: 'Bodo Khardwi',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '25',
        name: 'Bodo Gongona',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '26',
        name: 'Bodo Jotha',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '27',
        name: 'Assam Jaapi',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '28',
        name: 'Assam Asharikandi Terracotta Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '29',
        name: 'Assam Bihu Dhol',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '30',
        name: 'Assam Pani Meteka Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '31',
        name: 'Sarthebari Metal Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Bihar',
    items: [
      {
        serial: '1',
        name: 'Madhubani paintings',
        type: 'Handicraft',
        year: '2006–07',
      },
      {
        serial: '2',
        name: 'Applique (khatwa) work of Bihar',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '3',
        name: 'Sujini embroidery work of Bihar',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '4',
        name: 'Sikki Grass Products of Bihar',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '5',
        name: 'Bhagalpur silk',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '6',
        name: 'Applique (Khatwa) Work of Bihar (Logo)',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '7',
        name: 'Sikki Grass Products of Bihar (Logo)',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '8',
        name: 'Sujini Embroidery Work of Bihar (Logo)',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '9',
        name: 'Bhagalpuri Zardalu',
        type: 'Agricultural',
        year: '2017–18',
      },
      {
        serial: '10',
        name: 'Katarni Rice',
        type: 'Agricultural',
        year: '2017–18',
      },
      {
        serial: '11',
        name: 'Magahi Paan',
        type: 'Agricultural',
        year: '2017–18',
      },
      {
        serial: '12',
        name: 'Shahi Litchi of Bihar',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '13',
        name: 'Silao Khaja',
        type: 'Food stuff',
        year: '2018–19',
      },
      {
        serial: '14',
        name: 'Manjusha Art',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '15',
        name: 'Mithila Makhana',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '16',
        name: 'Marcha Rice',
        type: 'Agricultural',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Chhattisgarh',
    items: [
      {
        serial: '1',
        name: 'Bastar Dhokra',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '2',
        name: 'Bastar Wooden Craft',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '3',
        name: 'Bastar Iron Craft',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '4',
        name: 'Champa silk saree and fabrics',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '5',
        name: 'Bastar Dhokra (Logo)',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '6',
        name: 'Jeeraphool',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '7',
        name: 'Nagri Dubraj',
        type: 'Agricultural',
        year: '2022–23',
      },
    ],
  },
  {
    state: 'Germany',
    items: [
      {
        serial: '1',
        name: 'Münchener Bier',
        type: 'Manufactured',
        year: '2021–22',
      },
    ],
  },
  {
    state: 'Goa',
    items: [
      {
        serial: '1',
        name: 'Feni',
        type: 'Manufactured',
        year: '2008–09',
      },
      {
        serial: '2',
        name: 'Khola Chilli',
        type: 'Agricultural',
        year: '2019–20',
      },
      {
        serial: '3',
        name: 'Harmal Chilli',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '4',
        name: 'Myndoli Banana',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '5',
        name: 'Goan Khaje',
        type: 'Food stuff',
        year: '2021–22',
      },
      {
        serial: '6',
        name: 'Agsechi Vayingim (Agassaim Brinjal)',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '7',
        name: 'Sat Shiro Bheno',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '8',
        name: 'Goa Mankurad Mango',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '9',
        name: 'Goan Bebinca',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '10',
        name: 'Goa Cashew (Kaju or Caju)',
        type: 'Agricultural',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Gujarat',
    items: [
      {
        serial: '1',
        name: 'Sankheda Furniture',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '2',
        name: 'Agates of Cambay',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '3',
        name: 'Kutch Embroidery',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '4',
        name: 'Tangaliya Shawl',
        type: 'Handicraft',
        year: '2009–10',
      },
      {
        serial: '5',
        name: 'Surat Zari Craft',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '6',
        name: 'Gir Kesar Mango',
        type: 'Agricultural',
        year: '2011–12',
      },
      {
        serial: '7',
        name: 'Bhalia Wheat',
        type: 'Agricultural',
        year: '2011–12',
      },
      {
        serial: '8',
        name: 'Kachchh Shawls',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '9',
        name: 'Patan patola',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '10',
        name: 'Sankheda Furniture (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '11',
        name: 'Kutch Embroidery (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '12',
        name: 'Agates of Cambay (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '13',
        name: 'Jamnagari Bandhani',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '14',
        name: 'RajKot Patola',
        type: 'Handicraft',
        year: '2018–19',
      },
      {
        serial: '15',
        name: 'Pethapur Printing Blocks',
        type: 'Handicraft',
        year: '2018–19',
      },
      {
        serial: '16',
        name: 'Pithora',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '17',
        name: 'Mata ni Pachhedi',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '18',
        name: 'Kachchhi Kharek',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '19',
        name: 'Kutch Rogan Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '20',
        name: 'Ambaji White Marble',
        type: 'Natural',
        year: '2023–24',
      },
      {
        serial: '21',
        name: 'Kutch Bandhani',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '22',
        name: 'Gharchola Craft of Gujarat',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '23',
        name: 'Gujarat Suf Embroidery',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '24',
        name: 'Ahmedabad Sodagari Block Print',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '25',
        name: 'Surat Sadeli Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '26',
        name: 'Bharuch Sujani Weaving',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '27',
        name: 'Kutch Ajrakh',
        type: 'Handicraft',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Himachal Pradesh',
    items: [
      {
        serial: '1',
        name: 'Kullu Shawl',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '2',
        name: 'Kangra Tea',
        type: 'Agricultural',
        year: '2004–05',
      },
      {
        serial: '3',
        name: 'Chamba Rumal',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '4',
        name: 'Kinnauri Shawl',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '5',
        name: 'Kullu Shawl (Logo)',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '6',
        name: 'Kangra Paintings',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '7',
        name: 'Himachali Kala Zeera',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '8',
        name: 'Himachali Chulli Oil',
        type: 'Manufactured',
        year: '2018–19',
      },
      {
        serial: '9',
        name: 'Chamba Chappal',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '10',
        name: 'Lahauli Knitted Socks and Gloves',
        type: 'Handicraft',
        year: '2021–22',
      },
    ],
  },
  {
    state: 'Jammu and Kashmir',
    items: [
      {
        serial: '1',
        name: 'Kani Shawl',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '2',
        name: 'Kashmir Pashmina',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '3',
        name: 'Kashmir Sozani Craft',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '4',
        name: 'Kashmir paper machie',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '5',
        name: 'Kashmir Walnut Wood Carving',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '6',
        name: 'Khatamband',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '7',
        name: 'Kashmiri Hand Knotted Carpet',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '8',
        name: 'Kashmir Saffron',
        type: 'Agricultural',
        year: '2020–21',
      },
      {
        serial: '9',
        name: 'Basohli Painting',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '10',
        name: 'Mushqbudji Rice',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '11',
        name: 'Rajouri Chikri Wood Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '12',
        name: 'Bhaderwah Rajmash',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '13',
        name: 'Ramban Sulai Honey',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '14',
        name: 'Basohli Pashmina Woolen Products',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '15',
        name: 'Udhampur Kaladi',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '16',
        name: 'Ramban Anardana',
        type: 'Agricultural',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Jharkhand',
    items: [
      {
        serial: '1',
        name: 'Sohrai – Khovar Painting',
        type: 'Handicraft',
        year: '2020–21',
      },
    ],
  },
  {
    state: 'Karnataka',
    items: [
      {
        serial: '1',
        name: 'Mysore silk',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '2',
        name: 'Mysore Agarbathi',
        type: 'Manufactured',
        year: '2004–05',
      },
      {
        serial: '3',
        name: 'Bidriware',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '4',
        name: 'Channapatna toys and dolls',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '5',
        name: 'Mysore Rosewood Inlay',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '6',
        name: 'Mysore Sandalwood Oil',
        type: 'Manufactured',
        year: '2004–05',
      },
      {
        serial: '7',
        name: 'Mysore Sandal soap',
        type: 'Manufactured',
        year: '2004–05',
      },
      {
        serial: '8',
        name: 'Kasuti embroidery',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '9',
        name: 'Mysore Traditional Paintings',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '10',
        name: 'Coorg orange',
        type: 'Agricultural',
        year: '2004–05',
      },
      {
        serial: '11',
        name: 'Mysore betel leaf',
        type: 'Agricultural',
        year: '2006–07',
      },
      {
        serial: '12',
        name: 'Nanjanagud Banana',
        type: 'Agricultural',
        year: '2006–07',
      },
      {
        serial: '13',
        name: 'Mysore Malligae',
        type: 'Agricultural',
        year: '2007–08',
      },
      {
        serial: '14',
        name: 'Udupi Malligae',
        type: 'Agricultural',
        year: '2007–08',
      },
      {
        serial: '15',
        name: 'Hadagali Malligae',
        type: 'Agricultural',
        year: '2007–08',
      },
      {
        serial: '16',
        name: 'Ilkal sarees',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '17',
        name: 'Ganjifa Cards of Mysore',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '18',
        name: 'Navalgund Durries',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '19',
        name: 'Karnataka Bronzeware',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '20',
        name: 'Molakalmuru sarees',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '21',
        name: 'Coorg Green Cardamom',
        type: 'Agricultural',
        year: '2007–08',
      },
      {
        serial: '22',
        name: 'Dharwad Pedha',
        type: 'Food stuff',
        year: '2008–09',
      },
      {
        serial: '23',
        name: 'Devanahalli Pomello',
        type: 'Agricultural',
        year: '2009–10',
      },
      {
        serial: '24',
        name: 'Appemidi Mango',
        type: 'Agricultural',
        year: '2009–10',
      },
      {
        serial: '25',
        name: 'Kamalapur Red Banana',
        type: 'Agricultural',
        year: '2009–10',
      },
      {
        serial: '26',
        name: 'Sandur Lambani Embroidery',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '27',
        name: 'Byadagi chilli',
        type: 'Agricultural',
        year: '2010–11',
      },
      {
        serial: '28',
        name: 'Udupi Mattu Gulla Brinjal',
        type: 'Agricultural',
        year: '2011–12',
      },
      {
        serial: '29',
        name: 'Kinhal toys',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '30',
        name: 'Bangalore Blue Grapes',
        type: 'Agricultural',
        year: '2012–13',
      },
      {
        serial: '31',
        name: 'Bangalore Rose Onion',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '32',
        name: 'Karnataka Bronzeware (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '33',
        name: 'Ganjifa Cards of Mysore (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '34',
        name: 'Navalgund Durries (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '35',
        name: 'Guledgudd Khana',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '36',
        name: 'Udupi sarees',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '37',
        name: 'Mysore Silk (Logo)',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '38',
        name: 'Coorg Arabica Coffee',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '39',
        name: 'Chikmagalur Arabica Coffee',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '40',
        name: 'Bababudangiri Arabica Coffee',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '41',
        name: 'Sirsi Supari',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '42',
        name: 'Gulbarga Tur Dal',
        type: 'Agricultural',
        year: '2019–20',
      },
      {
        serial: '43',
        name: 'Indi Limbe',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '44',
        name: 'Kari Ishad Mango',
        type: 'Agricultural',
        year: '2022–23',
      },
    ],
  },
  {
    state: 'Karnataka, Kerala',
    items: [
      {
        serial: '1',
        name: 'Monsooned Malabar Arabica Coffee',
        type: 'Agricultural',
        year: '2007–08',
      },
      {
        serial: '2',
        name: 'Monsooned Malabar Robusta Coffee',
        type: 'Agricultural',
        year: '2007–08',
      },
    ],
  },
  {
    state: 'Kerala',
    items: [
      {
        serial: '1',
        name: 'Aranmula Kannadi',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '2',
        name: 'Alleppey Coir',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '3',
        name: 'Navara rice',
        type: 'Agricultural',
        year: '2007–08',
      },
      {
        serial: '4',
        name: 'Palakkadan Matta rice',
        type: 'Agricultural',
        year: '2007–08',
      },
      {
        serial: '5',
        name: 'Maddalam of Palakkad',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '6',
        name: 'Screw Pine Craft of Kerala',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '7',
        name: 'Brass Broidered Coconut Shell Crafts of Kerala',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '8',
        name: 'Pokkali Rice',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '9',
        name: 'Vazhakulam pineapple',
        type: 'Agricultural',
        year: '2009–10',
      },
      {
        serial: '10',
        name: 'Cannanore Home Furnishings',
        type: 'Handicraft',
        year: '2009–10',
      },
      {
        serial: '11',
        name: 'Balaramapuram sarees and fine cotton fabrics',
        type: 'Handicraft',
        year: '2009–10',
      },
      {
        serial: '12',
        name: 'Kasaragod sarees',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '13',
        name: 'Kuthampully sarees',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '14',
        name: 'Central Travancore Jaggery',
        type: 'Agricultural',
        year: '2010–11',
      },
      {
        serial: '15',
        name: 'Wayanad Jeerakasala rice',
        type: 'Agricultural',
        year: '2010–11',
      },
      {
        serial: '16',
        name: 'Wayanad Gandhakasala rice',
        type: 'Agricultural',
        year: '2010–11',
      },
      {
        serial: '17',
        name: 'Payyannur Pavithra Ring',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '18',
        name: 'Chendamangalam Dhoties and Set Mundu',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '19',
        name: 'Kaipad Rice',
        type: 'Agricultural',
        year: '2013–14',
      },
      {
        serial: '20',
        name: 'Chengalikodan Nendran Banana',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '21',
        name: 'Kuthampally Dhoties and Set Mundu',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '22',
        name: 'Maddalam of Palakkad (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '23',
        name: 'Brass Broidered Coconut Shell Craft of Kerala (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '24',
        name: 'Screw Pine Craft of Kerala (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '25',
        name: 'Nilambur Teak',
        type: 'Agricultural',
        year: '2017–18',
      },
      {
        serial: '26',
        name: 'Wayanaad Robusta Coffee',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '27',
        name: 'Marayoor Jaggery',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '28',
        name: 'Tirur Betel Leaf',
        type: 'Agricultural',
        year: '2019–20',
      },
      {
        serial: '29',
        name: 'Kuttiattoor Mango',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '30',
        name: 'Edayur Chilli',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '31',
        name: 'Attappady Aattukombu Avara',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '32',
        name: 'Attappady Thuvara',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '33',
        name: 'Onattukara Ellu',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '34',
        name: 'Kanthalloor Vattavada Veluthulli',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '35',
        name: 'Kodungallur Pottuvellari',
        type: 'Agricultural',
        year: '2022–23',
      },
    ],
  },
  {
    state: 'Kerala, Karnataka, Tamil Nadu',
    items: [
      {
        serial: '1',
        name: 'Malabar pepper',
        type: 'Agricultural',
        year: '2007–08',
      },
    ],
  },
  {
    state: 'Ladakh',
    items: [
      {
        serial: '1',
        name: 'Ladakh Raktsey Karpo Apricot',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '2',
        name: 'Pashmina Wool of Ladakh',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '3',
        name: 'Ladakh Shingskos',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '4',
        name: 'Ladakh Seabuckthorn',
        type: 'Agricultural',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Madhya Pradesh',
    items: [
      {
        serial: '1',
        name: 'Chanderi sarees',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '2',
        name: 'Leather Toys of Indore',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '3',
        name: 'Bagh Prints of Madhya Pradesh',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '4',
        name: 'Bell Metal Ware of Datia and Tikamgarh',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '5',
        name: 'Maheshwari Saree and fabrics',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '6',
        name: 'Bell Metal Ware of Datia and Tikamgarh (Logo)',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '7',
        name: 'Leather Toys of Indore (Logo)',
        type: 'Handicraft',
        year: '2014–15',
      },
      {
        serial: '8',
        name: 'Ratlami Sev',
        type: 'Food stuff',
        year: '2014–15',
      },
      {
        serial: '9',
        name: 'Bagh Prints of Madhya Pradesh (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '10',
        name: 'Jhabua Kadaknath Black Chicken Meat',
        type: 'Food stuff',
        year: '2018–19',
      },
      {
        serial: '11',
        name: 'Balaghat Chinnor',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '12',
        name: 'Morena Gajak',
        type: 'Food stuff',
        year: '2022–23',
      },
      {
        serial: '13',
        name: 'Rewa Sunderja Mango',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '14',
        name: 'Sharbati Gehu',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '15',
        name: 'Gond Painting of Madhya Pradesh',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '16',
        name: 'Wrought Iron Crafts of Dindori',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '17',
        name: 'Ujjain Batik Print',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '18',
        name: 'Gwalior Handmade Carpet',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '19',
        name: 'Waraseoni handloom saree and fabrics',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '20',
        name: 'Jabalpur Stone Craft',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '21',
        name: 'Ratlam Riyawan Lahsun',
        type: 'Agricultural',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Maharashtra',
    items: [
      {
        serial: '1',
        name: 'Solapuri chaddar',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '2',
        name: 'Solapur Terry Towel',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '3',
        name: 'Puneri Pagadi',
        type: 'Handicraft',
        year: '2009–10',
      },
      {
        serial: '4',
        name: 'Nashik valley wine',
        type: 'Manufactured',
        year: '2010–11',
      },
      {
        serial: '5',
        name: 'Paithani sarees and fabrics',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '6',
        name: 'Mahabaleshwar Strawberry',
        type: 'Agricultural',
        year: '2010–11',
      },
      {
        serial: '7',
        name: 'Nashik Grapes',
        type: 'Agricultural',
        year: '2010–11',
      },
      {
        serial: '8',
        name: 'Kolhapur Jaggery',
        type: 'Agricultural',
        year: '2013–14',
      },
      {
        serial: '9',
        name: 'Ajara Ghansal Rice',
        type: 'Agricultural',
        year: '2015–16',
      },
      {
        serial: '10',
        name: 'Mangalwedha Jowar',
        type: 'Agricultural',
        year: '2015–16',
      },
      {
        serial: '11',
        name: 'Sindhudurg and Ratnagiri Kokum',
        type: 'Agricultural',
        year: '2015–16',
      },
      {
        serial: '12',
        name: 'Waghya Ghevada',
        type: 'Agricultural',
        year: '2015–16',
      },
      {
        serial: '13',
        name: 'Navapur Tur Dal',
        type: 'Agricultural',
        year: '2015–16',
      },
      {
        serial: '14',
        name: 'Vengurla Cashew',
        type: 'Agricultural',
        year: '2015–16',
      },
      {
        serial: '15',
        name: 'Lasalgaon Onion',
        type: 'Agricultural',
        year: '2015–16',
      },
      {
        serial: '16',
        name: 'Sangli Raisins',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '17',
        name: 'Beed Custard Apple',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '18',
        name: 'Jalna Sweet Orange',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '19',
        name: 'Waigaon Turmeric',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '20',
        name: 'Purandar Fig',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '21',
        name: 'Jalgaon Bharit Brinjal',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '22',
        name: 'Solapur Pomegranate',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '23',
        name: 'Bhiwapur Chilli',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '24',
        name: 'Ambemohar Rice',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '25',
        name: 'Dahanu Gholvad Chikoo',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '26',
        name: 'Jalgaon Banana',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '27',
        name: 'Marathwada Kesar Mango',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '28',
        name: 'Karvath Kati sarees and fabrics',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '29',
        name: 'Alphonso mango',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '30',
        name: 'Sangli Turmeric',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '31',
        name: 'Alibag White Onion',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '32',
        name: 'Bhandara Chinoor Rice',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '33',
        name: 'Sawantwadi Ganjifa Cards',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '34',
        name: 'Vasmat Haldi (Turmeric)',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '35',
        name: 'Nandurbar Amchur',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '36',
        name: 'Nandurbar Mirchi',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '37',
        name: 'Miraj Tanpura',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '38',
        name: 'Hupari Silver Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '39',
        name: 'Miraj Sitar',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '40',
        name: 'Sawantwadi Wooden Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '41',
        name: 'Panchincholi Tamarind',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '42',
        name: 'Borsuri Tur Dal',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '43',
        name: 'Kasti Coriander',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '44',
        name: 'Badlapur Jamun',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '45',
        name: 'Bahadoli Jamun',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '46',
        name: 'Pen Ganesh Idol',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '47',
        name: 'Kunthalgiri Khawa',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '48',
        name: 'Kavdi Maal of Tuljapur',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '49',
        name: 'Dagdi Jowar of Jalna',
        type: 'Agricultural',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Maharashtra, Gujarat',
    items: [
      {
        serial: '1',
        name: 'Warli Painting',
        type: 'Handicraft',
        year: '2013–14',
      },
    ],
  },
  {
    state: 'Maharashtra, Karnataka',
    items: [
      {
        serial: '1',
        name: 'Kolhapuri Chappal',
        type: 'Handicraft',
        year: '2018–19',
      },
    ],
  },
  {
    state: 'Maharashtra, Madhya Pradesh',
    items: [
      {
        serial: '1',
        name: 'Nagpur Orange',
        type: 'Agricultural',
        year: '2013–14',
      },
    ],
  },
  {
    state: 'Manipur',
    items: [
      {
        serial: '1',
        name: 'Shaphee Lanphee',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '2',
        name: 'Wangkhei Phee',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '3',
        name: 'Moirang Phee',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '4',
        name: 'Kachai Lemon',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '5',
        name: 'Tamenglong Orange',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '6',
        name: 'Sirarakhong Hathei chilli',
        type: 'Agricultural',
        year: '2021–22',
      },
    ],
  },
  {
    state: 'Manipur, Nagaland',
    items: [
      {
        serial: '1',
        name: 'Chak-Hao',
        type: 'Agricultural',
        year: '2019–20',
      },
    ],
  },
  {
    state: 'Meghalaya',
    items: [
      {
        serial: '1',
        name: 'Khasi Mandarin',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '2',
        name: 'Memong Narang',
        type: 'Agricultural',
        year: '2015–16',
      },
      {
        serial: '3',
        name: 'Lakadong Turmeric',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '4',
        name: 'Meghalaya Garo Textile',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '5',
        name: 'Meghalaya Lyrnai Pottery',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '6',
        name: 'Meghalaya Chubitchi',
        type: 'Manufactured',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Mizoram',
    items: [
      {
        serial: '1',
        name: 'Mizo Chilli',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '2',
        name: 'Pawndum',
        type: 'Handicraft',
        year: '2019–20',
      },
      {
        serial: '3',
        name: 'Ngotekherh',
        type: 'Handicraft',
        year: '2019–20',
      },
      {
        serial: '4',
        name: 'Hmaram',
        type: 'Handicraft',
        year: '2019–20',
      },
      {
        serial: '5',
        name: 'Tawlhlohpuan',
        type: 'Handicraft',
        year: '2019–20',
      },
      {
        serial: '6',
        name: 'Mizo Puanchei',
        type: 'Handicraft',
        year: '2019–20',
      },
      {
        serial: '7',
        name: 'Mizo Ginger',
        type: 'Agricultural',
        year: '2021–22',
      },
    ],
  },
  {
    state: 'Nagaland',
    items: [
      {
        serial: '1',
        name: 'Naga Mircha',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '2',
        name: 'Naga Tree Tomato',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '3',
        name: 'Chakshesang Shawl',
        type: 'Handicrafts',
        year: '2017–18',
      },
      {
        serial: '4',
        name: 'Naga Cucumber',
        type: 'Agricultural',
        year: '2021–22',
      },
    ],
  },
  {
    state: 'Odisha',
    items: [
      {
        serial: '1',
        name: 'Kotpad Handloom fabrics',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '2',
        name: 'Orissa Ikat',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '3',
        name: 'Konark stone carving',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '4',
        name: 'Orissa Pattachitra',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '5',
        name: 'Pipli Applique Work',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '6',
        name: 'Khandua saree and fabrics',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '7',
        name: 'Gopalpur Tussar Fabrics',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '8',
        name: 'Ganjam Kewda Rooh',
        type: 'Manufactured',
        year: '2011–12',
      },
      {
        serial: '9',
        name: 'Ganjam Kewda Flower',
        type: 'Agricultural',
        year: '2011–12',
      },
      {
        serial: '10',
        name: 'Dhalapathar Parda & Fabrics',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '11',
        name: 'Sambalpuri bandha saree and fabrics',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '12',
        name: 'Bomkai saree and fabrics',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '13',
        name: 'Habaspuri saree and fabrics',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '14',
        name: 'Berhampur Patta (phoda kumbha) saree and joda',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '15',
        name: 'Orissa Pattachitra (Logo)',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '16',
        name: 'Kandhamal Haladi',
        type: 'Agricultural',
        year: '2019–20',
      },
      {
        serial: '17',
        name: 'Odisha Rasagola',
        type: 'Food stuff',
        year: '2019–20',
      },
      {
        serial: '18',
        name: 'Kendrapara Rasabali',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '19',
        name: 'Odisha Khajuri Guda',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '20',
        name: 'Dhenkanal Magji',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '21',
        name: 'Similipal Kai Chutney of Odisha',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '22',
        name: 'Nayagarh Kanteimundi Brinjal',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '23',
        name: 'Kapadaganda: Dungaria Kondh Embroidery Shawl',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '24',
        name: 'Koraput Kalajeera Rice',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '25',
        name: 'Painting of Lanjia Saura, Odisha',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '26',
        name: 'Cuttack Rupa Tarakasi',
        type: 'Handicraft',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Pondicherry',
    items: [
      {
        serial: '1',
        name: 'Villianur Terracotta Works',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '2',
        name: 'Tirukanur Papier Mache Craft',
        type: 'Handicraft',
        year: '2011–12',
      },
    ],
  },
  {
    state: 'Portugal',
    items: [
      {
        serial: '1',
        name: 'Porto',
        type: 'Manufactured',
        year: '2011–12',
      },
      {
        serial: '2',
        name: 'Douro',
        type: 'Manufactured',
        year: '2011–12',
      },
    ],
  },
  {
    state: 'Punjab, Haryana, Himachal Pradesh, Delhi, Uttarkhand, Uttar Pradesh, Jammu and Kashmir',
    items: [
      {
        serial: '1',
        name: 'Basmati',
        type: 'Agricultural',
        year: '2015–16',
      },
    ],
  },
  {
    state: 'Punjab, Haryana, Rajasthan',
    items: [
      {
        serial: '1',
        name: 'Phulkari',
        type: 'Handicraft',
        year: '2010–11',
      },
    ],
  },
  {
    state: 'Rajasthan',
    items: [
      {
        serial: '1',
        name: 'Kota Doria',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '2',
        name: 'Blue Pottery of Jaipur',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '3',
        name: 'Molela Clay Work',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '4',
        name: 'Kathputlis of Rajasthan',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '5',
        name: 'Sanganeri hand block printing',
        type: 'Handicraft',
        year: '2009–10',
      },
      {
        serial: '6',
        name: 'Bikaneri Bhujia',
        type: 'Food stuff',
        year: '2010–11',
      },
      {
        serial: '7',
        name: 'Kota Doria (logo)',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '8',
        name: 'Bagru Hand Block Print',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '9',
        name: 'Thewa Art Work',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '10',
        name: 'Makrana Marble',
        type: 'Natural Goods',
        year: '2014–15',
      },
      {
        serial: '11',
        name: 'Molela Clay Work of Rajasthan (Logo)',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '12',
        name: 'Blue Pottery of Jaipur (Logo)',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '13',
        name: 'Kathputlis of Rajasthan (Logo)',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '14',
        name: 'Pokaran Pottery',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '15',
        name: 'Sojat Mehndi',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '16',
        name: 'Nathdwara Pichhwai Painting',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '17',
        name: 'Udaipur Koftgari Metal Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '18',
        name: 'Bikaner Kashidakari Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '19',
        name: 'Jodhpur Bandhej Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '20',
        name: 'Bikaner Usta Kala Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Sikkim',
    items: [
      {
        serial: '1',
        name: 'Sikkim Large Cardamom',
        type: 'Agricultural',
        year: '2014–15',
      },
    ],
  },
  {
    state: 'Sikkim, West Bengal',
    items: [
      {
        serial: '1',
        name: 'Dalle Khursani',
        type: 'Agricultural',
        year: '2021–22',
      },
    ],
  },
  {
    state: 'Tamil Nadu',
    items: [
      {
        serial: '1',
        name: 'Salem fabric',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '2',
        name: 'Kancheepuram Silk',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '3',
        name: 'Bhavani Jamakkalam',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '4',
        name: 'Madurai Sungudi',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '5',
        name: 'Coimbatore Wet Grinder',
        type: 'Manufactured',
        year: '2004–05',
      },
      {
        serial: '6',
        name: 'Thanjavur Paintings',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '7',
        name: 'Temple Jewellery of Nagercoil',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '8',
        name: 'Thanjavur Art Plate',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '9',
        name: 'East India Leather',
        type: 'Manufactured',
        year: '2007–08',
      },
      {
        serial: '10',
        name: 'Salem Venpattu',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '11',
        name: 'Kovai Kora cotton sarees',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '12',
        name: 'Arani Silk',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '13',
        name: 'Swamimalai Bronze Icons',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '14',
        name: 'Eathomozhy Tall Coconut',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '15',
        name: 'Thanjavur Doll',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '16',
        name: 'Nilgiri (orthodox)',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '17',
        name: 'Virupakshi Hill Banana',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '18',
        name: 'Sirumalai Hill Banana',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '19',
        name: 'Madurai Malli',
        type: 'Agricultural',
        year: '2012–13',
      },
      {
        serial: '20',
        name: 'Pattamadai Mat',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '21',
        name: 'Nachiarkoil kuthuvilakku',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '22',
        name: 'Chettinad Kottan',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '23',
        name: 'Toda Embroidery',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '24',
        name: 'Thanjavur Veenai',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '25',
        name: 'Thanjavur Art Plate (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '26',
        name: 'Swamimalai Bronze Icons (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '27',
        name: 'Temple Jewellery of Nagercoil (Logo)',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '28',
        name: 'Mahabalipuram Stone Sculpture',
        type: 'Handicrafts',
        year: '2017–18',
      },
      {
        serial: '29',
        name: 'Erode Manjal',
        type: 'Agricultural',
        year: '2018–19',
      },
      {
        serial: '30',
        name: 'Thirubuvanam silk sarees',
        type: 'Handicraft',
        year: '2018–19',
      },
      {
        serial: '31',
        name: 'Kodaikanal Malai Poondu',
        type: 'Agricultural',
        year: '2019–20',
      },
      {
        serial: '32',
        name: 'Palani Panchamirtham',
        type: 'Food stuff',
        year: '2019–20',
      },
      {
        serial: '33',
        name: 'Dindigul Locks',
        type: 'Handicraft',
        year: '2019–20',
      },
      {
        serial: '34',
        name: 'Kandangi saree',
        type: 'Handicraft',
        year: '2019–20',
      },
      {
        serial: '35',
        name: 'Srivilliputtur Palkova',
        type: 'Food stuff',
        year: '2019–20',
      },
      {
        serial: '36',
        name: 'Kovilpatti Kadalai Mittai',
        type: 'Food stuff',
        year: '2019–20',
      },
      {
        serial: '37',
        name: 'Thanjavur Netti Works',
        type: 'Handicraft',
        year: '2020–21',
      },
      {
        serial: '38',
        name: 'Arumbavur Wood Carvings',
        type: 'Handicraft',
        year: '2020–21',
      },
      {
        serial: '39',
        name: 'Karuppur Kalamkari Paintings',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '40',
        name: 'Kallakurichi Wood Carving',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '41',
        name: 'Kanniyakumari Clove',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '42',
        name: 'Narasinghapettai Nagaswaram',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '43',
        name: 'Ramnathapuram Mundu Chilli',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '44',
        name: 'Vellore Spiny Brinjal',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '45',
        name: 'Myladi Stone Carvings',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '46',
        name: 'Manapparai Murukku',
        type: 'Food stuff',
        year: '2022–23',
      },
      {
        serial: '47',
        name: 'Ooty Varkey',
        type: 'Food stuff',
        year: '2022–23',
      },
      {
        serial: '48',
        name: 'Manamadurai Pottery',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '49',
        name: 'Thaikkal Rattan Craft',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '50',
        name: 'Salem Sago',
        type: 'Food stuff',
        year: '2022–23',
      },
      {
        serial: '51',
        name: 'Authoor Vetrilai',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '52',
        name: 'Cumbum Panneer Thratchai',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '53',
        name: 'Negamam cotton saree',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '54',
        name: 'Sholavandan Vetrilai',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '55',
        name: 'Marthandam Honey',
        type: 'Food stuff',
        year: '2022–23',
      },
      {
        serial: '56',
        name: 'Jaderi Namakatti',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '57',
        name: 'Kanyakumari Matti Banana',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '58',
        name: 'Chedibutta saree',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '59',
        name: 'Udangudi Panangkarupatti',
        type: 'Food stuff',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Tamil Nadu, Kerala',
    items: [
      {
        serial: '1',
        name: 'Alleppey Green Cardamom',
        type: 'Agricultural',
        year: '2007–08',
      },
    ],
  },
  {
    state: 'Telangana',
    items: [
      {
        serial: '1',
        name: 'Pochampally sari',
        type: 'Handicraft',
        year: '2004–05',
      },
      {
        serial: '2',
        name: 'Silver Filigree of Karimnagar',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '3',
        name: 'Nirmal toys and craft',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '4',
        name: 'Nirmal furniture',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '5',
        name: 'Nirmal paintings',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '6',
        name: 'Gadwal sarees',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '7',
        name: 'Hyderabad Haleem',
        type: 'Food stuff',
        year: '2010–11',
      },
      {
        serial: '8',
        name: 'Cheriyal Paintings',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '9',
        name: 'Pembarthi Metal Craft',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '10',
        name: 'Siddipet Gollabama',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '11',
        name: 'Narayanpet handloom sarees',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '12',
        name: 'Pochampally Ikat (Logo)',
        type: 'Handicrafts',
        year: '2017–18',
      },
      {
        serial: '13',
        name: 'Adilabad Dokra',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '14',
        name: 'Warangal Durries',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '15',
        name: 'Telia Rumal',
        type: 'Handicraft',
        year: '2020–21',
      },
      {
        serial: '16',
        name: 'Tandur Redgram',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '17',
        name: 'Hyderabad Lac Bangles',
        type: 'Handicraft',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Telangana, Andhra Pradesh',
    items: [
      {
        serial: '1',
        name: 'Banaganapalle Mangoes',
        type: 'Agricultural',
        year: '2017–18',
      },
    ],
  },
  {
    state: 'Tripura',
    items: [
      {
        serial: '1',
        name: 'Tripura Queen Pineapple',
        type: 'Agricultural',
        year: '2014–15',
      },
      {
        serial: '2',
        name: 'Tripura Risa Textile',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '3',
        name: 'Tripura Pachra-Rignai',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '4',
        name: 'Tripura Matabari Peda',
        type: 'Food stuff',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'United States of America',
    items: [
      {
        serial: '1',
        name: 'Napa Valley',
        type: 'Manufactured',
        year: '2010–11',
      },
    ],
  },
  {
    state: 'Uttar Pradesh',
    items: [
      {
        serial: '1',
        name: 'Allahabad Surkha guava',
        type: 'Agricultural',
        year: '2007–08',
      },
      {
        serial: '2',
        name: 'Lucknow Chikan Craft',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '3',
        name: 'Mango Malihabadi Dusseheri',
        type: 'Agricultural',
        year: '2009–10',
      },
      {
        serial: '4',
        name: 'Banaras brocades and sarees',
        type: 'Handicraft',
        year: '2009–10',
      },
      {
        serial: '5',
        name: 'Hand Made Carpet of Bhadohi',
        type: 'Handicraft',
        year: '2010–11',
      },
      {
        serial: '6',
        name: 'Agra Durrie',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '7',
        name: 'Farrukhabad Prints',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '8',
        name: 'Lucknow Zardozi',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '9',
        name: 'Banaras brocades and sarees (logo)',
        type: 'Handicraft',
        year: '2012–13',
      },
      {
        serial: '10',
        name: 'Kalanamak Rice',
        type: 'Agricultural',
        year: '2013–14',
      },
      {
        serial: '11',
        name: 'Firozabad Glass',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '12',
        name: 'Kannauj Perfume',
        type: 'Manufactured',
        year: '2013–14',
      },
      {
        serial: '13',
        name: 'Kanpur Saddlery',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '14',
        name: 'Moradabad Metal Craft',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '15',
        name: 'Saharanpur Wood Craft',
        type: 'Handicraft',
        year: '2013–14',
      },
      {
        serial: '16',
        name: 'Meerut Scissors',
        type: 'Manufactured',
        year: '2014–15',
      },
      {
        serial: '17',
        name: 'Khurja Pottery',
        type: 'Handicraft',
        year: '2014–15',
      },
      {
        serial: '18',
        name: 'Banaras Gulabi Meenakari Craft',
        type: 'Handicraft',
        year: '2014–15',
      },
      {
        serial: '19',
        name: 'Varanasi Wooden Lacquerware and Toys',
        type: 'Handicraft',
        year: '2014–15',
      },
      {
        serial: '20',
        name: 'Mirzapur Handmade Dari',
        type: 'Handicraft',
        year: '2014–2015',
      },
      {
        serial: '21',
        name: 'Nizamabad Black Pottery',
        type: 'Handicrafts',
        year: '2015–16',
      },
      {
        serial: '22',
        name: 'Banaras Metal Repouse Craft',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '23',
        name: 'Varanasi Glass beads',
        type: 'Handicrafts',
        year: '2016–17',
      },
      {
        serial: '24',
        name: 'Ghazipur Wall-hanging',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '25',
        name: 'Varanasi Soft Stone Jali Work',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '26',
        name: 'Chunar Balua Patthar',
        type: 'Natural',
        year: '2018–19',
      },
      {
        serial: '27',
        name: 'Gorakhpur Terracotta',
        type: 'Handicraft',
        year: '2019–20',
      },
      {
        serial: '28',
        name: 'Chunar Glaze Pottery',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '29',
        name: 'Banaras Zardozi',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '30',
        name: 'Mirzapur Pital Bartan',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '31',
        name: 'Banaras Wood Carving',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '32',
        name: 'Banaras Hand Block Print',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '33',
        name: 'Rataul Mango',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '34',
        name: 'Mau saree',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '35',
        name: 'Adamchini Chawal',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '36',
        name: 'Aligarh Tala',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '37',
        name: 'Bakhira Brassware',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '38',
        name: 'Banda Shazar Patthar craft',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '39',
        name: 'Nagina Wood Craft',
        type: 'Handicraft',
        year: '2022–23',
      },
      {
        serial: '40',
        name: 'Pratapgarh Aonla',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '41',
        name: 'Hathras Hing',
        type: 'Food stuff',
        year: '2022–23',
      },
      {
        serial: '42',
        name: 'Banaras Langda Aam',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '43',
        name: 'Ramnagar Bhanta',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '44',
        name: 'Muzaffarnagar Gur',
        type: 'Food stuff',
        year: '2022–23',
      },
      {
        serial: '45',
        name: 'Banaras Pan (Betel Leaf)',
        type: 'Agricultural',
        year: '2022–23',
      },
      {
        serial: '46',
        name: 'Mahoba Gaura Patthar Hastashlip',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '47',
        name: 'Mainpuri Tarkashi',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '48',
        name: 'Sambhal Horn Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '49',
        name: 'Amroha Dholak',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '50',
        name: 'Baghpat Home Furnishings',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '51',
        name: 'Barabanki Handloom Product',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '52',
        name: 'Kalpi Handmade Paper',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '53',
        name: 'Agra Leather Footwear',
        type: 'Manufactured',
        year: '2023–24',
      },
      {
        serial: '54',
        name: 'Jalesar Dhatu Shilp',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '55',
        name: 'Patchwork of Rampur',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '56',
        name: 'Mathura Sanjhi Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '57',
        name: 'Banaras Tabla',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '58',
        name: 'Banaras Lal Bharwamirch (Red Pickle Chilli)',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '59',
        name: 'Pilibhit Bansuri',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '60',
        name: 'Chiraigaon Karonda of Varanasi',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '61',
        name: 'Banaras Lal Peda',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '62',
        name: 'Banaras Shehnai',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '63',
        name: 'Sambhal Bone Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '64',
        name: 'Moonj Craft of Uttar Pradesh',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '65',
        name: 'Chitrakoot Wooden Craft and Toys',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '66',
        name: 'Jaunpur Imarti',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '67',
        name: 'Banaras Thandai',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '68',
        name: 'Banaras Mural Painting',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '69',
        name: 'Pilkhuwa Hand Block Print',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '70',
        name: 'Banaras Metal Casting Craft',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '71',
        name: 'Bareilly Cane and Bamboo',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '72',
        name: 'Tharu Embroidery',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '73',
        name: 'Bareilly Zari Zardoji',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '74',
        name: 'Banaras Tirangi Barfi',
        type: 'Food stuff',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Uttar Pradesh, Madhya Pradesh',
    items: [
      {
        serial: '1',
        name: 'Mahoba Desawari Pan',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '2',
        name: 'Bundelkhand Kathiya Gehu',
        type: 'Agricultural',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'Uttarakhand',
    items: [
      {
        serial: '1',
        name: 'Uttarakhand Tejpat',
        type: 'Agricultural',
        year: '2016–17',
      },
      {
        serial: '2',
        name: 'Bhotia Dann of Uttarakhand',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '3',
        name: 'Uttarakhand Aipan',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '4',
        name: 'Munsyari Razma',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '5',
        name: 'Uttarakhand Ringal Craft',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '6',
        name: 'Uttarakhand Tamta Product',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '7',
        name: 'Uttarakhand Thulma',
        type: 'Handicraft',
        year: '2021–22',
      },
      {
        serial: '8',
        name: 'Kumaon Chyura Oil',
        type: 'Agricultural',
        year: '2021–22',
      },
      {
        serial: '9',
        name: 'Uttarakhand Berinag Tea',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '10',
        name: 'Uttarakhand Bichhu Buti Fabrics',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '11',
        name: 'Uttarakhand Mandua',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '12',
        name: 'Uttarakhand Jhangora',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '13',
        name: 'Uttarakhand Gahat',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '14',
        name: 'Uttarakhand Lal Chawal',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '15',
        name: 'Uttarakhand Kala Bhat',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '16',
        name: 'Uttarakhand Malta Fruit',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '17',
        name: 'Uttarakhand Chaulai',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '18',
        name: 'Almora Lakhori Mirchi',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '19',
        name: 'Uttarakhand Buransh',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '20',
        name: 'Uttarakhand Pahari Toor Dal',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '21',
        name: 'Nainital Mombatti',
        type: 'Manufactured',
        year: '2023–24',
      },
      {
        serial: '22',
        name: 'Rangwali Pichhoda of Kumaon',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '23',
        name: 'Ramnagar Nainital Litchi',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '24',
        name: 'Ramgarh Nainital Aadu',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '25',
        name: 'Chamoli Wooden Ramman Mask',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '26',
        name: 'Uttarakhand Likhai',
        type: 'Handicraft',
        year: '2023–24',
      },
    ],
  },
  {
    state: 'West Bengal',
    items: [
      {
        serial: '1',
        name: 'Darjeeling Tea',
        type: 'Agricultural',
        year: '2004–05',
      },
      {
        serial: '2',
        name: 'Nakshi Kantha',
        type: 'Handicraft',
        year: '2007–08',
      },
      {
        serial: '3',
        name: 'Santiniketan Leather Goods',
        type: 'Handicraft',
        year: '2008–09',
      },
      {
        serial: '4',
        name: 'Malda Laxman Bhog mango',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '5',
        name: 'Malda Khirsapati (Himsagar) mango',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '6',
        name: 'Malda Fazli mango',
        type: 'Agricultural',
        year: '2008–09',
      },
      {
        serial: '7',
        name: 'Santipore saree',
        type: 'Handicraft',
        year: '2009–10',
      },
      {
        serial: '8',
        name: 'Baluchari Saree',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '9',
        name: 'Dhaniakhali Saree',
        type: 'Handicraft',
        year: '2011–12',
      },
      {
        serial: '10',
        name: 'Joynagar Moa',
        type: 'Food stuff',
        year: '2014–15',
      },
      {
        serial: '11',
        name: 'Bardhaman Sitabhog',
        type: 'Food stuff',
        year: '2016–17',
      },
      {
        serial: '12',
        name: 'Bardhaman Mihidana',
        type: 'Food stuff',
        year: '2016–17',
      },
      {
        serial: '13',
        name: 'Gobindobhog Rice',
        type: 'Agricultural',
        year: '2017–18',
      },
      {
        serial: '14',
        name: 'Tulaipanji Rice',
        type: 'Agricultural',
        year: '2017–18',
      },
      {
        serial: '15',
        name: 'Banglar Rasogolla',
        type: 'Food stuff',
        year: '2017–18',
      },
      {
        serial: '16',
        name: 'Bankura Panchmura Terracotta Craft',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '17',
        name: 'Bengal Dokra',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '18',
        name: 'Bengal Patachitra',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '19',
        name: 'Purulia Chau Mask',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '20',
        name: 'Wooden Mask of Kushmandi',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '21',
        name: 'Madur kathi',
        type: 'Handicraft',
        year: '2017–18',
      },
      {
        serial: '22',
        name: 'Tangail saree of Bengal',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '23',
        name: 'Garad saree',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '24',
        name: 'Korial saree',
        type: 'Handicraft',
        year: '2023–24',
      },
      {
        serial: '25',
        name: 'Kalonunia Rice',
        type: 'Agricultural',
        year: '2023–24',
      },
      {
        serial: '26',
        name: 'Sundarban Honey',
        type: 'Food stuff',
        year: '2023–24',
      },
      {
        serial: '27',
        name: 'Banglar Muslin',
        type: 'Handicraft',
        year: '2023–24',
      },
    ],
  },
] satisfies readonly GeographicalIndicationStateGroup[]

export const geographicalIndicationTitleLine =
  'Geographical Indications in India (645)' as const
