export type WildlifeSanctuaryEntry = {
  serial: string
  name: string
  declared: string
  district: string
}

export type WildlifeSanctuaryStateGroup = {
  state: string
  sanctuaries: readonly WildlifeSanctuaryEntry[]
}

export const wildlifeSanctuariesByState: readonly WildlifeSanctuaryStateGroup[] = [
  {
    state: 'Andaman and Nicobar Islands',
    sanctuaries: [
      {
        serial: '1',
        name: 'Arial Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '2',
        name: 'Bamboo Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '3',
        name: 'Barren Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '4',
        name: 'Battimalv Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Nicobar',
      },
      {
        serial: '5',
        name: 'Belle Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '6',
        name: 'Benett Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '7',
        name: 'Bingham Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '8',
        name: 'Blister Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '9',
        name: 'Bluff Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '10',
        name: 'Bondoville Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '11',
        name: 'Brush Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '12',
        name: 'Buchanan Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '13',
        name: 'Chanel Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '14',
        name: 'Cinque Islands Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '15',
        name: 'Clyde Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '16',
        name: 'Cone Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '17',
        name: 'Curlew (B.P.) Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '18',
        name: 'Curlew Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '19',
        name: 'Cuthbert Bay Wildlife Sanctuary',
        declared: '1997',
        district: 'Andaman',
      },
      {
        serial: '20',
        name: 'Defence Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '21',
        name: 'Dot Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '22',
        name: 'Dottrell Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '23',
        name: 'Duncan Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '24',
        name: 'East Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '25',
        name: 'East of Inglis Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '26',
        name: 'Egg Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '27',
        name: 'Entrance Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '28',
        name: 'Flat Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '29',
        name: 'Gander Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '30',
        name: 'Girjan Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '31',
        name: 'Galathea Bay Wildlife Sanctuary',
        declared: '-',
        district: 'Nicobar',
      },
      {
        serial: '32',
        name: 'Goose Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '33',
        name: 'Hump Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '34',
        name: 'Interview Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '35',
        name: 'James Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '36',
        name: 'Jungle Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '37',
        name: 'Kwangtung Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '38',
        name: 'Kyd Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '39',
        name: 'Landfall Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '40',
        name: 'Latouche Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '41',
        name: 'Lohabarrack Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '42',
        name: 'Mangrove Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '43',
        name: 'Mask Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '44',
        name: 'Mayo Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '45',
        name: 'Megapode Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Nicobar',
      },
      {
        serial: '46',
        name: 'Montogemery Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '47',
        name: 'Narcondam Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '48',
        name: 'North Brother Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '49',
        name: 'North Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '50',
        name: 'North Reef Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '51',
        name: 'Oliver Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '52',
        name: 'Orchid Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '53',
        name: 'Ox Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '54',
        name: 'Oyster Island‑I Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '55',
        name: 'Oyster Island‑II Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '56',
        name: 'Paget Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '57',
        name: 'Parkinson Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '58',
        name: 'Passage Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '59',
        name: 'Patric Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '60',
        name: 'Peacock Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '61',
        name: 'Pitman Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '62',
        name: 'Point Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '63',
        name: 'Potanma Islands Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '64',
        name: 'Ranger Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '65',
        name: 'Reef Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '66',
        name: 'Roper Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '67',
        name: 'Ross Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '68',
        name: 'Rowe Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '69',
        name: 'Sandy Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '70',
        name: 'Sea Serpent Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '71',
        name: 'Shark Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '72',
        name: 'Shearme Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '73',
        name: 'Sir Hugh Rose Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '74',
        name: 'Sisters Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '75',
        name: 'Snake Island‑I Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '76',
        name: 'Snake Island‑II Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '77',
        name: 'South Brother Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '78',
        name: 'South Reef Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '79',
        name: 'South Sentinel Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '80',
        name: 'Spike Island‑I Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '81',
        name: 'Spike Island‑II Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '82',
        name: 'Stoat Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '83',
        name: 'Surat Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '84',
        name: 'Swamp Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '85',
        name: 'Table (Delgarno) Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '86',
        name: 'Table (Excelsior) Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '87',
        name: 'Talabaicha Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '88',
        name: 'Temple Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '89',
        name: 'Tillongchang Island Wildlife Sanctuary',
        declared: '1985',
        district: 'Nicobar',
      },
      {
        serial: '90',
        name: 'Tree Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '91',
        name: 'Trilby Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '92',
        name: 'Tuft Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '93',
        name: 'Turtle Islands Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '94',
        name: 'West Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '95',
        name: 'Wharf Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
      {
        serial: '96',
        name: 'White Cliff Island Wildlife Sanctuary',
        declared: '1987',
        district: 'Andaman',
      },
    ],
  },
  {
    state: 'Andhra Pradesh',
    sanctuaries: [
      {
        serial: '1',
        name: 'Coringa Wildlife Sanctuary',
        declared: '1978',
        district: 'East Godavari',
      },
      {
        serial: '2',
        name: 'Gundla Brahmeswaram Wildlife Sanctuary',
        declared: '1990',
        district: 'Kurnool, Prakasam',
      },
      {
        serial: '3',
        name: 'Kambalakonda Wildlife Sanctuary',
        declared: '2002',
        district: 'Visakhapatnam',
      },
      {
        serial: '4',
        name: 'Koundinya Wildlife Sanctuary',
        declared: '1990',
        district: 'Chittoor',
      },
      {
        serial: '5',
        name: 'Kolleru Wildlife Sanctuary',
        declared: '1953',
        district: 'Krishna, West Godavari',
      },
      {
        serial: '6',
        name: 'Krishna Wildlife Sanctuary',
        declared: '1989',
        district: 'Guntur, Krishna',
      },
      {
        serial: '7',
        name: 'Nagarjunsagar-Srisailam Tiger Reserve',
        declared: '1978',
        district: 'Nandyal, Palnadu, Prakasam',
      },
      {
        serial: '8',
        name: 'Nelapattu Bird Sanctuary',
        declared: '1976',
        district: 'Tirupati',
      },
      {
        serial: '9',
        name: 'Pulicat Lake Bird Sanctuary',
        declared: '1976',
        district: 'Tirupati',
      },
      {
        serial: '10',
        name: 'Rollapadu Wildlife Sanctuary',
        declared: '1988',
        district: 'Nandyal',
      },
      {
        serial: '11',
        name: 'Sri Lankamalleswara Wildlife Sanctuary',
        declared: '1988',
        district: 'Kadapa',
      },
      {
        serial: '12',
        name: 'Sri Penusila Narasimha Wildlife Sanctuary',
        declared: '1997',
        district: 'Nellore',
      },
      {
        serial: '13',
        name: 'Sri Venkateswara Wildlife Sanctuary',
        declared: '1985',
        district: 'Tirupati',
      },
    ],
  },
  {
    state: 'Arunachal Pradesh',
    sanctuaries: [
      {
        serial: '1',
        name: 'D\'Ering Memorial Wildlife Sanctuary',
        declared: '1978',
        district: 'East Siang',
      },
      {
        serial: '2',
        name: 'Dibang Wildlife Sanctuary',
        declared: '1991',
        district: 'Dibang Valley',
      },
      {
        serial: '3',
        name: 'Eaglenest Wildlife Sanctuary',
        declared: '1989',
        district: 'West Kameng',
      },
      {
        serial: '4',
        name: 'Itanagar Wildlife Sanctuary',
        declared: '1978',
        district: 'Papum Pare',
      },
      {
        serial: '5',
        name: 'Kamala Wildlife Sanctuary',
        declared: '2015',
        district: 'Upper Subansiri',
      },
      {
        serial: '6',
        name: 'Kamlang Wildlife Sanctuary',
        declared: '1989',
        district: 'Lohit',
      },
      {
        serial: '7',
        name: 'Kane Wildlife Sanctuary',
        declared: '1991',
        district: 'West Siang',
      },
      {
        serial: '8',
        name: 'Mehao Wildlife Sanctuary',
        declared: '1980',
        district: 'Dibang Valley',
      },
      {
        serial: '9',
        name: 'Pakke Tiger Reserve',
        declared: '1977',
        district: 'East Kameng',
      },
      {
        serial: '10',
        name: 'Ringba-Roba Wildlife Sanctuary',
        declared: '2015',
        district: 'East Kameng',
      },
      {
        serial: '11',
        name: 'Sessa Orchid Wildlife Sanctuary',
        declared: '1989',
        district: 'West Kameng',
      },
      {
        serial: '12',
        name: 'Talle Valley Wildlife Sanctuary',
        declared: '1995',
        district: 'Lower Subansiri',
      },
      {
        serial: '13',
        name: 'Yordi Rabe Supse Wildlife Sanctuary',
        declared: '1996',
        district: 'West Siang',
      },
    ],
  },
  {
    state: 'Assam',
    sanctuaries: [
      {
        serial: '1',
        name: 'Amchang Wildlife Sanctuary',
        declared: '2004',
        district: 'Kamrup',
      },
      {
        serial: '2',
        name: 'Barnadi Wildlife Sanctuary',
        declared: '1980',
        district: 'Darrang',
      },
      {
        serial: '3',
        name: 'Bherjan-Borajan-Padumoni Wildlife Sanctuary',
        declared: '1999',
        district: 'Tinsukia',
      },
      {
        serial: '4',
        name: 'Borail Wildlife Sanctuary',
        declared: '2004',
        district: 'Cachar',
      },
      {
        serial: '5',
        name: 'Burachapori Wildlife Sanctuary',
        declared: '1995',
        district: 'Sonitpur',
      },
      {
        serial: '6',
        name: 'Chakrashila Wildlife Sanctuary',
        declared: '1994',
        district: 'Dhubri',
      },
      {
        serial: '7',
        name: 'Deepar Beel Wildlife Sanctuary',
        declared: '1989',
        district: 'Kamrup',
      },
      {
        serial: '8',
        name: 'East Karbi-Anglong Wildlife Sanctuary',
        declared: '2000',
        district: 'Karbi-Anglong',
      },
      {
        serial: '9',
        name: 'Garampani Wildlife Sanctuary',
        declared: '1952',
        district: 'Karbi-Anglong',
      },
      {
        serial: '10',
        name: 'Hoollongapar Gibbon Sanctuary',
        declared: '1997',
        district: 'Jorhat',
      },
      {
        serial: '11',
        name: 'Laokhowa Wildlife Sanctuary',
        declared: '1972',
        district: 'Nagaon',
      },
      {
        serial: '12',
        name: 'Marat Longri Wildlife Sanctuary',
        declared: '2003',
        district: 'Karbi-Anglong',
      },
      {
        serial: '13',
        name: 'Nambor Wildlife Sanctuary',
        declared: '2000',
        district: 'Karbi-Anglong',
      },
      {
        serial: '14',
        name: 'Nambor - Doigrung Wildlife Sanctuary',
        declared: '2003',
        district: 'Karbi-Anglong',
      },
      {
        serial: '15',
        name: 'Pabitora Wildlife Sanctuary',
        declared: '1987',
        district: 'Marigaon',
      },
      {
        serial: '16',
        name: 'Pani Dihing Wildlife Sanctuary',
        declared: '1995',
        district: 'Sibsagar',
      },
      {
        serial: '17',
        name: 'Sonai Rupai Wildlife Sanctuary',
        declared: '1998',
        district: 'Sonitpur',
      },
    ],
  },
  {
    state: 'Bihar',
    sanctuaries: [
      {
        serial: '1',
        name: 'Barela Bird Sanctuary',
        declared: '1997',
        district: 'Vaishali',
      },
      {
        serial: '2',
        name: 'Bhimbandh Wildlife Sanctuary',
        declared: '1976',
        district: 'Munger',
      },
      {
        serial: '3',
        name: 'Gautam Budha Wildlife Sanctuary',
        declared: '1976',
        district: 'Gaya',
      },
      {
        serial: '4',
        name: 'Kaimur Wildlife Sanctuary',
        declared: '1979',
        district: 'Rohtas',
      },
      {
        serial: '5',
        name: 'Kanwarjheel Wildlife Sanctuary',
        declared: '1989',
        district: 'Begusarai',
      },
      {
        serial: '6',
        name: 'Kusheshwar Asthan Bird Wildlife Sanctuary',
        declared: '1994',
        district: 'Darbhanga',
      },
      {
        serial: '7',
        name: 'Nagi Dam Wildlife Sanctuary',
        declared: '1987',
        district: 'Jamui',
      },
      {
        serial: '8',
        name: 'Nakti Dam Wildlife Sanctuary',
        declared: '1987',
        district: 'Jamui',
      },
      {
        serial: '9',
        name: 'Pant Wildlife Sanctuary',
        declared: '1978',
        district: 'Nalanda',
      },
      {
        serial: '10',
        name: 'Rajauli Wildlife Sanctuary',
        declared: '2019',
        district: 'Nawada',
      },
      {
        serial: '11',
        name: 'Udaypur Wildlife Sanctuary',
        declared: '1978',
        district: 'Pashchim Champaran',
      },
      {
        serial: '12',
        name: 'Valmiki Wildlife Sanctuary',
        declared: '1978',
        district: 'Pashchim Champaran',
      },
      {
        serial: '13',
        name: 'Vikramshila Gangetic Dolphin Sanctuary',
        declared: '1990',
        district: 'Bhagalpur',
      },
    ],
  },
  {
    state: 'Chandigarh',
    sanctuaries: [
      {
        serial: '1',
        name: 'City Birds Wildlife Sanctuary',
        declared: '1998',
        district: 'Chandigarh',
      },
      {
        serial: '2',
        name: 'Sukhna Wildlife Sanctuary',
        declared: '1986',
        district: 'Chandigarh',
      },
    ],
  },
  {
    state: 'Chhattisgarh',
    sanctuaries: [
      {
        serial: '1',
        name: 'Achanakmar Wildlife Sanctuary',
        declared: '1975',
        district: 'Bilaspur',
      },
      {
        serial: '2',
        name: 'Badalkhol Wildlife Sanctuary',
        declared: '1975',
        district: 'Jashpur',
      },
      {
        serial: '3',
        name: 'Barnawapara Wildlife Sanctuary',
        declared: '1976',
        district: 'Raipur',
      },
      {
        serial: '4',
        name: 'Bhairamgarh Wildlife Sanctuary',
        declared: '1983',
        district: 'Bijapur',
      },
      {
        serial: '5',
        name: 'Bhoramdev Wildlife Sanctuary',
        declared: '2001',
        district: 'Kawardha',
      },
      {
        serial: '6',
        name: 'Gomardha Wildlife Sanctuary',
        declared: '1975',
        district: 'Raigarh',
      },
      {
        serial: '7',
        name: 'Pamed Wildlife Sanctuary',
        declared: '1985',
        district: 'Bijapur',
      },
      {
        serial: '8',
        name: 'Semarsot Wildlife Sanctuary',
        declared: '1978',
        district: 'Surguja',
      },
      {
        serial: '9',
        name: 'Sitanadi Wildlife Sanctuary',
        declared: '1974',
        district: 'Dhamtari',
      },
      {
        serial: '10',
        name: 'Tamor Pingla Wildlife Sanctuary',
        declared: '1978',
        district: 'Surguja',
      },
      {
        serial: '11',
        name: 'Udanti Wildlife Sanctuary',
        declared: '1983',
        district: 'Gariaband',
      },
    ],
  },
  {
    state: 'Dadra Nagar Haveli and Daman and Diu',
    sanctuaries: [
      {
        serial: '1',
        name: 'Dadra and Nagar Haveli Wildlife Sanctuary',
        declared: '2000',
        district: 'Dadra and Nagar Haveli',
      },
      {
        serial: '2',
        name: 'Fudam Bird Sanctuary',
        declared: '1991',
        district: 'Diu',
      },
    ],
  },
  {
    state: 'Delhi',
    sanctuaries: [
      {
        serial: '1',
        name: 'Asola Bhatti Wildlife Sanctuary',
        declared: '1992',
        district: 'South Delhi',
      },
    ],
  },
  {
    state: 'Goa',
    sanctuaries: [
      {
        serial: '1',
        name: 'Bhagwan Mahavir Sanctuary',
        declared: '1967',
        district: 'North Goa',
      },
      {
        serial: '2',
        name: 'Bondla Wildlife Sanctuary',
        declared: '1969',
        district: 'North Goa',
      },
      {
        serial: '3',
        name: 'Cotigao Wildlife Sanctuary',
        declared: '1968',
        district: 'South Goa',
      },
      {
        serial: '4',
        name: 'Madei Wildlife Sanctuary',
        declared: '1999',
        district: 'North Goa',
      },
      {
        serial: '5',
        name: 'Netravali Wildlife Sanctuary',
        declared: '1999',
        district: 'South Goa',
      },
      {
        serial: '6',
        name: 'Salim Ali Bird Sanctuary',
        declared: '1988',
        district: 'North Goa',
      },
    ],
  },
  {
    state: 'Gujarat',
    sanctuaries: [
      {
        serial: '1',
        name: 'Balaram Ambaji Wildlife Sanctuary',
        declared: '1989',
        district: 'Banaskantha',
      },
      {
        serial: '2',
        name: 'Barda Wildlife Sanctuary',
        declared: '1979',
        district: 'Jamnagar, Porbandar',
      },
      {
        serial: '3',
        name: 'Gaga Wildlife Sanctuary',
        declared: '1988',
        district: 'Jamnagar',
      },
      {
        serial: '4',
        name: 'Gir Wildlife Sanctuary',
        declared: '1965',
        district: 'Amreli, Junagadh',
      },
      {
        serial: '5',
        name: 'Girnar Wildlife Sanctuary',
        declared: '2008',
        district: 'Junagadh',
      },
      {
        serial: '6',
        name: 'Hingolgadh Wildlife Sanctuary',
        declared: '1980',
        district: 'Rajkot',
      },
      {
        serial: '7',
        name: 'Jambughoda Wildlife Sanctuary',
        declared: '1990',
        district: 'Godhra',
      },
      {
        serial: '8',
        name: 'Jessore Sloth Bear Sanctuary',
        declared: '1978',
        district: 'Banaskantha',
      },
      {
        serial: '9',
        name: 'Khijadiya Bird Sanctuary',
        declared: '1981',
        district: 'Jamnagar',
      },
      {
        serial: '10',
        name: 'Kutch Bustard Sanctuary',
        declared: '1995',
        district: 'Kachchh',
      },
      {
        serial: '11',
        name: 'Kutch Desert Wildlife Sanctuary',
        declared: '1986',
        district: 'Kachchh',
      },
      {
        serial: '12',
        name: 'Marine Wildlife Sanctuary',
        declared: '1980',
        district: 'Jamnagar',
      },
      {
        serial: '13',
        name: 'Mitiyala Wildlife Sanctuary',
        declared: '2004',
        district: 'Junagadh',
      },
      {
        serial: '14',
        name: 'Nal Sarovar Bird Sanctuary',
        declared: '1969',
        district: 'Ahmedabad, Surendranagar',
      },
      {
        serial: '15',
        name: 'Narayan Sarovar Wildlife Sanctuary',
        declared: '1995',
        district: 'Kachchh',
      },
      {
        serial: '16',
        name: 'Pania Wildlife Sanctuary',
        declared: '1989',
        district: 'Amreli',
      },
      {
        serial: '17',
        name: 'Porbandar Bird Sanctuary',
        declared: '1988',
        district: 'Porbandar',
      },
      {
        serial: '18',
        name: 'Purna Wildlife Sanctuary',
        declared: '1990',
        district: 'Dangs',
      },
      {
        serial: '19',
        name: 'Rampara Wildlife Sanctuary',
        declared: '1988',
        district: 'Rajkot',
      },
      {
        serial: '20',
        name: 'Ratanmahal Wildlife Sanctuary',
        declared: '1982',
        district: 'Dahod',
      },
      {
        serial: '21',
        name: 'Shoolpaneshwar Wildlife Sanctuary',
        declared: '1982',
        district: 'Bharuch',
      },
      {
        serial: '22',
        name: 'Thol Lake Bird Sanctuary',
        declared: '1988',
        district: 'Mahesana',
      },
      {
        serial: '23',
        name: 'Wild Ass Wildlife Sanctuary',
        declared: '1973',
        district: 'Banaskantha, Kachchh, Mahesana, Patan, Rajkot, Surendranagar',
      },
    ],
  },
  {
    state: 'Haryana',
    sanctuaries: [
      {
        serial: '1',
        name: 'Abubshahar Wildlife Sanctuary',
        declared: '1987',
        district: 'Sirsa',
      },
      {
        serial: '2',
        name: 'Bhindawas Wildlife Sanctuary',
        declared: '1986',
        district: 'Jhajjar',
      },
      {
        serial: '3',
        name: 'Bir Shikargah Wildlife Sanctuary',
        declared: '1987',
        district: 'Panchkula',
      },
      {
        serial: '4',
        name: 'Chhilchhila Wildlife Sanctuary',
        declared: '1986',
        district: 'Kaithal',
      },
      {
        serial: '5',
        name: 'Kalesar Wildlife Sanctuary',
        declared: '1996',
        district: 'Yamuna Nagar',
      },
      {
        serial: '6',
        name: 'Khaparwas Wildlife Sanctuary',
        declared: '1991',
        district: 'Jhajjar',
      },
      {
        serial: '7',
        name: 'Khol Hi-Raitan Wildlife Sanctuary',
        declared: '2004',
        district: 'Panchkula',
      },
      {
        serial: '8',
        name: 'Nahar Wildlife Sanctuary',
        declared: '1987',
        district: 'Rewari',
      },
    ],
  },
  {
    state: 'Himachal Pradesh',
    sanctuaries: [
      {
        serial: '1',
        name: 'Bandli Wildlife Sanctuary',
        declared: '1962',
        district: 'Mandi',
      },
      {
        serial: '2',
        name: 'Chail Wildlife Sanctuary',
        declared: '1976',
        district: 'Sirmaur',
      },
      {
        serial: '3',
        name: 'Chandratal Wildlife Sanctuary',
        declared: '2007',
        district: 'Lahaul and Spiti',
      },
      {
        serial: '4',
        name: 'Churdhar Wildlife Sanctuary',
        declared: '1985',
        district: 'Sirmaur',
      },
      {
        serial: '5',
        name: 'Daranghati Wildlife Sanctuary',
        declared: '1962',
        district: 'Shimla',
      },
      {
        serial: '6',
        name: 'Dhauladhar Wildlife Sanctuary',
        declared: '1994',
        district: 'Kangra',
      },
      {
        serial: '7',
        name: 'Gamgul Siahbehi Wildlife Sanctuary',
        declared: '1962',
        district: 'Chamba',
      },
      {
        serial: '8',
        name: 'Kais Wildlife Sanctuary',
        declared: '1954',
        district: 'Kullu',
      },
      {
        serial: '9',
        name: 'Kalatop Khajjiar Wildlife Sanctuary',
        declared: '1958',
        district: 'Chamba',
      },
      {
        serial: '10',
        name: 'Kanwar Wildlife Sanctuary',
        declared: '1954',
        district: 'Kullu',
      },
      {
        serial: '11',
        name: 'Khokhan Wildlife Sanctuary',
        declared: '1954',
        district: 'Kullu',
      },
      {
        serial: '12',
        name: 'Kibber Wildlife Sanctuary',
        declared: '1992',
        district: 'Lahul and Spiti',
      },
      {
        serial: '13',
        name: 'Kugti Wildlife Sanctuary',
        declared: '1962',
        district: 'Chamba',
      },
      {
        serial: '14',
        name: 'Lippa Asrang Wildlife Sanctuary',
        declared: '2001',
        district: 'Kinnaur',
      },
      {
        serial: '15',
        name: 'Majathal Wildlife Sanctuary',
        declared: '1954',
        district: 'Solan',
      },
      {
        serial: '16',
        name: 'Manali Wildlife Sanctuary',
        declared: '1954',
        district: 'Kullu',
      },
      {
        serial: '17',
        name: 'Nargu Wildlife Sanctuary',
        declared: '1962',
        district: 'Mandi',
      },
      {
        serial: '18',
        name: 'Pong Dam Lake Wildlife Sanctuary',
        declared: '1982',
        district: 'Kangra',
      },
      {
        serial: '19',
        name: 'Rakchham Chitkul Wildlife Sanctuary',
        declared: '1989',
        district: 'Kinnaur',
      },
      {
        serial: '20',
        name: 'Renuka Wildlife Sanctuary',
        declared: '2013',
        district: 'Sirmaur',
      },
      {
        serial: '21',
        name: 'Rupi Bhaba Wildlife Sanctuary',
        declared: '1982',
        district: 'Kinnaur',
      },
      {
        serial: '22',
        name: 'Sainj Wildlife Sanctuary',
        declared: '1994',
        district: 'Kullu',
      },
      {
        serial: '23',
        name: 'Sechu Tuan Nala Wildlife Sanctuary',
        declared: '1962',
        district: 'Chamba',
      },
      {
        serial: '24',
        name: 'Shikari Devi Wildlife Sanctuary',
        declared: '1962',
        district: 'Mandi',
      },
      {
        serial: '25',
        name: 'Shimla Wildlife Sanctuary',
        declared: '1958',
        district: 'Shimla',
      },
      {
        serial: '26',
        name: 'Talra Wildlife Sanctuary',
        declared: '1962',
        district: 'Shimla',
      },
      {
        serial: '27',
        name: 'Tirthan Wildlife Sanctuary',
        declared: '1992',
        district: 'Kullu',
      },
      {
        serial: '28',
        name: 'Tundah Wildlife Sanctuary',
        declared: '1999',
        district: 'Chamba',
      },
    ],
  },
  {
    state: 'Jammu and Kashmir',
    sanctuaries: [
      {
        serial: '1',
        name: 'Baltal Thajwas Wildlife Sanctuary',
        declared: '1987',
        district: 'Srinagar',
      },
      {
        serial: '2',
        name: 'Gulmarg Wildlife Sanctuary',
        declared: '1987',
        district: 'Baramulla',
      },
      {
        serial: '3',
        name: 'Hirpora Wildlife Sanctuary',
        declared: '1987',
        district: 'Baramulla',
      },
      {
        serial: '4',
        name: 'Jasrota Wildlife Sanctuary',
        declared: '1987',
        district: 'Kathua',
      },
      {
        serial: '5',
        name: 'Lachipora Wildlife Sanctuary',
        declared: '1987',
        district: 'Baramulla',
      },
      {
        serial: '6',
        name: 'Limber Wildlife Sanctuary',
        declared: '1987',
        district: 'Baramulla',
      },
      {
        serial: '7',
        name: 'Nandini Wildlife Sanctuary',
        declared: '1990',
        district: 'Jammu',
      },
      {
        serial: '8',
        name: 'Overa-Aru Wildlife Sanctuary',
        declared: '1987',
        district: 'Anantnag',
      },
      {
        serial: '9',
        name: 'Rajparian Wildlife Sanctuary',
        declared: '1945',
        district: 'Anantnag',
      },
      {
        serial: '10',
        name: 'Ramnagar Rakha Wildlife Sanctuary',
        declared: '1990',
        district: 'Jammu',
      },
      {
        serial: '11',
        name: 'Surinsar-Mansar Wildlife Sanctuary',
        declared: '1990',
        district: 'Jammu',
      },
      {
        serial: '12',
        name: 'Tata Kutti Wildlife Sanctuary',
        declared: '2012',
        district: 'Jammu',
      },
      {
        serial: '13',
        name: 'Tral Wildlife Sanctuary',
        declared: '2019',
        district: 'Pulwama',
      },
    ],
  },
  {
    state: 'Jharkhand',
    sanctuaries: [
      {
        serial: '1',
        name: 'Dalma Wildlife Sanctuary',
        declared: '1976',
        district: 'Singhbhum East',
      },
      {
        serial: '2',
        name: 'Gautam Budha Wildlife Sanctuary',
        declared: '1976',
        district: 'Koderma',
      },
      {
        serial: '3',
        name: 'Hazaribagh Wildlife Sanctuary',
        declared: '1976',
        district: 'Hazaribagh',
      },
      {
        serial: '4',
        name: 'Koderma Wildlife Sanctuary',
        declared: '1985',
        district: 'Koderma',
      },
      {
        serial: '5',
        name: 'Lawalong Wildlife Sanctuary',
        declared: '1978',
        district: 'Chatra',
      },
      {
        serial: '6',
        name: 'Mahuadanr Wildlife Sanctuary',
        declared: '1976',
        district: 'Palamau',
      },
      {
        serial: '7',
        name: 'Palamau Wildlife Sanctuary',
        declared: '1976',
        district: 'Palamau',
      },
      {
        serial: '8',
        name: 'Palkot Wildlife Sanctuary',
        declared: '1990',
        district: 'Gumla',
      },
      {
        serial: '9',
        name: 'Parasnath Wildlife Sanctuary',
        declared: '1984',
        district: 'Giridih',
      },
      {
        serial: '10',
        name: 'Topchanchi Wildlife Sanctuary',
        declared: '1978',
        district: 'Dhanbad',
      },
      {
        serial: '11',
        name: 'Udhwa Lake Wildlife Sanctuary',
        declared: '1991',
        district: 'Sahebganj',
      },
    ],
  },
  {
    state: 'Karnataka',
    sanctuaries: [
      {
        serial: '1',
        name: 'Adichunchunagiri Wildlife Sanctuary',
        declared: '1981',
        district: 'Mandya',
      },
      {
        serial: '2',
        name: 'Arabithittu Wildlife Sanctuary',
        declared: '1985',
        district: 'Mysore',
      },
      {
        serial: '3',
        name: 'Arsikere Sloth Bear Wildlife Sanctuary',
        declared: '2023',
        district: 'Hassan',
      },
      {
        serial: '4',
        name: 'Attiveri Bird Sanctuary',
        declared: '1994',
        district: 'Uttara Kannada',
      },
      {
        serial: '5',
        name: 'Bankapura Wolf Wildlife Sanctuary',
        declared: '2023',
        district: 'Koppal',
      },
      {
        serial: '6',
        name: 'Bhadra Wildlife Sanctuary',
        declared: '1974',
        district: 'Chikmagalur, Shimoga',
      },
      {
        serial: '7',
        name: 'Bhimgad Wildlife Sanctuary',
        declared: '2010',
        district: 'Belgavi',
      },
      {
        serial: '8',
        name: 'Biligiri Rangaswamy Temple Wildlife Sanctuary',
        declared: '1987',
        district: 'Chamarajanagar',
      },
      {
        serial: '9',
        name: 'Brahmagiri Wildlife Sanctuary',
        declared: '1974',
        district: 'Kodagu',
      },
      {
        serial: '10',
        name: 'Bukkapatna Chinkara Wildlife Sanctuary',
        declared: '2019',
        district: 'Tumakuru',
      },
      {
        serial: '11',
        name: 'Cauvery Extension Wildlife Sanctuary',
        declared: '—',
        district: '—',
      },
      {
        serial: '12',
        name: 'Cauvery Wildlife Sanctuary',
        declared: '1987',
        district: 'Chamarajanagar, Mandya, Ramanagar',
      },
      {
        serial: '13',
        name: 'Chincholi Wildlife Sanctuary',
        declared: '2011',
        district: 'Kalaburagi',
      },
      {
        serial: '14',
        name: 'Dandeli Wildlife Sanctuary',
        declared: '1987',
        district: 'Uttara Kannada',
      },
      {
        serial: '15',
        name: 'Daroji Sloth Bear Sanctuary',
        declared: '1992',
        district: 'Dharwar',
      },
      {
        serial: '16',
        name: 'Ghataprabha Wildlife Sanctuary',
        declared: '1974',
        district: 'Belgaum',
      },
      {
        serial: '17',
        name: 'Gudavi Bird Sanctuary',
        declared: '1989',
        district: 'Shimoga',
      },
      {
        serial: '18',
        name: 'Gudekote Extension Wildlife Sanctuary',
        declared: '2019',
        district: 'Ballari',
      },
      {
        serial: '19',
        name: 'Gudekote Wildlife Sanctuary',
        declared: '2013',
        district: 'Ballari',
      },
      {
        serial: '20',
        name: 'Jogimatti Wildlife Sanctuary',
        declared: '2015',
        district: 'Chitradurga',
      },
      {
        serial: '21',
        name: 'Kamasandra Wildlife Sanctuary',
        declared: '2019',
        district: 'Ramanagara',
      },
      {
        serial: '22',
        name: 'Kappathagudda Wildlife Sanctuary',
        declared: '2019',
        district: 'Gadag',
      },
      {
        serial: '23',
        name: 'Malai Mahadeshwara Wildlife Sanctuary',
        declared: '2013',
        district: 'Chamarajanagar',
      },
      {
        serial: '24',
        name: 'Melkote Temple Wildlife Sanctuary',
        declared: '1974',
        district: 'Mandya',
      },
      {
        serial: '25',
        name: 'Mookambika Wildlife Sanctuary',
        declared: '1974',
        district: 'Udipi',
      },
      {
        serial: '26',
        name: 'Nugu Wildlife Sanctuary',
        declared: '1974',
        district: 'Mysore',
      },
      {
        serial: '27',
        name: 'Pushpagiri Wildlife Sanctuary',
        declared: '1987',
        district: 'Dakshina Kannada, Kodagu',
      },
      {
        serial: '28',
        name: 'Ramadevarabetta Vulture Sanctuary',
        declared: '2012',
        district: 'Ramanagara',
      },
      {
        serial: '29',
        name: 'Ranganathittu Bird Sanctuary',
        declared: '1940',
        district: 'Mysore',
      },
      {
        serial: '30',
        name: 'Rangayyanadurga Wildlife Sanctuary',
        declared: '2011',
        district: 'Davanagere',
      },
      {
        serial: '31',
        name: 'Ranibennur Blackbuck Sanctuary',
        declared: '1974',
        district: 'Dharwad',
      },
      {
        serial: '32',
        name: 'Sharavati Valley Wildlife Sanctuary',
        declared: '1974',
        district: 'Shimoga',
      },
      {
        serial: '33',
        name: 'Shettihalli Wildlife Sanctuary',
        declared: '1974',
        district: 'Shimoga',
      },
      {
        serial: '34',
        name: 'Someshwara Wildlife Sanctuary',
        declared: '1974',
        district: 'Udipi',
      },
      {
        serial: '35',
        name: 'Talakaveri Wildlife Sanctuary',
        declared: '1987',
        district: 'Kodagu',
      },
      {
        serial: '36',
        name: 'Thimlapura Wildlife Sanctuary',
        declared: '2016',
        district: 'Tumkur',
      },
      {
        serial: '37',
        name: 'Uttaregudda Wildlife Sanctuary',
        declared: '2023',
        district: 'Chitradurga',
      },
      {
        serial: '38',
        name: 'Yadahalli Chinkara Wildlife Sanctuary',
        declared: '2015',
        district: 'Bagalkot',
      },
    ],
  },
  {
    state: 'Kerala',
    sanctuaries: [
      {
        serial: '1',
        name: 'Aralam Butterfly Sanctuary',
        declared: '1984',
        district: 'Kannur',
      },
      {
        serial: '2',
        name: 'Chimmony Wildlife Sanctuary',
        declared: '1984',
        district: 'Thrissur',
      },
      {
        serial: '3',
        name: 'Chinnar Wildlife Sanctuary',
        declared: '1984',
        district: 'Idukki',
      },
      {
        serial: '4',
        name: 'Choolannur Pea Fowl Sanctuary',
        declared: '2007',
        district: 'Palakkad',
      },
      {
        serial: '5',
        name: 'Idukki Wildlife Sanctuary',
        declared: '1976',
        district: 'Idukki',
      },
      {
        serial: '6',
        name: 'Karimpuzha Wildlife Sanctuary',
        declared: '2019',
        district: 'Malappuram',
      },
      {
        serial: '7',
        name: 'Kottiyoor Wildlife Sanctuary',
        declared: '2011',
        district: 'Kannur',
      },
      {
        serial: '8',
        name: 'Kurinjimala Sanctuary',
        declared: '2006',
        district: 'Idukki',
      },
      {
        serial: '9',
        name: 'Malabar Wildlife Sanctuary',
        declared: '2010',
        district: 'Kozhikode',
      },
      {
        serial: '10',
        name: 'Mangalavanam Bird Sanctuary',
        declared: '2004',
        district: 'Ernakulam',
      },
      {
        serial: '11',
        name: 'Neyyar Wildlife Sanctuary',
        declared: '1958',
        district: 'Thiruvananthapuram',
      },
      {
        serial: '12',
        name: 'Parambikulam Wildlife Sanctuary',
        declared: '1973',
        district: 'Palakkad',
      },
      {
        serial: '13',
        name: 'Peechi-Vazhani Wildlife Sanctuary',
        declared: '1958',
        district: 'Thrissur',
      },
      {
        serial: '14',
        name: 'Peppara Wildlife Sanctuary',
        declared: '1983',
        district: 'Thiruvananthapuram',
      },
      {
        serial: '15',
        name: 'Periyar Wildlife Sanctuary',
        declared: '1950',
        district: 'Idukki',
      },
      {
        serial: '16',
        name: 'Shendurney Wildlife Sanctuary',
        declared: '1984',
        district: 'Kollam',
      },
      {
        serial: '17',
        name: 'Thattekad Bird Sanctuary',
        declared: '1983',
        district: 'Idukki',
      },
      {
        serial: '18',
        name: 'Wayanad Wildlife Sanctuary',
        declared: '1973',
        district: 'Wayanad',
      },
    ],
  },
  {
    state: 'Ladakh',
    sanctuaries: [
      {
        serial: '1',
        name: 'Changthang Cold Desert Wildlife Sanctuary',
        declared: '1987',
        district: 'Leh',
      },
      {
        serial: '2',
        name: 'Karakoram Wildlife Sanctuary',
        declared: '1987',
        district: 'Leh',
      },
    ],
  },
  {
    state: 'Lakshadweep',
    sanctuaries: [
      {
        serial: '1',
        name: 'Pitti',
        declared: '2002',
        district: 'Lakshadweep',
      },
    ],
  },
  {
    state: 'Madhya Pradesh',
    sanctuaries: [
      {
        serial: '1',
        name: 'Bagdara Wildlife Sanctuary',
        declared: '1978',
        district: 'Sidhi',
      },
      {
        serial: '2',
        name: 'Bori Wildlife Sanctuary',
        declared: '1977',
        district: 'Hoshangabad',
      },
      {
        serial: '3',
        name: 'Dr. Bhimrao Ambedkar Wildlife Sanctuary[22]',
        declared: '2025',
        district: 'Sagar',
      },
      {
        serial: '4',
        name: 'Gandhi Sagar Sanctuary',
        declared: '1981',
        district: 'Mandsaur',
      },
      {
        serial: '5',
        name: 'Gangau Wildlife Sanctuary',
        declared: '1979',
        district: 'Chhatarpur',
      },
      {
        serial: '6',
        name: 'Ghatigaon Wildlife Sanctuary',
        declared: '1981',
        district: 'Gwalior',
      },
      {
        serial: '7',
        name: 'Karera Wildlife Sanctuary',
        declared: '1981',
        district: 'Shivpuri',
      },
      {
        serial: '8',
        name: 'Karmajhiri Wildlife Sanctuary[23]',
        declared: '2022',
        district: 'Seoni',
      },
      {
        serial: '9',
        name: 'Ken Gharial Sanctuary',
        declared: '1981',
        district: 'Chhatarpur, Panna',
      },
      {
        serial: '10',
        name: 'Kheoni Wildlife Sanctuary',
        declared: '1982',
        district: 'Dewas, Sehore',
      },
      {
        serial: '11',
        name: 'Narsinghgarh Wildlife Sanctuary',
        declared: '1978',
        district: 'Raigarh',
      },
      {
        serial: '12',
        name: 'National Chambal Wildlife Sanctuary',
        declared: '1978',
        district: 'Morena, Bhind',
      },
      {
        serial: '13',
        name: 'Nauradehi Wildlife Sanctuary',
        declared: '1984',
        district: 'Damoh, Narsimhapur, Sagar',
      },
      {
        serial: '14',
        name: 'Orchha Wildlife Sanctuary',
        declared: '1994',
        district: 'Tikamgarh',
      },
      {
        serial: '15',
        name: 'Pachmarhi Wildlife Sanctuary',
        declared: '1977',
        district: 'Hoshangabad',
      },
      {
        serial: '16',
        name: 'Panpatha Wildlife Sanctuary',
        declared: '1983',
        district: 'Umaria',
      },
      {
        serial: '17',
        name: 'Pench Wildlife Sanctuary',
        declared: '1975',
        district: 'Chhindwara, Seoni',
      },
      {
        serial: '18',
        name: 'Phen Wildlife Sanctuary',
        declared: '1983',
        district: 'Mandla',
      },
      {
        serial: '19',
        name: 'Ralamandal Wildlife Sanctuary',
        declared: '1989',
        district: 'Indore',
      },
      {
        serial: '20',
        name: 'Ratapani Wildlife Sanctuary',
        declared: '1978',
        district: 'Raisen',
      },
      {
        serial: '21',
        name: 'Sailana Wildlife Sanctuary',
        declared: '1983',
        district: 'Ratlam',
      },
      {
        serial: '22',
        name: 'Sanjay Dubri Wildlife Sanctuary',
        declared: '1975',
        district: 'Sidhi',
      },
      {
        serial: '23',
        name: 'Sardarpur Wildlife Sanctuary',
        declared: '1983',
        district: 'Dhar',
      },
      {
        serial: '24',
        name: 'Singhori Wildlife Sanctuary',
        declared: '1976',
        district: 'Raisen',
      },
      {
        serial: '25',
        name: 'Son Gharial Wildlife Sanctuary',
        declared: '1981',
        district: 'Satna, Shahdol, Sidhi',
      },
      {
        serial: '26',
        name: 'Veerangana Durgavati Wildlife Sanctuary',
        declared: '1997',
        district: 'Damoh',
      },
    ],
  },
  {
    state: 'Maharashtra',
    sanctuaries: [
      {
        serial: '1',
        name: 'Amba Barwa Wildlife Sanctuary',
        declared: '1997',
        district: 'Buldhana',
      },
      {
        serial: '2',
        name: 'Andhari Wildlife Sanctuary',
        declared: '1986',
        district: 'Chandrapur',
      },
      {
        serial: '3',
        name: 'Aner Dam Wildlife Sanctuary',
        declared: '1986',
        district: 'Dhule',
      },
      {
        serial: '4',
        name: 'Bhamragarh Wildlife Sanctuary',
        declared: '1997',
        district: 'Gadchiroli',
      },
      {
        serial: '5',
        name: 'Bhimashankar Wildlife Sanctuary',
        declared: '1985',
        district: 'Pune, Raigad, Thane',
      },
      {
        serial: '6',
        name: 'Bor Wildlife Sanctuary',
        declared: '1970',
        district: 'Nagpur, Wardha',
      },
      {
        serial: '7',
        name: 'Chaprala Wildlife Sanctuary',
        declared: '1986',
        district: 'Gadchiroli',
      },
      {
        serial: '8',
        name: 'Deolgaon‑Rehkuri Wildlife Sanctuary',
        declared: '1980',
        district: 'Ahmednagar',
      },
      {
        serial: '9',
        name: 'Dnyanganga Wildlife Sanctuary',
        declared: '1997',
        district: 'Buldhana',
      },
      {
        serial: '10',
        name: 'Gautala Wildlife Sanctuary',
        declared: '1986',
        district: 'Aurangabad, Jalgaon',
      },
      {
        serial: '11',
        name: 'Ghodazari Wildlife Sanctuary',
        declared: '2018',
        district: 'Chandrapur',
      },
      {
        serial: '12',
        name: 'Great Indian Bustard Sanctuary',
        declared: '1979',
        district: 'Ahmednagar, Solapur',
      },
      {
        serial: '13',
        name: 'Isapur Wildlife Sanctuary',
        declared: '2014',
        district: 'Yavatmal',
      },
      {
        serial: '14',
        name: 'Jayakwadi Bird Sanctuary',
        declared: '1986',
        district: 'Ahmednagar, Aurangabad',
      },
      {
        serial: '15',
        name: 'Kalsubai Harishchandragad Wildlife Sanctuary',
        declared: '1986',
        district: 'Ahmednagar',
      },
      {
        serial: '16',
        name: 'Kanhargaon Wildlife Sanctuary[25]',
        declared: '2021',
        district: 'Chandrapur',
      },
      {
        serial: '17',
        name: 'Karanja Sohol Wildlife Sanctuary',
        declared: '2000',
        district: 'Akola',
      },
      {
        serial: '18',
        name: 'Karnala Bird Sanctuary',
        declared: '1968',
        district: 'Raigad',
      },
      {
        serial: '19',
        name: 'Katepurna Wildlife Sanctuary',
        declared: '1988',
        district: 'Akola',
      },
      {
        serial: '20',
        name: 'Koka Wildlife Sanctuary',
        declared: '2013',
        district: 'Bhandara',
      },
      {
        serial: '21',
        name: 'Koyna Wildlife Sanctuary',
        declared: '1985',
        district: 'Satara',
      },
      {
        serial: '22',
        name: 'Lonar Wildlife Sanctuary',
        declared: '2000',
        district: 'Buldhana',
      },
      {
        serial: '23',
        name: 'Malvan Wildlife Sanctuary',
        declared: '1987',
        district: 'Sindhudurg',
      },
      {
        serial: '24',
        name: 'Mayureswar Wildlife Sanctuary',
        declared: '1997',
        district: 'Pune',
      },
      {
        serial: '25',
        name: 'Mansingdeo Wildlife Sanctuary',
        declared: '2010',
        district: 'Nagpur',
      },
      {
        serial: '26',
        name: 'Melghat Wildlife Sanctuary',
        declared: '1985',
        district: 'Amravati',
      },
      {
        serial: '27',
        name: 'Nagzira Wildlife Sanctuary',
        declared: '1970',
        district: 'Bhandara',
      },
      {
        serial: '28',
        name: 'Naigaon Mayur Wildlife Sanctuary',
        declared: '1994',
        district: 'Beed',
      },
      {
        serial: '29',
        name: 'Nandur Madhameshwar Wildlife Sanctuary',
        declared: '1986',
        district: 'Nashik',
      },
      {
        serial: '30',
        name: 'Narnala Wildlife Sanctuary',
        declared: '1997',
        district: 'Akola',
      },
      {
        serial: '31',
        name: 'Nawegaon Wildlife Sanctuary',
        declared: '2012',
        district: 'Gondia',
      },
      {
        serial: '32',
        name: 'New Bor Wildlife Sanctuary',
        declared: '2012',
        district: 'Nagpur, Wardha',
      },
      {
        serial: '33',
        name: 'New Maldhok Bird (Gangewadi) Wildlife Sanctuary',
        declared: '2015',
        district: 'Solapur',
      },
      {
        serial: '34',
        name: 'New Nagzira Wildlife Sanctuary',
        declared: '2012',
        district: 'Bhandara',
      },
      {
        serial: '35',
        name: 'Painganga Wildlife Sanctuary',
        declared: '1986',
        district: 'Nanded, Yavatmal',
      },
      {
        serial: '36',
        name: 'Phansad Wildlife Sanctuary',
        declared: '1986',
        district: 'Raigad',
      },
      {
        serial: '37',
        name: 'Pranhita Wildlife Sanctuary',
        declared: '2014',
        district: 'Gadchiroli',
      },
      {
        serial: '38',
        name: 'Radhanagari Wildlife Sanctuary',
        declared: '1958',
        district: 'Kolhapur',
      },
      {
        serial: '39',
        name: 'Sagareshwar Wildlife Sanctuary',
        declared: '1985',
        district: 'Sangli',
      },
      {
        serial: '40',
        name: 'Sudhagad Wildlife Sanctuary',
        declared: '2014',
        district: 'Raigad',
      },
      {
        serial: '41',
        name: 'Tamhini Wildlife Sanctuary',
        declared: '2013',
        district: 'Pune',
      },
      {
        serial: '42',
        name: 'Tansa Wildlife Sanctuary',
        declared: '1970',
        district: 'Thane',
      },
      {
        serial: '43',
        name: 'Thane Creek Wildlife Sanctuary',
        declared: '2015',
        district: 'Thane',
      },
      {
        serial: '44',
        name: 'Tipeshwar Wildlife Sanctuary',
        declared: '1997',
        district: 'Yavatmal',
      },
      {
        serial: '45',
        name: 'Tungareshwar Wildlife Sanctuary',
        declared: '2003',
        district: 'Palghar',
      },
      {
        serial: '46',
        name: 'Umred Pauni Karhandla Wildlife Sanctuary',
        declared: '2012',
        district: 'Bhandara, Nagpur',
      },
      {
        serial: '47',
        name: 'Wan Wildlife Sanctuary',
        declared: '1997',
        district: 'Amravati',
      },
      {
        serial: '48',
        name: 'Yawal Wildlife Sanctuary',
        declared: '1969',
        district: 'Jalgaon',
      },
      {
        serial: '49',
        name: 'Yedsi Ramling Ghat Wildlife Sanctuary',
        declared: '1997',
        district: 'Osmanabad',
      },
    ],
  },
  {
    state: 'Manipur',
    sanctuaries: [
      {
        serial: '1',
        name: 'Bunning Wildlife Sanctuary',
        declared: '1997',
        district: 'Tamenglong',
      },
      {
        serial: '2',
        name: 'Jiri-Makru Wildlife Sanctuary',
        declared: '1997',
        district: 'Imphal East, Tamenglong',
      },
      {
        serial: '3',
        name: 'Kailam Wildlife Sanctuary',
        declared: '1997',
        district: 'Churachandpur',
      },
      {
        serial: '4',
        name: 'Khongjaingamba Ching Wildlife Sanctuary',
        declared: '2016',
        district: 'Imphal East',
      },
      {
        serial: '5',
        name: 'Thinungei Bird Sanctuary',
        declared: '2019',
        district: 'Bishnupur',
      },
      {
        serial: '6',
        name: 'Yangoupokpi-Lokchao Wildlife Sanctuary',
        declared: '1989',
        district: 'Chandel',
      },
      {
        serial: '7',
        name: 'Zeilad Wildlife Sanctuary',
        declared: '1997',
        district: 'Tamenglong',
      },
    ],
  },
  {
    state: 'Meghalaya',
    sanctuaries: [
      {
        serial: '1',
        name: 'Baghmara Pitcher Plant Wildlife Sanctuary',
        declared: '1984',
        district: 'South Garo Hills',
      },
      {
        serial: '2',
        name: 'Narpuh Wildlife Sanctuary',
        declared: '2014',
        district: 'East Jaintia Hills, West Jaintia Hills',
      },
      {
        serial: '3',
        name: 'Nongkhyllem Wildlife Sanctuary',
        declared: '1981',
        district: 'Ri Bhoi',
      },
      {
        serial: '4',
        name: 'Siju Wildlife Sanctuary',
        declared: '1979',
        district: 'South Garo Hills',
      },
    ],
  },
  {
    state: 'Mizoram',
    sanctuaries: [
      {
        serial: '1',
        name: 'Dampa Wildlife Sanctuary',
        declared: '1985',
        district: 'Aizawl',
      },
      {
        serial: '2',
        name: 'Khawnglung Wildlife Sanctuary',
        declared: '2000',
        district: 'Serchhip',
      },
      {
        serial: '3',
        name: 'Lengteng Wildlife Sanctuary',
        declared: '2002',
        district: 'Champhai',
      },
      {
        serial: '4',
        name: 'Ngengpui Wildlife Sanctuary',
        declared: '1997',
        district: 'Lawngtlai',
      },
      {
        serial: '5',
        name: 'Pualreng Wildlife Sanctuary',
        declared: '2013',
        district: 'Kolasib',
      },
      {
        serial: '6',
        name: 'Tawi Wildlife Sanctuary',
        declared: '2001',
        district: 'Lunglei',
      },
      {
        serial: '7',
        name: 'Thorangtlang Wildlife Sanctuary',
        declared: '2015',
        district: 'Lunglei',
      },
      {
        serial: '8',
        name: 'Tokalo Wildlife Sanctuary',
        declared: '2007',
        district: 'Saiha',
      },
    ],
  },
  {
    state: 'Nagaland',
    sanctuaries: [
      {
        serial: '1',
        name: 'Fakim Wildlife Sanctuary',
        declared: '1980',
        district: 'Tuensang',
      },
      {
        serial: '2',
        name: 'Puliebadze Wildlife Sanctuary',
        declared: '1980',
        district: 'Kohima',
      },
      {
        serial: '3',
        name: 'Rangapahar Wildlife Sanctuary',
        declared: '1986',
        district: 'Dimapur',
      },
      {
        serial: '4',
        name: 'Singphan Wildlife Sanctuary',
        declared: '2009',
        district: 'Mon',
      },
    ],
  },
  {
    state: 'Odisha',
    sanctuaries: [
      {
        serial: '1',
        name: 'Badrama Wildlife Sanctuary',
        declared: '1962',
        district: 'Sambalpur',
      },
      {
        serial: '2',
        name: 'Baisipalli Wildlife Sanctuary',
        declared: '1981',
        district: 'Nayagarh',
      },
      {
        serial: '3',
        name: 'Balukhand-Konark Wildlife Sanctuary',
        declared: '1984',
        district: 'Puri',
      },
      {
        serial: '4',
        name: 'Bhitarkanika Wildlife Sanctuary',
        declared: '1975',
        district: 'Kendrapara',
      },
      {
        serial: '5',
        name: 'Chandaka Dampara Wildlife Sanctuary',
        declared: '1982',
        district: 'Khurda, Cuttack',
      },
      {
        serial: '6',
        name: 'Debrigarh Wildlife Sanctuary',
        declared: '1985',
        district: 'Sambalpur',
      },
      {
        serial: '7',
        name: 'Gahirmatha Marine Sanctuary',
        declared: '1997',
        district: 'Kendrapara',
      },
      {
        serial: '8',
        name: 'Hadgarh Wildlife Sanctuary',
        declared: '1978',
        district: 'Keonjhar, Mayurbhanj',
      },
      {
        serial: '9',
        name: 'Kapilasa Wildlife Sanctuary',
        declared: '2011',
        district: 'Dhenkanal',
      },
      {
        serial: '10',
        name: 'Karlapat Wildlife Sanctuary',
        declared: '1992',
        district: 'Kalahandi',
      },
      {
        serial: '11',
        name: 'Khalasuni Wildlife Sanctuary',
        declared: '1982',
        district: 'Sambalpur',
      },
      {
        serial: '12',
        name: 'Kotgarh Wildlife Sanctuary',
        declared: '1981',
        district: 'Phulbani',
      },
      {
        serial: '13',
        name: 'Kuldiha Wildlife Sanctuary',
        declared: '1984',
        district: 'Balasore',
      },
      {
        serial: '14',
        name: 'Lakhari Valley Wildlife Sanctuary',
        declared: '1985',
        district: 'Gajapati',
      },
      {
        serial: '15',
        name: 'Nalbana Bird Sanctuary',
        declared: '1987',
        district: 'Ganjam, Khurda, Puri',
      },
      {
        serial: '16',
        name: 'Nandankanan Wildlife Sanctuary',
        declared: '1979',
        district: 'Khurda',
      },
      {
        serial: '17',
        name: 'Satkosia Gorge Wildlife Sanctuary',
        declared: '1976',
        district: 'Angul, Boudh, Cuttack',
      },
      {
        serial: '18',
        name: 'Simlipal Wildlife Sanctuary',
        declared: '1979',
        district: 'Mayurbhanj',
      },
      {
        serial: '19',
        name: 'Sunabeda Wildlife Sanctuary',
        declared: '1988',
        district: 'Nuapada',
      },
    ],
  },
  {
    state: 'Punjab',
    sanctuaries: [
      {
        serial: '1',
        name: 'Abohar Wildlife Sanctuary',
        declared: '1988',
        district: 'Firozpur',
      },
      {
        serial: '2',
        name: 'Bir Aishvan Wildlife Sanctuary',
        declared: '1952',
        district: 'Sangrur',
      },
      {
        serial: '3',
        name: 'Bir Bhadson Wildlife Sanctuary',
        declared: '1952',
        district: 'Patiala',
      },
      {
        serial: '4',
        name: 'Bir Bhunerheri Wildlife Sanctuary',
        declared: '1952',
        district: 'Patiala',
      },
      {
        serial: '5',
        name: 'Bir Dosanjh Wildlife Sanctuary',
        declared: '1952',
        district: 'Patiala',
      },
      {
        serial: '6',
        name: 'Bir Gurdialpura Wildlife Sanctuary',
        declared: '1977',
        district: 'Patiala',
      },
      {
        serial: '7',
        name: 'Bir Mehaswala Wildlife Sanctuary',
        declared: '1952',
        district: 'Patiala',
      },
      {
        serial: '8',
        name: 'Bir Motibagh Wildlife Sanctuary',
        declared: '1952',
        district: 'Patiala',
      },
      {
        serial: '9',
        name: 'Harike Lake Wildlife Sanctuary',
        declared: '1982',
        district: 'Firozpur',
      },
      {
        serial: '10',
        name: 'Jhajjar Bacholi Wildlife Sanctuary',
        declared: '1998',
        district: 'Rupnagar',
      },
      {
        serial: '11',
        name: 'Kathlaur Kushlian Wildlife Sanctuary',
        declared: '2007',
        district: 'Gurdaspur',
      },
      {
        serial: '12',
        name: 'Nangal Wildlife Sanctuary',
        declared: '2009',
        district: 'Rupnagar',
      },
      {
        serial: '13',
        name: 'Takhni-Rehampur Wildlife Sanctuary',
        declared: '1992',
        district: 'Hoshiarpur',
      },
    ],
  },
  {
    state: 'Puducherry',
    sanctuaries: [
      {
        serial: '1',
        name: 'Oussudu Bird Sanctuary',
        declared: '2008',
        district: 'Puducherry',
      },
    ],
  },
  {
    state: 'Rajasthan',
    sanctuaries: [
      {
        serial: '1',
        name: 'Bandh Baretha Wildlife Sanctuary',
        declared: '1985',
        district: 'Bharatpur, Karauli',
      },
      {
        serial: '2',
        name: 'Bassi Wildlife Sanctuary',
        declared: '1988',
        district: 'Chittaurgarh',
      },
      {
        serial: '3',
        name: 'Bhensrodgarh Wildlife Sanctuary',
        declared: '1983',
        district: 'Chittaurgarh',
      },
      {
        serial: '4',
        name: 'Darrah Wildlife Sanctuary',
        declared: '1955',
        district: 'Jhalawar, Kota',
      },
      {
        serial: '5',
        name: 'Desert National Sanctuary',
        declared: '1981',
        district: 'Barmer, Jaisalmer',
      },
      {
        serial: '6',
        name: 'Jaisamand Wildlife Sanctuary',
        declared: '1955',
        district: 'Rajsamand',
      },
      {
        serial: '7',
        name: 'Jamwa Ramgarh Wildlife Sanctuary',
        declared: '1982',
        district: 'Jaipur',
      },
      {
        serial: '8',
        name: 'Jawahar Sagar Wildlife Sanctuary',
        declared: '1975',
        district: 'Kota',
      },
      {
        serial: '9',
        name: 'Kailadevi Wildlife Sanctuary',
        declared: '1983',
        district: 'Karauli',
      },
      {
        serial: '10',
        name: 'Kesarbagh Wildlife Sanctuary',
        declared: '1955',
        district: 'Dholpur',
      },
      {
        serial: '11',
        name: 'Kumbhalgarh Wildlife Sanctuary',
        declared: '1971',
        district: 'Pali, Udaipur',
      },
      {
        serial: '12',
        name: 'Mount Abu Wildlife Sanctuary',
        declared: '1960',
        district: 'Sirohi',
      },
      {
        serial: '13',
        name: 'Nahargarh Wildlife Sanctuary',
        declared: '1980',
        district: 'Jaipur',
      },
      {
        serial: '14',
        name: 'National Chambal Wildlife Sanctuary',
        declared: '1979',
        district: 'Kota',
      },
      {
        serial: '15',
        name: 'Phulwari ki Nal Wildlife Sanctuary',
        declared: '1983',
        district: 'Pali, Udaipur',
      },
      {
        serial: '16',
        name: 'Ramgarh Vishdhari Wildlife Sanctuary',
        declared: '1982',
        district: 'Bundi',
      },
      {
        serial: '17',
        name: 'Ramsagar Wildlife Sanctuary',
        declared: '1955',
        district: 'Dholpur',
      },
      {
        serial: '18',
        name: 'Sajjangarh Wildlife Sanctuary',
        declared: '1987',
        district: 'Udaipur',
      },
      {
        serial: '19',
        name: 'Sariska Wildlife Sanctuary',
        declared: '1955',
        district: 'Alwar',
      },
      {
        serial: '20',
        name: 'Sawai Madhopur Wildlife Sanctuary',
        declared: '1955',
        district: 'Sawai Madhopur',
      },
      {
        serial: '21',
        name: 'Sawai Man Singh Wildlife Sanctuary',
        declared: '1984',
        district: 'Sawai Madhopur',
      },
      {
        serial: '22',
        name: 'Shergarh Wildlife Sanctuary',
        declared: '1983',
        district: 'Kota',
      },
      {
        serial: '23',
        name: 'Sita Mata Wildlife Sanctuary',
        declared: '1979',
        district: 'Chittaurgarh, Udaipur',
      },
      {
        serial: '24',
        name: 'Tal Chhapar Wildlife Sanctuary',
        declared: '1971',
        district: 'Churu',
      },
      {
        serial: '25',
        name: 'Todgarh-Raoli Wildlife Sanctuary',
        declared: '1983',
        district: 'Ajmer, Pali, Rajsamand',
      },
      {
        serial: '26',
        name: 'Van Vihar Wildlife Sanctuary',
        declared: '1955',
        district: 'Dholpur',
      },
    ],
  },
  {
    state: 'Sikkim',
    sanctuaries: [
      {
        serial: '1',
        name: 'Fambong Lho Wildlife Sanctuary',
        declared: '1984',
        district: 'East Sikkim',
      },
      {
        serial: '2',
        name: 'Kitam Bird Sanctuary',
        declared: '2005',
        district: 'Namchi',
      },
      {
        serial: '3',
        name: 'Kyongnosla Alpine Sanctuary',
        declared: '1977',
        district: 'East Sikkim',
      },
      {
        serial: '4',
        name: 'Maenam Wildlife Sanctuary',
        declared: '1987',
        district: 'South Sikkim',
      },
      {
        serial: '5',
        name: 'Pangolakha Wildlife Sanctuary',
        declared: '2002',
        district: 'East Sikkim',
      },
      {
        serial: '6',
        name: 'Shingba Rhododendron Sanctuary',
        declared: '1984',
        district: 'North Sikkim',
      },
      {
        serial: '7',
        name: 'Varsey Rhododendron Sanctuary',
        declared: '1998',
        district: 'West Sikkim',
      },
    ],
  },
  {
    state: 'Tamil Nadu',
    sanctuaries: [
      {
        serial: '1',
        name: 'Anamalai Wildlife Sanctuary',
        declared: '1976',
        district: 'Coimbatore, Tiruppur',
      },
      {
        serial: '2',
        name: 'Cauvery North Wildlife Sanctuary',
        declared: '2014',
        district: 'Dharmapuri, Krishnagiri',
      },
      {
        serial: '3',
        name: 'Cauvery South Wildlife Sanctuary',
        declared: '2022',
        district: 'Dharmapuri, Krishnagiri',
      },
      {
        serial: '4',
        name: 'Chitrangudi Bird Sanctuary',
        declared: '1989',
        district: 'Ramanathapuram',
      },
      {
        serial: '5',
        name: 'Gangaikondan Spotted Deer Sanctuary',
        declared: '2013',
        district: 'Tirunelveli',
      },
      {
        serial: '6',
        name: 'Grizzled Squirrel Wildlife Sanctuary',
        declared: '1988',
        district: 'Virudhunagar',
      },
      {
        serial: '7',
        name: 'Kadavur Wildlife Sanctuary',
        declared: '2022',
        district: 'Dindigul, Karur',
      },
      {
        serial: '8',
        name: 'Kalakkad Wildlife Sanctuary',
        declared: '1976',
        district: 'Tirunelveli',
      },
      {
        serial: '9',
        name: 'Kallaperambur Lake Bird Sanctuary',
        declared: '2015',
        district: 'Thanjavur',
      },
      {
        serial: '10',
        name: 'Kanjirankulam Bird Sanctuary',
        declared: '1989',
        district: 'Ramanathapuram',
      },
      {
        serial: '11',
        name: 'Kanyakumari Wildlife Sanctuary',
        declared: '2007',
        district: 'Kanyakumari',
      },
      {
        serial: '12',
        name: 'Karaivetti Bird Sanctuary',
        declared: '1999',
        district: 'Perambalur',
      },
      {
        serial: '13',
        name: 'Karikili Bird Sanctuary',
        declared: '1989',
        district: 'Kanchipuram',
      },
      {
        serial: '14',
        name: 'Kazhuveli Bird Sanctuary',
        declared: '2021',
        district: 'Villupuram',
      },
      {
        serial: '15',
        name: 'Kodaikanal Wildlife Sanctuary',
        declared: '2008',
        district: 'Dindigul, Theni',
      },
      {
        serial: '16',
        name: 'Koonthankulam Bird Sanctuary',
        declared: '1994',
        district: 'Tirunelveli',
      },
      {
        serial: '17',
        name: 'Megamalai Wildlife Sanctuary',
        declared: '2009',
        district: 'Madurai, Theni',
      },
      {
        serial: '18',
        name: 'Melaselvanur-Kilaselvanur Bird Sanctuary',
        declared: '2010',
        district: 'Ramanathapuram',
      },
      {
        serial: '19',
        name: 'Mudumalai Wildlife Sanctuary',
        declared: '1940',
        district: 'Nilgiris',
      },
      {
        serial: '20',
        name: 'Mundanthurai Wildlife Sanctuary',
        declared: '1962',
        district: 'Tirunelveli',
      },
      {
        serial: '21',
        name: 'Nanjarayan Tank Bird Sanctuary',
        declared: '2022',
        district: 'Tiruppur',
      },
      {
        serial: '22',
        name: 'Nellai Wildlife Sanctuary',
        declared: '2014',
        district: 'Tirunelveli',
      },
      {
        serial: '23',
        name: 'Point Calimere Wildlife and Bird Sanctuary',
        declared: '1967',
        district: 'Nagapattinam, Thanjavur, Thiruvarur',
      },
      {
        serial: '24',
        name: 'Pulicat Lake Bird Sanctuary',
        declared: '1980',
        district: 'Tiruvallur',
      },
      {
        serial: '25',
        name: 'Sakkarakottai Bird Sanctuary',
        declared: '2012',
        district: 'Ramanathapuram',
      },
      {
        serial: '26',
        name: 'Sathyamangalam Wildlife Sanctuary',
        declared: '2008',
        district: 'Erode',
      },
      {
        serial: '27',
        name: 'Thanthai Periyar Wildlife Sanctuary',
        declared: '2023[27]',
        district: 'Erode',
      },
      {
        serial: '28',
        name: 'Therthangal Bird Sanctuary',
        declared: '2010',
        district: 'Ramanathapuram',
      },
      {
        serial: '29',
        name: 'Udayamarthandapuram Bird Sanctuary',
        declared: '1998',
        district: 'Thiruvarur',
      },
      {
        serial: '30',
        name: 'Vaduvoor Bird Sanctuary',
        declared: '1991',
        district: 'Thiruvarur',
      },
      {
        serial: '31',
        name: 'Vedanthangal Bird Sanctuary',
        declared: '1936',
        district: 'Chengalpattu',
      },
      {
        serial: '32',
        name: 'Vallanadu Wildlife Sanctuary',
        declared: '1987',
        district: 'Thoothukudi',
      },
      {
        serial: '33',
        name: 'Vellode Bird Sanctuary',
        declared: '2000',
        district: 'Erode',
      },
      {
        serial: '34',
        name: 'Vettangudi Bird Sanctuary',
        declared: '1977',
        district: 'Sivagangai',
      },
    ],
  },
  {
    state: 'Telangana',
    sanctuaries: [
      {
        serial: '1',
        name: 'Eturnagaram Wildlife Sanctuary',
        declared: '1953',
        district: 'Karimnagar, Warangal',
      },
      {
        serial: '2',
        name: 'Kawal Wildlife Sanctuary',
        declared: '1965',
        district: 'Adilabad',
      },
      {
        serial: '3',
        name: 'Kinnerasani Wildlife Sanctuary',
        declared: '1977',
        district: 'Khammam',
      },
      {
        serial: '4',
        name: 'Manjira Wildlife Sanctuary',
        declared: '1978',
        district: 'Medak',
      },
      {
        serial: '5',
        name: 'Nagarjunsagar-Srisailam Tiger Reserve',
        declared: '1978',
        district: 'Mahabub Nagar, Nalgonda',
      },
      {
        serial: '6',
        name: 'Pakhal Wildlife Sanctuary',
        declared: '1952',
        district: 'Warangal',
      },
      {
        serial: '7',
        name: 'Pocharam Wildlife Sanctuary',
        declared: '1952',
        district: 'Medak, Nizamabad',
      },
      {
        serial: '8',
        name: 'Pranahita Wildlife Sanctuary',
        declared: '1980',
        district: 'Adilabad',
      },
      {
        serial: '9',
        name: 'Shivaram Wildlife Sanctuary',
        declared: '1978',
        district: 'Adilabad, Karimnagar',
      },
    ],
  },
  {
    state: 'Tripura',
    sanctuaries: [
      {
        serial: '1',
        name: 'Gumti Wildlife Sanctuary',
        declared: '1988',
        district: 'South Tripura',
      },
      {
        serial: '2',
        name: 'Rowa Wildlife Sanctuary',
        declared: '1988',
        district: 'North Tripura',
      },
      {
        serial: '3',
        name: 'Sepahijala Wildlife Sanctuary',
        declared: '1987',
        district: 'West Tripura',
      },
      {
        serial: '4',
        name: 'Trishna Wildlife Sanctuary',
        declared: '1988',
        district: 'South Tripura',
      },
    ],
  },
  {
    state: 'Uttar Pradesh',
    sanctuaries: [
      {
        serial: '1',
        name: 'Bakhira Wildlife Sanctuary',
        declared: '1990',
        district: 'Sant Kabir Nagar',
      },
      {
        serial: '2',
        name: 'Chandra Prabha Wildlife Sanctuary',
        declared: '1957',
        district: 'Chandauli',
      },
      {
        serial: '3',
        name: 'Dr. Bhimrao Ambedkar Bird Sanctuary',
        declared: '2003',
        district: 'Raebareli',
      },
      {
        serial: '4',
        name: 'Hastinapur Wildlife Sanctuary',
        declared: '1986',
        district: 'Bijnore, Ghaziabad, Jyotiba Nagar, Meerut, Muzaffarnagar',
      },
      {
        serial: '5',
        name: 'Kachhua Wildlife Sanctuary',
        declared: '1989',
        district: 'Varanasi',
      },
      {
        serial: '6',
        name: 'Kaimoor Wildlife Sanctuary',
        declared: '1982',
        district: 'Mirzapur, Sonbhadra',
      },
      {
        serial: '7',
        name: 'Katarniaghat Wildlife Sanctuary',
        declared: '1976',
        district: 'Bahraich',
      },
      {
        serial: '8',
        name: 'Kishanpur Wildlife Sanctuary',
        declared: '1972',
        district: 'Lakhimpur-Kheri, Shahjahanpur',
      },
      {
        serial: '9',
        name: 'Lakh Bahosi Wildlife Sanctuary',
        declared: '1988',
        district: 'Farrukhabad',
      },
      {
        serial: '10',
        name: 'Mahavir Swami Wildlife Sanctuary',
        declared: '1977',
        district: 'Lalitpur',
      },
      {
        serial: '11',
        name: 'National Chambal Wildlife Sanctuary',
        declared: '1979',
        district: 'Agra, Etawah',
      },
      {
        serial: '12',
        name: 'Nawabganj Bird Sanctuary',
        declared: '1984',
        district: 'Unnao, Lucknow',
      },
      {
        serial: '13',
        name: 'Okhla Wildlife Sanctuary',
        declared: '1990',
        district: 'Gautam Buddh Nagar',
      },
      {
        serial: '14',
        name: 'Parvati Arga Wildlife Sanctuary',
        declared: '1990',
        district: 'Gonda',
      },
      {
        serial: '15',
        name: 'Patna Bird Sanctuary',
        declared: '1990',
        district: 'Etah',
      },
      {
        serial: '16',
        name: 'Pilibhit Wildlife Sanctuary',
        declared: '2014',
        district: 'Pilibhit',
      },
      {
        serial: '17',
        name: 'Ranipur Wildlife Sanctuary',
        declared: '1977',
        district: 'Banda, Chitrakoot',
      },
      {
        serial: '18',
        name: 'Saman Bird Sanctuary',
        declared: '1990',
        district: 'Mainpuri',
      },
      {
        serial: '19',
        name: 'Samaspur Bird Sanctuary',
        declared: '1987',
        district: 'Rae Bareli',
      },
      {
        serial: '20',
        name: 'Sandi Bird Sanctuary',
        declared: '1990',
        district: 'Hardoi',
      },
      {
        serial: '21',
        name: 'Shekha Bird Sanctuary',
        declared: '2016',
        district: 'Aligarh',
      },
      {
        serial: '22',
        name: 'Sohagi Barwa Wildlife Sanctuary',
        declared: '1987',
        district: 'Maharajganj',
      },
      {
        serial: '23',
        name: 'Sohelwa Wildlife Sanctuary',
        declared: '1988',
        district: 'Balrampur, Shravasti',
      },
      {
        serial: '24',
        name: 'Sur Sarovar Bird Sanctuary',
        declared: '1991',
        district: 'Agra',
      },
      {
        serial: '25',
        name: 'Surha Tal Bird Sanctuary',
        declared: '1991',
        district: 'Ballia',
      },
      {
        serial: '26',
        name: 'Vijai Sagar Wildlife Sanctuary',
        declared: '1990',
        district: 'Mahoba',
      },
    ],
  },
  {
    state: 'Uttarakhand',
    sanctuaries: [
      {
        serial: '1',
        name: 'Askot Musk Deer Sanctuary',
        declared: '1986',
        district: 'Pithoragarh',
      },
      {
        serial: '2',
        name: 'Binsar Wildlife Sanctuary',
        declared: '1988',
        district: 'Almora',
      },
      {
        serial: '3',
        name: 'Govind Pashu Vihar Wildlife Sanctuary',
        declared: '1955',
        district: 'Uttarkashi',
      },
      {
        serial: '4',
        name: 'Kedarnath Wildlife Sanctuary',
        declared: '1972',
        district: 'Chamoli, Rudraprayag',
      },
      {
        serial: '5',
        name: 'Mussoorie Wildlife Sanctuary',
        declared: '1993',
        district: 'Dehradun',
      },
      {
        serial: '6',
        name: 'Nandhaur Wildlife Sanctuary',
        declared: '2012',
        district: 'Champawat, Nainital',
      },
      {
        serial: '7',
        name: 'Sonanadi Wildlife Sanctuary',
        declared: '1987',
        district: 'Pauri Garhwal',
      },
    ],
  },
  {
    state: 'West Bengal',
    sanctuaries: [
      {
        serial: '1',
        name: 'Ballabhpur Wildlife Sanctuary',
        declared: '1977',
        district: 'Birbhum',
      },
      {
        serial: '2',
        name: 'Bethuadahari Wildlife Sanctuary',
        declared: '1980',
        district: 'Nadia',
      },
      {
        serial: '3',
        name: 'Bibhutibhushan Wildlife Sanctuary',
        declared: '1985',
        district: 'North 24-Paraganas',
      },
      {
        serial: '4',
        name: 'Buxa Wildlife Sanctuary',
        declared: '1986',
        district: 'Jalpaiguri',
      },
      {
        serial: '5',
        name: 'Chapramari Wildlife Sanctuary',
        declared: '1976',
        district: 'Jalpaiguri',
      },
      {
        serial: '6',
        name: 'Chintamoni Kar Wildlife Sanctuary',
        declared: '1982',
        district: 'South 24 Parganas',
      },
      {
        serial: '7',
        name: 'Haliday Island Wildlife Sanctuary',
        declared: '1976',
        district: 'South 24-Paraganas',
      },
      {
        serial: '8',
        name: 'Jore Pokhri Wildlife Sanctuary',
        declared: '1985',
        district: 'Darjeeling',
      },
      {
        serial: '9',
        name: 'Lothian Island Wildlife Sanctuary',
        declared: '1976',
        district: 'South 24-Paraganas',
      },
      {
        serial: '10',
        name: 'Mahananda Wildlife Sanctuary',
        declared: '1976',
        district: 'Darjeeling',
      },
      {
        serial: '11',
        name: 'Pakhibitan Wildlife Sanctuary',
        declared: '2011',
        district: 'Jalpaiguri',
      },
      {
        serial: '12',
        name: 'Raiganj Wildlife Sanctuary',
        declared: '1985',
        district: 'North Dinajpur',
      },
      {
        serial: '13',
        name: 'Ramnabagan Wildlife Sanctuary',
        declared: '1981',
        district: 'Burdwan',
      },
      {
        serial: '14',
        name: 'Sajnakhali Wildlife Sanctuary',
        declared: '1976',
        district: 'South 24-Paraganas',
      },
      {
        serial: '15',
        name: 'Senchal Wildlife Sanctuary',
        declared: '1976',
        district: 'Darjeeling',
      },
      {
        serial: '16',
        name: 'West Sunderban Wildlife Sanctuary',
        declared: '2013',
        district: 'South 24-Paraganas',
      },
    ],
  },
] satisfies readonly WildlifeSanctuaryStateGroup[]

export const wildlifeSanctuariesTitleLine = 'Wildlife Sanctuaries in India (576)' as const
