export const currentAffairsQuiz = {
  quizzes: {
    'quiz-1': [
      {
        id: 1,
        question: "India won its first ever Commonwealth Games gold medal in which sport?",
        options: [
        "Athletics",
        "Hockey",
        "Tennis",
        "Badminton",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "The Gold Monetisation Scheme was launched in which year?",
        options: [
        "2015",
        "2016",
        "2017",
        "2018",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "The \"Global Engagement Scheme\" is implemented by which of the following ministries?",
        options: [
        "External Affairs",
        "Home Affairs",
        "Ministry of Culture",
        "Ministry of Tourism",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Who was the first Indian badminton player to win a gold medal at the Olympics?",
        options: [
        "P V Sindhu",
        "Sania Mirza",
        "Saina Nehwal",
        "PT Usha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Which global event in 1992 popularized sustainable development?",
        options: [
        "Kyoto Protocol",
        "Rio Earth Summit",
        "Montreal Protocol",
        "Paris Agreement",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Which famous Indian classical singer was awarded the Bharat Ratna in 1998 for her contribution to Carnatic music?",
        options: [
        "M.S. Subbulakshmi",
        "Aruna Sairam",
        "Shubha Mudgal",
        "Kishori Amonkar",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "Inida adopted the United Nations Sustainable Development Goals (SDGs) in which year?",
        options: [
        "2015",
        "2016",
        "2017",
        "2018",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "In which year was the first Regional Rural Banks (RRB) established in India?",
        options: [
        "1975",
        "1976",
        "1977",
        "1978",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Which of the following renowned Indian musicians performed at the Red Fort on the occasion of India's Independence Day in 1947?",
        options: [
        "Ravi Shankar",
        "Ustad Bismillah Khan",
        "Bhimsen Joshi",
        "Hari Prasad Chaurasia",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Folk songs of Haryana are commonly known by which of the following names?",
        options: [
        "Baul",
        "Bhand",
        "Bihu",
        "Raganis",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "Which folk music form of Uttar Pradesh is traditionally sung during the monsson season by women?",
        options: [
        "Bhatiali",
        "Kajri",
        "Lavani",
        "Maang",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "The report \"Strategic Roadmap for Making Ayurveda Global\", relased by NITI Aayog in July 2026, aims to transform Ayurveda into a globally recognized healthcare system by __________.",
        options: [
        "2030",
        "2035",
        "2040",
        "2047",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "The Government of India launched the Smart Cities Mission in which year?",
        options: [
        "2015",
        "2016",
        "2017",
        "2018",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Which Indian Musician and sitar player is the founder of the National Orchestra of India?",
        options: [
        "Ravi Shankar",
        "Ustad Bismillah Khan",
        "Bhimsen Joshi",
        "Hari Prasad Chaurasia",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "Who among the following renowned musicians is celebrated for popularising the unique instrument knonw as the \"Sarod\" and is considered one of the most famous maestros of the Senia Shahjahanpur Gharana?",
        options: [
        "Ustad Amjad Ali Khan",
        "Ustad Bismillah Khan",
        "Ustad Allarakha",
        "Ustad Zakir Hussain",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "Which of the following is the highest award in the Rashtriya Vigyan Puraskar awards",
        options: [
        "Vigyan vajra",
        "Vighay Mahan",
        "Vighay Shri",
        "Vigyan Ratna",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "International Plastic Free Day is observed on which date?",
        options: [
        "03 June",
        "03 July",
        "03 August",
        "03 September",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "The Borjuli Wild Rice Site in Assam was notified as a Biodiversity Heritage Site (BHS) under which Act?",
        options: [
        "The Biological Diversity Act, 2002",
        "The Environment Protection Act, 1986",
        "The Forest Act, 1927",
        "The Wildlife Protection Act, 1972",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "After receiving 23 new Geographical Indication (GI) tags in June 2026, West Bengal ranked __________ nationally with a total of 59 GI registrations.",
        options: [
        "First",
        "Second",
        "Third",
        "Fourth",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "In which year was the Integrated Child Development Scheme (ICDS) launched in India?",
        options: [
        "1975",
        "1976",
        "1977",
        "1978",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "The Green Revolution was commenced under the leadership of whom among the following Prime Ministers of India?",
        options: [
        "Indira Gandhi",
        "Rajiv Gandhi",
        "Morarji Desai",
        "Lal Bahadur Shastri",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "The first Indian woman judge of the Supreme Court of India was",
        options: [
        "Justice Indira Banerjee",
        "Justice Indu Malhotra",
        "Justice Bhanumati Joshi",
        "Fatima Beevi",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "After receiving 8 new Geographical Indication (GI) tags in July 2026, the total number of GI-tagged products in Himachal Pradesh reached __________.",
        options: [
        "14",
        "15",
        "16",
        "17",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "How many Tiger Reserves have been indentified by the Government of India for priority recovery through science-led Interventions in June 2026?",
        options: [
        "20",
        "22",
        "24",
        "25",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "__________ or \"Dance of Enchantress\" is a solo dance, performed by primarily by women, in the state of Kerala.",
        options: [
        "Bharatanatyam",
        "Kathak",
        "Kathakali",
        "Mohiniyattam",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-2': [
      {
        id: 1,
        question: "Which of the following dance forms is known as the mother of all other classical dance forms of India?",
        options: [
        "Bharatanatyam",
        "Kathak",
        "Kathakali",
        "Mohiniyattam",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Which of the following indicates the correct number of main regional styles of the classical Chhau dance form?",
        options: [
        "2",
        "3",
        "4",
        "5",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "Name the famous Malayalam poet who was instrumental in the revival of Kathakali as an art form.",
        options: [
        "Kumaranasan",
        "Ullor Parameswara Iyer",
        "Vallathol Narayana Menon",
        "Vyloppilli Srredhara Menon",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Which classical dance form was traditionally performed by Maharis (female temple dancers) in the sanctum of Jagannath Temple, Puri?",
        options: [
        "Bharatanatyam",
        "Sattriya",
        "Odissi",
        "Mohiniyattam",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Guru Bipin Singh was a legend in the field of which classical dance form?",
        options: [
        "Bharatanatyam",
        "Manipuri",
        "Odissi",
        "Mohiniyattam",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Sitara Devi was a dancer of the popular North Indian classical dance form __________.",
        options: [
        "Kathak",
        "Manipuri",
        "Kathakali",
        "Sattriya",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "Guru Pankaj Charan and Guru Debaprasad Das are associated with which of the following classical dance forms?",
        options: [
        "Odissi",
        "Manipuri",
        "Kathak",
        "Sattriya",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "Which Five-year Plan primarily focused on the \"Garibi Hatao\" slogan?",
        options: [
        "First Five-year Plan",
        "Third Five-year Plan",
        "Fourth Five-year Plan",
        "Fifth Five-year Plan",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Which of the following is the correct number of main regional styles of the classical Manipuri dance form?",
        options: [
        "2",
        "3",
        "4",
        "5",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Which of the following Indian Stadium is renowned as a major venue for Hockey matches?",
        options: [
        "Chidambaram Stadium",
        "Chinnaswamy Stadium",
        "Kalinga Stadium",
        "Feroz Shah Kotla Stadium",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "With what musical instrument is Ustad Binda Khan associated?",
        options: [
        "Sitar",
        "Sarangi",
        "Sarod",
        "Tabla",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "Warli painting, a traditional tribal art form, originates from which Indian state?",
        options: [
        "Maharashtra",
        "Madhya Pradesh",
        "Rajasthan",
        "Gujarat",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "\"Lu-Ngai-Ni\" festival is celebrated in which Indian state?",
        options: [
        "Manipur",
        "Meghalaya",
        "Mizoram",
        "Nagaland",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Which of the following commissions recommended the creation of the Inter-State Council?",
        options: [
        "Rajaji Commission",
        "Mohanlal Sukhadia Commission",
        "Nariman Commission",
        "Sarkaria Commission",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "Which Indian athlete won the nations first-ever Asian Games gold medal?",
        options: [
        "K D Jadhav",
        "Milkha Singh",
        "Primal Roy",
        "Sachin Nag",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "Minor points called \"Yuko\" are part of which of the following sports?",
        options: [
        "Hockey",
        "Basketball",
        "Skating",
        "Judo",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "In which year was radio broadcasting started in India by the Radio Club of Bombay?",
        options: [
        "1923",
        "1928",
        "1929",
        "1930",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "Which city is popularly known as the \"City of Dreaming Spires\"?",
        options: [
        "London",
        "Paris",
        "Rome",
        "Oxford",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "The term _______ is used to describe those receipts which can not be claimed from the government and are non redeemable",
        options: [
        "Capital Receipts",
        "Revenue Receipts",
        "Unsecured Receipts",
        "Non-Convertible Receipts",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Viksit Bharat-Guarantee for Rozgar and Ajeevika Mission (Grameen)[VB-G RAM G]Act, 2025 will come into effect from which date?",
        options: [
        "01 July 2026",
        "01 August 2026",
        "01 September 2026",
        "01 October 2026",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "Under the VB-G RAM G Bill, what is the reivsed annual employment guarantee per rural household?",
        options: [
        "100 days",
        "110 days",
        "120 days",
        "125 days",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "When a person is NOT paying anything for public goods, it is known as _______.",
        options: [
        "Free Rider",
        "Private good",
        "Rivalrous good",
        "Non-rivalrous good",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "Which of the following is the coverage provided by the \"Pradhan Mantri Suraksha Bima Yojana\" (PMSBY)\" in case of Partial disability?",
        options: [
        "1 lakh",
        "2 lakh",
        "3 lakh",
        "4 lakh",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "During the 80th Independence Day celebrations in 2026, Prime Minister Narendra Modi introduced a new framework to accelerate India's journey towards becoming a Viksit Bharat.",
        options: [
        "Amrit Kal Mission",
        "Panch Pran",
        "Sapta Dhara",
        "Viksit Bharat Sankalp",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "India won its first-ever Common Wealth Games gold medal in which sport?",
        options: [
        "Hockey",
        "Athletics",
        "Weightlifting",
        "Wrestling",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-3': [
      {
        id: 1,
        question: "In which year was the first Regional Bank established in India?",
        options: [
        "1975",
        "1980",
        "1982",
        "1985",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "The report \"Strategic Roadmap for Making Ayurveda Global\", released by NITI Aayog in July 2026, aims to make Ayurveda a global brand by which year?",
        options: [
        "2030",
        "2035",
        "2047",
        "2050",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "The Companies Act, _______ is an act to consolidate and amend the law relating to companies.",
        options: [
        "2005",
        "2013",
        "2015",
        "2017",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Who among the following is India's first-ever two-time Olympic medallist in an individual event and the first Indian to win a wrestling world championship?",
        options: [
        "Sushil Kumar",
        "Vijay Kumar",
        "Yogeshwar Dutt",
        "Harpreet Singh",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Which of the following is India's first Integrated Green Field Smart City?",
        options: [
        "Atal Nagar, Chhattisgarh",
        "Bengaluru, Karnataka",
        "Bhopal, Madhya Pradesh",
        "Chennai, Tamil Nadu",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "In the year 2010, the Government of India had categorised which animal as the National Heritage Animal of India?",
        options: [
        "Dolphin",
        "Elephant",
        "Lion",
        "Cheetah",
        ],
        correctAnswer: undefined,
      }
    ],
  },
}
