export const geographyQuiz = {
  quizzes: {
    'quiz-1': [
      {
        id: 1,
        question: "The seasonally shifting low-pressure belt near the equator where trade winds converge is best known as the _______",
        options: [
        "Subtropical high",
        "Inter-Tropical Convergence Zone (ITCZ)",
        "Polar front",
        "Aleutian low",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Western disturbances—extra-tropical cyclones embedded in subtropical westerly jet—most markedly impact winter weather over _______",
        options: [
        "Peninsular Kerala coast",
        "Northwest and adjoining northern India",
        "Andaman Sea only",
        "Chota Nagpur only",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "The summer monsoon over peninsular India is strengthened when the Tibetan Plateau heats and anchors a _______ aloft over Asia",
        options: [
        "Cold-core polar vortex at surface",
        "Warm anticyclone / high-pressure cell in the upper troposphere",
        "Permanent low in the stratosphere only",
        "Quasi-stationary easterly jet over 10°N always",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Which soil group, rich in iron and aluminium oxides due to intense leaching in humid tropics, turns iron-hard when baked?",
        options: [
        "Chernozem",
        "Laterite",
        "Tundra podzol",
        "Solonchak",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "The Western Ghats differ most strikingly from the Eastern Ghats in that they _______",
        options: [
        "Are discontinuous hills along the Odisha coast only",
        "Form an almost continuous wall intercepting rain-bearing winds off the Arabian Sea",
        "Lie entirely in the rain-shadow of the Bay of Bengal",
        "Have no effect on orographic rainfall",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "“Oxbow lakes” along mature floodplains form mainly due to _______",
        options: [
        "Volcanic caldera collapse",
        "Meander cut-offs and silting of abandoned channels",
        "Karst solution only",
        "Aeolian deflation basins",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "The Indian plate boundary with the Eurasian plate along the Himalayas is classically described as _______",
        options: [
        "Divergent ocean ridge",
        "Continental collision / suture zone with ongoing crustal shortening",
        "Transform fault like San Andreas only",
        "Subduction of Indian oceanic lithosphere under Tibet without collision",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "Composite volcanoes (stratovolcanoes) typical of subduction zones are characterised by _______",
        options: [
        "Only low-viscosity basalt shields like Mauna Loa",
        "Alternating layers of lava and pyroclastics—explosive and effusive episodes",
        "No pyroclastic hazard",
        "Flat flood basalt plateaus exclusively",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Low coral islands surrounding central lagoons, common in the Pacific and Indian Oceans, are called _______",
        options: [
        "Hornos",
        "Atolls",
        "Drumlins",
        "Tombolos",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "In Köppen’s scheme, a tropical savanna (Aw) climate is distinguished from rainforest (Af) chiefly by _______",
        options: [
        "Year-round surplus rainfall every month",
        "A distinct winter dry season with tree-grass vegetation mosaic",
        "Polar temperature means",
        "Year-round snow cover",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "Spring tides, which produce the largest tidal range, occur when _______",
        options: [
        "Moon is at quadrature with Sun (first/third quarter)",
        "Sun, Moon, and Earth are approximately aligned (full and new moon)",
        "Only during equatorial counter-current maxima",
        "Only when monsoon wind stress peaks",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "Limestone landscapes with sinkholes, caves, and disappearing streams arise from _______ weathering / erosion",
        options: [
        "Frost shattering",
        "Carbonation / solution karst",
        "Haloclasty only",
        "Pressure release in granite tors",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "Loess—fertile, wind-deposited silt mantles—are most famously extensive in _______",
        options: [
        "Amazon floodplain terraces",
        "North China Plain margins fed from Gobi desert sources",
        "Mid-Atlantic abyssal plain",
        "Basalt traps of the Deccan only",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Which Indian state has the longest mainland coastline (often cited in surveys excluding island UTs)?",
        options: [
        "Tamil Nadu",
        "Gujarat",
        "Maharashtra",
        "Andhra Pradesh",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "The Brahmaputra (Tsangpo in Tibet) enters India through which state before flowing into the Assam valley?",
        options: [
        "Nagaland",
        "Arunachal Pradesh",
        "Sikkim",
        "Manipur",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "“The Grand Canyon” scale V-shaped valleys in youthful mountain stages mostly reflect _______ dominance",
        options: [
        "Lateral planation",
        "Vertical down-cutting by streams",
        "Chemical solution only",
        "Solidluction",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "Which statement about the Indian peninsula’s east- and west-flowing rivers is most accurate?",
        options: [
        "All major peninsular rivers drain into the Arabian Sea",
        "Godavari and Krishna drain east; Narmada and Tapti drain west",
        "None crosses the Eastern Ghats",
        "Narmada rises in the Western Ghats and flows east to Bay of Bengal",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "The deepest oceanic trench on Earth is the _______ in the western Pacific",
        options: [
        "Puerto Rico Trench",
        "Mariana Trench",
        "Java Trench",
        "Tonga Trench",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "On 21 June (northern summer solstice), solar noon altitude is highest and day length is maximal at _______",
        options: [
        "Equator",
        "Tropic of Cancer (~23.5°N)",
        "Tropic of Capricorn",
        "North Pole only for entire planet",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Black (regur) soils of the Deccan traps derive much of their **vertisol** character from _______",
        options: [
        "Granite saprolite only",
        "Basaltic parent material with high clay (montmorillonite) swell–shrink",
        "Pure quartz sand",
        "Peat accumulation",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "Cold ocean currents along west coasts of continents (e.g., California, Peru) typically produce _______ surface conditions",
        options: [
        "Higher SST and frequent tropical cyclogenesis",
        "Cool, nutrient-rich upwelled waters supporting fisheries",
        "Brackish evaporation pans only",
        "Permanent sea ice to 40° latitude",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "Which landform chain runs roughly from Gujarat through Delhi–Haryana into Rajasthan as one of Earth’s oldest orogens?",
        options: [
        "Satpura",
        "Aravalli",
        "Vindhyan",
        "Garhwal",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "“Barchan” dunes are _______-shaped and migrate with the dominant wind",
        options: [
        "Linear ridges parallel to wind",
        "Crescentic with horns pointing downwind",
        "Star-shaped with equal arms",
        "Fixed parabolic openings upwind",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "The “roaring forties” of southern oceans refer to strong westerly winds near latitudes _______",
        options: [
        "0–10°",
        "20–30°",
        "roughly 40–50°S over open ocean",
        "70–80°N",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "Terrestrial “mid-latitude broadleaf and mixed forest” climates in Köppen are commonly labelled _______",
        options: [
        "BWk",
        "Cfa / Cfb (humid temperate with adequate precipitation)",
        "ET",
        "BWh",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-2': [
      {
        id: 1,
        question: "Destruction, weathering, dissolving, rainfall, and lithification are the major geological processes that contribute to the formation of which of the following rocks?",
        options: [
        "Igneous rocks",
        "Metamorphic rocks",
        "Sedimentary rocks",
        "Sub-metamorphic rocks",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Every year the Flamingo festival celebrated at the Pulicat Lake near the Nellapattu Bird Sanctuary in which state?",
        options: [
        "Tamil Nadu",
        "Andhra Pradesh",
        "Karnataka",
        "Kerala",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "Name the largest freshwater lake in India?",
        options: [
        "Dal Lake",
        "Wular Lake",
        "Pulicat Lake",
        "Nagarjuna Sagar Lake",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "India's \"SAGAR\" doctrine primarily focuses on which area of cooperation, security, and economic engangement in the Indo-Pacific region?",
        options: [
        "Cultural diplomacy",
        "Cyber security",
        "Defence manufacturing",
        "Maritime cooperation in the Indian Ocean",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Which of the following physiographic regions lies north of the Narmada River?",
        options: [
        "Deccan Plateau",
        "Karnataka Plateau",
        "Malwa Plateau",
        "Telangana Plateau",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "With reference to agriculture in India, what is \"Barani\"?",
        options: [
        "Deity of agriculture",
        "Rainfed farming",
        "Shifting agriculture",
        "Variety of maze",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "The Kali Tiger Reserve, where Mimeusemia kali was discovered, is located in which state?",
        options: [
        "Kerala",
        "Karnataka",
        "Madhya Pradesh",
        "Telangana",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "Which Indian state is known for the folk dance \"Chohara\"?",
        options: [
        "Gujarat",
        "Maharashtra",
        "Madhya Pradesh",
        "Himachal Pradesh",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Which of the following is the oldest landmass of India?",
        options: [
        "The Indus-Ganga plains",
        "The Indian desert",
        "The Peninsula plateau",
        "The Himalayan region",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Which of the following dances of Assam is associated with the workship of the snake goddess Manasa?",
        options: [
        "Bhor Tal Nritya",
        "Bagurumba",
        "Deodhani",
        "Jhumur",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "\"Chhau\" is a popular dance form of which Indian state?",
        options: [
        "Gujarat",
        "Kerala",
        "Jharkhand",
        "Chhattisgarh",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "Which of the following sources of underground water is derived from sedimentary rocks?",
        options: [
        "Connate water",
        "Juvinile water",
        "Saline water",
        "Meteoric water",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "The popular folk art of Phad painting is traditionally associated with which of the following Indian state?",
        options: [
        "Gujarat",
        "Maharashtra",
        "Madhya Pradesh",
        "Rajasthan",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "The Mediterranean region is best knwon for which type of vegetation?",
        options: [
        "Deciduous forests",
        "Coniferous forests",
        "Mangroves",
        "Scrub and drought-resistant trees",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "Which of the coastal plan is called the \"Hexadeltatic region\" or the \"Gift of Six Rivers\"?",
        options: [
        "Coastal plain of Odisha",
        "Coastal plain of Andhra Pradesh",
        "Coastal plain of Tamil Nadu",
        "Coastal plain of Karnataka",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "Which of the following states is known for extensive cultivation of coffee in India?",
        options: [
        "Tamil Nadu",
        "Kerala",
        "Karnataka",
        "Andhra Pradesh",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "Kakrapar Irrigation Project is situated on the bank of which river?",
        options: [
        "Bhagirathi",
        "Krishna",
        "Godavari",
        "Tapi",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "The fertile alluvial soils of the Great Indian Plains are mostly suited for the cultivation of which of the following crops?",
        options: [
        "Coffee and Tea",
        "Rice and Wheat",
        "Pulses and Oilseeds",
        "Cotton and Sugarcane",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "Which of the following crops is associated with plantation agriculture in India?",
        options: [
        "Bajra",
        "Wheat",
        "Tea",
        "Cotton",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "In which state is the shifting agriculture known as \"Jhum\" practiced?",
        options: [
        "Assam",
        "Bihar",
        "Madhya Pradesh",
        "Rajasthan",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "\"Zero tillage\" farming a technique that minimizes soil distrubance is primarily practiced in the cultivation of which of the following crops in India?",
        options: [
        "Banana",
        "Wheat",
        "Cotton",
        "Sugarcane",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "Which of the following is known as the \"Golden Fields\" of India?",
        options: [
        "Cotton",
        "Jute",
        "Maize",
        "Wheat",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "Which of the following Canal links the North Sea to Baltic Sea?",
        options: [
        "Corinth Canal",
        "Kiel Canal",
        "Panama Canal",
        "Suez Canal",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "The Vindhyan range separates which two major physiographic regions of India?",
        options: [
        "The Deccan Plateau and the Northern Plains",
        "The Deccan Plateau and the Western Ghats",
        "The Deccan Plateau and the Eastern Ghats",
        "The Deccan Plateau and the Western Ghats",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "Which templess garbhagriha houses a Chaturmukha (four-faced) Vishnu idol?",
        options: [
        "Lakshmana Temple, Khajuraho",
        "Meenakshi temple, Madurai",
        "Brihadeeshwara Temple, Tanjavur",
        "Dashavatara Temple, Deogarh",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-3': [
      {
        id: 1,
        question: "What is the priary material used in the 8th century CE Kailashnath Temple at Kanchipuram?",
        options: [
        "Granite",
        "Marble",
        "Sandstone",
        "Limestone",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Which of the following crops is mainly associated with Kharif season in Northern India?",
        options: [
        "Rice",
        "Wheat",
        "Cotton",
        "Sugarcane",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "On which of the tributaries of Ganga river, has Gandhi Sagar Dam been constructed?",
        options: [
        "Bhagirathi",
        "Yamuna",
        "Gandak",
        "Chambal",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Which Indian region is known for the monatic music tradition that includes sacred chants with dumbeats called \"Yang\"?",
        options: [
        "Goa",
        "Gujarat",
        "Kerala",
        "Ladakh",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Ananthapura Lake, often mentioned in Indian geography, is located in which of the following Indian state?",
        options: [
        "Kerala",
        "Karnataka",
        "Madhya Pradesh",
        "Tamil Nadu",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "The first Sugar mill in India was established in which of the following Indian state?",
        options: [
        "Bihar",
        "West Bengal",
        "Madhya Pradesh",
        "Tamil Nadu",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "Thang-Ta, often mentioned in cultural heritage, is associated with which of the following Indian state?",
        options: [
        "Manipur",
        "Kerala",
        "Madhya Pradesh",
        "Tamil Nadu",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "Gir Forest National Park is famous for the conservation of which of the following animal?",
        options: [
        "Asian Lion",
        "Siberian Tiger",
        "Indian Elephant",
        "Indian Rhinoceros",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Lai Haraoba, which literally means \"The festival of gods\" is primarily celebrated in which of the following Indian state?",
        options: [
        "Manipur",
        "Kerala",
        "Madhya Pradesh",
        "Tamil Nadu",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Which festival is celebrated to commemorate the birth anniversary of Lord Buddha?",
        options: [
        "Vesak",
        "Parinirvan day",
        "Kathina",
        "Ullambana",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "Which glacier located in the Karakoram range, is the longest in this range and the second longest in the world outside the polar regions?",
        options: [
        "Siachen Glacier",
        "Baltoro Glacier",
        "Ghanche Glacier",
        "Nubra Glacier",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "Which of the following is NOT a tributary of the Ganga river?",
        options: [
        "Yamuna",
        "Gandak",
        "Kosi",
        "Lohit",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "El Nino is a climate pattern that describes the unusal warming of surface water in which ocean?",
        options: [
        "Pacific Ocean",
        "Atlantic Ocean",
        "Indian Ocean",
        "Arctic Ocean",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Which is the water body that separates Andaman Islands and Nicobar Islands?",
        options: [
        "Eight Degree Channel",
        "Nine Degree Channel",
        "Ten Degree Channel",
        "Eleven Degree Channel",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "In India, the musical instrument \"Flute\" is also known as _______.",
        options: [
        "Bansuri",
        "Veena",
        "Manjira",
        "Tabla",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "Bharatanatyam of Tamil Nadu has grow out of the art of dancers dedicated to temples, and was earler known as _______.",
        options: [
        "Cholom",
        "Gat",
        "Jagoi",
        "Sadir",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "The Balimela Power Plant is located in which of the following Indian state?",
        options: [
        "Odisha",
        "Andhra Pradesh",
        "Karnataka",
        "Tamil Nadu",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "The Vindhyan range separates which two major physiographic regions of India?",
        options: [
        "The Deccan Plateau and the Northern Plains",
        "The Deccan Plateau and the Western Ghats",
        "The Deccan Plateau and the Eastern Ghats",
        "The Deccan Plateau and the Western Ghats",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "In which part of the India does the pre-monsoon \"Mango Rain\" occur?",
        options: [
        "Andhra Pradesh + Odisha",
        "Kerala + Karnataka",
        "West Bengal + Assam",
        "West Bengal + Odisha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Which of the following water body separates Sicily from Italy?",
        options: [
        "Strait of Messina",
        "Strait of Gibraltar",
        "Strait of Bonifacio",
        "Strait of Bosporus",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "Who put the continental drift theory in 1912?",
        options: [
        "Abraham Ortelius",
        "Antonia Pellegrini",
        "Alfred Wegener",
        "Arthur Holmes",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "In which of the following types of vegetation would we find species like ebony, mahogany, and rosewood?",
        options: [
        "Montane forests",
        "Tropical deciduous forests",
        "Mangroves forests",
        "Tropical evergreen forests",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "Which of the following is formed by each step of the food chain?",
        options: [
        "Ozone layer",
        "Stratosphere level",
        "Tropic level",
        "Troposphere level",
        ],
        correctAnswer: undefined,
      }
    ],
  },
}
