export const historyQuiz = {
  quizzes: {
    'quiz-1': [
      {
        id: 1,
        question: "Which of the following sites would be suitable for observing the architecture of the Harappan Civilization?",
        options: [
        "Banawali",
        "Sanchi",
        "Sunabeda",
        "Valparai",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "The Iron age site named Tekwada is located in the state of",
        options: [
        "Maharashtra",
        "Madhya Pradesh",
        "Gujarat",
        "Rajasthan",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "Which was the prominent architectural feature of the Indus Valley towns and cities?",
        options: [
        "Citadel",
        "False arch",
        "Pyramids",
        "Stupas",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Fire altars were found in which of the following groups of Harappan cities?",
        options: [
        "Banawali and Chanhudaro",
        "Kalibangan and Lothal",
        "Mohenjo-daro and Harappa",
        "Dholavira and Dholavira",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Which of the following Indus Valley sites is now located in Pakistan?",
        options: [
        "Mohenjo-daro",
        "Harappa",
        "Lothal",
        "Dholavira",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Pottery was first rraceable to which period of ancient Indian history?",
        options: [
        "Chalcolithic",
        "Mesolithic",
        "Neolithic",
        "Paleolithic",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "Which of the following Indus Valley sites is now located in Pakistan?",
        options: [
        "Mohenjo-daro",
        "Harappa",
        "Lothal",
        "Dholavira",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "Which of the following Harappan town was located on Khadir Beyt in the Runn of Kutch and was divided into three parts?",
        options: [
        "Chanhudaro",
        "Sotka-koh",
        "Surkotada",
        "Dholavira",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Bhimbetka, a noted site of the Paleolithic period, is located in which state of India?",
        options: [
        "Madhya Pradesh",
        "Rajasthan",
        "Gujarat",
        "Maharashtra",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Most Harappan seals made of",
        options: [
        "Brass",
        "Bricks",
        "Granite",
        "Steatite",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "Which of the following Harappan sites is located in Afghanistan?",
        options: [
        "Balakot",
        "Kalibangan",
        "Nageswar",
        "Shortughai",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "",
        options: [
        "Bhimbetka",
        "Sotka-koh",
        "Surkotada",
        "Dholavira",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "According to the Varna system that was prevalent in the Vedic period, whicho was the NOT a Varna?",
        options: [
        "Brahmin",
        "Kshatriya",
        "Vaishya",
        "Samiti",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Which Rigvedic God is considered an intermediary between the God and Men",
        options: [
        "Indra",
        "Agni",
        "Vishnu",
        "Yama",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "A large number of words are derived from the word \"Go\" meaing cow. A wealthy person was known as ________ in Vedic period",
        options: [
        "Gabaksha",
        "Gaveshana",
        "Gomat",
        "Gotra",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "How many Mandalas were in Rig Vedic Samhita?",
        options: [
        "10",
        "12",
        "14",
        "16",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "Which of the following is the earliest literary record of Indian culture?",
        options: [
        "Rigveda",
        "Yajurveda",
        "Samaveda",
        "Atharvaveda",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "Asikni, was a part of Sapta-Sindhu, is the name of which of the following rivers in preesent times?",
        options: [
        "Jhelum",
        "Chenab",
        "Ravi",
        "Beas",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "The main (chief) social unit of the Aryans was the ________",
        options: [
        "Gana",
        "Jana",
        "Parishad",
        "Rajan",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Which of the four Vedas contains a collection of magic spells and charms to fend off evil spirits and diseases?",
        options: [
        "Rigveda",
        "Yajurveda",
        "Samaveda",
        "Atharvaveda",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "The language of the Aryan texts was ________",
        options: [
        "Sanskrit",
        "Prakrit",
        "Persian",
        "Pali",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "As per the Rigvedic or Early Vedic period (1500-1000 BCE), who among the following was a River Goddess?",
        options: [
        "Agni",
        "Arika",
        "Sindhu",
        "Usha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "How many Mahajanapadas were there during the age of Buddha?",
        options: [
        "16",
        "18",
        "20",
        "22",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "Kosala Mahajanapada (6th century BCE) is a part of modern day ________",
        options: [
        "Haryana",
        "Gujarat",
        "Maharashtra",
        "Uttar Pradesh",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "What was the name of the first dynasty that ruled over Magadh Kingdom?",
        options: [
        "Haryanka",
        "Maurya",
        "Nanda",
        "Satavahana",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-2': [
      {
        id: 1,
        question: "Mahavir jayanti celebrates the birthday of lord mahavira who is the ________ tirthankara of the Jainism religion",
        options: [
        "23rd",
        "24th",
        "25th",
        "26th",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "The jain temple at pattadakal was built by ________",
        options: [
        "Chalukyas",
        "Cholas",
        "Hoysalas",
        "Rastrakutas",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "During which of the following rules did buddhism get split into two schools - hinayana and mahayana in the fourth buddhist council?",
        options: [
        "Gupta",
        "Kushana",
        "Parthian",
        "Shaka",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "The location of Dhamek Stupa is ________",
        options: [
        "Bodh Gaya",
        "Kushinagar",
        "Sarnath",
        "Shravasti",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Which of the following is the largest stupa in India?",
        options: [
        "Kesariya Stupa",
        "Maha Stupa",
        "Sanchi Stupa",
        "Shanti Stupa",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Who among the following has written the biography of the Buddha, Buddhacharita?",
        options: [
        "Ashvaghosha",
        "Charaka",
        "Nagarjuna",
        "Vasumitra",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "Which is the oldest Stupa of the Budhist period in India?",
        options: [
        "Dhamek Stupa",
        "Mahabodhi Stupa",
        "Kesariya Stupa",
        "Sanchi Stupa",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "The lion capital was built to commemorate the historical event of ________ of buddha",
        options: [
        "Acquisition of knowledge",
        "Death",
        "First sermon",
        "Home abandonment",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Ramabhar Stupa, which marks the site where lord buddha was cremated, is situated in which state of India?",
        options: [
        "Bihar",
        "Maharashtra",
        "Madhya Pradesh",
        "Uttar Pradesh",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "The earliest buddhist texts were written in ________",
        options: [
        "Sanskrit",
        "Prakrit",
        "Persian",
        "Pali",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "Which of the following edicts of king ashoka describes the Kalinga war?",
        options: [
        "Rock edict II",
        "Rock edict XIII",
        "Pillar edict III",
        "Pillar edict IV",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "The name Piyadassi is associated with whom among the following Mauryan kings?",
        options: [
        "Ashoka",
        "Bindusara",
        "Brihadratha",
        "Chandragupta Maurya",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "Deimachus, who was a Greek ambassador, came to India during the reign of which of the following Mauryan kings?",
        options: [
        "Ashoka",
        "Bindusara",
        "Brihadratha",
        "Chandragupta Maurya",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Barabar Cave, famously known for depicting Ashoka's inscription, is situated at ________",
        options: [
        "Gaya, Bihar",
        "Sanchi, Madhya Pradesh",
        "Sarnath, Uttar Pradesh",
        "Rampurva, Bihar",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "Who among the following rulers was defeated in the battle for Pataliputra by Chandragupta Maurya?",
        options: [
        "Dhana Nanda",
        "Elara",
        "Megasthenes",
        "Seleucus Nicator",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "What was the fucntion of an officer called Samaharta",
        options: [
        "Reserve the state treasury",
        "Security assurance",
        "Tax assessment",
        "To correspong",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "Emperor Ashoka conquered Kalinga after how many years of his coronation?",
        options: [
        "5",
        "8",
        "11",
        "15",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "How many classes of Indian society are mentioned in Megasthenes's book Indica?",
        options: [
        "5",
        "6",
        "7",
        "8",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "Which of the following texts lays down minute details of the administrative and military organisation during the Mauryan period?",
        options: [
        "Arthashastra",
        "Brihat Samhita",
        "Nitisara",
        "Shulba Sutras",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Which Mauryan ruler was called Amitrochates by the Greeks?",
        options: [
        "Ashoka",
        "Bindusara",
        "Brihadratha",
        "Chandragupta Maurya",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "What was the purpose behind the Pillars of Ashoka?",
        options: [
        "To spread bherighosha",
        "To spread mass conversion",
        "To spread sectarian faith",
        "To spread the dharma policies",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "Which of the following is not a Mauryan ruler?",
        options: [
        "Ashoka",
        "Bindusara",
        "Brihadratha",
        "Chandragupta Maurya",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "Which of the following plays was NOT written by Harsha Vardhan?",
        options: [
        "Priyadarshika",
        "Nagananda",
        "Ratnavali",
        "Vikramorvasiyam",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "Pulakeshin II assumed the title of Dakshinapatheshvara (lord of the south) after defeating which of the following rulers of North India?",
        options: [
        "Dhruvasena II",
        "Harsha Vardhan",
        "Prabhakaravardhana",
        "Rudrasena II",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "Pushyabhuti dynasty, after Prabhakarvardhana, strengthened its posistion in the regions of Punjab and Haryana after defeating which of the following dynasties?",
        options: [
        "Chalukyas",
        "Hunas",
        "Maitrakas",
        "Maukharis",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-3': [
      {
        id: 1,
        question: "Thaneswar where the Vardhana dynasty ruled around the present day state of ________",
        options: [
        "Gujarat",
        "Haryana",
        "Madhya Pradesh",
        "Rajasthan",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "According to which of the following foreign travellers did Dhruvasena II attend Harsha Vardhan's assembly at Prayag (Allahabad)?",
        options: [
        "Fa-Hien",
        "I-Tsing",
        "Hiuen Tsiang",
        "Marco Polo",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "Who sent an envoy to the Chinese court in 641 AD?",
        options: [
        "Harsha Vardhan",
        "Narasimhavarman I",
        "Narasimhavarman II",
        "Pulakeshin I",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "What is the period of Harsha Vardhan's reign?",
        options: [
        "606-647 CE",
        "647-681 CE",
        "681-705 CE",
        "705-730 CE",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Which of the following animals was the emblem of Chola dynasty?",
        options: [
        "Lion",
        "Elephant",
        "Tiger",
        "Dragon",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Brihadiswara temple of Tanjavur was built by which of the following Chola rulers?",
        options: [
        "Chamundaraya",
        "Rajendra I",
        "Raja Raja Chola",
        "Vijayalaya",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "Name the Chola inscription that provided details of the way in which the sabha was organised in the local administration in the Chola kingdom?",
        options: [
        "Darsanam koppu",
        "Thirunanthikarai",
        "Thiruvalangadu",
        "Uttaramerur",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "Who among the following rulers invaded Malaya to liberate their trade with China?",
        options: [
        "Chalukya",
        "Chola",
        "Pallava",
        "Rashtrakuta",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Sabha and Ur, two kinds of village assmeblies are referred to in which of the following dynasties?",
        options: [
        "Chalukya",
        "Chola",
        "Pallava",
        "Rashtrakuta",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Brahmadeya is a type of land during the Chola period was the ________",
        options: [
        "Land gifted to Brahmans",
        "Land of non-brahman peasant proprietors",
        "Land gifted to temples",
        "Land of royal persons",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "The term Vetti in Chola empire is related to ________",
        options: [
        "Army",
        "Forced labour",
        "Gold coins",
        "Part payment",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "Which was the first dynasty of the Delhi Sultanate?",
        options: [
        "Khilji",
        "Mamluks",
        "Mughals",
        "Tughlaqs",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "Who among the following was the daughter of Iltutmish, a ruler of Slave Mamluk dynasty?",
        options: [
        "Harkha",
        "Kurba Noorzai",
        "Razia Sultana",
        "Shafiqa Ziayee",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Razia Sultana was the first and only female ruler of the Sultanate, who ascended the throne in ________",
        options: [
        "1236",
        "1240",
        "1244",
        "1248",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "Which of the following Delhi Sultanate introduced two coins, namely silver tanka and copper jital?",
        options: [
        "Bahlul Lodi",
        "Ghiyasuddin Balban",
        "Iltutmish",
        "Qutubuddin Aibak",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "Balban followed the tradition of \"Sijda and Paibos\" from which of the following traditions?",
        options: [
        "Chinese",
        "Mangolian",
        "Persian",
        "Roman",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "Which of the following departments of Delhi Sultanate was reogranized by Balban?",
        options: [
        "Diwan-i-Ishtiaqa",
        "Diwan-i-Arz",
        "Diwan-i-Risalat",
        "Diwan-i-Mustakhraj",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "Which of the following Sultans of the Delhi primarily adopted a policy of consolidation rather than expansion?",
        options: [
        "Alauddin Khilji",
        "Balban",
        "Bahlul Lodi",
        "Qutubuddin Aibak",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "Which of the following Sultans of Delhi set up the officers like Barid (intelligence officer) and Munhiyans (secret spies) to control the markets?",
        options: [
        "Alauddin Khilji",
        "Balban",
        "Bahlul Lodi",
        "Qutubuddin Aibak",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "During Alauddin Khilji's reign, the cloth market was known as ________",
        options: [
        "Mandi",
        "Munhiyans",
        "Sarai-i-Adi",
        "Shahna-i-Mandi",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "The first southern campaign of Alauddin Khilji in 1307-08 AD was led to which of the following regions?",
        options: [
        "Devagiri",
        "Dwar Samudra",
        "Madura",
        "Warangal",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "Who was the first Sultan of the Delhi Sultanate to start military expeditions into south India?",
        options: [
        "Alauddin Khilji",
        "Balban",
        "Bahlul Lodi",
        "Qutubuddin Aibak",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "Ziyaddin Barani wrote this chronicle first in 1356 and another version in ________ years later?",
        options: [
        "2",
        "3",
        "4",
        "5",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "Who among the following was the successor of Muhammad-Bin Tughlaq to the throne of the Delhi Sultanate?",
        options: [
        "Firuz Shah Tughlaq",
        "Ghiyasuddin Balban",
        "Iltutmish",
        "Qutubuddin Aibak",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "Who was the first ruler of the Sayyid dynasty?",
        options: [
        "Khizr Khan",
        "Allauddin Alam Shah",
        "Muhammad Shah",
        "Muhammad khan",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-4': [
      {
        id: 1,
        question: "Which of the following dynasties of the Delhi Sultanate finally annexed Jaunpur into the empire of Delhi Sultanate?",
        options: [
        "Lodi dynasty",
        "Khilji dynasty",
        "Sayyed dynasty",
        "Tughlaq dynasty",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Who among the following was the ruler of the Delhi Sultanate who founded the Khwaja Bakhtiyar Khana?",
        options: [
        "Alauddin Khilji",
        "Balban",
        "Bahlul Lodi",
        "Qutubuddin Aibak",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "Who among the following was the last sult of Delhi Sultanate?",
        options: [
        "Firuz Shah Tughlaq",
        "Ghiyasuddin Balban",
        "Iltutmish",
        "Ibrahim Lodi",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "The founder of Vijayanagara empire, Harihara and Bukka Raya were the ministers of which of the following dynasties?",
        options: [
        "Eastern Ganga",
        "Kampili",
        "Kadambas",
        "Western Chalukyas",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Who among the following Portuguese travellers visited the Vijayanagara empire during the reign of King Krishnadevaraya?",
        options: [
        "Athanasius Nikitin",
        "Domingo Paes",
        "Ludovico de Varthema",
        "Nicolo Conti",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Which of the following was the last dynasty of the Vijayanagara empire?",
        options: [
        "Aravidu",
        "Saluva",
        "Sangam",
        "Tuluva",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "Which of the following kings of Vijayanagara took the title of \"establisher of the Yavana kingdom\"?",
        options: [
        "Krishnadevaraya",
        "Achutaraya",
        "Sada Siva raya",
        "Vira Narasimha Raya",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "The Vijayanagara empire included people from different cultural regions. Which of the following regions was NOT part of the empire?",
        options: [
        "Karnataka",
        "Andhra",
        "Tamil Nadu",
        "Maharashtra",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "What was the dominant source of income in the Vijayanagara empire?",
        options: [
        "Agriculture",
        "Trade",
        "Land revenue",
        "Taxation",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Who among the following Vijayanagara rulers married his daughter to Firuz Shah Bahmani?",
        options: [
        "Bukka I",
        "Deva Raya I",
        "Deva Raya II",
        "Krishnadevaraya",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "The founders of the Vijayanagara empire were the feudatories of which of the following dynasties?",
        options: [
        "Chola",
        "Hoysala",
        "Kakatiya",
        "Pandyas",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "The origin of \"Carnatic music\" is related to which of the following dynasties?",
        options: [
        "Chola",
        "Hoysala",
        "Kakatiya",
        "Vijayanagara",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "Raichur doab, the land between Krishna and Tungabhadra rivers was a reason of conflict between the kings of Vijayanagara and which of the following dynasties?",
        options: [
        "Bahmani",
        "Bengal",
        "Golconda",
        "Malwa",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Which battle led to destruction of the Vijayanagara empire?",
        options: [
        "Battle of Talikota",
        "Battle of Raichur",
        "Battle of Haldighati",
        "Battle of Arcot",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "Provda style of architecture belongs to which empire?",
        options: [
        "Bahamani",
        "Gupta",
        "Mauryan",
        "Vijayanagara",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "While historians use the term \"Vijayanagara\" empire and contemporaries of this empire described it as the ________",
        options: [
        "Andhra Samrajya",
        "Gajapati Samrajya",
        "Karnataka Samrajya",
        "Sthalapati Samrajya",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "After the breakup of the Bahmani kingdom, how many independent states were formed?",
        options: [
        "3",
        "4",
        "5",
        "6",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "Who among the following Bahamani sultans transferred his capital from Gulbarga to Bidar?",
        options: [
        "Ahmad Shah",
        "Firuz Shah",
        "Humayun",
        "Mujahid Shah",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "Which of the following was the capital of the Bahmani kingdom?",
        options: [
        "Bidar",
        "Gulbarga",
        "Hyderabad",
        "Tirupati",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Name the French jeweler who travelled to India at leat 6 times during the Mughal period?",
        options: [
        "Antonio Monserrat",
        "Jaean Baptiste",
        "Peter Mundy",
        "Seydi Ali Reis",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "Which Mughal prince translated the Upanishads into Persian in 1657?",
        options: [
        "Darak Shikoh",
        "Murad Mirza",
        "Shah Suja",
        "Sultan Luft Ali",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "The battle of Khanwa was fought between the forces of the Babur and the Rajuput forces led by:",
        options: [
        "Ibrahim Lodi",
        "Medini Rai",
        "Mahamud Lodi",
        "Rana Singh",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "Which of the following battles was fought between Babur and Rana Singh in 1527?",
        options: [
        "Battle of Khanwa",
        "Battle of Panipat",
        "Battle of Tughlaqabad",
        "Battle of Talikota",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "The first battle of Panipat took place between Babur and which of the following rulers?",
        options: [
        "Ibrahim Lodi",
        "Medini Rai",
        "Mahamud Lodi",
        "Rana Singh",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "Who among the following was the successor of Babur to the throne of the Mughal empire?",
        options: [
        "Humayun",
        "Akbar",
        "Aurangzeb",
        "Dara Shikoh",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-5': [
      {
        id: 1,
        question: "In which state of India is Sher Shah Suri's tomb located?",
        options: [
        "Bihar",
        "Madhya Pradesh",
        "Rajasthan",
        "Uttar Pradesh",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Akbars first expedition towards Deccan was sent to Ahmadnagar under the leadership of Prince Murad and ________",
        options: [
        "Adham Khan",
        "Abdul Rahim Khan-i-Khanan",
        "Birbal",
        "Man Singh Tomar",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "Who was the revenue minister during te reign of Akbar?",
        options: [
        "Abdul Rahim",
        "Mulla Do-Piyaz",
        "Tansen",
        "Todar Mal",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "After the death of Humayun, the 13 year old Akbar was coronated in 1556 at Kalanur in ________",
        options: [
        "Punjab",
        "Madhya Pradesh",
        "Rajasthan",
        "Uttar Pradesh",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Who amongst the following Mughal empowerors got classical Hindu mythological texts Ramayana and Mahabharata translated into Persian?",
        options: [
        "Babur",
        "Akbar",
        "Aurangzeb",
        "Dara Shikoh",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Who among the following was the Vakil under the reign of Mughal Emperor Akbar, who recieved the title of Khan-i-Khana?",
        options: [
        "Bairam Khan",
        "Mulla Do-Piyaz",
        "Tansen",
        "Todar Mal",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "25% of the land revenue collected by Marathas in the Deccan was _________",
        options: [
        "Bhaga",
        "Bhoga",
        "Chauth",
        "Sardeshmukhi",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "Who among the following was a famous ruler of the Maratha dynasty?",
        options: [
        "Chhatrapati Shivaji Maharaj",
        "Man Singh Tomar",
        "Porus",
        "Prithviraj Chauhan",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Which of the following personalities had the key role in fighting against the British East India Company in the battle of Porto Novo?",
        options: [
        "Alamgir II",
        "Gopala Nayakar",
        "Hyder Ali",
        "Maharaja Ranjit Singh",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Which of the following battles is considered the formal beginning of the British Raj in India?",
        options: [
        "Battle of Plassey",
        "Battle of Panipat",
        "Battle of Tughlaqabad",
        "Battle of Talikota",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "In which year was the battle of Buxar fought?",
        options: [
        "1764",
        "1765",
        "1766",
        "1767",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "Where was the first Jute mill established in India?",
        options: [
        "Rishra",
        "Kolkata",
        "Chennai",
        "Hyderabad",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "In 1600, the East India Company acquired a charter from ________",
        options: [
        "King James I of England",
        "King James II of England",
        "Queen Elizabeth I of England",
        "Queen Victoria of England",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "The first English factory was set up on the banks of the river ________ in 1651",
        options: [
        "Ganges",
        "Hugli",
        "Kaveri",
        "Cauvery",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "The British East India Company captured Pondicherry (now Puducherry) from the French in ________",
        options: [
        "1761",
        "1762",
        "1763",
        "1764",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "With reference to Sepoy Mutiny 1857, on which of the following dates did the soldiers at Meerut start thier journey to Delhi?",
        options: [
        "10 May 1857",
        "11 May 1857",
        "12 May 1857",
        "13 May 1857",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "The revolution of 1857 started in May from which of the following cantonments in India?",
        options: [
        "Meerut",
        "Lucknow",
        "Calcutta",
        "Bengaluru",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "Which Mughal ruler contributed to the revolt of 1857?",
        options: [
        "Bahadur Shah I",
        "Aurangzeb",
        "Bahadur Shah II",
        "Alimgar II",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "Nana Sahib, a rebel at Kanpur was the son of which of the following Peshwas?",
        options: [
        "Baji Rao I",
        "Baji Rao II",
        "Balaji Vishwanath",
        "Balaji Ganesh",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Which Governor General of British India helped Raja Ram Mohan Roy legally abolish the practice of Sati?",
        options: [
        "Lord Dalhousie",
        "Lord Wellesley",
        "Lord William Bentinck",
        "Lord Clive",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "Post 1857 revolt, the Peel commission was set up to give recommendations on ________ reorganization of British India?",
        options: [
        "Land revenue",
        "Military",
        "Trade",
        "Administrative",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "In which region did the Indigo Revolt 1859 occur?",
        options: [
        "Bengal",
        "Madras",
        "Bihar",
        "Orissa",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "In which year did the Santhal Rebellion take place?",
        options: [
        "1855-1856",
        "1856-1857",
        "1857-1858",
        "1858-1859",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "Who was the leader of the Paika Rebellion?",
        options: [
        "Baba Ram Singh",
        "Bakshi Jagabandhu Bidyadhara",
        "Tirath Singh",
        "Veer Surendra Sai",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "Who among the following participated in the All-World Religious Conference (Parliament of Religions) held in Chicago in 1893?",
        options: [
        "Rabindranath Tagore",
        "Mahatma Gandhi",
        "Subramania Bharati",
        "Swami Vivekananda",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-6': [
      {
        id: 1,
        question: "Who founded the Prarthana Samaj in Mumbai in 1867?",
        options: [
        "Atmaram Pandurang",
        "Gopal Krishna Gokhale",
        "Ram Mohan Roy",
        "Shri Ram Bajpai",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Which of the following social reformers of 19th century India was the author of \"Stree Purush Tulana\"?",
        options: [
        "Pandita Ramabai",
        "Swarnakumari Devi",
        "Tarabai Shinde",
        "Usha Mehta",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "Samata Saini Dal was formed in 1927 by whom among the following personalities?",
        options: [
        "Bhagwan Das",
        "Gopal Krishna Gokhale",
        "Ram Mohan Roy",
        "BR Ambedkar",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Who among the following founded the Atmiya Sabha in 1814?",
        options: [
        "Debendranath Tagore",
        "Iswar Chandra Vidyasagar",
        "Keshab Chandra Sen",
        "Raja Ram Mohan Roy",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Which of the following Sikh reform movements was started in 1873 in Amritsar?",
        options: [
        "Akali movement",
        "Babbar Akali movement",
        "Gurudwara movement",
        "Singh Sabha movement",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Which was the first socio-religious organization established in Bombay in 1840 to work for the annihilation of caste discrimination?",
        options: [
        "Dharma Sabha",
        "Paramhans Mandali",
        "Sathyashodhak Samaj",
        "Vishwa Jain Sangathan",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "Which organization was started in the Pune district of Maharasthra in the 1870s with the aim of promoting education and social rights among the underprivileged group of the society?",
        options: [
        "Deepalaya samaj",
        "Prarthana Samaj",
        "Satyashodhak Samaj",
        "Shoshit Seva Samaj",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "Who among the following was the pioneer of widow remarriages in Maharasthra and also started a girls school in Poona along with his wife?",
        options: [
        "BR Ambedkar",
        "Jyotirao Phule",
        "Gopal Hari Deshmukh",
        "Mahatma Gandhi",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Who among the following founded the Muhammadan Anglo-Oriental College in Aligarh for the spread of western education among the Muslims of India?",
        options: [
        "Badruddin Tyabji",
        "Maulana Abul Kalam Azad",
        "Sir Syed Ahmed Khan",
        "Syed Ahmed Ali",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "In which of the following years, was the Self-Respect movement started in Tamil Nadu region?",
        options: [
        "1925",
        "1926",
        "1927",
        "1928",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "Who among the following is associated with the Theosophical Society?",
        options: [
        "Annie Besant",
        "Sarojini Naidu",
        "Savitri bai Phule",
        "Tarabhai Shinde",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "Sree Narayana Guru considered the difference based on the caste and religion as meaningless and advocated the principle of \"One caste, one religion and one God\" for all. He belonged to which of the following organizations?",
        options: [
        "Arya Samaj",
        "Brahmo Samaj",
        "Sree Narayana Dharma Paripalana Yogam",
        "Veda Samaj",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "Who started the temple entry movement in 1927?",
        options: [
        "BR Ambedkar",
        "Mahatma Gandhi",
        "Sree Narayana Guru",
        "Swami Vivekananda",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Who is known as the founder of the Widow Remarriage Assocation in 1861?",
        options: [
        "Ataram Pandurang",
        "Dwarakanath Tagore",
        "Mahadev Govind Ranade",
        "RG Bhandarkar",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "Who among the following was the President of the Belgaum Session of the Indian National Congress in 1924?",
        options: [
        "Jawaharlal Nehru",
        "Mahatma Gandhi",
        "Subhas Chandra Bose",
        "Bal Gangadhar Tilak",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "The Quit India Resolution was ratified in the ________ session of the Indian National Congress to lauch the movement?",
        options: [
        "Bankipur",
        "Bombay",
        "Lucknow",
        "Nagpur",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "In which of the following places the Indian National Congress passed the resolution of Purna Swaraj?",
        options: [
        "Bankipur",
        "Bombay",
        "Lahore",
        "Nagpur",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "_______ was elected as the president of third session of the Indian National Congress.",
        options: [
        "AO Hume",
        "Badruddin Tyabji",
        "KT Telang",
        "Purna Chandra Bose",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "All India Kisan Sabha was founded in 1936 at Indian National Congress session _________ session as All India Kisan Congress.",
        options: [
        "Agra",
        "Delhi",
        "Lucknow",
        "Nagpur",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Indian National Congress celebrated the first Independence Day in Colonial India on _________",
        options: [
        "02 October 1929",
        "29 December 1929",
        "15 August 1930",
        "26 January 1930",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "Which among the following sessions of the Indian National Congress was the first sessio to be presided by a woman?",
        options: [
        "Surat 1907",
        "Culcatta 1917",
        "Kanpur 1927",
        "Nagpur 1937",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "Which of the following groups/parties was started in San Francisco, United States of America during the Indian National Movement?",
        options: [
        "Ghadar Party",
        "Hindustan Socialist Republic Association",
        "Khilafat Movement",
        "Swaraj Party",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "Which of the following revolutionists was associated with the Anushilan Samiti?",
        options: [
        "Jatindra Mohan Sengupta",
        "Bhagat Singh",
        "Rajguru",
        "Sukhdev",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "Who is regarded as the \"Mohter of Indian Revolution\"?",
        options: [
        "Annie Besant",
        "Madame Cama",
        "Kasturba Gandhi",
        "Usha Mehta",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "Who was the Mughal emperor, when a massive rebellion against the British rule broke out in 1857?",
        options: [
        "Akbar",
        "Aurangzeb",
        "Bahadur Shah Zafar",
        "Shah Alam II",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-7': [
      {
        id: 1,
        question: "Mughal ruler, Aurangazeb died in which year?",
        options: [
        "1707",
        "1717",
        "1727",
        "1737",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "What does the term \"Upa\" in the term Upanishad mean?",
        options: [
        "Happiness",
        "Nearness",
        "Secret",
        "Totality",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "The main (chief) social unit of the Aryans was ________",
        options: [
        "Gana",
        "Jana",
        "Parishad",
        "Rajan",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Which of the following Vedas depicts the life of the early Vedic people of India and has a collection of 1028 hymns divided into 10 mandalas?",
        options: [
        "Rigveda",
        "Yajurveda",
        "Samaveda",
        "Atharvaveda",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "In the lated Vedic period, which of the following Varnas was mainly engaged in farming, animal husbandry and trade?",
        options: [
        "Brahmanas",
        "Kshatriyas",
        "Vaishyas",
        "Shudras",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Who among the following is supposed to compile both the Puranas and the Mahabharata?",
        options: [
        "Sage Vasistha",
        "Sage Bharadwaj",
        "Sage Valmiki",
        "Sage Vyasa",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "The great poet and humanist writer Rabindranath Tagore returned his knighthood in protest of which incident?",
        options: [
        "Jallianwala Bagh Massacre",
        "Champaran Satyagraha",
        "Ahmedabad Textile Strike",
        "Non-Cooperation Movement",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "In which year was \"Self Help Group-Bank Linkage Program(SHGBLP)\" started in India?",
        options: [
        "1988",
        "1990",
        "1992",
        "1994",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "The Shilendra kings who had close contacts with the Indian rulers were followers of which of the following religions?",
        options: [
        "Hinduism",
        "Jainism",
        "Buddhism",
        "Islam",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Who among the following envoys was sent by Seleucus Nicator to the court of Chandragupta Maurya?",
        options: [
        "Megasthenes",
        "Kautilya",
        "Chanakya",
        "Chanakya",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "Which temple is a prime example of Kalinga architecture, featuring a tall shikhara (Rekha Deul) and eleaborate carvings?",
        options: [
        "Konark Sun Temple",
        "Puri Jagannath Temple",
        "Lingaraja Temple",
        "Kailash Mansarovar",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "Which secret society was founded by Vinayak Damodar Savarkar promoted armed revolution against the British rule?",
        options: [
        "Abhinav Bharat",
        "Anushilan Samiti",
        "Hindu Jana Sangh",
        "Hindu Mahasabha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "In which of the following years was the All India Muslim League founded?",
        options: [
        "1906",
        "1907",
        "1908",
        "1909",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Which of the following Sultans of Delhi adopted the policy of Blood and Iron?",
        options: [
        "Alauddin Khilji",
        "Shamsuddin Iltutmish",
        "Shah Jahan",
        "Balban",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "An Indian woman social reformer, ___________ is credited with the establishment of \"Bharat Stree Mandal\" in 1910.",
        options: [
        "Savitri Bai Phule",
        "Sarala Devi",
        "Sarojini Naidu",
        "Usha Mehta",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "In which year was the temple entry movement started by BR Ambedkar?",
        options: [
        "1927",
        "1928",
        "1929",
        "1930",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "Who among the following was proclaimed as the leader of the revolt by the rebels during the First war of Indian independence, 1857, against the British oppression?",
        options: [
        "Rani Lakshmi Bai",
        "Nana Sahib",
        "Shah Alam II",
        "Bahadur Shah Zafar",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "Who among the following compiled the Mrga-pasi-shastra in the 13th century, which provided an account of beasts and birds of hunting?",
        options: [
        "Akbar",
        "Hamsadeva",
        "Jahangir",
        "Shah Jahan",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "Who among the following was the successor of Sultan Iltumish in the Delhi Sultanate?",
        options: [
        "Alauddin Khilji",
        "Feroz Shah Tughlaq",
        "Shah Alam II",
        "Razia Sultana",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Bolgatty Palace in Kochi, Kerala, India was built in the ________ architectural style?",
        options: [
        "Mughal",
        "Dutch",
        "British",
        "Portuguese",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "Which liberal Viceroy enacted local self-government for muncipalities and repealed the unpopular Vernacular Press Act of 1878?",
        options: [
        "Lord Ripon",
        "Lord Curzon",
        "Lord Hardinge",
        "Lord Minto",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "Which of the following policies allowed the British to indirectly control the Indian states while maintaining the appearance of local sovereignty?",
        options: [
        "Doctrine of Lapse",
        "Dual Government",
        "Regulating act",
        "Subsidiary Alliance",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "Which language was predominantly used by Amir Khusrau in his literary compositions during the Delhi Sultanate Period?",
        options: [
        "Prakrit",
        "Urdu",
        "Persian",
        "Arabic",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "Who among the following social reformers of Bengal earnestly fought for widow remarriage and girl's education?",
        options: [
        "Bakim Chandra Chattopadhyay",
        "Debendranath Tagore",
        "Isvar Chandra Vidyasagar",
        "Nabinchandra Sen",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "The system in which peasants were forced into lifelong labour due to debts obligations was known as",
        options: [
        "Dadni system",
        "Hazara system",
        "Kamiyauti system",
        "Tinkathia system",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-8': [
      {
        id: 1,
        question: "What was the nature of the land tax system introduced by Haider Ali and Tipu Sultan?",
        options: [
        "Taxation in goods",
        "Direct land tax paid in cash",
        "Poll tax",
        "Barter-based taxation",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "The book \"Sutta Pitaka\" contains the words of which religious preacher?",
        options: [
        "Buddha",
        "Mahavira",
        "Guru Nanak",
        "Sudras",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "The British police attacked Lala Lajpat Rai during peaceful demonstration against the ________ in 1928.",
        options: [
        "British Salt monopoly",
        "Hindu casteism",
        "Simon commission",
        "Unjust taxation",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Bhagat Singh and ________ threw a bomb in the Central Legislative Assembly on 8 April 1929.",
        options: [
        "Sukhdev",
        "Rajguru",
        "Shivaram Rajguru",
        "Batukeshwar Dutt",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Who among the following was NOT sentenced to death in the Kakori Conspiracy Case (1925)?",
        options: [
        "Ashfaqullah Khan",
        "Rajendra Lahiri",
        "Roshan Singh",
        "Sachindra Nath Bakshi",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "The Harappan cities were famous for their ________",
        options: [
        "Grid systme of town planning",
        "Irregular street patterns",
        "Stone places",
        "Wooden structures",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "The result of which of the following movements/satyagrahas was the abolishment of the Tinkathia system under which the farmers were asked to cultivate indigo in 3/20th of their land?",
        options: [
        "Champaran Satyagraha",
        "Ahmedabad Textile Strike",
        "Non-Cooperation Movement",
        "Khilafat Movement",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "The ‘Prayaga Prashasti’ also known as the ‘Allahabad Pillar’ is composed in praise of which of the following rulers?",
        options: [
        "Ashoka",
        "Chandragupta II",
        "Rudradaman",
        "Samudragupta",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Which of the following incidents prompted Mahatma Gandhi to withdraw the Non-Cooperation Movement in 1922?",
        options: [
        "Alipore bomb case",
        "Chauri-Chuara incident",
        "Suspension of the Roolatt Act",
        "Withdrawal of of the Khilafat Movement",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Who secretely reorganised the Hindustan Republican Association (HRA) with Bhagat Singh and other rebels in 1928 and changed its name to Hindustan Socialist Republic Association (HSRA)?",
        options: [
        "Chandra Shekhar Azad",
        "Sukhdev",
        "Rajguru",
        "Chitta Ranjan Das",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "In which of the following years did Aurangzeb annex Golconda to his kingdom?",
        options: [
        "1687",
        "1688",
        "1689",
        "1690",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "In which year did Babar defeat Rana Sanga, Rajput kings, and their supporters at the Battle of Khanwa?",
        options: [
        "1527",
        "1528",
        "1529",
        "1530",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "Which of the following Sultans of Delhi adopted the policy of Blood and Iron?",
        options: [
        "Alauddin Khilji",
        "Shamsuddin Iltutmish",
        "Shah Jahan",
        "Balban",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Which of the following battles was fought in the year 1911 AD?",
        options: [
        "Battle of Plassey",
        "Battle of Buxar",
        "Battle of Panipat",
        "Battle of Tarain",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "The first systematisation of the Jain canonical literature took place at which of the following places?",
        options: [
        "Lumbini",
        "Mathura",
        "Pataliputra",
        "Vallabhi",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "Who among the following was the minister who helped the King Ashoka acquire the throne?",
        options: [
        "Bhadrayudha",
        "Radha Gupta",
        "Samudra",
        "Susima",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "Which dynasty ruled Delhi immediately after the Khilji dynasty?",
        options: [
        "Mughal",
        "Sayyid",
        "Tughlaq",
        "Lodi",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "During the First Anglo-Maratha war, who served as the Governor-General of Bengal?",
        options: [
        "Cornwallis",
        "Wellesley",
        "Lord Hardinge",
        "Warren Hastings",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "In 1309 CE, Malik Kafur was invaded which of the following kingdoms in South India?",
        options: [
        "Hoysala",
        "Pandya",
        "Kakatiya",
        "Yadava",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Who among the following introduced the system of branding of horses (dagh) and maintaining descriptive rolls of soldiers (chehra)?",
        options: [
        "Alauddin Khilji",
        "Balban",
        "Shamsuddin Iltutmish",
        "Feroz Shah Tughlaq",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "It is said that South Indian Music, as known today, flourished in the capital city of the Yadavas in the middle ages. The name of this city is ________",
        options: [
        "Kaveripattinam",
        "Badami",
        "Deogiri",
        "Hampi",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "Gangaikonda Cholapuram was established as capital city by which of the following kings?",
        options: [
        "Rajendra Chola I",
        "Rajendra Chola II",
        "Rajaraja Chola I",
        "Kulothunga Chola I",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "The Pallava dynasty had its capital at which of the following places?",
        options: [
        "Kanchipuram",
        "Kanyakumari",
        "Kaveripattinam",
        "Kumbakonam",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "Mos of the Ashoka's edicts were compiled in which of the following languages?",
        options: [
        "Sanskrit",
        "Pali",
        "Prakrit",
        "Hindi",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "Seleucus sent his ambassador Megasthenes to the court of which Mauryan ruler?",
        options: [
        "Ashoka",
        "Chandragupta Maurya",
        "Brihadratha",
        "Bimbisara",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-9': [
      {
        id: 1,
        question: "What was the name given to the special official appointed by Ashoka to spread his policy of Dhamma?",
        options: [
        "Dhamma Lekhas",
        "Dhamma Janapada",
        "Dhamma Mahamatta",
        "Dhamma Mukhyas",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Kalidasa, the celebrated Sanskrit poet and dramatist, flourished in the court of which Gupta ruler?",
        options: [
        "Samudragupta",
        "Chandragupta I",
        "Chandragupta II",
        "Skandagupta",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "The \"Iron Pillar\" in Delhi famous for its rust-resistance, was built by which of the following rulers?",
        options: [
        "Samudragupta",
        "Chandragupta I",
        "Chandragupta II",
        "Harsha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "In Vaishali, the Second Buddhist Council was conducted by ________",
        options: [
        "Anuruddha",
        "Kalashoka",
        "Munda",
        "Sunidha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Which of the following baskets of the Buddhist Tipitaka contains monastic rules and regulations?",
        options: [
        "Abhidhamma Pitaka",
        "Jataka Pitaka",
        "Sutta Pitaka",
        "Vinaya Pitaka",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Which Buddhist text, from the 1st century BCE, records the dialuges of the Buddha?",
        options: [
        "Abhidhamma Pitaka",
        "Jataka Pitaka",
        "Sutta Pitaka",
        "Vinaya Pitaka",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "In Harappan Civilization, at Dholavira, _______ was used to build massive fortifications?",
        options: [
        "Bricks",
        "Stone",
        "Wood",
        "Bamboo",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "The Harappan Civilization flourished mainly during which of the following archaeological eras?",
        options: [
        "Bronze Age",
        "Iron Age",
        "Stone Age",
        "Neolithic Age",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Which of the following Harappan sites is famous for its dockyards?",
        options: [
        "Mohenjo-Daro",
        "Kalibangan",
        "Rakhigarhi",
        "Lothal",
        ],
        correctAnswer: undefined,
      }
    ],
  },
}
