export const physicsQuiz = {
  quizzes: {
    'quiz-1': [
      {
        id: 1,
        question: "The bluish color of water in the deep sea is due to:",
        options: [
        "Diffraction of light",
        "Reflection of light",
        "Refraction of light",
        "Scattering of light",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "On which of the following principles does the human eye work?",
        options: [
        "Reflection of light",
        "Refraction of light",
        "Diffraction of light",
        "Scattering of light",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "What is the ratio of sine of angle of incidence to the sine of the angle of refraction called?",
        options: [
        "Refractive index",
        "Transparency",
        "Translucent index",
        "Opacity",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Which of the following is an example of scattering of light?",
        options: [
        "Rainbow",
        "Twinkling of stars",
        "Blue colour of the sky",
        "Splitting of white light into its constituent colours",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Which is the main fuel used in a Nuclear Power Plant?",
        options: [
        "Uranium",
        "Plutonium",
        "Thorium",
        "Americium",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Which of the following is not a fundamental force of nature?",
        options: [
        "Gravitational force",
        "Electromagnetic force",
        "Strong nuclear force",
        "Frictional force",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "What is the purpose of the moderator in a Nuclear Reactor?",
        options: [
        "To slow down the neutrons",
        "To speed up the neutrons",
        "To absorb the neutrons",
        "To reflect the neutrons",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "Which equation demonstrates that electricity, magnetism and light are all manifestations of the electromagnetic field?",
        options: [
        "Maxwell's equations",
        "Lorentz force law",
        "Faraday's law of induction",
        "Ampere's law",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "An optical instrument used in a system of prisms, lenses or mirrors to reflect images through a tube is called __________.",
        options: [
        "Microscope",
        "Telescope",
        "Periscope",
        "Microphone",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "The provision for the appointment of a Governor for each state appears in which article of the Indian Constitution?",
        options: [
        "Article 153",
        "Article 154",
        "Article 155",
        "Article 156",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "When white light is falls on a glass prism, it splits into seven colours. This phenomenon is called",
        options: [
        "Dispersion",
        "Refraction",
        "Reflection",
        "Diffraction",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "Particles of matter are continously moving because of ________",
        options: [
        "Kinetic energy",
        "Potential energy",
        "Size of the particles",
        "Intermixing of particles",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "Where does the centre of curvature of a concave mirror lie?",
        options: [
        "In front of the mirror",
        "Behind the mirror",
        "At the centre of the mirror",
        "At the focus of the mirror",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Which of the following can have higher optical density but lower mass density?",
        options: [
        "Glass",
        "Water",
        "Germanium",
        "Turpentine",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "The gravitional force between two objects of masses m1 and m2 is directly proportional to ________",
        options: [
        "m1 - m2",
        "m1 * m2",
        "m1 / m2",
        "m1 + m2",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "The line joining the centre of curvature and the pole of a given spherical mirror is called the __________",
        options: [
        "Principal axis",
        "Principal focus",
        "Principal centre",
        "Principal radius",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "If a force \"F\" acts on a body such that body gets displaced through the distance \"d\" in the direction of the force, the work done by the force is given by __________",
        options: [
        "F * d",
        "F / d",
        "F + d",
        "F - d",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "In which year did Galileo Galilei describe the regular, swinging motion of a pendulum by the action of gravity and acquired momentum?",
        options: [
        "1602",
        "1603",
        "1604",
        "1605",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "Which type of electormagnetic radiation was discovered by Johann Wilhelm Ritter in 1801?",
        options: [
        "Ultraviolet radiation",
        "Infrared radiation",
        "Microwaves",
        "X-rays",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "A long straight conductor carries current vertically upwards. What will be the direction of the magnetic field at a point lying to the east of the wire?",
        options: [
        "Towards the north",
        "Towards the south",
        "Towards the east",
        "Towards the west",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "Candela is the unit of which of the following physical quantity?",
        options: [
        "Luminous intensity",
        "Luminous flux",
        "Luminous efficiency",
        "Luminous efficiency",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "Which principle states that the partial vapour pressure of each volatile component in a solution is directly proportional to its mole fraction in the solution?",
        options: [
        "Raoult's law",
        "Henry's law",
        "Dalton's law",
        "Avogadro's law",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "When a car is moving through a dusty road during night a path of beam from the headlight is clearly visible. This is due to ________",
        options: [
        "Scattering of light",
        "Reflection of light",
        "Refraction of light",
        "Diffraction of light",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "Which of the following physical quantities has zero dimension in mass and time?",
        options: [
        "Force",
        "Momentum",
        "Volume",
        "Work",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "A ray of light passes from water to glass. It bends ________",
        options: [
        "Away from the normal and speeds up",
        "Away from the normal and slows down",
        "Towards the normal and speeds up",
        "Towards the normal and slows down",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-2': [
      {
        id: 1,
        question: "Which of the following has the shortest wavelength?",
        options: [
        "Ultraviolet rays",
        "Infrared rays",
        "Gamma rays",
        "X-rays",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Which type of wave is primarily formed on a stretched string when plucked or disturbed?",
        options: [
        "Longitudinal wave",
        "Transverse wave",
        "Surface wave",
        "Torsional wave",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "Which of the following best describes the shape of a sinusoidal wave signal during  one complete cycle?",
        options: [
        "Square wave",
        "Triangle wave",
        "Rectangular wave",
        "S-shaped wave",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Which of the following is a dimensionaless quantity?",
        options: [
        "Acceleration",
        "Velocity",
        "Gravitational force",
        "Refractive index",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Who, in 1816, modified Newtons formula for the speed of sound to take into account adiabatic compression in air?",
        options: [
        "Galileo Galilei",
        "Hermann von Helmholtz",
        "Pierre-Simon Laplace",
        "Lord Rayleigh",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "The Oersted unit is used to measure which of the following?",
        options: [
        "Current intensity",
        "Electrical potential",
        "Electric field strength",
        "Magnetic field strength",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "Which of the following increases the rate of evaporation of a liquid?",
        options: [
        "Low surface area and cold air temperature",
        "Dense atmosphere and generally cool weather",
        "High temperature and increased wind speed",
        "High humidity and absence of wind movement",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "Which law is shown by fixed 1:8 mass ratio in water formation?",
        options: [
        "Dalton's Atomic Theory",
        "Law of Multiple Proportions",
        "Law of Conservation of Energy",
        "Law of Constant Proportions",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "An object is placed in front of concave mirror of focal length 12 cm at a distance of 6 cm. Its image is formed at a distance of ________ and is ________.",
        options: [
        "4 cm, real",
        "4 cm, Virual",
        "12 cm, real",
        "12 cm, Virual",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Which of the following conditions will NOT favour evaporation of a liquid?",
        options: [
        "High wind speed",
        "High humidity",
        "Low humidity",
        "High temperature",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "If we shine a green light on a tree, the tree will appear ________",
        options: [
        "Appear darker",
        "Appear brighter",
        "Appear the same as before",
        "Will camouflage in the light",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "Which of the following laws support the fact that it is difficult to fix a nail on a freely suspended wooden frame?",
        options: [
        "Pascal's law",
        "Newton's second law",
        "Newton's third law",
        "Newton's law of inertia",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "A galvanometer can be converted into a voltmeter by connecting in with which of the following?",
        options: [
        "A high resistance wire in series",
        "A low resistance wire in series",
        "A high resistance wire in parallel",
        "A low resistance wire in parallel",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "The direction of the magnetic field lines around a current carrying straight wire can be determined by which of the following?",
        options: [
        "Right hand thumb rule",
        "Fleming's left hand rule",
        "Ohm's law",
        "Lenz's law",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "Kepler's law of areas, relates to ________",
        options: [
        "Constant angular speed",
        "Conservation of linear momentum",
        "Conservation of angular momentum",
        "None of the above",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "Kepler's third laws were extracted from the data compiled by which of the following?",
        options: [
        "Tycho Brahe",
        "Galileo Galilei",
        "Isaac Newton",
        "Maxwell",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "Who among the following was able to explain the photoelectric effect using Planck's quantum theory of electromagnetic radiation as a straight point?",
        options: [
        "Albert Einstein",
        "Isaac Newton",
        "Max Planck",
        "Faraday",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "A method for measuring atmospheric pressure was first devised by which of the following?",
        options: [
        "Torricelli",
        "Pascal",
        "Archimedes",
        "Bernoulli",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "What is the correct dimensional formula for force?",
        options: [
        "MLT^-2",
        "MLT^2",
        "ML^-1T^-2",
        "ML^-2T^-2",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "The gravitational force between two objects is 36 N. if the distance between the two objects is halved while their masses remain the same, what will be the new gravitational force between the two objects?",
        options: [
        "18 N",
        "72 N",
        "144 N",
        "288 N",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "The product of force and the time for which the force acts on a body is equal to the change in ________ of the body.",
        options: [
        "Momentum",
        "Velocity",
        "Acceleration",
        "Displacement",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "Find the kinetic energy (in joules) of a body of mass 10 kg moving with a velocity of 4 m/s.",
        options: [
        "80 J",
        "160 J",
        "320 J",
        "640 J",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "Radio waves transimitted from the earth are refelcted back to the earth by which layer of the atmosphere?",
        options: [
        "Ionosphere",
        "Stratosphere",
        "Troposphere",
        "Mesosphere",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "Consider a conductor in the plane of the paper with current going from bottom to top. What will be the direction of the magnetic field lines to the left of the conductor?",
        options: [
        "Opposite to the direction of the current",
        "Perpendicular to the plane of the paper and going in",
        "In the direction of the current",
        "Perpendicular to the plane of the paper and coming out",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "What is the name of the phenomenon that causes white light to split into seven colours as it passes through a glass prism?",
        options: [
        "Diffraction",
        "Refraction",
        "Scattering",
        "Dispersion",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-3': [
      {
        id: 1,
        question: "In 1995, physicists Eric Cornell and Carl Wieman created the first Bose-Einstein condensate (BEC) using which isotope?",
        options: [
        "Caesium-133",
        "Rubidium-87",
        "Sodium-23",
        "Thorium-232",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "When light enters from air into a medium, its speed changes. Which of the following properties of light remains constant during this transition?",
        options: [
        "Frequency",
        "Wavelength",
        "Amplitude",
        "Phase",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "Which of the following instrument is used to detect the presence of electricity in a circuit?",
        options: [
        "Ammeter",
        "Voltmeter",
        "Ohmmeter",
        "Galvanometer",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "If an object moves from point A to point B (50 m east) and returns to point A in 10 seconds, what is the average velocity of the object?",
        options: [
        "0 m/s",
        "5 m/s",
        "10 m/s",
        "20 m/s",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "The technology that uses the reflection of ultrasound waves to produce image of the heart is called ________",
        options: [
        "Echocardiography",
        "Magnetic resonance imaging",
        "Sonography",
        "Computed tomography",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Reverberation is the persistence of sound after the source has stopped emitting sound due to ________ from multiple surfaces.",
        options: [
        "Reflection",
        "Refraction",
        "Diffraction",
        "Scattering",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "If the kinetic energy of a moving body is 450 joules and its velocity is 15 m/s, what is the mass of the body?",
        options: [
        "10 kg",
        "20 kg",
        "15 kg",
        "4 kg",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "Which of the following is a practical application of the Archimedes principle in daily life?",
        options: [
        "Operating a pendulum",
        "Using a thermometer",
        "Using a prism for light dispersion",
        "Design of ships and submarines",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "What happens to the speed of sound in a medium when the temperature of the medium is increased?",
        options: [
        "Increases",
        "Decreases",
        "Remains the same",
        "Becomes zero",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "A pyranometer is a ________ measuring instrument, commonly used for climate research or monitoring  weather performance?",
        options: [
        "Atmospheric pressure",
        "Cloud ceiling",
        "Solar irradiance",
        "Weather forecast",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "In which year did Galileo Galilei describe the regular, swinging motion of a pendulum by the action of gravity and acquired momentum?",
        options: [
        "1602",
        "1603",
        "1604",
        "1605",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "When white light is passed through a glass prism, it is split into several colours. This is due to ________",
        options: [
        "Refraction",
        "Reflection",
        "Dispersion",
        "Scattering",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "Where does the center of curvature of a concave mirror lie?",
        options: [
        "In front of the mirror",
        "Behind the mirror",
        "At the center of the mirror",
        "At the focal point",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "The work done by a constant force acting on a body is ________",
        options: [
        "Always zero",
        "Always positive",
        "Always negative",
        "Can be positive or negative",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "The electrical equivalent of one horse power is equal to ________ in the International System of Units (SI)?",
        options: [
        "746 watts",
        "746 joules",
        "746 volts",
        "746 amperes",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "An elecric bulb is connected to a 220 V generator. The current generated through the bulb is 0.5 A. What is the power of the bulb?",
        options: [
        "110 watts",
        "220 watts",
        "440 watts",
        "880 watts",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "As the temperature increases, the kinetic energy of particles in a matter ________",
        options: [
        "Increases",
        "Decreases",
        "Remains the same",
        "Becomes zero",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "What happens to the kinetic energy of a moving object if its velocity is tripled?",
        options: [
        "Increases by 3 times",
        "Increases by 9 times",
        "Decreases by 3 times",
        "Decreases by 9 times",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "Which of the following principles is responsible for the operation of spray bottles, such as those used for household cleaners or perfumes?",
        options: [
        "Bernoulli's principle",
        "Pascal's law",
        "Archimedes' principle",
        "Stokes's law",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "If a wire is stretched to quadruple its length without changing its area, what will happen to its resistivity?",
        options: [
        "It halves",
        "It doubles",
        "It quadruples",
        "It remains the same",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "If a resistor of 15 ohms carries a current of 2.5 amperes for 12 seconds, the heat produced is ________",
        options: [
        "900 joules",
        "1125 joules",
        "1500 joules",
        "1800 joules",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "If a conductor follows Ohm's law, then the graph between voltage and current is ________",
        options: [
        "A straight line",
        "A curve",
        "A parabola",
        "A hyperbola",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "If a 5 newton force is applied to an object and it displaces it by 3 meters from its initial position, then what is the work done by the force?",
        options: [
        "15 joules",
        "30 joules",
        "45 joules",
        "60 joules",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "Which state of matter has the highest kinetic energy of particles?",
        options: [
        "Solid",
        "Liquid",
        "Gas",
        "Plasma",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "Which of the following correctly describes the sum of kinetic energy and potential energy of an object?",
        options: [
        "Total chemical energy",
        "Total mechanical energy",
        "Total thermal energy",
        "Total nuclear energy",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-4': [
      {
        id: 1,
        question: "An object is placed 12 cm in front of a convex mirror with a focal length of 8 cm. What is the distance of the image from the mirror?",
        options: [
        "4.8 cm",
        "8 cm",
        "12 cm",
        "16.8 cm",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Which of the following works on the basis of conservation of linear momentum?",
        options: [
        "Aeroplane",
        "Helicopter",
        "Jet engine",
        "Rocket",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "Which one of the following types of mirrors is used to see the traffic behind the car?",
        options: [
        "Convex mirror",
        "Concave mirror",
        "Plane mirror",
        "Spherical mirror",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Which among the following has highest electron affinity?",
        options: [
        "Fluorine",
        "Chlorine",
        "Helium",
        "Xenon",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Using which of the following processes can one separate a solute from its solution?",
        options: [
        "Evaporation",
        "Distillation",
        "Filtration",
        "Crystallization",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "What is the value of the least distance of distinct vision (in cm) for a normal human being?",
        options: [
        "25 cm",
        "30 cm",
        "15 cm",
        "20 cm",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "What is the angle between the centripetal acceleration and the tangential acceleration of a body moving in a circular path?",
        options: [
        "0°",
        "45°",
        "90°",
        "180°",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "The instrument used in measuring the distance covered by vehicle is ________",
        options: [
        "Odometer",
        "Tachometer",
        "Chronometer",
        "Chronograph",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "For which one of the following does the centre of mass lie outside the body?",
        options: [
        "Fountain pen",
        "Cricket ball",
        "Book",
        "Ring",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Which of the following electromagnetic waves has minimum wavelength?",
        options: [
        "Alpha",
        "Beta",
        "Gamma",
        "X-rays",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "What is the heat released by a heating filament rated 20 watts when it is kept on for 2 seconds?",
        options: [
        "20 joules",
        "40 joules",
        "80 joules",
        "160 joules",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "Heat is transmitted from higher temperature to lower temperature by which of the following processes?",
        options: [
        "Conduction",
        "Convection",
        "Radiation",
        "All of the above",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "An air bubble in water will act like as a ________",
        options: [
        "Convex mirror",
        "Convex lens",
        "Concave mirror",
        "Concave lens",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Which of the following physical quantities is scalar quantity?",
        options: [
        "Impulse",
        "Acceleration",
        "Power",
        "Weight",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "The frictional force exerted by fluids is also called as ________",
        options: [
        "Drag force",
        "Buoyancy force",
        "Thrust force",
        "Centripetal force",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "A device which converts electrical energy into mechanical energy is called as ________",
        options: [
        "Motor",
        "Generator",
        "Transformer",
        "Dynamo",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "What is the phenomenon which established the transeverse nature of light?",
        options: [
        "Interference",
        "Refraction",
        "Diffraction",
        "Polarization",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "When a ball is thrown vertically upwards, which of the following quantities remains constant during its motion?",
        options: [
        "Velocity",
        "Acceleration",
        "Time",
        "Distance",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "Which of the following is used as a non-stick coating for cooking utensils?",
        options: [
        "Teflon",
        "Silicon",
        "Perspex",
        "Styrofoam",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Which of the following methods is used for measuring the age of the earth?",
        options: [
        "Biological dating",
        "Iron dating",
        "Thermoluminescence dating",
        "Uranium processing",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "The Sun and the Moon appear elliptical near the horizon because of ________",
        options: [
        "Refraction of light",
        "Reflection of light",
        "Diffraction of light",
        "Scattering of light",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "With which scientist did William Ramsay show in 1894 that air also contained an element unknown until then, which was later named as Argon?",
        options: [
        "Glenn Seaborg",
        "Harold Urey",
        "Hermann Kolbe",
        "Lord Rayleigh",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "What is the name of the chemical compound having the molecular formula C3H4O which is mostly used for the production of acrylic acid and acrylate esters?",
        options: [
        "Acrolein",
        "Muscone",
        "Naphthaldehyde",
        "Vanillin",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "Which physical quantity is represented by the ratio of momentum and velocity of the body?",
        options: [
        "Mass",
        "Inertia",
        "Force",
        "Acceleration",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "What is the fundamental unit of amount of a substance?",
        options: [
        "Mole",
        "Kelvin",
        "Candela",
        "Meter",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-5': [
      {
        id: 1,
        question: "The ozone layer protects us from harmful ________ rays of the sun",
        options: [
        "Ultraviolet",
        "Infrared",
        "Gamma",
        "X-rays",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Which one of the following is the unit of measure of the thickness of the ozone layer of the atmosphere?",
        options: [
        "Knot",
        "Dobson",
        "Maxwell",
        "Poise",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "In 1851, who founded the science of hydrodynamics with his law of viscosity describing the velocity of small sphere through a viscous fluid?",
        options: [
        "Daniel Bernoulli",
        "Evangelista Torricelli",
        "George Stokes",
        "Heinrich Magnus",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Hydrogen bomb is based on the principle of ________",
        options: [
        "Controlled Nuclear fission",
        "Uncontrolled Nuclear fission",
        "Controlled Nuclear fusion",
        "Uncontrolled Nuclear fusion",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "________ is same on every point on a rotating body.",
        options: [
        "Angular momentum",
        "Linear momentum",
        "Angular velocity",
        "Linear velocity",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "What is the name of the thermionic electron tube used to oscillate and amplify microwave frequency signals?",
        options: [
        "Klystron",
        "Magnetron",
        "Neutrino",
        "Thyratron",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "The instrument used to regulate the temperature to a particular degree is ________",
        options: [
        "Thermometer",
        "Thermostat",
        "Manometer",
        "Thermocouple",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "If the orbit of a planet is an ellipse, then what is the point at which the Sun is located called ________",
        options: [
        "Centre",
        "Circumcenter",
        "Focus",
        "Solstice",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Which of the following elements is highly effective for making a permanent magnet?",
        options: [
        "Zinc",
        "Copper",
        "Steel",
        "Aluminum",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Which of the following laws state that \"The magnitude of the induced EMF in a circuit is equal to the time rate of change of magnetic flux through the circuit\"?",
        options: [
        "Faraday's law of induction",
        "Ampere's law",
        "Coulomb's law",
        "Gauss's law",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "The bluish color of the water in the deep sea is due to ________",
        options: [
        "Scattering of light",
        "Reflection of light",
        "Refraction of light",
        "Diffraction of light",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "The blue color of the sky is due to ________",
        options: [
        "Scattering of light",
        "Reflection of light",
        "Refraction of light",
        "Diffraction of light",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "Which of the following relations represents the correct mathematical form of the Ohm's law?",
        options: [
        "V = I × R",
        "I = V × R",
        "R = V × I",
        "V = I / R",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Twinkling of stars is due to ________",
        options: [
        "Scattering of light",
        "Reflection of light",
        "Refraction of light",
        "Diffraction of light",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "What is the SI unit of power of a lens called ________",
        options: [
        "Diopter",
        "Dyne",
        "Lumen",
        "Lux",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "The resistivity of a material is dependent on which of the following factors?",
        options: [
        "Length",
        "Area",
        "Temperature",
        "All of the above",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "The frequency of AC supply for household appliances is ________",
        options: [
        "50 Hz",
        "60 Hz",
        "100 Hz",
        "120 Hz",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "We hear others speaking to us from adjacent rooms due to __________ of sound waves",
        options: [
        "Echo",
        "Reflection",
        "Refraction",
        "Diffraction",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "What is the human ear's normal audible range?",
        options: [
        "20 Hz - 20000 Hz",
        "20 Hz - 2000 Hz",
        "20 Hz - 200 Hz",
        "20 Hz - 2000 Hz",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Which of the following is the sound of single frequency?",
        options: [
        "Harmonic",
        "Tone",
        "Noise",
        "Note",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "What is the wavelength range of infra-red rays?",
        options: [
        "780 nm - 1 mm",
        "800 nm - 1 µm",
        "400 nm - 1 mm",
        "600 nm - 1 µm",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "Which part of the ear turns the sound vibrations into electrical signals?",
        options: [
        "Tympanic membrane",
        "Cochlea",
        "Auditory nerve",
        "Pinna",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "Four wires of the same material are connected like beads of a garland. The equivalent resistance of the garland is ________",
        options: [
        "R/4",
        "R/2",
        "R",
        "4R",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "The shape of the voltage-current graph for a conductor is ________",
        options: [
        "Straight line",
        "Parabola",
        "Hyperbola",
        "Ellipse",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "Who among the following established a unit of horse power that is equal to one horse doing 33,000 foot-pounds of work per minute?",
        options: [
        "James Watt",
        "James Croll",
        "James Black",
        "James Prescott Joule",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-6': [
      {
        id: 1,
        question: "Which one of the following is NOT a scalar quantity?",
        options: [
        "Distance",
        "Speed",
        "Force",
        "Time",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Which of the following phenomenona is NOT involved during the formation of a rainbow?",
        options: [
        "Refraction",
        "Total internal reflection",
        "Dispersion",
        "Scattering",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "The angle between the direction of electric current and magnetic field of an electromagntic wave is ________",
        options: [
        "90°",
        "180°",
        "360°",
        "270°",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Which of the following quantities remains unchanged when a charged particle moves in a magnetic field?",
        options: [
        "Kinetic energy",
        "Potential energy",
        "Momentum",
        "Angular momentum",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Which of the following techniques is used to separate colloidal particles from a solution?",
        options: [
        "Filtration",
        "Centrifugation",
        "Electrolysis",
        "Sublimation",
        ],
        correctAnswer: undefined,
      }
    ],
  },
}
