export const polityQuiz = {
  quizzes: {
    'quiz-1': [
      {
        id: 1,
        question: "The Indian Constitution has established _______",
        options: [
        "Dual judicial system",
        "Independent judicial system",
        "Partial judicial system",
        "Plural judicial system",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "During the framing of the Indian Constitution, the Constituent Assembly held a total of eleven sessions, with sittings spread over how many days?",
        options: [
        "165",
        "175",
        "185",
        "195",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "Who among the following, while praising the amnding feature of the Indian Constitution said that \"This variety in the aminding process is wise but is rarely found\"",
        options: [
        "Granville Austin",
        "HM Seervai",
        "Ivor Jennings",
        "KC Wheare",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "When was the \"The Objective Resolution\" moved by Jawaharlal Nehru?",
        options: [
        "13.12.1946",
        "17.11.1946",
        "15.08.1947",
        "16.11.194",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Who among the following persnalities was appointed as the legal advisor of the Constituent Assembly that drafted the documentof the Constitution of India?",
        options: [
        "BN Rau",
        "BR Ambedkar",
        "HVR Iyengar",
        "SN Mukherjee",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "The original Constitution of India was handwritten in English by whom?",
        options: [
        "HVR Iyengar",
        "Prem Behari Narayan Raizada",
        "SN Mukherjee",
        "Vasant Krishan Vaidya",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "Who among the following wrote in calligraphic style the Hindi version of the original Constitution of India?",
        options: [
        "HVR Iyengar",
        "Prem Behari Narayan Raizada",
        "SN Mukherjee",
        "Vasant Krishan Vaidya",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "The structural part of the Indian Constitution is, to a large extent, derived from the act of _______",
        options: [
        "The Government of India Act, 1935",
        "The Government of India Act, 1919",
        "The Government of India Act, 1909",
        "The Government of India Act, 1926",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "How many female members were part of the Constituent Assembly that framed the Constitution of India?",
        options: [
        "12",
        "13",
        "14",
        "15",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Who was the chairman of the House Committee of the Constituent Assembly of India?",
        options: [
        "AV Thakkar",
        "B Pattabhi Sitaramayya",
        "JB Kripalani",
        "KM Munshi",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "The total membership of the Constituent Assembly was 389, of which _______ were representatives of the princely states",
        options: [
        "84",
        "93",
        "102",
        "109",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "When was the first meeting of the Constituent Assembly of India held?",
        options: [
        "09.12.1946",
        "15.08.1947",
        "26.11.1949",
        "26.01.1950",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "Who was the President of the Constituent Assembly of India?",
        options: [
        "Rajendra Prasad",
        "Sarvepalli Radhakrishnan",
        "V.V. Giri",
        "Zakir Husain",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Which plan led to the formation of the Constituent Assembly of India?",
        options: [
        "August Plan",
        "Cabinet Mission Plan",
        "Cripps Mission Plan",
        "Mountbatten Plan",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "How many members were originally in the Constituent Assembly of India?",
        options: [
        "299",
        "352",
        "389",
        "401",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "Which part of the Constitution of India deals with the Directive Principles of State Policy?",
        options: [
        "Part III",
        "Part IV",
        "Part II",
        "Part V",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "Fundamental Rights are in which part of the Constitution of India?",
        options: [
        "Part III",
        "Part IV",
        "Part II",
        "Part V",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "Which part of the Constitution of India deals with the Union Government",
        options: [
        "Part V",
        "Part VI",
        "Part VII",
        "Part VIII",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "Emergency provisions are contained in which part of the Constitution of India?",
        options: [
        "Part XVI",
        "Part XVII",
        "Part XVIII",
        "Part XIX",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Which part of the Constitution of India deals with the Panchayats",
        options: [
        "Part IX",
        "Part X",
        "Part XI",
        "Part XII",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "Which Schedule of the Constitution of India contains the languages recognized by the Constitution of India?",
        options: [
        "Schedule VI",
        "Schedule VII",
        "Schedule VIII",
        "Schedule IX",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "Which Schedule of the Constitution of India deals with the allocation of seats in the Rajya Sabha",
        options: [
        "Schedule III",
        "Schedule IV",
        "Schedule V",
        "Schedule VI",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "The Tenth Schedule of the Constitution of India deals with the _______",
        options: [
        "Anti-defection law",
        "Language",
        "Oaths and Affirmations",
        "National Integration",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "Which Schedule of the Constitution of India contains provisions for administration of tribal areas in Assam, Meghalaya, Tripura and Mizoram?",
        options: [
        "Schedule V",
        "Schedule VI",
        "Schedule VII",
        "Schedule VIII",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "",
        options: [
        "",
        "",
        "",
        "",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-2': [
      {
        id: 1,
        question: "Which article has a similar provision to that of Article 32 and deals with writ jurisdiction?",
        options: [
        "Article 226",
        "Article 227",
        "Article 228",
        "Article 229",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Right of prisoner to speedy trial will be categorised in which of the folowing Fundamental Rights?",
        options: [
        "Right against Exploitation",
        "Right to Equality",
        "Right to Constitutional Remedies",
        "Right to Life and Liberty",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "Which Article of the Indian Constitution prohibits of any religious instruction in the educational istitutions maintained by the Union or by a State or by a local authority?",
        options: [
        "Article 28",
        "Article 29",
        "Article 30",
        "Article 31",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Which Article of the Indian Constitution deals with the Right to Constitutional Remedies?",
        options: [
        "Article 32",
        "Article 33",
        "Article 34",
        "Article 35",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Which of the following Articles of the Indian Constitution CANNOT be suspended even during an emergency declared on the grounds of external aggression or internal disturbance?",
        options: [
        "Articles 14 and 16",
        "Articles 15 and 17",
        "Articles 20 and 21",
        "Articles 30 and 32",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "If a 12-year old is found to be working in a factory manufacturing carpets, which of the following Articles of the Indian Constitution will be violated?",
        options: [
        "Article 23",
        "Article 24",
        "Article 25",
        "Article 26",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "In which part of the Constitution of India will you find the six broad categories of fundamental rights?",
        options: [
        "Part III",
        "Part IV",
        "Part II",
        "Part V",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "Writ of Mandamus is a fundamental right classified under which of the following categories?",
        options: [
        "Cultural and educational rights",
        "Constitutional remedies",
        "the right to freedom of religion",
        "the right to equality",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Which of the following Articles of the Indian Constitution prohibits traffic in human beings and forced labour?",
        options: [
        "Article 23",
        "Article 24",
        "Article 25",
        "Article 26",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Which clause of Article 20 incorporates the doctrine of double jeopardy?",
        options: [
        "Clause (1)",
        "Clause (2)",
        "Clause (3)",
        "Clause (4)",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "_______ has called the Right to Constitutional Remedy as the \"Soul of the Constitution\"",
        options: [
        "Bal Gangadhar Tilak",
        "Dr. BR Ambedkar",
        "Jawaharlal Nehru",
        "Lala Lajpat Rai",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "__________ is issued to prevent an inferior court or tribunal from exceeding its jurisdiction, which is not legally vested, or acting without jurisdiction or acting against the principles of natural justice.",
        options: [
        "Writ of Prohibition",
        "Writ of Mandamus",
        "Writ of Habeas Corpus",
        "Writ of Quo Warranto",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "Which of the following Fundamental Rights is available for Indians as well as foreigners?",
        options: [
        "Right to protection of language, script and culture of minorities",
        "Equality of opportunity in matters of public employment",
        "Right to minorities establish and administer educational institutions",
        "Right to elementary education",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Which writ literally means \"what is your authority to do this?\"",
        options: [
        "Quo Warranto",
        "Prohibition",
        "Mandamus",
        "Habeas Corpus",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "Citizens are NOT discriminated against on the basis of religion, caste, or sex because of _______",
        options: [
        "Right to Equality",
        "Right to Freedom of Religion",
        "Right to Freedom of Speech",
        "Right to Freedom of the Press",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "How many Fundamental Rights were initially provided in the Constitution of India?",
        options: [
        "5",
        "6",
        "7",
        "8",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "__________ of the Constitution of India has provision for legal enforcement of Fundamental Rights?",
        options: [
        "Article 32",
        "Article 33",
        "Article 34",
        "Article 35",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "Which of the following is enforceable by the Indian Constitution?",
        options: [
        "Directive Principles of State Policy",
        "Fundamental Rights",
        "Fundamental Duties",
        "Preamble",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "The Preamble of the Constitution of India describes India as a \"_______\"",
        options: [
        "an atheist state",
        "a unitary state",
        "a secular state",
        "a federal state",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Which of the following word sequences is correct as per the Preamble of the Constitution of India?",
        options: [
        "Sovereign, socialist, secular, democratic, republic",
        "Secular, democratic, socialist, sovereign",
        "Sovereign, secular, socialist, democratic, republic",
        "Socialist, secular, democratic,republic, sovereign",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "When was the Preamble of the Constitution of India amended?",
        options: [
        "1976",
        "1977",
        "1978",
        "1979",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "Who called the Preamble of the Constitution of India as the \"The Political Horoscope of our Constitution\"?",
        options: [
        "Dr. KM Munshi",
        "M. Hidayatullah",
        "Sir Alladi Krishnaswami Aiyar",
        "Sir Ernest Barker",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "From which of the following Constitutions is the idea of \"Charter of Fundamental Rights\" adapted in the Constitution of India?",
        options: [
        "Brazil",
        "France",
        "Spain",
        "USA",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "Which of the following words is not found in the original Preamble of the Constitution of India?",
        options: [
        "Sovereign",
        "Socialist",
        "Secular",
        "Both B and C",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "The Preamble of the Constitution of India declares India to be a \"_______\"",
        options: [
        "A federal state",
        "A unitary state",
        "A Sovereign Socialist Secular Democratic Republic",
        "A monarchy",
        ],
        correctAnswer: undefined,
      },
      {
        id: 26,
        question: "Which amendment added the words \"Socialist\" and \"Secular\" to the Preamble of the Constitution of India?",
        options: [
        "42nd Amendment",
        "43rd Amendment",
        "44th Amendment",
        "45th Amendment",
        ],
        correctAnswer: undefined,
      },
      {
        id: 27,
        question: "Who described the Preamble as the \"Identity Card of the Constitution\"?",
        options: [
        "Dr. BR Ambedkar",
        "Dr. Rajendra Prasad",
        "Jawaharlal Nehru",
        "Nani Palkhivala",
        ],
        correctAnswer: undefined,
      },
      {
        id: 28,
        question: "The idea of the Preamble of the Constitution of India was inspired by the Constitution of the ________",
        options: [
        "United States of America",
        "United Kingdom",
        "France",
        "Germany",
        ],
        correctAnswer: undefined,
      },
      {
        id: 29,
        question: "The Preamble is part of the Constitution as per the verdict in which case?",
        options: [
        "A.K Gopalan vs State of Madras",
        "Golaknath vs State of Punjab",
        "Kesavananda Bharti vs State of Kerala",
        "M.C Mehta vs Union of India",
        ],
        correctAnswer: undefined,
      },
      {
        id: 30,
        question: "Which of the following best describes the nature of the Preamble of the Constitution of India?",
        options: [
        "It is enforceable by the courts",
        "It is not a part of the Constitution",
        "It is just a decorative element",
        "It embodies the spirit of the Constitution",
        ],
        correctAnswer: undefined,
      },
      {
        id: 31,
        question: "",
        options: [
        "",
        "",
        "",
        "",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-3': [
      {
        id: 1,
        question: "Which of the following provisions of the Indian Constitution has NOT been taken from the British Constitution?",
        options: [
        "Bicameral system",
        "Fundamental Rights",
        "Legislative process",
        "Rule of Law",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "The concurrent list in the Constitution of India was adopted from _______",
        options: [
        "Australia",
        "Canada",
        "New Zealand",
        "South Africa",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "Which of the following provisions of the Indian Constitution has been taken from the constitution of Canada?",
        options: [
        "Advisory jurisdiction of the Supreme Court",
        "Concept of Republic",
        "Concept of Concurrent List",
        "Independent Judiciary",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Which of the following provisions of the Indian Constitution has NOT been taken from the constitution of Canada?",
        options: [
        "Advisory jurisdiction of the Supreme Court",
        "Appointment of the Governor of the state by the Centre",
        "Concept of Concurrent List",
        "Union with a strong center",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Which of the following provisions and the constitutions of different countries from which they have been adopted in the Indian Constitution has been incorectly paired?",
        options: [
        "Charted of Fundamental Rights - US Constitution",
        "Directive Principles of State Policy - Irish Constitution",
        "Principles of Liberty, Equality and Fraternity - Canadian Constitution",
        "The idea of the rule of law - UK Constitution",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Which of the following features in the Indian Constitution was derived from the Union Soviet Socialist Republic (USSR)?",
        options: [
        "Concurrent List",
        "Fundamental Rights",
        "Five year plan",
        "Preamble",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "In the Indian Constitution, the principle of liberty is borrowed from the which of the following countries?",
        options: [
        "United States of America",
        "United Kingdom",
        "France",
        "Germany",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "The feature of \"Parliamentary Privileges\" of the Indian Constitution has been borrowed from the constitution of which country?",
        options: [
        "United States of America",
        "United Kingdom",
        "France",
        "Germany",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "The Quasi-federal form of government in the Indian Constitution has been borrowed from the constitution of which country?",
        options: [
        "United States of America",
        "United Kingdom",
        "France",
        "Canada",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "In which of the following countries the system of judicial review was originated?",
        options: [
        "United States of America",
        "United Kingdom",
        "France",
        "Canada",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "From which of the following are the Fundamental Duties adopted in the Indian Constitution?",
        options: [
        "United States of America",
        "United Kingdom",
        "Russia",
        "Canada",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "The idea of having a provision for a Bicameral Parliament in the Indian Constitution has been borrowed from the constitution of which country?",
        options: [
        "United States of America",
        "United Kingdom",
        "Russia",
        "Canada",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "The cabinet system of the Indian Constitution has been borrowed from the constitution of which country?",
        options: [
        "United States of America",
        "United Kingdom",
        "Russia",
        "Canada",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "In India, the principle of procedure established by law has been borrowed from the constitution of which country?",
        options: [
        "United States of America",
        "United Kingdom",
        "Japan",
        "Canada",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "Inspired by the constitution of which of the following nations, India has added the feature of \"Directive Principles of State Policy\" in its Constitution?",
        options: [
        "United States of America",
        "Ireland",
        "Japan",
        "Canada",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "The concept of liberty, equality and fraternity (contained in the preablem of the Indian Constitution) has been borrowed from the constitution of which country?",
        options: [
        "United States of America",
        "United Kingdom",
        "France",
        "Canada",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "Which of the following acts introduced federal features and provincial autonomy in the legislature and also made provisions for the distribution of legislative powers between the Centre and the Provinces?",
        options: [
        "Indian Councils Act 1909",
        "The Government of India Act, 1935",
        "The Government of India Act, 1919",
        "The Government of India Act, 1926",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "The provision of the speaker and his role of the Indian Constitution are borrowed from the ________ Constitution?",
        options: [
        "British",
        "American",
        "Canadian",
        "Australian",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "According to the Indian Constitution, which of the following is NOT a fundamental duty?",
        options: [
        "To protect public property",
        "To promote the feeling of brotherhood",
        "To follow the constitution and respects its identity",
        "Voting in Public Elections",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Which of the following options is NOT included in the Fundamental Duties of the Indian Constitution?",
        options: [
        "Focussing only on personal development and personal activity",
        "Respecting the National flag and National anthem",
        "To value and preserve the rich heritage of our composite culture",
        "To maintain and protect the sovereignty, unity and integrity of the nation",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-4': [
      {
        id: 1,
        question: "A money bill after having been passed by the Lok Sabha, and sent to Rajya Sabha for its recommendations, has to be returned to Lok Sabha by the Rajya Sabha, within a period of __________ from the date of its receipt, with or without recommendations",
        options: [
        "14 days",
        "16 days",
        "18 days",
        "20 days",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "The Rajya Sabha members are elected for a terms of how many years?",
        options: [
        "4",
        "5",
        "6",
        "7",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "Which bill can not originate in Rajya Sabha?",
        options: [
        "Money Bill",
        "Constitutional Amendment Bill",
        "Fundamental Bill",
        "Ordinary Bill",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Who is the Chairman of the Rajya Sabha?",
        options: [
        "President of India",
        "Vice President of India",
        "Speaker of Lok Sabha",
        "Deputy Speaker of Rajya Sabha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "In which of the following years was the council of states (Rajya Sabha) first constituted?",
        options: [
        "1952",
        "1953",
        "1954",
        "1955",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "How many members of the Rajya Sabha are elected every two years?",
        options: [
        "All",
        "Half",
        "One-third",
        "One-fourth",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "Out of 552 members of the Rajya Sabha, how many are elected from the states?",
        options: [
        "530",
        "535",
        "540",
        "545",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "Who among the following decides whether a particular bill is a money bill or not?",
        options: [
        "President of India",
        "Vice President of India",
        "Speaker of Lok Sabha",
        "Deputy Speaker of Rajya Sabha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Who was the first woman speaker of Lok Sabha?",
        options: [
        "Meira Kumar",
        "Meira Gandhi",
        "Sushma Swaraj",
        "Sumitra Mahajan",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "After question hour, a motion movd by a member of parliament to draw the attention of the executive for discussing a definite matter of public importance is called __________",
        options: [
        "Calling attention motion",
        "Adjournment motion",
        "No-confidence motion",
        "Privilege motion",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "Who presides over the jint sitting of the Lok Sabha and the Rajya Sabha?",
        options: [
        "President of India",
        "Vice President of India",
        "Speaker of Lok Sabha",
        "Deputy Speaker of Rajya Sabha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "Vote of No-confidence motion is brought in which house?",
        options: [
        "Lok Sabha",
        "Rajya Sabha",
        "Both",
        "None of the above",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "The President of India can dissolve the Lok Sabha before completion of term __________",
        options: [
        "On the advice of the Prime Minister",
        "On the advice of the President",
        "On the advice of the Speaker of Lok Sabha",
        "On the advice of the Deputy Speaker of Lok Sabha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Who among the following was the deputy speaker of the first Lok Sabha?",
        options: [
        "AK Gopalan",
        "MN Kaul",
        "Rabi Ray",
        "M A Ayangar",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "The minimum number of members that must be present to hold the meeting of the Lok Sabha is __________",
        options: [
        "One-fourth of the total membership",
        "One-tenth of the total membership",
        "Fifty percent of the total membership",
        "At least 100 members",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "The parliament form of government is also referred to as the ______________ model",
        options: [
        "Communist",
        "Plutocracy",
        "Theocracy",
        "Westminster",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "How many sessions of the Lok Sabha are normally held in a year?",
        options: [
        "1",
        "2",
        "3",
        "4",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "Who decides on the issue related to the dis-qualification of a member of Lok Sabha under Tenth Schedule of the Indian Constitution?",
        options: [
        "President of India",
        "Vice President of India",
        "Speaker of Lok Sabha",
        "Deputy Speaker of Lok Sabha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "Which of the following articles of the Indian Constitution provides for the Bicameral Parliament of India?",
        options: [
        "Article 76",
        "Article 77",
        "Article 78",
        "Article 79",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Who decides disputes regarding the dis-qualification of members of Parliament?",
        options: [
        "President of India",
        "Election Commission",
        "The Prime Minister in consultation with the Election Commission",
        "The President in consultation with the Election Commission",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "What is the Quorum laid down to constitute a meeting of either of the houses of Parliament?",
        options: [
        "One-third",
        "One-fifth",
        "One-tenth",
        "One-twelfth",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "In the context of the Indian Parliament, what is zero-hour?",
        options: [
        "Time in the first half of the Parliamentary proceeding",
        "Time immediately after question hour",
        "Time before question hour",
        "Time in the last half of the Parliamentary proceeding",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-5': [
      {
        id: 1,
        question: "How many other members are there in the Finance Commission EXCEPT, Chairman?",
        options: [
        "3",
        "4",
        "5",
        "6",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "In which of the following years was the Election Commission of India established?",
        options: [
        "1950",
        "1951",
        "1952",
        "1953",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "What is the tenure of office of the Chief Election Commissioner?",
        options: [
        "5 years or upto age of 60 years",
        "5 years or upto age of 65 years",
        "6 years or upto age of 60 years",
        "6 years or upto age of 65 years",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Who among the is NOT a member of the National Human Rights Commission?",
        options: [
        "District Magistrate",
        "Former Chief Justice of the High Court",
        "Former Judge of the Supreme Court",
        "Former Chief Justice of the Supreme Court",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Which part of the Indian Constitution deals with the Election Commission of India?",
        options: [
        "Part XIII",
        "Part XIV",
        "Part XV",
        "Part XVI",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "UPSC is a Constitutional Body to conduct examinations for appointments to the services of the Union and the services of the State, respectively, under Article ________ of the Constitution of India?",
        options: [
        "Article 320",
        "Article 321",
        "Article 322",
        "Article 323",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "The establishment of Union Public Service Commission, State Public Service Commissions and Joint Public Service Commission falls under which of the following features of the Indian Constitution?",
        options: [
        "Directive Principles of State Policy",
        "Fundamental Rights",
        "Federalism",
        "Parliamentary System",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "Which Article of the Indian Constitution mentions about the recommendations of the Finance Commission?",
        options: [
        "Article 280",
        "Article 281",
        "Article 282",
        "Article 283",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "What is the maximum age for a member of a joint public service commission to hold his/her officer as per the Indian Constitution?",
        options: [
        "60 years",
        "62 years",
        "63 years",
        "65 years",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Who was the first Chairman of the Finance Commission of India?",
        options: [
        "Ashok Kumar Chanda",
        "K Santhanam",
        "KC Neogy",
        "PV Rajamannar",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "Under which of the following Acts was the National Commission for Women established?",
        options: [
        "The National Commission for Women Act, 1987",
        "The National Commission for Women Act, 1988",
        "The National Commission for Women Act, 1989",
        "The National Commission for Women Act, 1990",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "Who appoints the State Election Commissioners?",
        options: [
        "Chief Minister",
        "Governor",
        "President",
        "Advocate General",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "The Chairman of a State Public Service Commission can be removed by the order of the __________",
        options: [
        "Chief Minister",
        "Governor",
        "President",
        "Advocate General",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Which of the following is NOT a Constitutional Body in India?",
        options: [
        "Election Commission of India",
        "State Human Rights Commission",
        "State Public Service Commission",
        "Union Public Service Commission",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "The elections to the Panchayati Raj Institutions are conducted by the __________",
        options: [
        "Election Commission of India",
        "State Election Commission",
        "Union Election Commission",
        "State Public Service Commission",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "What is the tenure of the Chairperson of National Human Rights Commission?",
        options: [
        "3 years",
        "4 years",
        "5 years",
        "6 years",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "In which year was the National Commission for Women established in India?",
        options: [
        "1990",
        "1991",
        "1992",
        "1993",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "",
        options: [
        "District Magistrate",
        "Former Chief Justice of the High Court",
        "Former Judge of the Supreme Court",
        "Former Chief Justice of the Supreme Court",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-6': [
      {
        id: 1,
        question: "In India, who among the following has the power to pardon, remit or commute the punishment of a criminal",
        options: [
        "President of India",
        "Vice President of India",
        "Speaker of Lok Sabha",
        "Prime Minister",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Which of the following statements in NOT correct regarding the election of the Vice President of India?",
        options: [
        "He should be a citizen of India",
        "He is eligible to contest elections as a member of the Rajya Sabha",
        "He is eligible to contest elections as a member of the Lok Sabha",
        "He should be above 35 years of age",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "A bill becomes an Act of the Parliament after being passed by both the Houses of Parliament and assented to by the __________",
        options: [
        "President of India",
        "Vice President of India",
        "Speaker of Lok Sabha",
        "Prime Minister",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Which of the following Articles of the Constitution of India states that there will be Vice President of India",
        options: [
        "Article 61",
        "Article 62",
        "Article 63",
        "Article 64",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Which of the following Articles of Constitution of India deals with the manner of election of the President of India",
        options: [
        "Article 55",
        "Article 56",
        "Article 57",
        "Article 58",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "The President of India has the power to pardon under which article of the Constitution of India?",
        options: [
        "Article 70",
        "Article 71",
        "Article 72",
        "Article 73",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "As per the Constitution of India, who is authorised to transfer the Judge of the High Court to another High Court?",
        options: [
        "President of India",
        "Governor of the State",
        "Chief Justice of the High Court",
        "Chief Justice of the Supreme Court",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "With whose consultation does the President of India convene ad prorogue Parliament?",
        options: [
        "The Speaker",
        "The Prime Minister",
        "The Council of Ministers",
        "The Prime Minister and the leader of the opposition in Lok Sabha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "In case of death of the President and Vice President of India, who will act as the President of India?",
        options: [
        "Attorney General of India",
        "Chief Justice of Supreme Court",
        "Prime Minister of India",
        "Parliament chosen candidate",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "How many members can be nominated by the President of India in the Rajya Sabha?",
        options: [
        "8",
        "10",
        "12",
        "14",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "Who has the right to investigate and decide all the doubts and controversies arising out of the election of the President of India?",
        options: [
        "Supreme Court of India",
        "Vice President of India",
        "Speaker of Lok Sabha",
        "Lokpal",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "Under which article of the Constitution of India can the President of India promulgate an ordinance?",
        options: [
        "Article 120",
        "Article 121",
        "Article 122",
        "Article 123",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "Who is nominal executive authority of India?",
        options: [
        "President of India",
        "Vice President of India",
        "Speaker of Lok Sabha",
        "Prime Minister",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Which of the following is NOT an eligibility requirement to become the Vice President of India?",
        options: [
        "He should be a citizen of India",
        "He should have completed 40 years of age",
        "He should be qualified to be as a member of Rajya Sabha",
        "They should not hold any office of profit under the Government of India or the Government of any State",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "Which of the following statement is CORRECT",
        options: [
        "The Governor can dissolve the Legislative Assembly of a State",
        "The Speaker of the Lok Sabha can dissolve the Lok Sabha",
        "The President of India can dissolve the Rajya Sabha",
        "The Vice President of India can dissolve the Legislative Assembly of a State",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "Which Article of the Constitution of India deals with the \"Pardoning Power of the Governor\"",
        options: [
        "Article 160",
        "Article 161",
        "Article 162",
        "Article 163",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "Who was the first Woman Governor of an Indian State?",
        options: [
        "Sarojini Naidu",
        "Sucheta Kripalani",
        "Padmaja Naidu",
        "Tarkeswari Sinha",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-7': [
      {
        id: 1,
        question: "Who is the real executive head of the Union Government in India?",
        options: [
        "President of India",
        "Vice President of India",
        "Prime Minister",
        "Speaker of Lok Sabha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "The Prime Minister of India is appointed by the __________",
        options: [
        "President of India",
        "Vice President of India",
        "Parliament",
        "Council of Ministers",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "The Prime Minister of India must be a member of __________",
        options: [
        "Lok Sabha",
        "Rajya Sabha",
        "Either Lok Sabha or Rajya Sabha",
        "Neither Lok Sabha nor Rajya Sabha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Who presides over the meetins of the Union Cabinet?",
        options: [
        "President of India",
        "Vice President of India",
        "Prime Minister",
        "Speaker of Lok Sabha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Which Article of the Constitution of India mentions the Prime Minister of India?",
        options: [
        "Article 74",
        "Article 75",
        "Article 78",
        "All of the above",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Who acts as the link between the President and Council of Ministers?",
        options: [
        "President of India",
        "Vice President of India",
        "Prime Minister",
        "Speaker of Lok Sabha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "In the event of the death or resignation of the Prime Minister, the Council of Ministers",
        options: [
        "Continues",
        "Automatically dissolves",
        "Is headed by the President",
        "Stay until Parliament is dissolved",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "Who prepares the list of Portfolios for the Council of Ministers?",
        options: [
        "President of India",
        "Vice President of India",
        "Prime Minister",
        "Speaker of Lok Sabha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Which body is responsible for making major policy decisions in India?",
        options: [
        "Lok Sabha",
        "Planning Commission",
        "President of India",
        "Union Cabinet",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Who is the real executive head of a state?",
        options: [
        "Governor",
        "Chief Minister",
        "Chief Secretary",
        "State Assembly Speaker",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "Who appoints the Chief Minister of a state?",
        options: [
        "President of India",
        "Governor of the State",
        "Chief Justice of the High Court",
        "Speaker of Lok Sabha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "Which Article of the Constitution of India deals with the \"Appointment of the Chief Minister of a State\"?",
        options: [
        "Article 164",
        "Article 165",
        "Article 166",
        "Article 167",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "What is the maximum term of a Chief Minister of a State?",
        options: [
        "4 years",
        "5 years",
        "6 years",
        "No fixed term",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "The Chief Minister communicates all administrative decisions to__________",
        options: [
        "President of India",
        "Governor of the State",
        "Chief Justice of the High Court",
        "State Assembly Speaker",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "Who allocates the portfolios among the state ministers?",
        options: [
        "Governor of the State",
        "Chief Minister",
        "Chief Justice of the High Court",
        "State Assembly Speaker",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "In case of resignation of Chief Minister, the Council of Ministers",
        options: [
        "Continues",
        "Automatically dissolves",
        "Is headed by the Governor",
        "Is reappointed by the Governor",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "The Chief Minister is required to be a member of the state legislature within:",
        options: [
        "3 months",
        "4 months",
        "6 months",
        "1 year",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "Which Article of the Constitution of India deals with the duties of Chief Minister to communicate with the Governor?",
        options: [
        "Article 164",
        "Article 165",
        "Article 166",
        "Article 167",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "Chief Minister is the head of the",
        options: [
        "State Government",
        "Union Government",
        "State Legislature",
        "Council of Ministers",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "The Council of Ministers is collectively responsible for",
        options: [
        "Lok Sabha",
        "Rajya Sabha",
        "President",
        "Supreme Court",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "What is the maximum number of ministers in a state including the Chief Minister?",
        options: [
        "10% of the total members",
        "15% of the total members",
        "20% of the total members",
        "25% of the total members",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "Ministers hold office during the peasure of the:",
        options: [
        "Prime Minister",
        "President",
        "Parliament",
        "Supreme Court",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "The Council of Ministers includes the",
        options: [
        "Cabinet Ministers only",
        "Minister of State only",
        "Deputy Ministers only",
        "All of the above",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "Who decides the rank of ministers in the Council of Ministers?",
        options: [
        "President of India",
        "Vice President of India",
        "Prime Minister",
        "Speaker of Lok Sabha",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-8': [
      {
        id: 1,
        question: "If the President neither signs nor returns a bill, it is consider as:",
        options: [
        "Absolute veto",
        "Pocket veto",
        "Suspensive veto",
        "Line-term veto",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Which veto power can the President of India exercise only in the case of non-money bills?",
        options: [
        "Absolute veto",
        "Pocket veto",
        "Suspensive veto",
        "Line-term veto",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "The President of India can not use veto power in case of",
        options: [
        "Consititutional amendment bills",
        "Financial bills",
        "Ordinary bills",
        "All of the above",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "The term \"absolute veto\" means:",
        options: [
        "President returns the bill for reconsideration",
        "Presidnet withholds assent permanently",
        "Presidnet delays the bill indefinitely",
        "President signs the bill into law",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "The veto power of the President of India is taken from:",
        options: [
        "British Constitution",
        "Canadian Constitution",
        "Irish Constitution",
        "US Constitution",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Which article of the Constitution of India empowers the President of India to give or withhold assent to a bill?",
        options: [
        "Article 110",
        "Article 111",
        "Article 112",
        "Article 113",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "Which of the following is NOT a veto power of the President of India?",
        options: [
        "Absolute veto",
        "Pocket veto",
        "Suspensive veto",
        "Line-term veto",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "What is the \"absolute veto\" means?",
        options: [
        "Amending a bill before passing",
        "Keeping the bill pending indefinitely",
        "Returning a bill for reconsideration",
        "Withholding assent to a bill",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "The President of India can exercise a pocket veto on whicy type of bills?",
        options: [
        "Consititutional amendment bills",
        "Financial bills",
        "Ordinary bills",
        "All of the above",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "The President of India must give assent to which of the following bills without using any veto power?",
        options: [
        "Consititutional amendment bills",
        "Financial bills",
        "Ordinary bills",
        "All of the above",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "Which articles of the Constitution of India deals with the Governor\"s assent to bills?",
        options: [
        "Article 200",
        "Article 201",
        "Article 202",
        "Article 203",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "The Governor can reserve a bill for the consideration of the President in which situation?",
        options: [
        "The bill is of political importance",
        "The bill conflicts with central laws",
        "The bill deals with salaries of MLAs",
        "The bill is passed by a voice vote",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "How many options does the Governor have when a bill is presented to him?",
        options: [
        "1",
        "2",
        "3",
        "4",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Can the Governor exercise a pocket veto like the President of India?",
        options: [
        "Yes",
        "No",
        "Only for money bills",
        "Only during Presidnetial rule",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "Which of the following powers i available to the President but not to the Governor?",
        options: [
        "Absolute veto",
        "Pocket veto",
        "Suspensive veto",
        "Line-term veto",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "How many types of emergencies are provided in the Constitution of India?",
        options: [
        "1",
        "2",
        "3",
        "4",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "Which Article of the Constitution of India deals with the \"National Emergency\"?",
        options: [
        "Article 352",
        "Article 353",
        "Article 354",
        "Article 355",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "Which type of emergency can be declared on the grounds of war, external aggression, or armed rebellion?",
        options: [
        "National emergency",
        "State emergency",
        "Financial emergency",
        "All of the above",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "The President can proclaim a national emergency only on the written advice of the:",
        options: [
        "The Prime Minister",
        "The Parliament",
        "The Cabinet",
        "The Speaker of the Lok Sabha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Once proclaimed, a national emergency must be approved by the Parliament within a period of:",
        options: [
        "1 month",
        "2 months",
        "3 months",
        "4 months",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "During a National Emergency, the fundamental rights uder which Article of the Constitution of India are suspended?",
        options: [
        "Article 19",
        "Article 20",
        "Article 21",
        "Article 22",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "Which constitutional amendment introduced the requirement of cabinet advice for national emergency?",
        options: [
        "42nd Amendment",
        "43rd Amendment",
        "44th Amendment",
        "45th Amendment",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "President\"s rule is declared when there is failure of constitutional machinery in a state under which Article of the Constitution of India?",
        options: [
        "Article 356",
        "Article 357",
        "Article 358",
        "Article 359",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "Maximum duration of President\"s rule in a state, with parliament approval:",
        options: [
        "6 months",
        "1 year",
        "2 years",
        "3 years",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "Which article empowers the President to declare a financial emergency?",
        options: [
        "Article 360",
        "Article 361",
        "Article 362",
        "Article 363",
        ],
        correctAnswer: undefined,
      },
      {
        id: 26,
        question: "A financial emergency must be approved by the Parliament within a period of:",
        options: [
        "1 month",
        "2 months",
        "3 months",
        "4 months",
        ],
        correctAnswer: undefined,
      },
      {
        id: 27,
        question: "Which of the following has never been declared by the President of India?",
        options: [
        "National emergency",
        "State emergency",
        "Financial emergency",
        "Presidential rule",
        ],
        correctAnswer: undefined,
      },
      {
        id: 28,
        question: "In India, the Pocket Veto was first used by which President of India?",
        options: [
        "Rajendra Prasad",
        "Zakir Husain",
        "Fakhruddin Ali Ahmed",
        "Gian Zail Singh",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-9': [
      {
        id: 1,
        question: "By which constitutional amendment were the fundamental duties included in the Constitution of India?",
        options: [
        "42nd Amendment",
        "43rd Amendment",
        "44th Amendment",
        "45th Amendment",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Which of the following amendments to the constitution of India was passed with the primary objective to constitutionally encode the reorganization of Indian states based on language?",
        options: [
        "6th Amendment",
        "7th Amendment",
        "8th Amendment",
        "9th Amendment",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "________ constitutional amendement act gave constitutional status to Panchayati Raj System?",
        options: [
        "73rd Amendment",
        "74th Amendment",
        "75th Amendment",
        "76th Amendment",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Which of the following amendements of the Constitution of India was enacted in 1993 to constitutionally recognize Muncipal governance?",
        options: [
        "74th Amendment",
        "75th Amendment",
        "76th Amendment",
        "77th Amendment",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "The Constitution of India was amended for the first time in which year?",
        options: [
        "1950",
        "1951",
        "1952",
        "1953",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "By which constitutional amendment were the words \"Socialist\", \"Secular\" and \"Integrity\" added to the Preamble of the Constitution of India?",
        options: [
        "42nd Amendment",
        "43rd Amendment",
        "44th Amendment",
        "45th Amendment",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "Which kind of majority is required for a constitutional amendment in forming a new state?",
        options: [
        "Simple",
        "Two-third",
        "Three-fourth",
        "Two-third plus ratification by half of the all states",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "An amendment of the constitution may be initiated by which of the following?",
        options: [
        "By introduction of the President of the India",
        "By introducing of a bill in Rajya Sabha",
        "By Governors of states",
        "By in introduction of a bill in either house of parliament",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "In the year 1978, the __________ amendment eliminated the right to acquire, hold and dispose of property as a fundamental right?",
        options: [
        "44th",
        "45th",
        "46th",
        "47th",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "103rd constitutional amendment is related to ________",
        options: [
        "Economic Reservation",
        "Female Reservation",
        "Right to Education",
        "Right against Exploitation",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "Under which article can the Parliament amend the Constitution of India?",
        options: [
        "Article 368",
        "Article 369",
        "Article 370",
        "Article 371",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "The ________ amendement act of the Constitution of India introduced the Goods and Services Tax (GST) in India?",
        options: [
        "101st",
        "102nd",
        "103rd",
        "104th",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "By ________ constitutional amendment act 2003 the Natioanal Commission for Scheduled Tribes was established?",
        options: [
        "89th",
        "90th",
        "91st",
        "92nd",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Which constitutional amendment act deals with the disqualification of MPs and MLAs on the grounds of defection?",
        options: [
        "50th",
        "51st",
        "52nd",
        "53rd",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "The 61st constitutional amendment act to the constitution of India _________",
        options: [
        "Restricted the size of council of ministers to 15% of the number of legislators",
        "Reduced the age for Voting from 21 to 18 years",
        "Substitued Odia to Oriya",
        "Exempted Arunachal Pradesh from reservation for scheduled castes in Panchayati Raj System",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "Which part has been added to the Indian Constitution by the 73rd constitutional amendement act?",
        options: [
        "Part IX",
        "Part X",
        "Part XI",
        "Part XII",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "Which article of the Constitution of India gives the right of the High Court to issue writ",
        options: [
        "Article 225",
        "Article 226",
        "Article 227",
        "Article 228",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "Which of the following is the oldest High Court of India?",
        options: [
        "Madras High Court",
        "Bombay High Court",
        "Calcutta High Court",
        "Delhi High Court",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "Which among the following is TRUE for the Supreme Court of India?",
        options: [
        "Court of appeal",
        "Federal Court",
        "Guardian of the Constitution",
        "All of the above",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Which of the following is related to Advisory Jurisdiction of the Supreme Court?",
        options: [
        "Election commission seeking opinion from the Supreme Court",
        "President of India seeks opnion on law or facts",
        "States seeking opinion from the Supreme Court",
        "Speaker of the Lok Sabha seeking opinion from the Supreme Court",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "How many types of writs can be issued under Article 32 and Article 226 of the Constitution of India?",
        options: [
        "4",
        "5",
        "6",
        "7",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "Subordinate courts are supervised by the",
        options: [
        "High Court",
        "Supreme Court",
        "Chief Justice of the High Court",
        "Chief Justice of the Supreme Court",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "Which of the following articles is related to the Ancillary powers of the Supreme Court?",
        options: [
        "Article 140",
        "Article 142",
        "Article 143",
        "Article 144",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-10': [
      {
        id: 1,
        question: "Which of the following articles about fundamental duties is related to the respect of the National Anthem?",
        options: [
        "Article 51(A)(a)",
        "Article 51(A)(b)",
        "Article 51(A)(c)",
        "Article 51(A)(d)",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Which of the following Articles of the Constitution of India provides protection to persons arrested or detained under the preventive detention laws?",
        options: [
        "Article 20",
        "Article 21",
        "Article 22",
        "Article 23",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "Which of the following Articles of the Constitution of India guarantees equality of opportunity in matters of public employment?",
        options: [
        "Article 16",
        "Article 17",
        "Article 18",
        "Article 19",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "According to article ________ in the Indian Constitution, the Governor appoints the Chief Minister and other Ministers?",
        options: [
        "Article 164",
        "Article 165",
        "Article 166",
        "Article 167",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "As per article 172(2) ___________ of a state shall NOT be subject to dissolution",
        options: [
        "Legislative Assembly",
        "Legislative Council",
        "Lok Sabha",
        "Rajya Sabha",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Article one of the Indian Constitution, which states that \"India that is Bharah shall be a Union of States\", mentions which of the following features of the Constitution of India?",
        options: [
        "Cooperative Federalism",
        "Independent Judiciary",
        "Parliamentary Sovereignty",
        "Secularism",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "Which articles of the Indian Constitution related to the executive of the Union Government?",
        options: [
        "Articles 52 to 78",
        "Articles 79 to 103",
        "Articles 104 to 123",
        "Articles 124 to 153",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "In which of the following articles of the Indian Constitution is right to property mentioned?",
        options: [
        "Article 300A",
        "Article 300B",
        "Article 301A",
        "Article 301B",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Which of the following articles of the Indian Constitution related to the privileges of Members of Parliament?",
        options: [
        "Article 105",
        "Article 106",
        "Article 107",
        "Article 108",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Which of the following articles of the Indian Constitution says that the elections to the House of the People and to the Legislative Assembly of every state shall be on the basis of adult suffrage?",
        options: [
        "Article 323",
        "Article 324",
        "Article 325",
        "Article 326",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "Which of the following pairs is NOT correctly matched?",
        options: [
        "Article 79 - Supreme Court",
        "Article 114 - Appropriation Bill",
        "Article 280 - Finance Commission",
        "Article 312 - All India Services",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "Which of the following articles of the Indian Constitution deals with the money bills?",
        options: [
        "Article 110",
        "Article 111",
        "Article 112",
        "Article 113",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "Article ________ of the Indian Constitution lays down the process for introducing changes in the Constitution of India?",
        options: [
        "Article 368",
        "Article 369",
        "Article 370",
        "Article 371",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Article 323 of the Indian Constitution deals with the ________",
        options: [
        "Functions of Public Service Commission",
        "Reports of Public Service Commission",
        "Power to expand the functions of the Public Service Commission",
        "Expenses of the Public Service Commission",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "Under which article of the Indian Constitution is the Union Public Service Commission established?",
        options: [
        "Article 315",
        "Article 316",
        "Article 317",
        "Article 318",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "The Indian Administrative Service and the Indian Police Service are deemed to be services created by the Parliament under:",
        options: [
        "Article 310",
        "Article 311",
        "Article 312",
        "Article 313",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "Article ________ of the Indian Constitution gives the Election Commission the power to supervise elections to the Parliament and the Legislatures of the States?",
        options: [
        "Article 322",
        "Article 323",
        "Article 324",
        "Article 325",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "The National Commission for Backward Classes (NCBC) was formed by insertion of Article ________ in the Constitution of India?",
        options: [
        "Article 328A",
        "Article 328B",
        "Article 338A",
        "Article 338B",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "Which of the following articles of the Indian Constitution emphasizes on the fundamental duty \"to maintain and protect the sovereignty, unity and integrity of the nation\"",
        options: [
        "Article 51(A)(a)",
        "Article 51(A)(b)",
        "Article 51(A)(c)",
        "Article 51(A)(d)",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "According to which article of the Indian Constitution, population census is a Union subject?",
        options: [
        "Article 245",
        "Article 246",
        "Article 247",
        "Article 248",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "Abolition of the practice of untouchability is mentioned in which article of the Indian Constitution?",
        options: [
        "Article 17",
        "Article 18",
        "Article 19",
        "Article 20",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "Article 2 of the Indian Constitution, related to:",
        options: [
        "Entry or establishment of new states",
        "Change in the areas of existing states",
        "Change in the names of existing states",
        "Name and territory of the Union",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "Which of the following articles of the Indian Constitution empowers a state Governor to promulgate an ordinance?",
        options: [
        "Article 211",
        "Article 212",
        "Article 213",
        "Article 214",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "Article 27 of the Indian Constitution \"Freedom as to payment of taxes for promotion of any particular religion\" deals with which of the following?",
        options: [
        "The Union Government",
        "The State Government",
        "The Directive Principles of State Policy",
        "The Fundamental Rights",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "The Prime Minister and the other Ministers of the Indian Union are appointed by the President under which article of the Indian Constitution?",
        options: [
        "Article 74",
        "Article 75",
        "Article 76",
        "Article 77",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-11': [
      {
        id: 1,
        question: "The Election Commission of India is the watchdog of free and fair elections in the country under which article of the Indian Constitution?",
        options: [
        "Article 322",
        "Article 323",
        "Article 324",
        "Article 325",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Recently revoked the Article 370 is associated with which state of India?",
        options: [
        "Jammu and Kashmir",
        "Telangana",
        "Andhra Pradesh",
        "Karnataka",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "Which of the following articles of the Indian Constitution deals with the functions of the Public Service Commission?",
        options: [
        "Article 323",
        "Article 324",
        "Article 325",
        "Article 326",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Which of the following words were added in the Preamble of the Constitution of India by the 42nd Constitutional Amendment Act, 1976?",
        options: [
        "Socialist, Secular, Integrity",
        "Socialist, Secular, Socialist",
        "Socialist, Secular, Integrity",
        "Socialist, Secular, Socialist",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "What is the term of office of the Chiarman and Members of the National Commission for Scheduled Tribes?",
        options: [
        "3 years",
        "4 years",
        "5 years",
        "6 years",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Before the framing of the Constitution of India, an \"Objective Resolution\" was proposed by _________ in 1946.",
        options: [
        "Jawaharlal Nehru",
        "Subhas Chandra Bose",
        "Vallabhbhai Patel",
        "Rajendra Prasad",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "The demand for Pakistan was made in ________ at the Lahore session of the All India Muslim League.",
        options: [
        "1940",
        "1941",
        "1942",
        "1943",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "Which Article of the Indian Constitution provides for the post of Comptroller and Auditor General of India?",
        options: [
        "Article 148",
        "Article 149",
        "Article 150",
        "Article 151",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Which of the following Parts of the Constitution of India deals with the provision regarding composition, appointment and removal of members along with the independence, power and function of the UPSC?",
        options: [
        "Part IX",
        "Part X",
        "Part XI",
        "Part XIV",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Which Article discusses people born in the Indian province, people with either of their parents born in India and people whotypically became Indian residents for five or more years instantaneously before the implementation of the Constitution of India?",
        options: [
        "Article 5",
        "Article 6",
        "Article 7",
        "Article 8",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "Which articles authorize the parliament to protect persons in the service of the Unior or State in respect of any action taken by them during martial law?",
        options: [
        "Article 23-25",
        "Article 26-27",
        "Article 28-29",
        "Article 33-34",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "Which article authorizes the State to make special provisions for the welfare of women and children?",
        options: [
        "Article 15(3)",
        "Article 16(3)",
        "Article 17(3)",
        "Article 18(3)",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "From which country the concept of \"Equality before law\" was borrowed?",
        options: [
        "United Kingdom",
        "United States",
        "France",
        "Germany",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "Which of the following correctly describes the relationship between Fundamental Rights and Directive Principles of State Policy?",
        options: [
        "Directive Principles are irrevelant if they clash with rights",
        "Directive principles are superior in conflict",
        "Fundamental rights always prevail",
        "The judiciary aims to harmonize the two",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "Which Constitutional Amendment added \"public order\", \"Friendly relations with foreign states\", and \"incitement to an offence\" as grounds for restricting freedom of speech and expression?",
        options: [
        "First Constitutional Amendment",
        "Second Constitutional Amendment",
        "Third Constitutional Amendment",
        "Fourth Constitutional Amendment",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "Fundamental Rights are mentioned in which Part of the Constitution of India?",
        options: [
        "Part I",
        "Part II",
        "Part III",
        "Part IV",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "Article 25 of the Indian Constitution primarily guarantees which of the following rights?",
        options: [
        "Right to freedom of religion",
        "Right to freedom of speech and expression",
        "Right to freedom of the press",
        "Right to freedom of assembly",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "The constitutional provision that prohibits conviction or punishment for an act that was not an offence at the time it was committed, thereby preventing retrospective criminal liability, is contained in which article of the Indian Constitution?",
        options: [
        "Article 20(1)",
        "Article 20(2)",
        "Article 20(3)",
        "Article 20(4)",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "",
        options: [
        "Article 323",
        "Article 324",
        "Article 325",
        "Article 326",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "The President of India can promulgate ordinances during the Parliament recess under which article of the Indian Constitution?",
        options: [
        "Article 123",
        "Article 124",
        "Article 125",
        "Article 126",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "Which constitutional amendment granted constitutional status to the Panchayati Raj System?",
        options: [
        "73rd Amendment",
        "74th Amendment",
        "75th Amendment",
        "76th Amendment",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "The Waqf (Amendment) Bill, 2025 amended which Act to address issues and challenges in the regulation and management of Waqf properties?",
        options: [
        "The Waqf Act, 1995",
        "The Waqf Act, 1997",
        "The Waqf Act, 1999",
        "The Waqf Act, 2000",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "Which of the following articles of the Indian Constitution deals with the power of the President to make regulations for certain Union Territories?",
        options: [
        "Article 240",
        "Article 241",
        "Article 242",
        "Article 243",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "Who among the following has the power to dissolve the Legislative Assembly of a state?",
        options: [
        "The President",
        "The Chief Minister",
        "The Governor",
        "The Chief Justice of the High Court",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "Which article of the Indian Constitution empowers Parliament to alter state boundaries and form new states?",
        options: [
        "Article 3",
        "Article 4",
        "Article 5",
        "Article 6",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-12': [
      {
        id: 1,
        question: "In which of the following years was the foundation of Pondicherry laid?",
        options: [
        "1673",
        "1674",
        "1675",
        "1676",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Which Act led to the creation of Tripura, Manipur, and Meghalaya as full-fledged states?",
        options: [
        "The States Reorganisation Act, 1956",
        "The States Reorganisation Act, 1957",
        "Assam Reorganisation Act, 1968",
        "North Eastern Areas (Reorganisation) Act, 1971",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "Nagaland state became India's 16th state in which year?",
        options: [
        "1963",
        "1964",
        "1965",
        "1966",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "Which of the following commissions recommended the creation of the Inter-State Council?",
        options: [
        "Balwant Rai Mehta Commission",
        "Mandal Commission",
        "Punchhi Commission",
        "Sarkaria Commission",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Which of the following was one of the last princely states to join the Indian Union?",
        options: [
        "Hyderabad",
        "Jodhpur",
        "Mysore",
        "Travancore",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Which of the following subjects is NOT under the control of the Delhi Legislative Assembly, according to the Constitution of India?",
        options: [
        "Education",
        "Public Order",
        "Health",
        "Transport",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "In which of the following years was the Punjab Reorganisation Act enacted by the Indian Parliament?",
        options: [
        "1966",
        "1967",
        "1968",
        "1969",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "How many days before notice must be given before proposing the removal of the Vice President of India?",
        options: [
        "10 days",
        "12 days",
        "14 days",
        "15 days",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Which of the following nation was the first to introduce the Preamble?",
        options: [
        "United Kingdom",
        "United States",
        "France",
        "India",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "Under which of the following Acts, the Board of Control was established in England to control and supervise the administration of British India?",
        options: [
        "Regulation Act of 1773",
        "Charter Act of 1793",
        "Chartered Act of 1818",
        "Pitt's India Act, 1784",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "Which of the following Constitutional Amendments Acts made the President bound by the advice of the council of ministers headed by the Prime Minister?",
        options: [
        "42nd Amendment Act, 1976",
        "43rd Amendment Act, 1976",
        "44th Amendment Act, 1976",
        "45th Amendment Act, 1976",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "The state shall take steps to separate the judiciary from the executive in the public servicesof the state. This is mentioned under of __________ of the Indian Constitution.",
        options: [
        "PART IV",
        "PART V",
        "PART VI",
        "PART VII",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "The term \"Dhamma\" is the Prakrit word that is associated with which of the following rulers of ancient India?",
        options: [
        "Ashoka",
        "Akbar",
        "Chandragupta Maurya",
        "Samudragupta",
        ],
        correctAnswer: undefined,
      },
      {
        id: 14,
        question: "\"Swaraj Constitution\" is attributed to which of the following Indian leaders?",
        options: [
        "Jawaharlal Nehru",
        "Motilal Nehru",
        "Vallabhbhai Patel",
        "Rajendra Prasad",
        ],
        correctAnswer: undefined,
      },
      {
        id: 15,
        question: "At which of the following sessions of the Congress did it get into the Moderates and Extremists camp?",
        options: [
        "Allahabad",
        "Surat",
        "Calcutta",
        "Madras",
        ],
        correctAnswer: undefined,
      },
      {
        id: 16,
        question: "The Speaker has a special power to certify a bill, declaring it can not be blocked by the Rajya Sabha. What is this bill called?",
        options: [
        "Money Bill",
        "Constitutional Amendment Bill",
        "Financial Bill",
        "Taxation Bill",
        ],
        correctAnswer: undefined,
      },
      {
        id: 17,
        question: "How many types of Bills are passed in the Indian Parliament?",
        options: [
        "1",
        "2",
        "3",
        "4",
        ],
        correctAnswer: undefined,
      },
      {
        id: 18,
        question: "How many members does the Estimate Committee of the Lok Sabha have?",
        options: [
        "20",
        "25",
        "30",
        "35",
        ],
        correctAnswer: undefined,
      },
      {
        id: 19,
        question: "A \"Cut motion\" in Indian Parliament is used to",
        options: [
        "Stop the discussion on a bill",
        "Pass the bill",
        "Amend the bill",
        "Reduce the budget demands",
        ],
        correctAnswer: undefined,
      },
      {
        id: 20,
        question: "Which body is responsible for approving India's Union Budget before it can be implemented?",
        options: [
        "Lok Sabha",
        "Rajya Sabha",
        "Finance Ministry",
        "NITI Aayog",
        ],
        correctAnswer: undefined,
      },
      {
        id: 21,
        question: "Which of the following veto powers is NOT available to the President of India?",
        options: [
        "Absolute veto",
        "Pocket veto",
        "Qualified veto",
        "Suspensive veto",
        ],
        correctAnswer: undefined,
      },
      {
        id: 22,
        question: "Which article of the Indian Constitution allows for a common High Court for two or more states?",
        options: [
        "Article 230",
        "Article 231",
        "Article 232",
        "Article 233",
        ],
        correctAnswer: undefined,
      },
      {
        id: 23,
        question: "With respect to Directive Principles of State Policy under the Constitution of India, the organization of village Panchayat is a/an:",
        options: [
        "Gandhian Principle",
        "Constitutional Right",
        "Socialist Principle",
        "Neo-liberal Principle",
        ],
        correctAnswer: undefined,
      },
      {
        id: 24,
        question: "NABARD was established during which phases of Indias planned economic development?",
        options: [
        "Fourth Five Year Plan",
        "Fifth Five Year Plan",
        "Sixth Five Year Plan",
        "Seventh Five Year Plan",
        ],
        correctAnswer: undefined,
      },
      {
        id: 25,
        question: "In which year was the 52nd Amendment Act of the Indian Constitution, which introduced the Anti Defection Law to prevent elected representatives from switching political parties without resigning?",
        options: [
        "1985",
        "1986",
        "1987",
        "1988",
        ],
        correctAnswer: undefined,
      }
    ],
    'quiz-13': [
      {
        id: 1,
        question: "Which article in the fundamental duty is invoked when you see in a private party that the Indian flag has been used as a covering for the speakers desk",
        options: [
        "Article 51(A)",
        "Article 51(B)",
        "Article 51(C)",
        "Article 51(D)",
        ],
        correctAnswer: undefined,
      },
      {
        id: 2,
        question: "Beign the President of the Indian National Congress, who among the following had called for complete independence from the British Raj in 1929?",
        options: [
        "Jawaharlal Nehru",
        "Subhas Chandra Bose",
        "Vallabhbhai Patel",
        "Rajendra Prasad",
        ],
        correctAnswer: undefined,
      },
      {
        id: 3,
        question: "The UIDAI is under the jurisdiction of which of the following ministries?",
        options: [
        "Home Ministry",
        "Ministry of Education",
        "Finance Ministry",
        "Ministry of Electronics and Information Technology",
        ],
        correctAnswer: undefined,
      },
      {
        id: 4,
        question: "The 24th Constitutional Amendment gave the Parliament which of the following powers?",
        options: [
        "Amend Fundamental Rights",
        "Amend Directive Principles of State Policy",
        "Amend Fundamental Duties",
        "Amend the Preamble",
        ],
        correctAnswer: undefined,
      },
      {
        id: 5,
        question: "Which article provides that all minorites have the right to establish and administer educational institutions of their choice?",
        options: [
        "Article 29",
        "Article 30",
        "Article 31",
        "Article 32",
        ],
        correctAnswer: undefined,
      },
      {
        id: 6,
        question: "Members of the Rajya Sabha are elected for a term of how many years?",
        options: [
        "3 years",
        "4 years",
        "5 years",
        "6 years",
        ],
        correctAnswer: undefined,
      },
      {
        id: 7,
        question: "Which article of the Indian Constitution was given practical effect through the 73rd Constitutional Amendment Act, 1992, leading to the establishment of the Panchayati Raj System?",
        options: [
        "Article 38",
        "Article 39",
        "Article 40",
        "Article 41",
        ],
        correctAnswer: undefined,
      },
      {
        id: 8,
        question: "The 9th amendment act 1960 made adjustments to the Indian territory due to an agreement with which country?",
        options: [
        "China",
        "Pakistan",
        "Bangladesh",
        "Bhutan",
        ],
        correctAnswer: undefined,
      },
      {
        id: 9,
        question: "Which among the following Constitutional Amendments Act is also known as Anti Defection Law?",
        options: [
        "44th",
        "52nd",
        "62nd",
        "72nd",
        ],
        correctAnswer: undefined,
      },
      {
        id: 10,
        question: "On which date did the Constituent Assembly of India adopt the Indian National Flag?",
        options: [
        "15 August 1947",
        "22 July 1947",
        "26 January 1949",
        "26 January 1950",
        ],
        correctAnswer: undefined,
      },
      {
        id: 11,
        question: "Following the Indian Constitution and respecting the National Anthem and Flag is the ________ fundamental duty included in our Constitution?",
        options: [
        "First",
        "Second",
        "Third",
        "Fourth",
        ],
        correctAnswer: undefined,
      },
      {
        id: 12,
        question: "In which of the following Indian National Congress (INC) sessions was the National Anthem sung for the first time?",
        options: [
        "Allahabad",
        "Surat",
        "Calcutta",
        "Madras",
        ],
        correctAnswer: undefined,
      },
      {
        id: 13,
        question: "On which date did the Government of India adopt the Lion Capital of Sarnath, with bull, wheel, and horse, as the national emblem?",
        options: [
        "15 August 1947",
        "22 July 1947",
        "26 January 1949",
        "26 January 1950",
        ],
        correctAnswer: undefined,
      }
    ],
  },
}
