import React from 'react'

const circulars = [
  "SCOUT ACTIVITIES ON THE INDIAN RAILWAYS",
  "HOLIDAY HOMES",
  "RAILWAY INSTITUES/CLUBS",
  "STAFF BENEFIT FUND",
  "SERVICE BOOK/RECORDS",
  "JOINING TIME",
  "RECRUITMENT AGASINT CULTURAL/SCOUTS AND GUIDES QUOTA",
  "APPRENTICE ACT, 1961-TRAINING OF APPRENTICES IN RAILWAY",
  "IRREGULAR RETENTION IN SERVICE BEYOND THE AGE OF SUPERANNUATION",
  "SPECIAL CASUAL LEAVE",
  "GRANT OF HONORARIUM",
  "PROCEDURE FOR RECORDING DATE OF BIRTH ON ENTERING RAILWAY SERVICE",
  "RESERVATION OF RECRUITMENT FOR PHYSICALLY HANDICAPPED",
  "RECRUITMENT OF SPORTS PERSONS UNDER SPORTS QUOTA",
  "CASUAL LEAVE",
  "APPOINTMENT ON COMPASSIONATE GROUNDS",
  "ASSISTANCE TO RAILWAY EMPLOYEES FOR EDUCATION OF THEIR CHILDREN",
  "[PART I] PROVISION OF SCHOOLS IN RAILWAY COLONIES FOR THE CHILDREN OF RAILWAY EMPLOYEES",
  "CONFIRMATION OF NON-GAZATTED RAILWAY SERVANTS",
  "SUBSTITUTES",
  "RESIGNATION FROM RAILWAY SERVICE",
  "ABSORBTION AND UTILIZATION OF SURPLUS STAFF ON THE RAILWAYS",
  "FACTORIES ACT 1948",
  "TRANSFER OF NON-GAZATTED RAILWAY SERVANTS",
  "ABSORPTION OF MEDICALLY DE-CATEGORIESED NON GAZATTED STAFF",
  "CONTRACT LABOUR UNDER CONTRACT LABOUR [REGULATION & ABOLITION] ACT, 1970",
  "LEGAL AND FINANCIAL ASSISTANCE TO RAILWAY SERVANTS",
  "CONFIDENTIAL REPORTS ON NON-GAZATTED RAILWAY SERVANTS",
  "TRAINING OF NON-GAZATTED DIRECT RECRUITS",
  "FORWARDING OF APPLICATION FOR POSTS OUTSIDE RAILWAYS",
  "PROMOTION OF NON GAZATTED STAFF TO SELECTION POSTS",
  "RECRUITMENT RULES AND RECRUITMENT OF NON GAZATTED STAFF",
  "EXTENSION IN SERVICE/RE-EMPLOYMENT OF RAILWAY SERVANTS AFTER SUPER ANNUATION",
  "SENIORITY OF NON-GAZATTED STAFF",
  "RETIREMENT",
  "ARREARS CLAIMS AND INVESTIGATION TEHREOF",
  "PROMOTION OF NON-GAZATTED STAFF/TO NON-SELECTION POSTS",
  "CANTEENS ON INDIAN RAILWAYS",
  "ADVANCES AND THEIR RECOVERY",
  "DEPUTATION/SECONDMENT OF NON-GAZATTED RAILWAY EMPLOYEES OUTSIDE THE RAILWAYS",
  "LEAVE RESERVE- PROVISION OF IN NON-GAZATTED CATEGORIES",
  "CULTURAL ACTIVITIES ON RAILWAYS",
  "TRADE TEST FOR PROMOTION IN ARTISAN CATEGOREIS",
  "IN-SERVICE TRAINING TO NON-GAZATTED RAILWAY STAFF",
  "INDIGENOUS SYSTEM OF MEDICINE-HOMEOPATHIC/AYURVEDIC DISPENSARIES",
  "DRAWAL OF INCREMENTS OF NON-GAZATTED STAFF CONSOLIDATION OF INSTRUCTIONS",
  "HOLIDAYS",
  "CASUAL LABOUR",
  "ALLOTMENT OF QUARTERS AND RETENTION THEREOF ON TRANSFER ETC.",
  "HOUSE BUILDING ADVANCE",
  "RESERVATION FOR SCHEDULED CASTES/SCHEDULED TRIBES IN RAILWAY SERVICES",
  "RE-EMPLOYMENT INCLUDING EMPLOYMENT OF CONSULTANTS",
  "PENSION SCHEME AND RETIREMENT BENIFITS ON ABSORBTION IN PUBLIC SECTOR",
  "QUALIFYING SERVICE FOR PENSIONARY PURPOSES",
  "EMOLUMENTS/AVERAGE EMOLUMENT FOR PENSIONARY BENIFITS",
  "FIXATION OF PAY- CONSOLIDATION OF INSTRUCTIONS",
  "DEPUTATION",
  "INCREMENTS-CONSOLIDATION",
  "PAYMENT OF WAGES ACT",
  "PENSION AND RETIREMENT/DEATH GRATUITY",
  "COMMUTATION OF PENSION",
  "STATE RAILWAY PROVIDENT FUND RULES FOR RAILWAY SERVANTS",
  "CONDUCT OF PENSION ADALATS ON RAILWAYS",
  "SUSPENSION OF RAILWAY EMPLOYEES- MASTER CIRCULAR",
  "FACILITIES GRANTED TO ALL INDIA SC/ST EMPLOYEES ASSOCIATION",
  "PENALTIES AND DISCIPLINARY AUTHORITES",
  "IMPORTANT POINTS TO BE KEPT IN VIEW WHILE HANDLING DISCIPLINARY CASE",
  "INSTRUCTIONS GOVERNING PROMOTION FROM GROUP 'C' TO GROUP 'B'.",
]

const MasterCirculars = () => {
  return (
    <div className="min-h-screen bg-linear-to-br from-slate-900 via-slate-800 to-cyan-900/20 py-10 px-2 sm:px-3 lg:px-8">
      <div className="max-w-7xl mx-auto space-y-6">
        {/* Title Section */}
        <section className="bg-slate-800/80 rounded-2xl shadow-xl shadow-cyan-500/10 border border-slate-700/80 overflow-hidden">
          <div className="bg-linear-to-r from-cyan-600 via-cyan-600 to-teal-600 text-white px-6 py-5 relative overflow-hidden">
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_50%,rgba(255,255,255,0.08),transparent)]" />
            <h1 className="text-xl sm:text-2xl font-bold tracking-tight relative z-10 text-center">LIST OF MASTER CIRCULARS</h1>
          </div>

          <div className="p-6 sm:p-8">
            <div className="grid gap-3 sm:grid-cols-1 lg:grid-cols-2">
              {circulars.map((title, i) => (
                <div
                  key={i}
                  className="group flex gap-4 rounded-lg bg-slate-700/30 px-3 py-3 transition-colors hover:bg-slate-700/50"
                >
                  <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-cyan-500/20 text-cyan-400 text-sm font-bold">
                    {i + 1}
                  </span>
                  <div className="min-w-0 flex-1">
                    <span className="text-cyan-400/80 text-xs font-medium">MASTER CIRCULAR</span>
                    <p className="text-slate-200 text-sm leading-relaxed mt-0.5">{title}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
      </div>
    </div>
  )
}

export default MasterCirculars
