export const aomFinanceEstablishmentRulesTest02 = {
    tests: {
        'aom-finance-establishment-rules-test-02': [
            {
                question: 'Which section of the Right To Information Act, 2005 deals with the exemption from disclosure of information?',
                options: ['Section 8', 'Section 9', 'Section 10', 'Section 11'],
                correct: 0,
                explanation: 'Section 8 of the Right To Information Act, 2005 deals with the exemption from disclosure of information.',
            },
            {
                question: 'How many days of LHAP can be accumulated to a Railway Employee in his whole service?',
                options: ['300 days', '400 days', '450 days', 'Unlimited'],
                correct: 3,
                explanation: 'Unlimited days of LHAP can be accumulated to a Railway Employee in his whole service.',
            },
            {
                question: 'Reply to Draft Para must be sent under the personal signature of which of the following?',
                options: ['DRM', 'GM', 'PCPO', 'PFA'],
                correct: 1,
                explanation: 'GM is the authority who can reply to Draft Para must be sent under the personal signature of.',
            },
            {
                question: 'What is the parameter that indicates the financial performance of a division?',
                options: ['Revenue Expenditure', 'Plan head expenditure', 'Capital Expenditure', 'Performance Efficency Index'],
                correct: 3,
                explanation: 'Performance Efficency Index is the parameter that indicates the financial performance of a division.',
            },
            {
                question: 'The higest Pay Level in Pay Matrix(PLPM) in the Railway level is __________',
                options: ['PLPM-16', 'PLPM-17', 'PLPM-18', 'PLPM-19'],
                correct: 1,
                explanation: 'PLPM-17 is the higest Pay Level in Pay Matrix(PLPM) in the Railway level.',
            },
            {
                question: 'Within how much period after delivery, Paternity Leave can be granted to a Railway Employee?',
                options: ['3 months', '6 months', '9 months', '12 months'],
                correct: 1,
                explanation: '6 months is the period after delivery, Paternity Leave can be granted to a Railway Employee.',
            },
            {
                question: 'After availing 365 days of Child Care Leave(CCL), a female railway servant or a single male railway servant shall be paid @ ________ of salary for the next 365 days of Child Care Leave(CCL)',
                options: ['50%', '60%', '70%', '80%'],
                correct: 3,
                explanation: '80% is the salary that a female railway servant or a single male railway servant shall be paid @ 80% of salary for the next 365 days of Child Care Leave(CCL).',
            },
            {
                question: 'During Study leave availed in India, an employee is eligible for __________',
                options: ['Pay and DA', 'Pay and Da, Study allowance', 'Pay, DA, HRA', 'Pay, DA, HRA, Study allowance'],
                correct: 2,
                explanation: 'Pay, DA, HRA is the eligible for during Study leave availed in India, an employee.',
            },
            {
                question: 'Traffic suspense consists of _______',
                options: ['Station outstanding', 'Accounts office outstanding', 'Cash in transit and balance under demands recoverable', 'All of the above'],
                correct: 3,
                explanation: 'All of the above is the traffic suspense consists of.',
            },
            {
                question: 'Lower Operating Ratio indicates _______',
                options: ['Efficient working', 'Poor working', 'No loss no profit', 'None of the above'],
                correct: 0,
                explanation: 'Efficient working is the Lower Operating Ratio indicates.',
            },
            {
                question: 'The following is not accounted under other coaching earnings?',
                options: ['Luggage earnings', 'Parcel earnings', 'TTE earnings', 'Passenger Fares'],
                correct: 3,
                explanation: 'Passenger Fares is the not accounted under other coaching earnings.',
            },
            {
                question: 'Traffic Book Part - A deals with _______',
                options: ['Appointment', 'Accounts office balance sheet', 'Originating station earnings', 'All of the above'],
                correct: 2,
                explanation: 'Originating station earnings is the Traffic Book Part - A deals with.',
            },
            {
                question: 'There is a provision to give the document related to disciplinary proceedings to the employee in which language?',
                options: ['Hindi', 'English', 'Both', 'Hindi or English in the language the employee prefers'],
                correct: 3,
                explanation: 'Hindi or English in the language the employee prefers is the language in which there is a provision to give the document related to disciplinary proceedings to the employee.',
            },
            {
                question: 'Which of the following options is the rate of ordinary Family Pension?',
                options: ['25% of Basic pay (Subject to minimum of 9,000/-)', '30% of Basic pay (Subject to minimum of 9,000/-)', '35% of Basic pay (Subject to minimum of 9,000/-)', '40% of Basic pay (Subject to minimum of 9,000/-)'],
                correct: 1,
                explanation: '30% of Basic pay (Subject to minimum of 9,000/-) is the rate of ordinary Family Pension.',
            },
            {
                question: 'What is the time limit for appeal under Disciplinary and Appeal proceedings?',
                options: ['15 days', '30 days', '45 days', '60 days'],
                correct: 2,
                explanation: '45 days is the time limit for appeal under Disciplinary and Appeal proceedings.',
            },
            {
                question: 'The check exercised by railway accounts office on financial transactions is called _______',
                options: ['Internal check', 'Internal audit', 'Post check', 'Pre check'],
                correct: 0,
                explanation: 'Internal check is the check exercised by railway accounts office on financial transactions.',
            },
            {
                question: 'Children Education Allowance shall be admissible for receipt only for children up to the age of _______ years',
                options: ['18', '20', '21', '24'],
                correct: 1,
                explanation: '20 years is the age of the children for which Children Education Allowance shall be admissible for receipt.',
            },
            {
                question: 'Who has the powers to relax recruitment criteria?',
                options: ['GM', 'DRM', 'PCPO', 'Railway Board'],
                correct: 3,
                explanation: 'Railway Board is the powers to relax recruitment criteria.',
            },
            {
                question: 'Which form is issued to nominate an Inquiry Officer in DAR proceedings?',
                options: ['SF - 5', 'SF - 6', 'SF - 7', 'SF - 8'],
                correct: 2,
                explanation: 'SF - 7 is the form issued to nominate an Inquiry Officer in DAR proceedings.',
            },
            {
                question: 'Minimum notice period of quotations is _______ days',
                options: ['5', '7', '10', '15'],
                correct: 1,
                explanation: '7 days is the minimum notice period of quotations.',
            },
            {
                question: 'Including dependents, how many family members can be included in the privilege pass?',
                options: ['4', '5', '6', 'No limit'],
                correct: 1,
                explanation: '5 is the number of family members that can be included in the privilege pass.',
            },
            {
                question: 'The amount of Leave on Average Pay (LAP) that can be availed in one spell is _______',
                options: ['120 days', '180 days', '240 days', '360 days'],
                correct: 1,
                explanation: '180 days is the amount of Leave on Average Pay (LAP) that can be availed in one spell.',
            },
            {
                question: 'Re-appropriation of funds from one source to another source is within the powers of _______',
                options: ['GM', 'DRM', 'PCPO', 'Railway Board'],
                correct: 3,
                explanation: 'Railway Board is the powers of re-appropriation of funds from one source to another source.',
            },
        ],
    },
};