export const aomFinanceEstablishmentRulesTest01 = {
    tests: {
        'aom-finance-establishment-rules-test-01': [
            {
                question: 'The report of Comptroller and Auditor General of India is presented to the Parliament and it is taken up for consideration by the _________ of the Parliament',
                options: ['Business Advisory Committee', 'Committee of Public undertakings', 'Estimates Committee', 'Public Accounts Committee'],
                correct: 3,
                explanation: 'The report of Comptroller and Auditor General of India is presented to the Parliament and it is taken up for consideration by the Public Accounts Committee of the Parliament.',
            },
            {
                question: 'A person seeking any information from any Railway office, under Right to Information Act, 2005, has to make request to the _______________',
                options: ['Central Public Information Officer of that office', 'Head of that office', 'Officer who is custodian of that information', 'Head of Dak Receipt section'],
                correct: 0,
                explanation: 'A person seeking any information from any Railway office, under Right to Information Act, 2005, has to make request to the Central Public Information Officer of that office.',
            },
            {
                question: 'The unavailed period of joining time admissible to a Railway servant shall be credited to his/her which leave account?',
                options: ['LAP', 'LHAP', 'Casual Leave', 'Restricted Holiday'],
                correct: 0,
                explanation: 'The unavailed period of joining time admissible to a Railway servant shall be credited to his/her LAP account.',
            },
            {
                question: 'Which is correct plan head for RSP proposals?',
                options: ['PH 21', 'PH 31', 'PH 41', 'PH 51'],
                correct: 0,
                explanation: 'The correct plan head for RSP proposals is PH 21.',
            },
            {
                question: 'Operating Expenses - Fuel shall be charged to __________',
                options: ['Demand No. 10', 'Demand No. 11', 'Demand No. 12', 'Demand No. 13'],
                correct: 0,
                explanation: 'Operating Expenses - Fuel shall be charged to Demand No. 10 as per the Finance Establishment Rules.',
            },
            {
                question: 'The total value of Railway Assets is reflected in which Accounts statement?',
                options: ['Block accounts', 'Current accounts', 'Final accounts', 'Capital and Revenue Accounts'],
                correct: 0,
                explanation: 'The total value of Railway Assets is reflected in the Block accounts.',
            },
            {
                question: 'Administrative approval of Competent authority for  incurring expenditure is accorded at this stage?',
                options: ['Abstract Estimate', 'Completion Estimate', 'Detailed Estimate', 'Revised Estimate'],
                correct: 0,
                explanation: 'Administrative approval of Competent authority for incurring expenditure is accorded at this stage of Abstract Estimate.',
            },
            {
                question: 'In Indian Railways, Pink Book is issued by which of the following?',
                options: ['Division', 'Zonal Railway', 'Ministry of Finance', 'Railway Board'],
                correct: 3,
                explanation: 'Pink Book is issued by the Railway Board.',
            },
            {
                question: 'What is the periodicity of "Participation of Railway Employees in Management (PREM)" meeting at Zonal level?',
                options: ['Once in a month', 'Once in 3 months', 'Once in 6 months', 'Once in a year'],
                correct: 1,
                explanation: 'The periodicity of "Participation of Railway Employees in Management (PREM)" meeting at Zonal level is once in 3 months.',
            },
            {
                question: 'Which of the following tier is mandatory under National Pension Scheme (NPS) for Railway Employees?',
                options: ['Tier 1', 'Tier 2', 'Both', 'Not compulsory'],
                correct: 0,
                explanation: 'Tier 1 is mandatory under National Pension Scheme (NPS) for Railway Employees.',
            },
            {
                question: 'The study of proposals for new marshalling yards, major yards, Goods terminals, Transit yards, with an objective of removing bottlenecks in movement of increased traffic is known as __________',
                options: ['Machine and Plant works', 'Line capacity works', 'Development works', 'Maintenance works'],
                correct: 1,
                explanation: 'The study of proposals for new marshalling yards, major yards, Goods terminals, Transit yards, with an objective of removing bottlenecks in movement of increased traffic is known as Line capacity works.',
            },
            {
                question: 'What amount is given as Subsistence Allowance?',
                options: ['25% of last pay drawn', '50% of last pay drawn', '75% of last pay drawn', '100% of last pay drawn'],
                correct: 1,
                explanation: '50% of last pay drawn is given as Subsistence Allowance.',
            },
            {
                question: 'Who is the Chairman of Headquarter level committee of Staff Benefit Fund (SBF)?',
                options: ['AGM', 'GM', 'PCPO', 'PFA'],
                correct: 2,
                explanation: 'PCPO is the Chairman of Headquarter level committee of Staff Benefit Fund (SBF).',
            },
            {
                question: 'Commuted pension of a Railway servant is resotred after a period of __________ years',
                options: ['10', '12', '15', '20'],
                correct: 2,
                explanation: 'Commuted pension of a Railway servant is restored after a period of 15 years.',
            },
            {
                question: 'Which standard form is used for deedmed suspension of a Railway servant?',
                options: ['SF - 1', 'SF - 2', 'SF - 3', 'SF - 4'],
                correct: 1,
                explanation: 'SF - 2 is used for deedmed suspension of a Railway servant.',
            },
            {
                question: 'Under HOER(Hours of Employment Regulation) Rules, which category of employees will NOT have roster hours?',
                options: ['Continuous', 'Essentially Intermittent', 'Excluded', 'Intensive'],
                correct: 2,
                explanation: 'Excluded category of employees will NOT have roster hours.',
            },
            {
                question: 'Name the tribunal specially constituted to adjudicate disputes and complaints with respect to recruitment and conditions of service of persons appointed by central government offices?',
                options: ['Railway Claims Tribunal', 'Railway Rates Tribunal', 'Industrial Disputes Tribunal', 'Central Administrative Tribunal'],
                correct: 3,
                explanation: 'Central Administrative Tribunal is the tribunal specially constituted to adjudicate disputes and complaints with respect to recruitment and conditions of service of persons appointed by central government offices.',
            },
            {
                question: 'How much Transport Allowance is paid to a railway employee with disability?',
                options: ['The normal rate of TA', 'Double the normal rate of TA', 'Triple the normal rate of TA', 'None of the above'],
                correct: 1,
                explanation: 'Double the normal rate of TA is paid to a railway employee with disability.',
            },
            {
                question: 'To what extent commutation of pension is allowed into a lumpsum payment as a retirement benefit to a Railway servant?',
                options: ['25%', '40%', '50%', '60%'],
                correct: 1,
                explanation: '40% commutation of pension is allowed into a lumpsum payment as a retirement benefit to a Railway servant.',
            },
            {
                question: 'Railway servant is required to report to government any movable property transaction, if value of this transaction exceeds "X" amount. What is the value of "X" amount?',
                options: ['One month basic pay', 'Two months basic pay', 'Three months basic pay', 'Four months basic pay'],
                correct: 1,
                explanation: 'Two months basic pay is the value of "X" amount.',
            },
            {
                question: 'Re-appropriation of funds from one itemised work to another itemised work of a plan head is within power of __________',
                options: ['DRM', 'GM', 'PHOD', 'Railway Board'],
                correct: 1,
                explanation: 'GM is the power of re-appropriation of funds from one itemised work to another itemised work of a plan head.',
            },
            {
                question: 'The Plan Head under which works for Traffic Facilities are included?',
                options: ['PH 16', 'PH 17', 'PH 18', 'PH 19'],
                correct: 0,
                explanation: 'PH 16 is the Plan Head under which works for Traffic Facilities are included.',
            },
            {
                question: 'From which financial year, was the Railway Budget included with the General Budget of the Government of India?',
                options: ['2015-16', '2016-17', '2017-18', '2018-19'],
                correct: 2,
                explanation: '2017-18 is the financial year from which the Railway Budget was included with the General Budget of the Government of India.',
            },
            {
                question: 'Who is the custodian of listed documents in a departmental enquiry?',
                options: ['Defence Assistant', 'Inquiry Officer', 'Presenting Officer', 'None of the above'],
                correct: 2,
                explanation: 'Presenting Officer is the custodian of listed documents in a departmental enquiry.',
            },
            {
                question: 'What is the minimum period of Child Care Leave(CCL) allowed to be considered for sanction to a  Female Railway servant?',
                options: ['5 days', '10 days', '15 days', '20 days'],
                correct: 0,
                explanation: '5 days is the minimum period of Child Care Leave(CCL) allowed to be considered for sanction to a Female Railway servant.',
            },
            {
                question: 'Which authority is empowered to order for cut in pension of retired railway servant under DAR proceedings?',
                options: ['Chairman of the Board', 'GM', 'PCPO', 'President of India'],
                correct: 3,
                explanation: 'President of India is the authority empowered to order for cut in pension of retired railway servant under DAR proceedings.',
            },
            {
                question: 'How much employee contribution is made to the National Pension Scheme (NPS) by the Railway servant?',
                options: ['8% of basic pay + DA', '10% of basic pay + DA', '14% of basic pay + DA', '16% of basic pay + DA'],
                correct: 1,
                explanation: '10% of basic pay + DA is the employee contribution made to the National Pension Scheme (NPS) by the Railway servant.',
            },
            {
                question: 'Under which rule of Raliway Service Conduct Rules is movable and immovable property mentioned?',
                options: ['Rule 16', 'Rule 17', 'Rule 18', 'Rule 19'],
                correct: 2,
                explanation: 'Rule 18 is the rule under which movable and immovable property is mentioned.',
            },
        ],
    },
}