export const aomFinanceEstablishmentRulesTest03 = {
    test: {
        'aom-finance-establishment-rules-test-03': [
            {
                question: 'Who is the President and Secretary for "Participation of Railway Employees in Management (PREM)" meetings from Railway side at Division level?',
                options: ['DRM, Sr. DPO', 'DRM, Sr DSO', 'ADRM, Sr. DPO', 'ADRM, Sr DSO'],
                correct: 0,
                explanation: 'DRM, Sr. DPO is the President and Secretary for "Participation of Railway Employees in Management (PREM)" meetings from Railway side at Division level.',
            },
            {
                question: 'If a Railway servant is transferred at a distance fo more than 1000 kms but less than 2000 kms, then ______ days will be the maximum permissible joining period?',
                options: ['10 days', '12 days', '15 days', '20 days'],
                correct: 1,
                explanation: '12 days is the maximum permissible joining period for a Railway servant transferred at a distance of more than 1000 kms but less than 2000 kms.',
            },
            {
                question: 'If a Railway servant is transferred at a distance of more than 2000 kms, then ______ days will be the maximum permissible joining period?',
                options: ['10 days', '15 days', '20 days', '25 days'],
                correct: 0,
                explanation: '25 days is the maximum permissible joining period for a Railway servant transferred at a distance of more than 2000 kms.',
            },
            {
                question: 'When was the Railway Service Conduct Rules formed?',
                options: ['1962', '1963', '1965', '1966'],
                correct: 3,
                explanation: '1966 is the year when the Railway Service Conduct Rules were formed.',
            },
            {
                question: 'Which of the is NOT a function of Accounts Department?',
                options: ['Accounts keeping', 'Budget preparation', 'Financial advice', 'Internal check'],
                correct: 1,
                explanation: 'Budget preparation is not a function of Accounts Department.',
            },
            {
                question: 'Final Modification Estimates (FME) is usually prepared in which month?',
                options: ['August - September', 'February - March', 'December - January', 'April - May'],
                correct: 1,
                explanation: 'February - March is the month when the Final Modification Estimates (FME) is usually prepared.',
            },
            {
                question: 'Proposal under which of the following funds should mandatorily indicates RoR (Rate of Return)?',
                options: ['Capital', 'DF', 'DRF', 'RRSK'],
                correct: 0,
                explanation: 'Capital is the fund that should mandatorily indicates RoR (Rate of Return).',
            },
            {
                question: 'Which of the following CANNOT be classified as Revenue Expenditure?',
                options: ['Expenditure on salary', 'Expenditure on purchase of stock item', 'Expenditure on purchase of non-stock item', 'Expenditure on setting up new wheel lathe'],
                correct: 3,
                explanation: 'Expenditure on setting up new wheel lathe cannot be classified as Revenue Expenditure.',
            },
            {
                question: 'To which head the material issued to workshop are generally charged to?',
                options: ['MAC', 'Purchase suspense', 'SINT', 'WMS'],
                correct: 3,
                explanation: 'WMS is the head to which the material issued to workshop are generally charged to.',
            },
            {
                question: 'Proposal for a machinery against replacement under Works Programme is proposed in which of the following funds?',
                options: ['Capital', 'DF', 'DRF', 'RRSK'],
                correct: 2,
                explanation: 'DRF is the fund in which the proposal for a machinery against replacement under Works Programme is proposed.',
            },
            {
                question: 'The Development Funds are divided into how many heads?',
                options: ['2', '3', '4', '5'],
                correct: 2,
                explanation: '4 is the number of heads into which the Development Funds are divided.',
            },
            {
                question: 'M&P Programme is drawn by each Railway under _______',
                options: ['PH 21', 'PH 31', 'PH 41', 'PH 51'],
                correct: 2,
                explanation: 'PH 41 is the programme under which the M&P Programme is drawn by each Railway.',
            },
            {
                question: 'Payments to contractors for the works done under maintenance are charged to _______',
                options: ['PU 27', 'PU 32', 'PU 47', 'PU 52'],
                correct: 1,
                explanation: 'PU 32 is the programme under which the Payments to contractors for the works done under maintenance are charged to.',
            },
            {
                question: 'Demand Number 4 of Ordinary Working Expenses pertains to _______',
                options: ['Repair and Maintenance of Motive power', 'Staff welfare and amenities', 'Operating expenses - Traffic', 'Repair and Maintenance of P.Way and works'],
                correct: 3,
                explanation: 'Repair and Maintenance of P.Way and works is the Demand Number 4 of Ordinary Working Expenses pertains to.',
            },
            {
                question: 'Who is responsible for custody of the Bank Guarantee submitted by the contractors to Railway?',
                options: ['Accounts officer', 'Audit officer', 'Cashier', 'Executive officer'],
                correct: 0,
                explanation: 'Accounts officer is responsible for custody of the Bank Guarantee submitted by the contractors to Railway.',
            },
            {
                question: 'What works are carried under Plan Head 51?',
                options: ['Electrification', 'Gauge conversion', 'Passenger amenities', 'Staff quarters'],
                correct: 3,
                explanation: 'Staff quarters is the work that is carried under Plan Head 51.',
            },
            {
                question: 'Which of the following works will NOT be charged to Depreciation Reserve Fund?',
                options: ['Construction of new line', 'Track renewal', 'Replacement of existing signalling system', 'Replacement of overage Rolling Stock'],
                correct: 0,
                explanation: 'Construction of new line is the work that will NOT be charged to Depreciation Reserve Fund.',
            },
            {
                question: 'In reference to Discipline & Appeal Rules 1968, inquiry is NOT mandatory under Rule _______',
                options: ['Rule 10', 'Rule 11(i)', 'Rule 12(ii)', 'Rule 14(ii)'],
                correct: 3,
                explanation: 'Rule 14(ii) is the rule under which inquiry is NOT mandatory in the Discipline & Appeal Rules 1968.',
            },
            {
                question: 'Which of the following is the type of metal pass?',
                options: ['Silver, Gold, Copper', 'Aluminium, Silver, Gold', 'Bronze, Silver, Gold', 'Gold, Platinum, Silver'],
                correct: 2,
                explanation: 'Bronze, Silver, Gold is the type of metal pass.',
            },
            {
                question: 'Name the forum in Indian Railways for resolving the disputes and differences arising between the administration and the employees?',
                options: ['PNM', 'PREM', 'JCM', 'CAT'],
                correct: 0,
                explanation: 'PNM is the forum in Indian Railways for resolving the disputes and differences arising between the administration and the employees.',
            },
            {
                question: 'The family of Railway servant, who dies during service, may be allowed to retain Railway accommodation for ______ months on normal rent.',
                options: ['6', '12', '18', '24'],
                correct: 3,
                explanation: '24 is the number of months on normal rent that the family of Railway servant, who dies during service, may be allowed to retain Railway accommodation for.',
            },
            {
                question: 'What is upper limit of Child Care Leave(CCL) for Railway servants?',
                options: ['365 days', '450 days', '540 days', '730 days'],
                correct: 3,
                explanation: '730 days is the upper limit of Child Care Leave(CCL) for Railway servants.',
            },
            {
                question: 'What is upper limit of Child Care Leave(CCL) for Railway servants?',
                options: ['365 days', '450 days', '540 days', '730 days'],
                correct: 3,
                explanation: '730 days is the upper limit of Child Care Leave(CCL) for Railway servants.',
            },
            {
                question: 'Under the old pension scheme, the commuted portion of pension will be restored to full pension after ______ years.',
                options: ['5 years from the date of commutation', '10 years from the date of commutation', '15 years from the date of commutation', '20 years from the date of commutation'],
                correct: 2,
                explanation: '15 years from the date of commutation is the number of years after which the commuted portion of pension will be restored to full pension under the old pension scheme.',
            },
            {
                question: 'Maximum number of financial upgradation which can be granted to a Railway servant under MACP is ______',
                options: ['3', '4', '5', '6'],
                correct: 0,
                explanation: '3 is the maximum number of financial upgradation which can be granted to a Railway servant under MACP.',
            },
            {
                question: 'Which one of the following is NOT a penalty under Railway Servants Discipline & Appeal Rules 1968?',
                options: ['Suspension', 'Censure', 'Privilege pass cut', 'Reduction to lower grade'],
                correct: 0,
                explanation: 'Suspension is NOT a penalty under Railway Servants Discipline & Appeal Rules 1968.',
            },
        ],
    },
};