'use client'
import React from 'react'
import { 
  Train,
  AlertTriangle,
  Eye,
  CheckCircle,
  Wrench,
  Users,
  Lightbulb,
  UserCheck,
  Car,
  ArrowRight,
  AlertOctagon,
  Shield,
  RadioTower,
  MessageSquare,
  Bell,
  Clock,
  Gauge,
  HardHat,
  Settings,
  Zap,
  AlertCircle,
  MapPin,
  Timer,
} from 'lucide-react'

const OMPage87 = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-900 via-indigo-900 to-purple-900 relative overflow-hidden">
      {/* Animated Background Elements */}
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-gradient-to-br from-blue-400/20 to-indigo-400/20 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-gradient-to-tr from-purple-400/20 to-blue-400/20 rounded-full blur-3xl animate-pulse delay-1000"></div>
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-gradient-to-r from-indigo-400/10 to-blue-400/10 rounded-full blur-3xl animate-pulse delay-500"></div>
      </div>

      <div className="relative z-10 py-6 lg:px-4 px-2">
        <div className="max-w-7xl mx-auto">
          {/* Header Section */}
          <div className="text-center mb-10">
            <div className="inline-block p-2 bg-gradient-to-r from-blue-500/20 to-indigo-500/20 rounded-full mb-6 backdrop-blur-sm">
              <div className="bg-gradient-to-r from-blue-500 to-indigo-600 p-3 rounded-full">
                <AlertTriangle className="w-8 h-8 text-white" />
              </div>
            </div>
            <h1 className="lg:text-6xl text-2xl font-bold bg-gradient-to-r from-white via-blue-100 to-indigo-100 bg-clip-text text-transparent mb-6 animate-fade-in">
              FLAT TYRE & SAFETY PROTOCOLS
            </h1>
            <h2 className="lg:text-4xl text-2xl font-bold text-purple-300 mb-4">Comprehensive Safety Procedures & Emergency Response</h2>
            <div className="w-24 h-1 bg-gradient-to-r from-blue-500 to-indigo-600 mx-auto mb-6 rounded-full"></div>
            <p className="lg:text-xl text-base text-gray-200 max-w-4xl mx-auto leading-relaxed">
              Essential procedures for handling flat tyre incidents, brake binding, delayed trains, and block section safety 
              to ensure railway operational safety and prevent accidents.
            </p>
          </div>

          {/* Content Sections */}
          <div className="space-y-6">
            
            {/* Flat Tyre Section */}
            <div className="bg-white/10 backdrop-blur-lg rounded-2xl shadow-2xl py-6 lg:px-4 px-2 border border-white/20 hover:bg-white/15 transition-all duration-300">
              <h2 className="lg:text-3xl text-xl font-bold text-white mb-8 flex flex-col lg:flex-row gap-4 items-center justify-center">
                <span className="bg-gradient-to-r from-red-500 to-orange-500 lg:p-4 p-2 rounded-full mr-4 shadow-lg flex items-center justify-center">
                  <AlertTriangle className="lg:w-8 lg:h-8 w-6 h-6 text-white" />
                </span>
                Flat Tyre Detection & Response
              </h2>
              <div className="bg-gradient-to-br from-red-500/20 to-orange-500/20 backdrop-blur-lg rounded-xl py-6 lg:px-4 px-2 shadow-lg border border-red-400/30">
                <div className="space-y-4">
                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-red-300 mb-3 flex items-center flex-col gap-2 text-center">
                      <Eye className="w-5 h-5 mr-2" />
                      Identification & Detection
                    </h5>
                    <p className="text-white lg:text-base text-sm leading-relaxed mb-4">
                      Flat tyre can be identified through the continuous hammering sound generated by the affected wheel during its run. It can cause extensive damage to track by causing rail fractures and weld failures resulting into serious accidents to the following trains.
                    </p>
                    <div className="space-y-3">
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-red-400">
                          <Lightbulb className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">Flat tyre can happen due to brake binding causing hardening/stopping of wheel movement thereby a particular area of wheel tyre wears excessively resulting in flatness on the wheel tyre.</span>
                      </div>
                    </div>
                  </div>

                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-orange-300 mb-3 flex flex-col lg:flex-row gap-4 items-center text-center">
                      <UserCheck className="w-5 h-5 mr-2" />
                      TXR Staff Responsibilities
                    </h5>
                    <div className="space-y-3">
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-orange-400">
                          <Shield className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">TXR staff during &apos;rolling-in&apos; examination at all major train examination points shall observe keenly to detect flat tyre in the train while in motion.</span>
                      </div>
                    </div>
                  </div>

                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-red-400 mb-3 flex flex-col lg:flex-row gap-4 items-center text-center">
                      <Bell className="w-5 h-5 mr-2" />
                      Station Staff Vigilance
                    </h5>
                    <div className="space-y-3">
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-red-400">
                          <AlertOctagon className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">Station Operating Staff while exchanging &apos;all-right&apos; signals & Engineering Gatemen shall be vigilant to hear any unusual / hammering sound in the running train and make efforts to stop and examine the train or intimate the Station Master if they failed to stop train in case they observe any such sound.</span>
                      </div>
                    </div>
                  </div>

                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-orange-400 mb-3 flex flex-col lg:flex-row gap-4 items-center text-center">
                      <Users className="w-5 h-5 mr-2" />
                      On-board Staff Actions
                    </h5>
                    <div className="space-y-3">
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-orange-400">
                          <Train className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">On-board staff like TTEs, Coach Attendants, AC Mechanics and other Supervisor / Officers travelling by the train/particular coach shall also take appropriate action to bring it to the notice of Train Guard/Loco Pilot/Station Master of nearby station on detecting any unusual / hammering sound in the coach / train.</span>
                      </div>
                    </div>
                  </div>

                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-red-500 mb-3 flex flex-col lg:flex-row gap-4 items-center text-center">
                      <CheckCircle className="w-5 h-5 mr-2" />
                      Immediate Response Procedures
                    </h5>
                    <div className="space-y-3">
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-red-500">
                          <ArrowRight className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">Once such information is received, the Loco pilot shall bring the train to a stop at the earliest. On stopping, the train crew shall examine the suspected vehicle and share the details to the C&W control.</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-red-600">
                          <CheckCircle className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">After consultation, the train can be moved with necessary conditions to clear the block section.</span>
                      </div>
                    </div>
                  </div>

                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-orange-500 mb-3 flex flex-col lg:flex-row gap-4 items-center text-center">
                      <Wrench className="w-5 h-5 mr-2" />
                      TXR Staff Examination
                    </h5>
                    <div className="space-y-3">
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-orange-500">
                          <Wrench className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">If TXR staff is available at that station or they can come quickly from other station, the flat tyre shall be examined by them and they will certify whether the flatness is within the permissible limits or beyond.</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-orange-600">
                          <Gauge className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">If the flatness is within the permissible limit, they can certify for running the train further at normal speed and if flatness is beyond the permissible limit, the wagon has to be detached at the same station.</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-orange-700">
                          <AlertCircle className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">If no TXR staff is posted to work at that station, and it is likely to take more time for TXR staff to come, the Loco Pilot, Guard and Station Master shall decide in consultation with the SCOR to detach the coach/wagon at the same station.</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-orange-800">
                          <Shield className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">Under no circumstances, the Station Master shall allow the train to run with a suspected flat tyre, once the information is received.</span>
                      </div>
                    </div>
                  </div>

                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-red-600 mb-3 flex flex-col lg:flex-row gap-4 items-center text-center">
                      <HardHat className="w-5 h-5 mr-2" />
                      Track Inspection Requirements
                    </h5>
                    <div className="space-y-3">
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-red-600">
                          <MapPin className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">Apart from examining the wagon, the track on which the flat tyre ran should also be inspected. The SSE (P. Way) / JE/P. Way / P. Way Supervisor of Engineering Department shall inspect the rear block section passed by the affected train.</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-red-700">
                          <Car className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">Inspection can be done either by travelling in a light engine/Tower Car with a restricted speed of 30 KMPH or by proceeding on a motor/push trolley if Loco/Tower car is not readily available.</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-red-800">
                          <CheckCircle className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">They shall certify the track duly taking protective action for any failure noticed.</span>
                      </div>
                    </div>
                  </div>

                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-orange-600 mb-3 flex flex-col lg:flex-row gap-4 items-center text-center">
                      <Settings className="w-5 h-5 mr-2" />
                      Speed Restrictions & USFD Testing
                    </h5>
                    <div className="space-y-3">
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-orange-600">
                          <Gauge className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">Engineering Control in consultation with SSE/JE-P.Way Supervisor who has inspected the section shall impose SR of 50 KMPH for Passenger trains as well as for empty Goods trains in the affected section till USFD test is conducted.</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-orange-700">
                          <AlertOctagon className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">No loaded goods train shall be allowed to run unless USFD testing is completed.</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-orange-800">
                          <Timer className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">On completion of USFD testing, speed of passenger trains and that of empty goods trains shall be raised to 75 KMPH and after observing for 24 hours, normal sectional speed shall be restored for these trains.</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-orange-900">
                          <Gauge className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">Loaded goods shall be permitted at 50 KMPH on completion of USFD and after observing for 24 hours, normal speed shall be restored for such trains.</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Brake Binding Section */}
            <div className="bg-white/10 backdrop-blur-lg rounded-2xl shadow-2xl py-6 lg:px-4 px-2 border border-white/20 hover:bg-white/15 transition-all duration-300">
              <h2 className="lg:text-3xl text-xl font-bold text-white mb-8 flex flex-col lg:flex-row gap-4 items-center justify-center">
                <span className="bg-gradient-to-r from-yellow-500 to-orange-500 lg:p-4 p-2 rounded-full mr-4 shadow-lg">
                  <Wrench className="lg:w-8 lg:h-8 w-6 h-6 text-white" />
                </span>
                Brake Binding & Prevention
              </h2>
              <div className="bg-gradient-to-br from-yellow-500/20 to-orange-500/20 backdrop-blur-lg rounded-xl py-6 lg:px-4 px-2 shadow-lg border border-yellow-400/30">
                <div className="space-y-4">
                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-yellow-300 mb-3 flex flex-col lg:flex-row gap-4 items-center text-center">
                      <AlertTriangle className="w-5 h-5 mr-2" />
                      Brake Binding Causes
                    </h5>
                    <p className="text-white lg:text-base text-sm leading-relaxed mb-4">
                      Brake binding of a wagon/coach occurs when any of the following happens:
                    </p>
                    <div className="space-y-3">
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-yellow-400">
                          <AlertCircle className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">Hand brakes are not released</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-yellow-500">
                          <Settings className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">Distribute Valves (DV) are not released after engine change</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-yellow-600">
                          <Gauge className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">Load/empty wagon is placed in load position when the wagon is empty or gross weight of the wagon is below 42.5 tonnes</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-yellow-700">
                          <Zap className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">Release of Distribution Valve is not ensured after resetting ACP</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-yellow-800">
                          <Wrench className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">Defect in C3W DV</span>
                      </div>
                    </div>
                  </div>

                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-orange-300 mb-3 flex flex-col lg:flex-row gap-4 items-center text-center">
                      <Shield className="w-5 h-5 mr-2" />
                      Safety Implications & Response
                    </h5>
                    <div className="space-y-3">
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-orange-400">
                          <AlertTriangle className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">Brake binding jams the wheel movement and causes flat tyre which in turn damages the track.</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-orange-500">
                          <CheckCircle className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">Hence, as and when Brake binding is noticed, the train shall be stopped and the brakes must be released.</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Delayed Trains Section */}
            <div className="bg-white/10 backdrop-blur-lg rounded-2xl shadow-2xl py-6 lg:px-4 px-2 border border-white/20 hover:bg-white/15 transition-all duration-300">
              <h2 className="lg:text-3xl text-xl font-bold text-white mb-8 flex flex-col lg:flex-row gap-4 items-center justify-center text-center">
                <span className="bg-gradient-to-r from-purple-500 to-pink-500 lg:p-4 p-2 rounded-full mr-4 shadow-lg">
                  <Clock className="lg:w-8 lg:h-8 w-6 h-6 text-white" />
                </span>
                Trains Unusually Delayed in Section
              </h2>
              <div className="bg-gradient-to-br from-purple-500/20 to-pink-500/20 backdrop-blur-lg rounded-xl py-6 lg:px-4 px-2 shadow-lg border border-purple-400/30">
                <div className="space-y-4">
                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-purple-300 mb-3 flex flex-col lg:flex-row gap-4 items-center text-center">
                      <Timer className="w-5 h-5 mr-2" />
                      Delay Detection Criteria
                    </h5>
                    <div className="space-y-3">
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-purple-400">
                          <AlertCircle className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">If a train carrying passengers does not arrive within 10 minutes or if a goods train does not arrive within 20 minutes more than its normal running time from the station in rear, the Station Master at the station in advance shall immediately advise the station in rear and the Control of this fact.</span>
                      </div>
                    </div>
                  </div>

                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-pink-300 mb-3 flex flex-col lg:flex-row gap-4 items-center text-center">
                      <Shield className="w-5 h-5 mr-2" />
                      Safety Measures for Multiple Lines
                    </h5>
                    <div className="space-y-3">
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-pink-400">
                          <AlertOctagon className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">On double or multiple lines, the Station Masters at either end of the block section shall immediately stop all trains proceeding into the block section on adjacent line or lines in either direction.</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-pink-500">
                          <Bell className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">They shall warn the Loco Pilots and Guards of such trains by issue of suitable Caution Orders.</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-pink-600">
                          <Eye className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">They shall also ascertain the whereabouts and the condition of the delayed train.</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Trains Stopped in Block Section */}
            <div className="bg-white/10 backdrop-blur-lg rounded-2xl shadow-2xl py-6 lg:px-4 px-2 border border-white/20 hover:bg-white/15 transition-all duration-300">
              <h2 className="lg:text-3xl text-xl font-bold text-white mb-8 flex flex-col lg:flex-row gap-4 items-center justify-center text-center">
                <span className="bg-gradient-to-r from-green-500 to-emerald-500 lg:p-4 p-2 rounded-full mr-4 shadow-lg">
                  <MapPin className="lg:w-8 lg:h-8 w-6 h-6 text-white" />
                </span>
                Trains Stopped in Block Section
              </h2>
              <div className="bg-gradient-to-br from-green-500/20 to-emerald-500/20 backdrop-blur-lg rounded-xl py-6 lg:px-4 px-2 shadow-lg border border-green-400/30">
                <div className="space-y-4">
                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-green-300 mb-3 flex flex-col lg:flex-row gap-4 items-center text-center">
                      <Timer className="w-5 h-5 mr-2" />
                      Extended Stoppage Procedures
                    </h5>
                    <div className="space-y-3">
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-green-400">
                          <AlertCircle className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">If, for any reason, a train is brought to a stand for a period longer than 15 minutes, the hand brakes of the locomotive shall be applied in addition to the application of air brake etc.</span>
                      </div>
                    </div>
                  </div>

                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-emerald-300 mb-3 flex flex-col lg:flex-row gap-4 items-center text-center">
                      <Gauge className="w-5 h-5 mr-2" />
                      Gradient Safety Measures
                    </h5>
                    <div className="space-y-3">
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-emerald-400">
                          <AlertTriangle className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">If such stoppage happens to be on sections with a gradient of 1 in 150 the following additional precautions shall be taken:</span>
                      </div>
                    </div>
                  </div>

                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-green-400 mb-3 flex flex-col lg:flex-row gap-4 items-center text-center">
                      <Users className="w-5 h-5 mr-2" />
                      Passenger Train Safety
                    </h5>
                    <div className="space-y-3">
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-green-400">
                          <Shield className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">On trains carrying passengers, the Guard shall apply hand brakes in the brake-van and wedges to the wheels of two vehicles towards the falling gradient.</span>
                      </div>
                    </div>
                  </div>

                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-emerald-400 mb-3 flex flex-col lg:flex-row gap-4 items-center text-center">
                      <Train className="w-5 h-5 mr-2" />
                      Goods Train Safety
                    </h5>
                    <div className="space-y-3">
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-emerald-400">
                          <Wrench className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">On goods trains, hand brakes of at least one third of the wagons in the train or 10 wagons behind the engine and 5 wagons inside the brake-van, whichever is more, shall be pinned down.</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-emerald-500">
                          <Shield className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">This is in addition to the application of Guard&apos;s hand brake in the brake-van.</span>
                      </div>
                    </div>
                  </div>

                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-green-500 mb-3 flex flex-col lg:flex-row gap-4 items-center text-center">
                      <CheckCircle className="w-5 h-5 mr-2" />
                      Train Restart Procedures
                    </h5>
                    <div className="space-y-3">
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-green-500">
                          <Gauge className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">When the train is expected to start, proper air pressure must be built up to prescribed levels.</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-green-600">
                          <Wrench className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">Hand brakes must be released; wedges and skids have to be removed.</span>
                      </div>
                      <div className="flex items-start">
                        <span className="shrink-0 mt-1 mr-3 text-green-700">
                          <ArrowRight className="w-5 h-5" />
                        </span>
                        <span className="text-white lg:text-base text-sm">Thereafter, the air brakes may be released to start the train.</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Key Safety Points Summary */}
            <div className="bg-white/10 backdrop-blur-lg rounded-2xl shadow-2xl py-6 lg:px-4 px-2 border border-white/20 hover:bg-white/15 transition-all duration-300">
              <h2 className="lg:text-3xl text-xl font-bold text-white mb-8 flex flex-col lg:flex-row gap-4 items-center justify-center text-center">
                <span className="bg-gradient-to-r from-cyan-500 to-blue-500 lg:p-4 p-2 rounded-full mr-4 shadow-lg">
                  <Shield className="lg:w-8 lg:h-8 w-6 h-6 text-white" />
                </span>
                Key Safety Points Summary
              </h2>
              <div className="bg-gradient-to-br from-cyan-500/20 to-blue-500/20 backdrop-blur-lg rounded-xl py-6 lg:px-4 px-2 shadow-lg border border-cyan-400/30">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-cyan-300 mb-2 flex items-center flex-col gap-2 text-center">
                      <AlertTriangle className="w-4 h-4 mr-2" />
                      Flat Tyre Detection
                    </h5>
                    <p className="text-sm text-gray-200">
                      Listen for hammering sounds and observe wheel condition.
                    </p>
                  </div>
                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-blue-300 mb-2 flex items-center flex-col gap-2 text-center">
                      <Wrench className="w-4 h-4 mr-2" />
                      Brake Binding Prevention
                    </h5>
                    <p className="text-sm text-gray-200">
                      Ensure proper release of hand brakes and DVs.
                    </p>
                  </div>
                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-cyan-400 mb-2 flex items-center flex-col gap-2 text-center">
                      <Clock className="w-4 h-4 mr-2" />
                      Delay Monitoring
                    </h5>
                    <p className="text-sm text-gray-200">
                      Monitor passenger (10 min) and goods (20 min) delays.
                    </p>
                  </div>
                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-blue-400 mb-2 flex items-center flex-col gap-2 text-center">
                      <MapPin className="w-4 h-4 mr-2" />
                      Block Section Safety
                    </h5>
                    <p className="text-sm text-gray-200">
                      Apply hand brakes after 15 minutes of stoppage.
                    </p>
                  </div>
                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-cyan-500 mb-2 flex items-center flex-col gap-2 text-center">
                      <Gauge className="w-4 h-4 mr-2" />
                      Speed Restrictions
                    </h5>
                    <p className="text-sm text-gray-200">
                      Impose 50 KMPH SR until USFD testing completion.
                    </p>
                  </div>
                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20">
                    <h5 className="font-semibold text-blue-500 mb-2 flex items-center flex-col gap-2 text-center">
                      <HardHat className="w-4 h-4 mr-2" />
                      Track Inspection
                    </h5>
                    <p className="text-sm text-gray-200">
                      Inspect affected track sections after flat tyre incidents.
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Emergency Response Flow */}
            <div className="bg-white/10 backdrop-blur-lg rounded-2xl shadow-2xl py-6 lg:px-4 px-2 border border-white/20 hover:bg-white/15 transition-all duration-300">
              <h2 className="lg:text-3xl text-xl font-bold text-white mb-8 flex flex-col lg:flex-row gap-4 items-center justify-center text-center">
                <span className="bg-gradient-to-r from-purple-500 to-pink-500 lg:p-4 p-2 rounded-full mr-4 shadow-lg">
                  <AlertTriangle className="lg:w-8 lg:h-8 w-6 h-6 text-white" />
                </span>
                Emergency Response Flow
              </h2>
              <div className="bg-gradient-to-br from-purple-500/20 to-pink-500/20 backdrop-blur-lg rounded-xl py-6 lg:px-4 px-2 shadow-lg border border-purple-400/30">
                <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                  {[
                    {
                      title: "Detection",
                      color: "purple-300",
                      numberBg: "from-purple-500 to-pink-500",
                      desc: "Identify flat tyre or brake binding"
                    },
                    {
                      title: "Alert",
                      color: "pink-300",
                      numberBg: "from-pink-500 to-purple-500",
                      desc: "Stop train and inform authorities"
                    },
                    {
                      title: "Examine",
                      color: "purple-400",
                      numberBg: "from-purple-600 to-pink-600",
                      desc: "TXR staff examination and certification"
                    },
                    {
                      title: "Action",
                      color: "pink-400",
                      numberBg: "from-pink-600 to-purple-600",
                      desc: "Detach wagon or proceed with conditions"
                    }
                  ].map((step, idx) => (
                    <div
                      key={idx}
                      className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20 text-center flex flex-col items-center shadow-lg transition-transform hover:-translate-y-1 hover:shadow-2xl duration-300"
                    >
                      <div
                        className={`bg-gradient-to-br ${step.numberBg} text-white font-bold text-2xl lg:text-3xl w-12 h-12 lg:w-16 lg:h-16 flex items-center justify-center rounded-full shadow-lg mb-4 border-4 border-white/20 animate-fade-in`}
                        style={{ letterSpacing: '2px' }}
                      >
                        {idx + 1}
                      </div>
                      <h5
                        className={`font-semibold text-${step.color} lg:text-lg text-base mb-2 tracking-wide`}
                        style={{ letterSpacing: '0.5px' }}
                      >
                        {step.title}
                      </h5>
                      <p className="text-sm text-gray-200">{step.desc}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Communication Priority */}
            <div className="bg-white/10 backdrop-blur-lg rounded-2xl shadow-2xl py-6 lg:px-4 px-2 border border-white/20 hover:bg-white/15 transition-all duration-300">
              <h2 className="lg:text-3xl text-xl font-bold text-white mb-8 flex flex-col lg:flex-row gap-4 items-center justify-center text-center">
                <span className="bg-gradient-to-r from-cyan-500 to-blue-500 lg:p-4 p-2 rounded-full mr-4 shadow-lg">
                  <MessageSquare className="lg:w-8 lg:h-8 w-6 h-6 text-white" />
                </span>
                Communication Priority
              </h2>
              <div className="bg-gradient-to-br from-cyan-500/20 to-blue-500/20 backdrop-blur-lg rounded-xl py-6 lg:px-4 px-2 shadow-lg border border-cyan-400/30">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20 text-center">
                    <div className="bg-gradient-to-r from-cyan-500 to-blue-500 p-3 rounded-full lg:w-16 lg:h-16 w-10 h-10 mx-auto mb-3 flex items-center justify-center">
                      <RadioTower className="w-8 h-8 text-white" />
                    </div>
                    <h5 className="font-semibold text-cyan-300 mb-2">C&W Control</h5>
                    <p className="text-sm text-gray-200">Immediate notification of defects</p>
                  </div>
                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20 text-center">
                    <div className="bg-gradient-to-r from-blue-500 to-cyan-500 p-3 rounded-full lg:w-16 lg:h-16 w-10 h-10 mx-auto mb-3 flex items-center justify-center">
                      <Train className="w-8 h-8 text-white" />
                    </div>
                    <h5 className="font-semibold text-blue-300 mb-2">SCOR</h5>
                    <p className="text-sm text-gray-200">Senior Control Office Representative</p>
                  </div>
                  <div className="bg-white/10 backdrop-blur-sm rounded-lg lg:p-6 p-5 border border-white/20 text-center">
                    <div className="bg-gradient-to-r from-cyan-600 to-blue-600 p-3 rounded-full lg:w-16 lg:h-16 w-10 h-10 mx-auto mb-3 flex items-center justify-center">
                      <Users className="w-8 h-8 text-white" />
                    </div>
                    <h5 className="font-semibold text-cyan-400 mb-2">Engineering Control</h5>
                    <p className="text-sm text-gray-200">Track inspection and speed restrictions</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <style jsx>{`
        @keyframes fade-in {
          from { opacity: 0; transform: translateY(20px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-fade-in {
          animation: fade-in 1s ease-out;
        }
      `}</style>
    </div>
  )
}

export default OMPage87