export const worldInformationPageTitle = 'World Information' as const
export const africanCountriesHeaderLine = 'African Countries' as const
export const africanCountriesSectionTitle = 'Countries, Capitals & Leaders' as const

export type AfricanCountryRow = {
  country: string
  capital: string
  currency: string
  headOfState: string
  headOfGovernment: string
}

export const africanCountriesRows: readonly AfricanCountryRow[] = [
  {
    country: 'Algeria',
    capital: 'Algiers',
    currency: 'Algerian Dinar',
    headOfState: 'Abdelmadjid Tebboune',
    headOfGovernment: 'Nadir Larbaoui',
  },
  {
    country: 'Angola',
    capital: 'Luanda',
    currency: 'Angolan Kwanza',
    headOfState: 'João Lourenço',
    headOfGovernment: 'No Prime Minister',
  },
  {
    country: 'Benin',
    capital: 'Porto-Novo',
    currency: 'West African CFA Franc',
    headOfState: 'Patrice Talon',
    headOfGovernment: 'No Prime Minister',
  },
  {
    country: 'Botswana',
    capital: 'Gaborone',
    currency: 'Botswana Pula',
    headOfState: 'Duma Boko',
    headOfGovernment: 'No Prime Minister',
  },
  {
    country: 'Burkina Faso',
    capital: 'Ouagadougou',
    currency: 'West African CFA Franc',
    headOfState: 'Ibrahim Traoré',
    headOfGovernment: 'Jean Emmanuel Ouédraogo',
  },
  {
    country: 'Burundi',
    capital: 'Gitega',
    currency: 'Burundian Franc',
    headOfState: 'Évariste Ndayishimiye',
    headOfGovernment: 'Gervais Ndirakobuca',
  },
  {
    country: 'Cabo Verde',
    capital: 'Praia',
    currency: 'Cape Verdean Escudo',
    headOfState: 'José Maria Neves',
    headOfGovernment: 'Ulisses Correia e Silva',
  },
  {
    country: 'Cameroon',
    capital: 'Yaoundé',
    currency: 'Central African CFA Franc',
    headOfState: 'Paul Biya',
    headOfGovernment: 'Joseph Dion Ngute',
  },
  {
    country: 'Central African Republic',
    capital: 'Bangui',
    currency: 'Central African CFA Franc',
    headOfState: 'Faustin-Archange Touadéra',
    headOfGovernment: 'Félix Moloua',
  },
  {
    country: 'Chad',
    capital: "N'Djamena",
    currency: 'Central African CFA Franc',
    headOfState: 'Mahamat Idriss Déby',
    headOfGovernment: 'Allah-Maye Halina',
  },
  {
    country: 'Comoros',
    capital: 'Moroni',
    currency: 'Comorian Franc',
    headOfState: 'Azali Assoumani',
    headOfGovernment: 'No Prime Minister',
  },
  {
    country: 'Democratic Republic of the Congo',
    capital: 'Kinshasa',
    currency: 'Congolese Franc',
    headOfState: 'Félix Tshisekedi',
    headOfGovernment: 'Judith Suminwa Tuluka',
  },
  {
    country: 'Republic of the Congo',
    capital: 'Brazzaville',
    currency: 'Central African CFA Franc',
    headOfState: 'Denis Sassou Nguesso',
    headOfGovernment: 'Anatole Collinet Makosso',
  },
  {
    country: 'Côte d’Ivoire',
    capital: 'Yamoussoukro',
    currency: 'West African CFA Franc',
    headOfState: 'Alassane Ouattara',
    headOfGovernment: 'Robert Beugré Mambé',
  },
  {
    country: 'Djibouti',
    capital: 'Djibouti',
    currency: 'Djiboutian Franc',
    headOfState: 'Ismaïl Omar Guelleh',
    headOfGovernment: 'Abdoulkader Kamil Mohamed',
  },
  {
    country: 'Egypt',
    capital: 'Cairo',
    currency: 'Egyptian Pound',
    headOfState: 'Abdel Fattah el-Sisi',
    headOfGovernment: 'Mostafa Madbouly',
  },
  {
    country: 'Equatorial Guinea',
    capital: 'Malabo',
    currency: 'Central African CFA Franc',
    headOfState: 'Teodoro Obiang Nguema Mbasogo',
    headOfGovernment: 'Manuel Osa Nsue Nsua',
  },
  {
    country: 'Eritrea',
    capital: 'Asmara',
    currency: 'Eritrean Nakfa',
    headOfState: 'Isaias Afwerki',
    headOfGovernment: 'No Prime Minister',
  },
  {
    country: 'Eswatini',
    capital: 'Mbabane (administrative)',
    currency: 'Lilangeni',
    headOfState: 'King Mswati III',
    headOfGovernment: 'Russell Dlamini',
  },
  {
    country: 'Ethiopia',
    capital: 'Addis Ababa',
    currency: 'Ethiopian Birr',
    headOfState: 'Taye Atske Selassie',
    headOfGovernment: 'Abiy Ahmed',
  },
  {
    country: 'Gabon',
    capital: 'Libreville',
    currency: 'Central African CFA Franc',
    headOfState: 'Brice Oligui Nguema',
    headOfGovernment: 'Raymond Ndong Sima',
  },
  {
    country: 'Gambia',
    capital: 'Banjul',
    currency: 'Dalasi',
    headOfState: 'Adama Barrow',
    headOfGovernment: 'No Prime Minister',
  },
  {
    country: 'Ghana',
    capital: 'Accra',
    currency: 'Ghanaian Cedi',
    headOfState: 'John Dramani Mahama',
    headOfGovernment: 'No Prime Minister',
  },
  {
    country: 'Guinea',
    capital: 'Conakry',
    currency: 'Guinean Franc',
    headOfState: 'Mamady Doumbouya',
    headOfGovernment: 'Amadou Oury Bah',
  },
  {
    country: 'Guinea-Bissau',
    capital: 'Bissau',
    currency: 'West African CFA Franc',
    headOfState: 'Umaro Sissoco Embaló',
    headOfGovernment: 'Rui Duarte de Barros',
  },
  {
    country: 'Kenya',
    capital: 'Nairobi',
    currency: 'Kenyan Shilling',
    headOfState: 'William Ruto',
    headOfGovernment: 'No Prime Minister',
  },
  {
    country: 'Lesotho',
    capital: 'Maseru',
    currency: 'Lesotho Loti',
    headOfState: 'King Letsie III',
    headOfGovernment: 'Sam Matekane',
  },
  {
    country: 'Liberia',
    capital: 'Monrovia',
    currency: 'Liberian Dollar',
    headOfState: 'Joseph Boakai',
    headOfGovernment: 'No Prime Minister',
  },
  {
    country: 'Libya',
    capital: 'Tripoli',
    currency: 'Libyan Dinar',
    headOfState: 'Mohamed al-Menfi (Presidential Council)',
    headOfGovernment: 'Abdul Hamid Dbeibeh',
  },
  {
    country: 'Madagascar',
    capital: 'Antananarivo',
    currency: 'Ariary',
    headOfState: 'Andry Rajoelina',
    headOfGovernment: 'Christian Ntsay',
  },
  {
    country: 'Malawi',
    capital: 'Lilongwe',
    currency: 'Malawian Kwacha',
    headOfState: 'Lazarus Chakwera',
    headOfGovernment: 'No Prime Minister',
  },
  {
    country: 'Mali',
    capital: 'Bamako',
    currency: 'West African CFA Franc',
    headOfState: 'Assimi Goïta',
    headOfGovernment: 'Abdoulaye Maïga',
  },
  {
    country: 'Mauritania',
    capital: 'Nouakchott',
    currency: 'Ouguiya',
    headOfState: 'Mohamed Ould Ghazouani',
    headOfGovernment: 'Mokhtar Ould Djay',
  },
  {
    country: 'Mauritius',
    capital: 'Port Louis',
    currency: 'Mauritian Rupee',
    headOfState: 'Dharam Gokhool',
    headOfGovernment: 'Navin Ramgoolam',
  },
  {
    country: 'Morocco',
    capital: 'Rabat',
    currency: 'Moroccan Dirham',
    headOfState: 'King Mohammed VI',
    headOfGovernment: 'Aziz Akhannouch',
  },
  {
    country: 'Mozambique',
    capital: 'Maputo',
    currency: 'Mozambican Metical',
    headOfState: 'Daniel Chapo',
    headOfGovernment: 'Maria Benvinda Levi',
  },
  {
    country: 'Namibia',
    capital: 'Windhoek',
    currency: 'Namibian Dollar',
    headOfState: 'Netumbo Nandi-Ndaitwah',
    headOfGovernment: 'Elijah Ngurare',
  },
  {
    country: 'Niger',
    capital: 'Niamey',
    currency: 'West African CFA Franc',
    headOfState: 'Abdourahamane Tiani',
    headOfGovernment: 'Ali Mahamane Lamine Zeine',
  },
  {
    country: 'Nigeria',
    capital: 'Abuja',
    currency: 'Nigerian Naira',
    headOfState: 'Bola Tinubu',
    headOfGovernment: 'No Prime Minister',
  },
  {
    country: 'Rwanda',
    capital: 'Kigali',
    currency: 'Rwandan Franc',
    headOfState: 'Paul Kagame',
    headOfGovernment: 'Édouard Ngirente',
  },
  {
    country: 'São Tomé and Príncipe',
    capital: 'São Tomé',
    currency: 'Dobra',
    headOfState: 'Carlos Vila Nova',
    headOfGovernment: 'Américo Ramos',
  },
  {
    country: 'Senegal',
    capital: 'Dakar',
    currency: 'West African CFA Franc',
    headOfState: 'Bassirou Diomaye Faye',
    headOfGovernment: 'Ousmane Sonko',
  },
  {
    country: 'Seychelles',
    capital: 'Victoria',
    currency: 'Seychellois Rupee',
    headOfState: 'Wavel Ramkalawan',
    headOfGovernment: 'No Prime Minister',
  },
  {
    country: 'Sierra Leone',
    capital: 'Freetown',
    currency: 'Leone',
    headOfState: 'Julius Maada Bio',
    headOfGovernment: 'David Moinina Sengeh',
  },
  {
    country: 'Somalia',
    capital: 'Mogadishu',
    currency: 'Somali Shilling',
    headOfState: 'Hassan Sheikh Mohamud',
    headOfGovernment: 'Hamza Abdi Barre',
  },
  {
    country: 'South Africa',
    capital: 'Pretoria (executive)',
    currency: 'South African Rand',
    headOfState: 'Cyril Ramaphosa',
    headOfGovernment: 'No Prime Minister',
  },
  {
    country: 'South Sudan',
    capital: 'Juba',
    currency: 'South Sudanese Pound',
    headOfState: 'Salva Kiir Mayardit',
    headOfGovernment: 'Benjamin Bol Mel',
  },
  {
    country: 'Sudan',
    capital: 'Khartoum',
    currency: 'Sudanese Pound',
    headOfState: 'Abdel Fattah al-Burhan',
    headOfGovernment: 'Kamil Idris',
  },
  {
    country: 'Tanzania',
    capital: 'Dodoma',
    currency: 'Tanzanian Shilling',
    headOfState: 'Samia Suluhu Hassan',
    headOfGovernment: 'Kassim Majaliwa',
  },
  {
    country: 'Togo',
    capital: 'Lomé',
    currency: 'West African CFA Franc',
    headOfState: 'Jean-Lucien Savi de Tové',
    headOfGovernment: 'Faure Gnassingbé',
  },
  {
    country: 'Tunisia',
    capital: 'Tunis',
    currency: 'Tunisian Dinar',
    headOfState: 'Kais Saied',
    headOfGovernment: 'Sarra Zaafrani Zenzri',
  },
  {
    country: 'Uganda',
    capital: 'Kampala',
    currency: 'Ugandan Shilling',
    headOfState: 'Yoweri Museveni',
    headOfGovernment: 'Robinah Nabbanja',
  },
  {
    country: 'Zambia',
    capital: 'Lusaka',
    currency: 'Zambian Kwacha',
    headOfState: 'Hakainde Hichilema',
    headOfGovernment: 'No Prime Minister',
  },
  {
    country: 'Zimbabwe',
    capital: 'Harare',
    currency: 'Zimbabwe Gold (ZiG)',
    headOfState: 'Emmerson Mnangagwa',
    headOfGovernment: 'No Prime Minister',
  },
]
