export const worldInformationPageTitle = 'World Information' as const
export const asianCountriesHeaderLine = 'Asian Countries' as const
export const asianCountriesSectionTitle = 'Countries, Capitals & Leaders' as const

export type AsianCountryRow = {
  country: string
  capital: string
  currency: string
  headOfState: string
  headOfGovernment: string
}

export const asianCountriesRows: readonly AsianCountryRow[] = [
  {
    country: 'Afghanistan',
    capital: 'Kabul',
    currency: 'Afghan Afghani',
    headOfState: 'Supreme Leader Hibatullah Akhundzada',
    headOfGovernment: 'Hasan Akhund',
  },
  {
    country: 'Armenia',
    capital: 'Yerevan',
    currency: 'Armenian Dram',
    headOfState: 'Vahagn Khachaturyan',
    headOfGovernment: 'Nikol Pashinyan',
  },
  {
    country: 'Azerbaijan',
    capital: 'Baku',
    currency: 'Azerbaijani Manat',
    headOfState: 'Ilham Aliyev',
    headOfGovernment: 'Ali Asadov',
  },
  {
    country: 'Bahrain',
    capital: 'Manama',
    currency: 'Bahraini Dinar',
    headOfState: 'King Hamad bin Isa Al Khalifa',
    headOfGovernment: 'Salman bin Hamad Al Khalifa',
  },
  {
    country: 'Bangladesh',
    capital: 'Dhaka',
    currency: 'Bangladeshi Taka',
    headOfState: 'Mohammed Shahabuddin',
    headOfGovernment: 'Muhammad Yunus',
  },
  {
    country: 'Bhutan',
    capital: 'Thimphu',
    currency: 'Ngultrum',
    headOfState: 'King Jigme Khesar Namgyel Wangchuck',
    headOfGovernment: 'Tshering Tobgay',
  },
  {
    country: 'Brunei',
    capital: 'Bandar Seri Begawan',
    currency: 'Brunei Dollar',
    headOfState: 'Sultan Hassanal Bolkiah',
    headOfGovernment: 'Hassanal Bolkiah',
  },
  {
    country: 'Cambodia',
    capital: 'Phnom Penh',
    currency: 'Riel',
    headOfState: 'King Norodom Sihamoni',
    headOfGovernment: 'Hun Manet',
  },
  {
    country: 'China',
    capital: 'Beijing',
    currency: 'Renminbi (Yuan)',
    headOfState: 'Xi Jinping',
    headOfGovernment: 'Li Qiang',
  },
  {
    country: 'Cyprus',
    capital: 'Nicosia',
    currency: 'Euro',
    headOfState: 'Nikos Christodoulides',
    headOfGovernment: 'No separate PM',
  },
  {
    country: 'Georgia',
    capital: 'Tbilisi',
    currency: 'Georgian Lari',
    headOfState: 'Mikheil Kavelashvili',
    headOfGovernment: 'Irakli Kobakhidze',
  },
  {
    country: 'India',
    capital: 'New Delhi',
    currency: 'Indian Rupee',
    headOfState: 'Droupadi Murmu',
    headOfGovernment: 'Narendra Modi',
  },
  {
    country: 'Indonesia',
    capital: 'Jakarta',
    currency: 'Indonesian Rupiah',
    headOfState: 'Prabowo Subianto',
    headOfGovernment: 'No separate PM',
  },
  {
    country: 'Iran',
    capital: 'Tehran',
    currency: 'Iranian Rial',
    headOfState: 'Masoud Pezeshkian',
    headOfGovernment: 'No separate PM',
  },
  {
    country: 'Iraq',
    capital: 'Baghdad',
    currency: 'Iraqi Dinar',
    headOfState: 'Abdul Latif Rashid',
    headOfGovernment: "Mohammed Shia' al-Sudani",
  },
  {
    country: 'Israel',
    capital: 'Jerusalem',
    currency: 'Israeli New Shekel',
    headOfState: 'Isaac Herzog',
    headOfGovernment: 'Benjamin Netanyahu',
  },
  {
    country: 'Japan',
    capital: 'Tokyo',
    currency: 'Japanese Yen',
    headOfState: 'Emperor Naruhito',
    headOfGovernment: 'Shigeru Ishiba',
  },
  {
    country: 'Jordan',
    capital: 'Amman',
    currency: 'Jordanian Dinar',
    headOfState: 'King Abdullah II',
    headOfGovernment: 'Jafar Hassan',
  },
  {
    country: 'Kazakhstan',
    capital: 'Astana',
    currency: 'Tenge',
    headOfState: 'Kassym-Jomart Tokayev',
    headOfGovernment: 'Olzhas Bektenov',
  },
  {
    country: 'Kuwait',
    capital: 'Kuwait City',
    currency: 'Kuwaiti Dinar',
    headOfState: 'Emir Mishal Al-Ahmad Al-Jaber Al-Sabah',
    headOfGovernment: 'Ahmad Abdullah Al-Ahmad Al-Sabah',
  },
  {
    country: 'Kyrgyzstan',
    capital: 'Bishkek',
    currency: 'Kyrgyzstani Som',
    headOfState: 'Sadyr Japarov',
    headOfGovernment: 'Adylbek Kasymaliev',
  },
  {
    country: 'Laos',
    capital: 'Vientiane',
    currency: 'Kip',
    headOfState: 'Thongloun Sisoulith',
    headOfGovernment: 'Sonexay Siphandone',
  },
  {
    country: 'Lebanon',
    capital: 'Beirut',
    currency: 'Lebanese Pound',
    headOfState: 'Joseph Aoun',
    headOfGovernment: 'Nawaf Salam',
  },
  {
    country: 'Malaysia',
    capital: 'Kuala Lumpur',
    currency: 'Malaysian Ringgit',
    headOfState: 'King Ibrahim',
    headOfGovernment: 'Anwar Ibrahim',
  },
  {
    country: 'Maldives',
    capital: 'Malé',
    currency: 'Maldivian Rufiyaa',
    headOfState: 'Mohamed Muizzu',
    headOfGovernment: 'No separate PM',
  },
  {
    country: 'Mongolia',
    capital: 'Ulaanbaatar',
    currency: 'Tögrög',
    headOfState: 'Ukhnaagiin Khürelsükh',
    headOfGovernment: 'Gombojav Zandanshatar',
  },
  {
    country: 'Myanmar',
    capital: 'Naypyidaw',
    currency: 'Kyat',
    headOfState: 'Min Aung Hlaing',
    headOfGovernment: 'Nyo Saw',
  },
  {
    country: 'Nepal',
    capital: 'Kathmandu',
    currency: 'Nepalese Rupee',
    headOfState: 'Ram Chandra Paudel',
    headOfGovernment: 'K. P. Sharma Oli',
  },
  {
    country: 'North Korea',
    capital: 'Pyongyang',
    currency: 'North Korean Won',
    headOfState: 'Kim Jong Un',
    headOfGovernment: 'Pak Thae Song',
  },
  {
    country: 'Oman',
    capital: 'Muscat',
    currency: 'Omani Rial',
    headOfState: 'Sultan Haitham bin Tariq',
    headOfGovernment: 'Haitham bin Tariq',
  },
  {
    country: 'Pakistan',
    capital: 'Islamabad',
    currency: 'Pakistani Rupee',
    headOfState: 'Asif Ali Zardari',
    headOfGovernment: 'Shehbaz Sharif',
  },
  {
    country: 'State of Palestine',
    capital: 'East Jerusalem (claimed) / Ramallah (administrative)',
    currency: 'Israeli New Shekel & Jordanian Dinar',
    headOfState: 'Mahmoud Abbas',
    headOfGovernment: 'Mohammad Mustafa',
  },
  {
    country: 'Philippines',
    capital: 'Manila',
    currency: 'Philippine Peso',
    headOfState: 'Ferdinand Marcos Jr.',
    headOfGovernment: 'No separate PM',
  },
  {
    country: 'Qatar',
    capital: 'Doha',
    currency: 'Qatari Riyal',
    headOfState: 'Emir Tamim bin Hamad Al Thani',
    headOfGovernment: 'Mohammed bin Abdulrahman Al Thani',
  },
  {
    country: 'Saudi Arabia',
    capital: 'Riyadh',
    currency: 'Saudi Riyal',
    headOfState: 'King Salman bin Abdulaziz',
    headOfGovernment: 'Mohammed bin Salman',
  },
  {
    country: 'Singapore',
    capital: 'Singapore',
    currency: 'Singapore Dollar',
    headOfState: 'Tharman Shanmugaratnam',
    headOfGovernment: 'Lawrence Wong',
  },
  {
    country: 'South Korea',
    capital: 'Seoul',
    currency: 'South Korean Won',
    headOfState: 'Lee Jae Myung',
    headOfGovernment: 'Kim Min-seok',
  },
  {
    country: 'Sri Lanka',
    capital: 'Sri Jayawardenepura Kotte',
    currency: 'Sri Lankan Rupee',
    headOfState: 'Anura Kumara Dissanayake',
    headOfGovernment: 'Harini Amarasuriya',
  },
  {
    country: 'Syria',
    capital: 'Damascus',
    currency: 'Syrian Pound',
    headOfState: 'Ahmed al-Sharaa',
    headOfGovernment: 'No separate PM',
  },
  {
    country: 'Taiwan',
    capital: 'Taipei',
    currency: 'New Taiwan Dollar',
    headOfState: 'Lai Ching-te',
    headOfGovernment: 'Cho Jung-tai',
  },
  {
    country: 'Tajikistan',
    capital: 'Dushanbe',
    currency: 'Somoni',
    headOfState: 'Emomali Rahmon',
    headOfGovernment: 'Kokhir Rasulzoda',
  },
  {
    country: 'Thailand',
    capital: 'Bangkok',
    currency: 'Baht',
    headOfState: 'King Vajiralongkorn',
    headOfGovernment: 'Anutin Charnvirakul',
  },
  {
    country: 'Timor-Leste',
    capital: 'Dili',
    currency: 'United States Dollar',
    headOfState: 'José Ramos-Horta',
    headOfGovernment: 'Xanana Gusmão',
  },
  {
    country: 'Turkey',
    capital: 'Ankara',
    currency: 'Turkish Lira',
    headOfState: 'Recep Tayyip Erdoğan',
    headOfGovernment: 'No separate PM',
  },
  {
    country: 'Turkmenistan',
    capital: 'Ashgabat',
    currency: 'Turkmen Manat',
    headOfState: 'Serdar Berdimuhamedow',
    headOfGovernment: 'No separate PM',
  },
  {
    country: 'United Arab Emirates',
    capital: 'Abu Dhabi',
    currency: 'UAE Dirham',
    headOfState: 'President Mohamed bin Zayed Al Nahyan',
    headOfGovernment: 'Mohammed bin Rashid Al Maktoum',
  },
  {
    country: 'Uzbekistan',
    capital: 'Tashkent',
    currency: 'Uzbek Soʻm',
    headOfState: 'Shavkat Mirziyoyev',
    headOfGovernment: 'Abdulla Aripov',
  },
  {
    country: 'Vietnam',
    capital: 'Hanoi',
    currency: 'Vietnamese Đồng',
    headOfState: 'Lương Cường',
    headOfGovernment: 'Phạm Minh Chính',
  },
  {
    country: 'Yemen',
    capital: 'Aden (interim)',
    currency: 'Yemeni Rial',
    headOfState: 'Rashad al-Alimi',
    headOfGovernment: 'Salem bin Buraik',
  },
]
