export const worldInformationPageTitle = 'World Information' as const
export const europeanCountriesHeaderLine = 'European Countries' as const
export const europeanCountriesSectionTitle = 'Countries, Capitals & Leaders' as const

export type EuropeanCountryRow = {
  country: string
  capital: string
  currency: string
  headOfState: string
  headOfGovernment: string
}

export const europeanCountriesRows: readonly EuropeanCountryRow[] = [
  {
    country: 'Albania',
    capital: 'Tirana',
    currency: 'Albanian Lek',
    headOfState: 'Bajram Begaj',
    headOfGovernment: 'Edi Rama',
  },
  {
    country: 'Andorra',
    capital: 'Andorra la Vella',
    currency: 'Euro',
    headOfState: 'Co-Princes: Joan-Enric Vives & Emmanuel Macron',
    headOfGovernment: 'Xavier Espot Zamora',
  },
  {
    country: 'Austria',
    capital: 'Vienna',
    currency: 'Euro',
    headOfState: 'Alexander Van der Bellen',
    headOfGovernment: 'Christian Stocker',
  },
  {
    country: 'Belarus',
    capital: 'Minsk',
    currency: 'Belarusian Ruble',
    headOfState: 'Alexander Lukashenko',
    headOfGovernment: 'Alexander Turchin',
  },
  {
    country: 'Belgium',
    capital: 'Brussels',
    currency: 'Euro',
    headOfState: 'King Philippe',
    headOfGovernment: 'Bart De Wever',
  },
  {
    country: 'Bosnia and Herzegovina',
    capital: 'Sarajevo',
    currency: 'Convertible Mark',
    headOfState: 'Željka Cvijanović (Presidency Chair)',
    headOfGovernment: 'Borjana Krišto',
  },
  {
    country: 'Bulgaria',
    capital: 'Sofia',
    currency: 'Bulgarian Lev',
    headOfState: 'Rumen Radev',
    headOfGovernment: 'Rosen Zhelyazkov',
  },
  {
    country: 'Croatia',
    capital: 'Zagreb',
    currency: 'Euro',
    headOfState: 'Zoran Milanović',
    headOfGovernment: 'Andrej Plenković',
  },
  {
    country: 'Czech Republic',
    capital: 'Prague',
    currency: 'Czech Koruna',
    headOfState: 'Petr Pavel',
    headOfGovernment: 'Petr Fiala',
  },
  {
    country: 'Denmark',
    capital: 'Copenhagen',
    currency: 'Danish Krone',
    headOfState: 'King Frederik X',
    headOfGovernment: 'Mette Frederiksen',
  },
  {
    country: 'Estonia',
    capital: 'Tallinn',
    currency: 'Euro',
    headOfState: 'Alar Karis',
    headOfGovernment: 'Kristen Michal',
  },
  {
    country: 'Finland',
    capital: 'Helsinki',
    currency: 'Euro',
    headOfState: 'Alexander Stubb',
    headOfGovernment: 'Petteri Orpo',
  },
  {
    country: 'France',
    capital: 'Paris',
    currency: 'Euro',
    headOfState: 'Emmanuel Macron',
    headOfGovernment: 'François Bayrou',
  },
  {
    country: 'Germany',
    capital: 'Berlin',
    currency: 'Euro',
    headOfState: 'Frank-Walter Steinmeier',
    headOfGovernment: 'Friedrich Merz',
  },
  {
    country: 'Greece',
    capital: 'Athens',
    currency: 'Euro',
    headOfState: 'Konstantinos Tasoulas',
    headOfGovernment: 'Kyriakos Mitsotakis',
  },
  {
    country: 'Hungary',
    capital: 'Budapest',
    currency: 'Hungarian Forint',
    headOfState: 'Tamás Sulyok',
    headOfGovernment: 'Viktor Orbán',
  },
  {
    country: 'Iceland',
    capital: 'Reykjavík',
    currency: 'Icelandic Króna',
    headOfState: 'Halla Tómasdóttir',
    headOfGovernment: 'Kristrún Frostadóttir',
  },
  {
    country: 'Ireland',
    capital: 'Dublin',
    currency: 'Euro',
    headOfState: 'Michael D. Higgins',
    headOfGovernment: 'Micheál Martin',
  },
  {
    country: 'Italy',
    capital: 'Rome',
    currency: 'Euro',
    headOfState: 'Sergio Mattarella',
    headOfGovernment: 'Giorgia Meloni',
  },
  {
    country: 'Latvia',
    capital: 'Riga',
    currency: 'Euro',
    headOfState: 'Edgars Rinkēvičs',
    headOfGovernment: 'Evika Siliņa',
  },
  {
    country: 'Liechtenstein',
    capital: 'Vaduz',
    currency: 'Swiss Franc',
    headOfState: 'Prince Hans-Adam II',
    headOfGovernment: 'Brigitte Haas',
  },
  {
    country: 'Lithuania',
    capital: 'Vilnius',
    currency: 'Euro',
    headOfState: 'Gitanas Nausėda',
    headOfGovernment: 'Gintautas Paluckas',
  },
  {
    country: 'Luxembourg',
    capital: 'Luxembourg',
    currency: 'Euro',
    headOfState: 'Grand Duke Henri',
    headOfGovernment: 'Luc Frieden',
  },
  {
    country: 'Malta',
    capital: 'Valletta',
    currency: 'Euro',
    headOfState: 'Myriam Spiteri Debono',
    headOfGovernment: 'Robert Abela',
  },
  {
    country: 'Moldova',
    capital: 'Chișinău',
    currency: 'Moldovan Leu',
    headOfState: 'Maia Sandu',
    headOfGovernment: 'Dorin Recean',
  },
  {
    country: 'Monaco',
    capital: 'Monaco',
    currency: 'Euro',
    headOfState: 'Prince Albert II',
    headOfGovernment: 'Isabelle Berro-Amadeï (acting Minister of State)',
  },
  {
    country: 'Montenegro',
    capital: 'Podgorica',
    currency: 'Euro',
    headOfState: 'Jakov Milatović',
    headOfGovernment: 'Milojko Spajić',
  },
  {
    country: 'Netherlands',
    capital: 'Amsterdam',
    currency: 'Euro',
    headOfState: 'King Willem-Alexander',
    headOfGovernment: 'Dick Schoof',
  },
  {
    country: 'North Macedonia',
    capital: 'Skopje',
    currency: 'Macedonian Denar',
    headOfState: 'Gordana Siljanovska-Davkova',
    headOfGovernment: 'Hristijan Mickoski',
  },
  {
    country: 'Norway',
    capital: 'Oslo',
    currency: 'Norwegian Krone',
    headOfState: 'King Harald V',
    headOfGovernment: 'Jonas Gahr Støre',
  },
  {
    country: 'Poland',
    capital: 'Warsaw',
    currency: 'Polish Złoty',
    headOfState: 'Karol Nawrocki (President-elect)',
    headOfGovernment: 'Donald Tusk',
  },
  {
    country: 'Portugal',
    capital: 'Lisbon',
    currency: 'Euro',
    headOfState: 'Marcelo Rebelo de Sousa',
    headOfGovernment: 'Luís Montenegro',
  },
  {
    country: 'Romania',
    capital: 'Bucharest',
    currency: 'Romanian Leu',
    headOfState: 'Nicușor Dan',
    headOfGovernment: 'Ilie Bolojan',
  },
  {
    country: 'Russia',
    capital: 'Moscow',
    currency: 'Russian Ruble',
    headOfState: 'Vladimir Putin',
    headOfGovernment: 'Mikhail Mishustin',
  },
  {
    country: 'San Marino',
    capital: 'San Marino',
    currency: 'Euro',
    headOfState: 'Captains Regent (rotating)',
    headOfGovernment: 'No Prime Minister',
  },
  {
    country: 'Serbia',
    capital: 'Belgrade',
    currency: 'Serbian Dinar',
    headOfState: 'Aleksandar Vučić',
    headOfGovernment: 'Đuro Macut',
  },
  {
    country: 'Slovakia',
    capital: 'Bratislava',
    currency: 'Euro',
    headOfState: 'Peter Pellegrini',
    headOfGovernment: 'Robert Fico',
  },
  {
    country: 'Slovenia',
    capital: 'Ljubljana',
    currency: 'Euro',
    headOfState: 'Nataša Pirc Musar',
    headOfGovernment: 'Robert Golob',
  },
  {
    country: 'Spain',
    capital: 'Madrid',
    currency: 'Euro',
    headOfState: 'King Felipe VI',
    headOfGovernment: 'Pedro Sánchez',
  },
  {
    country: 'Sweden',
    capital: 'Stockholm',
    currency: 'Swedish Krona',
    headOfState: 'King Carl XVI Gustaf',
    headOfGovernment: 'Ulf Kristersson',
  },
  {
    country: 'Switzerland',
    capital: 'Bern',
    currency: 'Swiss Franc',
    headOfState: 'Karin Keller-Sutter (Federal President)',
    headOfGovernment: 'Federal Council system – no separate PM',
  },
  {
    country: 'Ukraine',
    capital: 'Kyiv',
    currency: 'Ukrainian Hryvnia',
    headOfState: 'Volodymyr Zelenskyy',
    headOfGovernment: 'Denys Shmyhal',
  },
  {
    country: 'United Kingdom',
    capital: 'London',
    currency: 'Pound Sterling',
    headOfState: 'King Charles III',
    headOfGovernment: 'Keir Starmer',
  },
  {
    country: 'Vatican City',
    capital: 'Vatican City',
    currency: 'Euro',
    headOfState: 'Pope Leo XIV',
    headOfGovernment: 'No Prime Minister',
  },
]
