export const aomPreviousPaper2022 = {
  quizzes: {
    'aom-previous-paper-2022': [
        {
          question: "Which of the following is not COA function?",
          options: [
            "Train ordering",
            "Caution order",
            "Indent placement",
            "Graph plotting",
          ],
          correct: 2,
          explanation: "Indent placement is the correct answer.",
        },
        {
          question: "Master charts indicate trains run in ..... Hours?",
          options: [
            "6",
            "8",
            "12",
            "24",
          ],
          correct: 3,
          explanation: "24 is the correct answer.",
        },
        {
          question: "Corridor blocks of ..... hours have been provided in Zero Based Time Table?",
          options: [
            "2",
            "2.5",
            "3",
            "4",
          ],
          correct: 2,
          explanation: "3 is the correct answer.",
        },
        {
          question: "While calculating Wagon Turn Round which of the following figures is not required?",
          options: [
            "Effective Wagon Holding",
            "Loaded Wagons",
            "Loaded received wagons",
            "Loaded wagons made over",
          ],
          correct: 3,
          explanation: "Loaded wagons made over is the correct answer.",
        },
        {
          question: "Which action is taken by section controller after getting information of accident?",
          options: [
            "Name noting of informer",
            "Stop trains entering affected section",
            "Information of sending ART",
            "All of the given options",
          ],
          correct: 3,
          explanation: "All of the given options is the correct answer.",
        },
        {
          question: "Plan Head under which construction of doubling works are proposed & sanctioned?",
          options: [
            "PH-11",
            "PH-12",
            "PH-15",
            "PH-14",
          ],
          correct: 2,
          explanation: "PH-15 is the correct answer.",
        },
        {
          question: "The actual punishment imposed on the staff found responsible for lapses in an accident shall be communicated to the ______ with in the stipulated time?",
          options: [
            "GM",
            "DRM",
            "Senior DSO",
            "PCSO",
          ],
          correct: 3,
          explanation: "PCSO is the correct answer.",
        },
        {
          question: "What is the meaning of CTC?",
          options: [
            "Centralised Traffic Control",
            "Centralised Train Control",
            "Centralised Time Control",
            "Central Train Control",
          ],
          correct: 0,
          explanation: "Centralised Traffic Control is the correct answer.",
        },
        {
          question: "On line Caution Order is generated through?",
          options: [
            "FOIS",
            "TMS",
            "ICMS",
            "FMM",
          ],
          correct: 2,
          explanation: "ICMS is the correct answer.",
        },
        
            {
              question: "Position of asset failure can be analyzed through?",
              options: [
                "FOIS",
                "PAM",
                "COIS",
                "All of the given options",
              ],
              correct: 1,
              explanation: "PAM is the correct answer.",
            },
            {
              question: "In case of fire to a passenger coach, the_______under the coach should be specially examined to see whether the fire has originated from them?",
              options: [
                "Wheels",
                "Brake block",
                "Battery boxes",
                "Axle boxes",
              ],
              correct: 2,
              explanation: "Battery boxes is the correct answer.",
            },
            {
              question: "Mail/Express trains run with ICF coaches on round trip upto …..kms will undergo Primary Maintenance on pit line at Primary end?",
              options: [
                "3000",
                "3200",
                "3500",
                "4000",
              ],
              correct: 2,
              explanation: "3500 is the correct answer.",
            },
            {
              question: "The Officers and Senior Subordinates present at the site of accident must _____ the cause and advise DRM and other Officers concerned, their opinion, mentioning the department or departments responsible and person or persons responsible for the occurrence?",
              options: [
                "Jointly investigate",
                "Observe",
                "Video graph",
                "Take witness",
              ],
              correct: 0,
              explanation: "Jointly investigate is the correct answer.",
            },
            {
              question: "In case of SPAD, root cause analysis may be carried out in which manner to improve the incisiveness of the accident investigation?",
              options: [
                "Failure mode and effects analysis",
                "Perito chart analysis",
                "Five WHYs (why - why)",
                "None of the given options",
              ],
              correct: 2,
              explanation: "Five WHYs (why - why) is the correct answer.",
            },
            {
              question: "Rake link information is available in?",
              options: [
                "PAM",
                "COIS",
                "FOIS",
                "TMS",
              ],
              correct: 1,
              explanation: "COIS is the correct answer.",
            },
            {
              question: "Who is the authorized person for crew grading?",
              options: [
                "Chief Commercial Controller",
                "Chief Loco Inspector",
                "Chief Commercial Controller or Chief Loco Inspector",
                "Branch Officers",
              ],
              correct: 1,
              explanation: "Chief Loco Inspector is the correct answer.",
            },
            {
              question: "Non Interlocked Working is required in which of the following cases?",
              options: [
                "Replacement of panel by RRI",
                "Commissioning of new SSI or RRI",
                "Changes in yard layout",
                "Replacement of mechanical lever frame by panel",
              ],
              correct: 2,
              explanation: "Changes in yard layout is the correct answer.",
            },
            {
              question: "All cases of Indicative Accidents shall be inquired into by a Committee of______ Officers?",
              options: [
                "Senior Scale",
                "Junior Scale",
                "Either Senior Scale or Junior Scale",
                "Senior Supervisors",
              ],
              correct: 2,
              explanation: "Either Senior Scale or Junior Scale is the correct answer.",
            },
            {
              question: "Following is not correct about the Public time table?",
              options: [
                "It gives arrival and departure of trains at important stations",
                "It gives time of important trains",
                "It gives fare list",
                "It is supplied to all employes related to train operation without cost",
              ],
              correct: 3,
              explanation: "It is supplied to all employes related to train operation without cost is the correct answer.",
            },
            {
              question: "If two or more trains have to run in pilot guard system, by which train pilot guard will be sent?",
              options: [
                "First train",
                "Last train",
                "Any train",
                "None of the given options",
              ],
              correct: 1,
              explanation: "Last train is the correct answer.",
            },
            {
                question: "Maximum permissible speed is approved by?",
                options: [
                  "GM",
                  "PCOM",
                  "CPTM",
                  "CRS",
                ],
                correct: 3,
                explanation: "CRS is the correct answer.",
              },
              {
                question: "The Committee may suggest any improvements in the_____ of working, which in their opinion, would prevent similar accidents in future or improve the working in any way, based not only on the cause or causes of the accident, but also the contributory factors, if any, and the extenuating circumstances, if any?",
                options: [
                  "Rules or practices",
                  "Guidelines",
                  "JPOs",
                  "Methodology",
                ],
                correct: 0,
                explanation: "Rules or practices is the correct answer.",
              },
              {
                question: "What is not included in the personal tool of a loco pilot?",
                options: [
                  "Hand Hammer",
                  "Tri Color Torch",
                  "Palm Coupler",
                  "Green Flag",
                ],
                correct: 1,
                explanation: "Tri Color Torch is the correct answer.",
              },
              {
                question: "Passenger transport is an important necessity for?",
                options: [
                  "Individual",
                  "Groups",
                  "Organisations",
                  "All of the given options",
                ],
                correct: 3,
                explanation: "All of the given options is the correct answer.",
              },
              {
                question: "Control Office Application covers which of the following work areas?",
                options: [
                  "Handling of train movement",
                  "Advance plotting of charts",
                  "Ordering of trains",
                  "All of the given options",
                ],
                correct: 3,
                explanation: "All of the given options is the correct answer.",
              },
              {
                question: "Which of the following is not true about the Marshalling Yard? (i) Ordinarily a yard should be adequate enough for its requirements of sorting, handling of local traffic, formation of trains for holding. (ii) Whatever may be the cause of late start of trains for a yard, apart from reducing available capacity of the section, in turn, it affects working of the yard itself by delaying subsequent formation of trains. (iii) In case of heavy congestion requiring block back on the neighbouring section, neighbouring yard should be called upon or directed by Sr.DOM/DOM by taking upon them some of the sorting and marshalling work, the congested yard would normally have done. (iv) In the event of an accident in Marshalling Yard temporarily reducing working capacity, steps should be taken to regulate the inflow of trains into the yard until the emergency is over and the yard has regained its normal working capacity.",
                options: [
                  "I & II are correct",
                  "III & IV are correct",
                  "None of the given options are correct",
                  "All of the given options are correct",
                ],
                correct: 3,
                explanation: "All of the given options are correct is the correct answer.",
              },
              {
                question: "Loco outage means the average number of locos available to traffic use in?",
                options: [
                  "24 hours",
                  "a month",
                  "10 days",
                  "15 days",
                ],
                correct: 0,
                explanation: "24 hours is the correct answer.",
              },
              {
                question: "What details related to crew and guards are ensured by CMS?",
                options: [
                  "Details of rest of crew and guards",
                  "Details of medical treatment of crew and guards",
                  "Training details of crew and guards",
                  "Details of all of the given options",
                ],
                correct: 3,
                explanation: "Details of all of the given options is the correct answer.",
              },
              {
                question: "What is the basis of calculation of average detention of a wagon?",
                options: [
                  "Wagon exchange register",
                  "Inward register",
                  "Station diary",
                  "None of the given options",
                ],
                correct: 0,
                explanation: "Wagon exchange register is the correct answer.",
              },
              {
                question: "What is the authority to receive a train on an obstructed line?",
                options: [
                  "T-509",
                  "T-609",
                  "T-A 602",
                  "T-1518",
                ],
                correct: 0,
                explanation: "T-509 is the correct answer.",
              },
              {
                question: "If the turn round of BOXN rakes in a coal circuit is 4 days, minimum how many rakes will be required to achieve the loading level of five rakes per day?",
                options: [
                  "18",
                  "1.25",
                  "20",
                  "4",
                ],
                correct: 2,
                explanation: "20 is the correct answer.",
              },
              {
                question: "As per G&SR ‘Night’ Means?",
                options: [
                  "22:00 Hrs to 08:00 Hrs",
                  "20:00 Hrs to 06:00 Hrs",
                  "Sunrise to Sunset",
                  "Sunset to Sunrise",
                ],
                correct: 3,
                explanation: "Sunset to Sunrise is the correct answer.",
              },
              {
                question: "How many dead engines can be attached to Mail/Express/Superfast trains?",
                options: [
                  "1",
                  "Cannot be attached",
                  "2",
                  "3",
                ],
                correct: 0,
                explanation: "1 is the correct answer.",
              },
              {
                question: "The maximum speed of WAP-7 loco is?",
                options: [
                  "160kmph",
                  "140kmph",
                  "130kmph",
                  "120kmph",
                ],
                correct: 1,
                explanation: "140kmph is the correct answer.",
              },
              {
                question: "Punctuality is affected by?",
                options: [
                  "Faulty time table",
                  "Bad controlling",
                  "Delay in shunting",
                  "All of the given options",
                ],
                correct: 3,
                explanation: "All of the given options is the correct answer.",
              },
              {
                question: "Which of the following signals cannot be used for shunting?",
                options: [
                  "Home",
                  "Shunt signal",
                  "Hand signal",
                  "None of the given options",
                ],
                correct: 0,
                explanation: "Home is the correct answer.",
              },
              {
                question: "‘’SFOORTI’’ App is used for?",
                options: [
                  "Monitoring and managing freight business",
                  "Generation of RR",
                  "Monitoring the punctuality of Express trains",
                  "None of the given options",
                ],
                correct: 0,
                explanation: "Monitoring and managing freight business is the correct answer.",
              },
              {
                question: "The vision test required for Loco Pilot/Assistant Loco Pilot is?",
                options: [
                  "A1",
                  "A2",
                  "A3",
                  "B1",
                ],
                correct: 0,
                explanation: "A1 is the correct answer.",
              },
              {
                question: "The SWRs should be reviewed once in every______ years?",
                options: [
                  "Two years",
                  "Three years",
                  "Four years",
                  "Five years",
                ],
                correct: 3,
                explanation: "Five years is the correct answer.",
              },
              {
                question: "Total Goods train KM divided by total Goods train engine hours gives the statistical figure of?",
                options: [
                  "Average speed of Goods train",
                  "Engine KM per Goods train",
                  "Goods train KM per engine",
                  "None of the given options",
                ],
                correct: 0,
                explanation: "Average speed of Goods train is the correct answer.",
              },
              {
                question: "Damage of Railway property to the tune of which of the following value shall be treated as serious damage to property?",
                options: [
                  "2 Crore",
                  "2.50 Crore",
                  "20 Lacs",
                  "1.99 Crore",
                ],
                correct: 0,
                explanation: "2 Crore is the correct answer.",
              },
              {
                question: "Fog signal post is placed at_____m from First stop signal?",
                options: [
                  "120 m",
                  "180 m",
                  "270 m",
                  "400 m",
                ],
                correct: 2,
                explanation: "270 m is the correct answer.",
              },
              {
                question: "In which of the following, NI working may not be required and work can be completed in a traffic block?",
                options: [
                  "Replacement of Panel by RRI",
                  "Overhauling of Lever frame",
                  "Changes in Yard layout",
                  "Meggering of cables",
                ],
                correct: 0,
                explanation: "Replacement of Panel by RRI is the correct answer.",
              },
              {
                question: "At what restricted speed will the loco pilot proceed if the visibility is not clear while passing the automatic stop signal in ON position in a double line?",
                options: [
                  "08 KMPH",
                  "10 KMPH",
                  "15 KMPH",
                  "None of the given options",
                ],
                correct: 1,
                explanation: "10 KMPH is the correct answer.",
              },
              {
                question: "Within how many days after the date of accident, DAR action must be completed?",
                options: [
                  "D+30",
                  "D+60",
                  "D+90",
                  "D+120",
                ],
                correct: 2,
                explanation: "D+90 is the correct answer.",
              },
              {
                question: "Customers can track their goods in transit through?",
                options: [
                  "PNR",
                  "FNR",
                  "COIS",
                  "None of the given options",
                ],
                correct: 1,
                explanation: "FNR is the correct answer.",
              },
              {
                question: "Proper rake links help in optimum utilization of rolling stock?",
                options: [
                  "yes",
                  "No",
                  "Somewhat",
                  "In most cases",
                ],
                correct: 0,
                explanation: "yes is the correct answer.",
              },
              {
                question: "For accidents not coming under the purview of CRS, the ______ shall order an enquiry by a committee of officers from the departments concerned?",
                options: [
                  "DRM",
                  "PHOD",
                  "AGM",
                  "PCSO",
                ],
                correct: 0,
                explanation: "DRM is the correct answer.",
              },
              {
                question: "Arrangement between points, signals and other appliances interconnected electrically or mechanically or both to ensure safety is?",
                options: [
                  "Isolation",
                  "Interlocking",
                  "Obstruction",
                  "System of working",
                ],
                correct: 1,
                explanation: "Interlocking is the correct answer.",
              },
              {
                question: "Target for Committee to submit the inquiry report to DRM /GM is within _____?",
                options: [
                  "Date of accident(D)+1",
                  "Date of accident(D)+15",
                  "Date of accident(D)+3",
                  "Date of accident(D)+7",
                ],
                correct: 3,
                explanation: "Date of accident(D)+7 is the correct answer.",
              },
              {
                question: "Which of the following does not feature in the Yard working instructions of a Marshalling Yard?",
                options: [
                  "Full description of the yard including number of lines with their holding capacity",
                  "Marshalling Order in force",
                  "Quantum of inward, outward and internal traffic required to be dealt with by the yard and their timing",
                  "Speed of the train in main line after dispatch",
                ],
                correct: 3,
                explanation: "Speed of the train in main line after dispatch is the correct answer.",
              },
              {
                question: "A GPS based Fog Safety device is being provided to loco pilots in fog affected areas which enables loco pilots to know?",
                options: [
                  "The exact distance of the approaching signals, level crossing gates etc",
                  "The exact aspect of the approaching stop signals",
                  "The exact distance and aspect of approaching signals",
                  "The exact location of stations through GPS",
                ],
                correct: 0,
                explanation: "The exact distance of the approaching signals, level crossing gates etc is the correct answer.",
              },
              {
                question: "The supply control post where the incoming feeder lines from grid sub station are terminated is known as?",
                options: [
                  "Feeding post",
                  "Supply control post",
                  "Feeding post & Supply control post",
                  "None of the given options",
                ],
                correct: 0,
                explanation: "Feeding post is the correct answer.",
              },
              {
                question: "Mail/Express trains run with LHB coaches on round trip upto …..kms will undergo Primary Maintenance on pit line at Primary end?",
                options: [
                  "3000",
                  "3200",
                  "3500",
                  "4000",
                ],
                correct: 3,
                explanation: "4000 is the correct answer.",
              },
              {
                question: "Minimum visibility distance of warner signal when placed on a post by it self?",
                options: [
                  "600 meter",
                  "400 Meter",
                  "300 Meter",
                  "250 Meter",
                ],
                correct: 1,
                explanation: "400 Meter is the correct answer.",
              },
              {
                question: "Loco maintenance schedule AOH for coaching Locos (conventional Loco) is carried out in?",
                options: [
                  "3 months + or - 15 days",
                  "6 months + or - 15 days",
                  "12 months + or - 15 days",
                  "9 months + or - 15 days",
                ],
                correct: 2,
                explanation: "12 months + or - 15 days is the correct answer.",
              },
              {
                question: "The speed of Motor Trolley should not exceed ….. kmph over points & crossings?",
                options: [
                  "10",
                  "15",
                  "30",
                  "Sectional speed",
                ],
                correct: 1,
                explanation: "15 is the correct answer.",
              },
              {
                question: "Full form of RRSK?",
                options: [
                  "Rashtriya Rail Suraksha Kosh",
                  "Rashtriya Rail Security Kosh",
                  "Rashtriya Road Sanraksha Kosh",
                  "Rashtriya Rail Sanraksha Kosh",
                ],
                correct: 3,
                explanation: "Rashtriya Rail Sanraksha Kosh is the correct answer.",
              },
              {
                question: "Who will provide In Motion Electronic Way bridge at MGR Loading Terminal?",
                options: [
                  "By Railway",
                  "By Customer",
                  "Not required",
                  "None of the given options",
                ],
                correct: 1,
                explanation: "By Customer is the correct answer.",
              },
              {
                question: "What is included in operating ratio?",
                options: [
                  "NTKM per engine hours",
                  "Wagon Turn Round",
                  "Average starting Wagon load",
                  "None of the given options",
                ],
                correct: 3,
                explanation: "None of the given options is the correct answer.",
              },
              {
                question: "Indian Railways generally adopts which theoretical formula to measure section capacity?",
                options: [
                  "Scott Formula",
                  "American Formula",
                  "Stain Back Formula",
                  "G.I.P. Formula",
                ],
                correct: 0,
                explanation: "Scott Formula is the correct answer.",
              },
              {
                question: "In order to avoid any dispute later, the fact that a Loco Pilot has passed a signal at danger, should be formally brought to his notice through______ by the station master of the concerned station?",
                options: [
                  "Verbal instructions",
                  "Loco Inspector",
                  "Written memo",
                  "Guard of the train",
                ],
                correct: 2,
                explanation: "Written memo is the correct answer.",
              },
              {
                question: "Before introduction of new trains, compliance with RPC-4 will be certified jointly by…… of the originating Railways?",
                options: [
                  "CPTM & CRSE",
                  "PCOM & PCME",
                  "Sr. DOM & Sr. DME",
                  "None of the given options",
                ],
                correct: 0,
                explanation: "CPTM & CRSE is the correct answer.",
              },
              {
                question: "What is the main work of Central Control?",
                options: [
                  "Section Capacity Work",
                  "Supervision of Goods trains",
                  "Supervision of Passenger trains",
                  "Safety Drive",
                ],
                correct: 1,
                explanation: "Supervision of Goods trains is the correct answer.",
              },
              {
                question: "Long haul train will be run in which of the following conditions?",
                options: [
                  "Both rakes empty",
                  "One rake empty and one loaded",
                  "Both rakes loaded",
                  "All of the given options",
                ],
                correct: 3,
                explanation: "All of the given options is the correct answer.",
              },
              {
                question: "Wind Velocity can be measured by?",
                options: [
                  "Galvanometer",
                  "Ammeter",
                  "Thermo meter",
                  "Anemometer",
                ],
                correct: 3,
                explanation: "Anemometer is the correct answer.",
              },
              {
                question: "Two coupled powers are working together to whom authority to proceed will be given?",
                options: [
                  "Leading loco",
                  "Rear loco",
                  "Leading loco & Rear loco",
                  "None of the given options",
                ],
                correct: 0,
                explanation: "Leading loco is the correct answer.",
              },
              {
                question: "Full form of e-DAS?",
                options: [
                  "Electronic Drawing Approval System",
                  "Electronic Device Approval System",
                  "Electronic Drawing Agreement System",
                  "None of the given options",
                ],
                correct: 0,
                explanation: "Electronic Drawing Approval System is the correct answer.",
              },
              {
                question: "At the time of preparation of Time Table suggestions from following are taken?",
                options: [
                  "MP or MLA",
                  "ZRUCC",
                  "DRUCC",
                  "All of the given options",
                ],
                correct: 3,
                explanation: "All of the given options is the correct answer.",
              },
              {
                question: "At Block station the station limits are between?",
                options: [
                  "Two outermost signals",
                  "Two outer signals",
                  "Two First Stop signals",
                  "Two Last Stop signals",
                ],
                correct: 0,
                explanation: "Two outermost signals is the correct answer.",
              },
              {
                question: "Normally upper class coaches shall be marshalled in the ……. of the train?",
                options: [
                  "Middle",
                  "Front end",
                  "Rear end",
                  "As per convenience",
                ],
                correct: 0,
                explanation: "Middle is the correct answer.",
              },
              {
                question: "If a critical trauma patient is not given definite medical care within______ from the time of accident, chances of his ultimate recovery reduce drastically, even with the best of medical attention thereafter. This initial period is of?",
                options: [
                  "30 Mins",
                  "One hour",
                  "1 ½ hours",
                  "2 hours",
                ],
                correct: 1,
                explanation: "One hour is the correct answer.",
              },
              {
                question: "Which shield is awarded by Railway Board for the overall efficiency to the Best Zonal Railway?",
                options: [
                  "Lal Bahadur Shashtri Shield",
                  "Pt. Govind Ballabh Pant Shield",
                  "Rail Minister’s Shield",
                  "None of the given options",
                ],
                correct: 1,
                explanation: "Pt. Govind Ballabh Pant Shield is the correct answer.",
              },
              {
                question: "Tonne kilometer is a ..... unit?",
                options: [
                  "Primary unit",
                  "Secondary unit",
                  "Fundamental unit",
                  "Derivative unit",
                ],
                correct: 2,
                explanation: "Fundamental unit is the correct answer.",
              },
              {
                question: "Whistle Boards shall be provided at a distance of..…metres on the approaches to all unmanned level crossings?",
                options: [
                  "200",
                  "300",
                  "400",
                  "600",
                ],
                correct: 3,
                explanation: "600 is the correct answer.",
              },
              {
                question: "Accident drills should be conducted once in ……… months, if no actual accident occurs within that period?",
                options: [
                  "4 months",
                  "3 months",
                  "6 months",
                  "12 months",
                ],
                correct: 1,
                explanation: "3 months is the correct answer.",
              },
              {
                question: "In case of collision/averted collision, ______ should be signed so as to indicate the last entry made and then seized?",
                options: [
                  "Train signal register",
                  "Station diary",
                  "S&T failure register",
                  "PN exchange register",
                ],
                correct: 0,
                explanation: "Train signal register is the correct answer.",
              },
              {
                question: "Which of the following shall have highest priority in allotment of Parcel Vans?",
                options: [
                  "Perishable Goods",
                  "General Goods",
                  "Livestock",
                  "None of the given options",
                ],
                correct: 0,
                explanation: "Perishable Goods is the correct answer.",
              },
              {
                question: "In Sections where there is provision of MACL signal with only one Distant signal, Warning Board provided will be of which type?",
                options: [
                  "Passenger Warning Board",
                  "Goods Warning Board",
                  "Both Passenger Warning Board & Goods Warning Board",
                  "None of the given options",
                ],
                correct: 2,
                explanation: "Both Passenger Warning Board & Goods Warning Board is the correct answer.",
              },
              {
                question: "Who prepares crew link of Loco pilot?",
                options: [
                  "Power controller",
                  "Section controller",
                  "Chief controller",
                  "AOM",
                ],
                correct: 0,
                explanation: "Power controller is the correct answer.",
              },
              {
                question: "CRS shall hold statutory enquiry into the accidents falling under Section_____of Railways Act 1989?",
                options: [
                  "110",
                  "111",
                  "112",
                  "113",
                ],
                correct: 3,
                explanation: "113 is the correct answer.",
              },
              {
                question: "Goods stock, duly certified 'fit to run on passenger trains' by examining staff, can be attached to run on?",
                options: [
                  "Intercity trains",
                  "Short distance trains",
                  "Passenger trains",
                  "Not permitted",
                ],
                correct: 2,
                explanation: "Passenger trains is the correct answer.",
              },
              {
                question: "In goods train C.C. rake if nominated circuit is broken B.P.C. will become ______?",
                options: [
                  "Valid",
                  "Invalid",
                  "None of the given options",
                  "All of the given options",
                ],
                correct: 1,
                explanation: "Invalid is the correct answer.",
              },
              {
                question: "Minimum Punishment to be given to a Gateman for the Failure of closure of gate due to which there is loss of life?",
                options: [
                  "Dismissal",
                  "Removal",
                  "Compulsory Retirement",
                  "Reduction to the next lower grade for 3 year with cumulative effect",
                ],
                correct: 0,
                explanation: "Dismissal is the correct answer.",
              },
              {
                question: "What is the unit for measuring line capacity?",
                options: [
                  "All Trains",
                  "Goods Trains",
                  "All Passenger Trains",
                  "All Light Engines",
                ],
                correct: 0,
                explanation: "All Trains is the correct answer.",
              },
              {
                question: "When any House of Parliament (Lok Sabha or Rajya Sabha) is adjourned without naming a day for reassembly it is known as?",
                options: [
                  "Demand for Grants",
                  "Adjournment of Debate",
                  "Adjournment of the sitting of the House",
                  "Adjournment Sine Die",
                ],
                correct: 3,
                explanation: "Adjournment Sine Die is the correct answer.",
              },
              {
                question: "How many articles are mentioned in Chapter-2 related to the language of the Union in Part-17 of the Constitution?",
                options: [
                  "5",
                  "8",
                  "4",
                  "3",
                ],
                correct: 3,
                explanation: "3 is the correct answer.",
              },
              {
                question: "In how many parts of the Indian Constitution are there provisions related to language?",
                options: [
                  "Two",
                  "Four",
                  "Three",
                  "Five",
                ],
                correct: 2,
                explanation: "Three is the correct answer.",
              },
              {
                question: "Who was known as Iron Man of India?",
                options: [
                  "Shri Govind Ballabh Pant",
                  "Pandit Jawaharlal Nehru",
                  "Netaji Subhash Chandra Bose",
                  "Sardar Vallabhbhai Patel",
                ],
                correct: 3,
                explanation: "Sardar Vallabhbhai Patel is the correct answer.",
              },
              {
                question: "The highest law officer in the state is?",
                options: [
                  "Attorney General",
                  "Advocate General",
                  "Additional General",
                  "None of the given options",
                ],
                correct: 1,
                explanation: "Advocate General is the correct answer.",
              },
              {
                question: "What will be the form of numerals to be used for the official purposes of the Union?",
                options: [
                  "1, 2, 3, 4",
                  "एक, दो, तीन, चार",
                  "I, II, III, IV",
                  "१, २, ३, ४",
                ],
                correct: 0,
                explanation: "1, 2, 3, 4 is the correct answer.",
              },
              {
                question: "The name Kunjarani Devi is associated with?",
                options: [
                  "Weight Lifting",
                  "Target shooting",
                  "Athletics",
                  "Swimming",
                ],
                correct: 0,
                explanation: "Weight Lifting is the correct answer.",
              },
              {
                question: "For seeing objects at the surface of water from a submarine under water, the instrument used is?",
                options: [
                  "Periscope",
                  "Telescope",
                  "Kaleidoscope",
                  "Spectroscope",
                ],
                correct: 0,
                explanation: "Periscope is the correct answer.",
              },
              {
                question: "Which of the following zonal headquarters - city combination is incorrect?",
                options: [
                  "South East Central Railway - Bilaspur",
                  "North Western Railway - Jodhpur",
                  "East Central Railway - Hajipur",
                  "West Central Railway - Jabalpur",
                ],
                correct: 1,
                explanation: "North Western Railway - Jodhpur is the correct answer.",
              },
              {
                question: "In which year the Official Language Act, 1963 was amended?",
                options: [
                  "1967",
                  "1964",
                  "1965",
                  "1966",
                ],
                correct: 0,
                explanation: "1967 is the correct answer.",
              },
              {
                question: "What is the name of the person that controls a football match?",
                options: [
                  "A referee",
                  "An umpire",
                  "A spectator",
                  "A goalkeeper",
                ],
                correct: 0,
                explanation: "A referee is the correct answer.",
              },
              {
                question: "The State which is neutral in matters of religion and does not uphold any particular religion as the State religion is called?",
                options: [
                  "Independent State",
                  "Democratic State",
                  "Secular State",
                  "None of the given options",
                ],
                correct: 2,
                explanation: "Secular State is the correct answer.",
              },
              {
                question: "Heavy Water Project (Talcher) and Fertilizer plant (Paradeep) are famous industries of?",
                options: [
                  "Orissa",
                  "Kerala",
                  "Tamilnadu",
                  "Andhra Pradesh",
                ],
                correct: 0,
                explanation: "Orissa is the correct answer.",
              },
              {
                question: "By which act a nation wide network to provide free and competent legal aid to the poor and to organize lok adalats for promoting equal justice has been established?",
                options: [
                  "The Legal Services Authorities Act (1987)",
                  "The Protection of Civil Rights Act, 1955",
                  "Prevention of Atrocities Act, 1989",
                  "None of the given options",
                ],
                correct: 0,
                explanation: "The Legal Services Authorities Act (1987) is the correct answer.",
              },
              {
                question: "Golden Quadrilateral Project for the development of National Highways was initiated by?",
                options: [
                  "Shri P V Narasimha Rao",
                  "Shri I K Gujral",
                  "Dr. Manmohan Singh",
                  "Shri Atal Bihari Vajpayee",
                ],
                correct: 3,
                explanation: "Shri Atal Bihari Vajpayee is the correct answer.",
              },
              {
                question: "What percentage of work can be directed by the Head of Office individually to officers proficient in Hindi to do their work in Hindi?",
                options: [
                  "75%",
                  "80%",
                  "90%",
                  "100%",
                ],
                correct: 3,
                explanation: "100% is the correct answer.",
              },
              {
                question: "CFCs are used as?",
                options: [
                  "Refrigerants",
                  "Insulators",
                  "Aerosol Propellants",
                  "All of the given options",
                ],
                correct: 3,
                explanation: "All of the given options is the correct answer.",
              },
              {
                question: "Who was the first Indian Chief of Army Staff of the Indian Army?",
                options: [
                  "Gen. K.M. Cariappa",
                  "Gen. Maharaja Rajendra Singhji",
                  "Vice-Admiral R.D. Katari",
                  "None of the given options",
                ],
                correct: 1,
                explanation: "Gen. Maharaja Rajendra Singhji is the correct answer.",
              },
              {
                question: "The 'Dronacharya Award' is given to?",
                options: [
                  "Sportsmen",
                  "Coaches",
                  "Umpires",
                  "Sports Editors",
                ],
                correct: 1,
                explanation: "Coaches is the correct answer.",
              },
              {
                question: "Filaria is caused by?",
                options: [
                  "Protozoa",
                  "Mosquito",
                  "Virus",
                  "Bacteria",
                ],
                correct: 1,
                explanation: "Mosquito is the correct answer.",
              },
              {
                question: "Which was the 1st non Test playing country to beat India in an international cricket match?",
                options: [
                  "Canada",
                  "Sri Lanka",
                  "Zimbabwe",
                  "East Africa",
                ],
                correct: 1,
                explanation: "Sri Lanka is the correct answer.",
              },
              {
                question: "The provisions as covered by Article 343 to 351 under Part XVII of the Constitution of India deals with?",
                options: [
                  "Religion",
                  "Official Language",
                  "President",
                  "Emergency",
                ],
                correct: 1,
                explanation: "Official Language is the correct answer.",
              },
              {
                question: "How many members are there in the Parliamentary Official Language Committee?",
                options: [
                  "30",
                  "28",
                  "25",
                  "20",
                ],
                correct: 0,
                explanation: "30 is the correct answer.",
              },
              {
                question: "In which of the following cities is the National Rail Museum located?",
                options: [
                  "Mumbai",
                  "New Delhi",
                  "Hyderabad",
                  "Chennai",
                ],
                correct: 1,
                explanation: "New Delhi is the correct answer.",
              },
              {
                question: "How much distance was travelled by first train of India?",
                options: [
                  "33 km",
                  "36 km",
                  "34 km",
                  "46 km",
                ],
                correct: 2,
                explanation: "34 km is the correct answer.",
              },
              {
                question: "Ecology deals with?",
                options: [
                  "Cell formation",
                  "Birds",
                  "Relation between organisms and their environment",
                  "Tissues",
                ],
                correct: 2,
                explanation: "Relation between organisms and their environment is the correct answer.",
              },
              {
                question: "Professor Amartya Sen is famous in which of the fields?",
                options: [
                  "Biochemistry",
                  "Electronics",
                  "Economics",
                  "Geology",
                ],
                correct: 2,
                explanation: "Economics is the correct answer.",
              },
              {
                question: "How many years/months is the tenure of the Chief Official Language Officer?",
                options: [
                  "1 Year",
                  "2 Years",
                  "3 Years",
                  "6 Months",
                ],
                correct: 0,
                explanation: "1 Year is the correct answer.",
              },
              {
                question: "Which of the following is an east flowing river of the Peninsula?",
                options: [
                  "Tapi",
                  "Narmada",
                  "Mahanadi",
                  "None of the given options",
                ],
                correct: 2,
                explanation: "Mahanadi is the correct answer.",
              },
              {
                question: "Which Zone is the largest railway zone in India?",
                options: [
                  "Central Railway",
                  "Northern Railway",
                  "Eastern Railway",
                  "Western Railway",
                ],
                correct: 1,
                explanation: "Northern Railway is the correct answer.",
              },
              {
                question: "Under the Hindi Dictation Award Scheme, what is the amount of award fixed for the officers of 'C' region?",
                options: [
                  "Rs. 4000",
                  "Rs. 1000",
                  "Rs. 2000",
                  "Rs. 5000",
                ],
                correct: 3,
                explanation: "Rs. 5000 is the correct answer.",
              },
              {
                question: "The highest civilian award of India 'Bharat Ratna' has been awarded to only two foreigners so far. One of them is Nelson Mandela. The other is?",
                options: [
                  "Abdul Ghaffar Khan",
                  "Mikhail Gorbachev",
                  "Marshal Tito",
                  "Abdul Wali Khan",
                ],
                correct: 0,
                explanation: "Abdul Ghaffar Khan is the correct answer.",
              },
              {
                question: "Where are the days and nights of equal length all year long?",
                options: [
                  "At 66.5 degree",
                  "No where",
                  "At 23.5 degree",
                  "At the Equator",
                ],
                correct: 3,
                explanation: "At the Equator is the correct answer.",
              },
              {
                question: "In which year the practice of presenting the railway budget separate from the general budget (or vice versa in true sense) started in India?",
                options: [
                  "1920",
                  "1924",
                  "1925",
                  "1930",
                ],
                correct: 1,
                explanation: "1924 is the correct answer.",
              },
              {
                question: "For the cause of national liberation Swami Dayanand stressed on?",
                options: [
                  "Swabhasha and Swarajya",
                  "Swadharma",
                  "Swadeshi",
                  "All of the given options",
                ],
                correct: 3,
                explanation: "All of the given options is the correct answer.",
              },
              {
                question: "Which act was passed to legalize the assurances given to the residents of non-Hindi speaking areas?",
                options: [
                  "Act 1963",
                  "Act 1976",
                  "Act 1967 (Amended)",
                  "Act 1965",
                ],
                correct: 2,
                explanation: "Act 1967 (Amended) is the correct answer.",
              },
              {
                question: "Particulate pollutants are?",
                options: [
                  "Small solid particles and liquid droplets",
                  "Liquid droplets in atmosphere",
                  "Small solid particles released into the atmosphere",
                  "All of the given options",
                ],
                correct: 0,
                explanation: "Small solid particles and liquid droplets is the correct answer.",
              },
              {
                question: "Who was the first Governor General of the new Indian Dominion?",
                options: [
                  "Dr. Rajendra Prasad",
                  "Sardar Vallabhbhai Patel",
                  "Shri Rajagopalachari",
                  "Lord Mountbatten",
                ],
                correct: 3,
                explanation: "Lord Mountbatten is the correct answer.",
              },
              {
                question: "Who qualifies as an employee proficient in Hindi?",
                options: [
                  "Knowledge of Hindi at primary level",
                  "Passed Primary Level Exam in Hindi Medium",
                  "Knowledge of Hindi at matriculation level",
                  "Matriculation Level Exam Passed in Hindi Medium",
                ],
                correct: 3,
                explanation: "Matriculation Level Exam Passed in Hindi Medium is the correct answer.",
              },
              {
                question: "How many sub-committees are there in the Committee of Parliament on Official Language?",
                options: [
                  "1",
                  "2",
                  "3",
                  "4",
                ],
                correct: 2,
                explanation: "3 is the correct answer.",
              },
              {
                question: "Who was admired as tempestuous Hindu in 1893 in the World Parliament of Religions in Chicago?",
                options: [
                  "Swami Dayanand Saraswati",
                  "Rabindra Nath Tagore",
                  "Gautam Budha",
                  "Swami Vivekanand",
                ],
                correct: 3,
                explanation: "Swami Vivekanand is the correct answer.",
              },
              {
                question: "What is the education system of Central Government for Hindi courses?",
                options: [
                  "Regular",
                  "Intensive",
                  "Correspondence",
                  "All the given options",
                ],
                correct: 3,
                explanation: "All the given options is the correct answer.",
              },
              {
                question: "Which one of the following states receives the highest rainfall during winter months?",
                options: [
                  "Punjab",
                  "Kerala",
                  "Meghalaya",
                  "Tamil Nadu",
                ],
                correct: 3,
                explanation: "Tamil Nadu is the correct answer.",
              },
              {
                question: "India's longest tunnel Jawahar tunnel is located in which state?",
                options: [
                  "Jammu and Kashmir",
                  "Maharashtra",
                  "Karnataka",
                  "Himachal Pradesh",
                ],
                correct: 0,
                explanation: "Jammu and Kashmir is the correct answer.",
              },
              {
                question: "Who is the first Asian Winner of Nobel Prize?",
                options: [
                  "C.V. Raman",
                  "Rajiv Gandhi",
                  "Rabindranath Tagore",
                  "Mother Teresa",
                ],
                correct: 2,
                explanation: "Rabindranath Tagore is the correct answer.",
              },
              {
                question: "In which year did the Constituent Assembly accept Hindi as the official language of independent India?",
                options: [
                  "26th January, 1950",
                  "15th August, 1947",
                  "9th August, 1942",
                  "14th September, 1949",
                ],
                correct: 3,
                explanation: "14th September, 1949 is the correct answer.",
              },
              {
                question: "Which of the following is used in pencils?",
                options: [
                  "Graphite",
                  "Silicon",
                  "Charcoal",
                  "Phosphorous",
                ],
                correct: 0,
                explanation: "Graphite is the correct answer.",
              },
              {
                question: "In which order the name board, designation board and information board are expected to be displayed in non-Hindi speaking states?",
                options: [
                  "Hindi Language, English Language, Regional Language",
                  "Regional Language, Hindi Language, English Language",
                  "Regional Language, English Language, Hindi Language",
                  "English Language, Regional Language, Hindi Language",
                ],
                correct: 1,
                explanation: "Regional Language, Hindi Language, English Language is the correct answer.",
              },
              {
                question: "The hardest substance available on earth is?",
                options: [
                  "Gold",
                  "Iron",
                  "Diamond",
                  "Platinum",
                ],
                correct: 2,
                explanation: "Diamond is the correct answer.",
              },
              {
                question: "The one-horned Rhinoceros is now restricted to which state?",
                options: [
                  "Maharashtra",
                  "Gujarat",
                  "Assam",
                  "Uttar Pradesh",
                ],
                correct: 2,
                explanation: "Assam is the correct answer.",
              },
              {
                question: "Who is the first Indian woman to win an Asian Games gold in 400m run?",
                options: [
                  "M.L. Valsamma",
                  "P.T. Usha",
                  "Kamaljit Sandhu",
                  "K. Malleshwari",
                ],
                correct: 2,
                explanation: "Kamaljit Sandhu is the correct answer.",
              },
              {
                question: "Which of the following sea ports is nearest to Rourkela Steel Plant?",
                options: [
                  "Haldia",
                  "Vishakhapatnam",
                  "Kandla",
                  "Paradip",
                ],
                correct: 3,
                explanation: "Paradip is the correct answer.",
              },
              {
                question: "The Frontier Gandhi actively participated in?",
                options: [
                  "Khilafat Movement",
                  "Non-Cooperation Movement",
                  "Civil Disobedience Movement",
                  "All of the given options",
                ],
                correct: 2,
                explanation: "Civil Disobedience Movement is the correct answer.",
              },
              {
                question: "Which of these languages is not written in Devanagari script?",
                options: [
                  "Hindi",
                  "Sanskrit",
                  "Gujarati",
                  "Marathi",
                ],
                correct: 2,
                explanation: "Gujarati is the correct answer.",
              },
              {
                question: "Pitt's India Act brought the company in direct subordination to a body representing?",
                options: [
                  "The Parliament of Britain",
                  "The English Merchants in India",
                  "The Indian Merchants",
                  "Princely States",
                ],
                correct: 0,
                explanation: "The Parliament of Britain is the correct answer.",
              },
              {
                question: "Reappropriation of funds from one itemised work to another itemised work is within the powers of?",
                options: [
                  "DRM",
                  "PHOD",
                  "GM",
                  "Railway Board",
                ],
                correct: 2,
                explanation: "GM is the correct answer.",
              },
              {
                question: "Which of the following is NOT a Reserve Fund of Indian Railways as in 2019-20?",
                options: [
                  "Capital Fund",
                  "Development Fund",
                  "Revenue Reserve Fund",
                  "RRSK",
                ],
                correct: 2,
                explanation: "Revenue Reserve Fund is the correct answer.",
              },
              {
                question: "Identify the autonomous bodies / authorities of IR out of the following options?",
                options: [
                  "CONCOR and DFCCIL",
                  "RITES and RVNL",
                  "CORE and IRFC",
                  "CRIS and RLDA",
                ],
                correct: 3,
                explanation: "CRIS and RLDA is the correct answer.",
              },
              {
                question: "Which is the most sanctioned leave for maximum 05 years?",
                options: [
                  "Study leave",
                  "Extra ordinary leave",
                  "Paternity leave",
                  "Maternity leave",
                ],
                correct: 1,
                explanation: "Extra ordinary leave is the correct answer.",
              },
              {
                question: "If the employee who opts for his salary fixation after 1 month from the date of promotion, then who is capable of waiving the option delay to refix his salary?",
                options: [
                  "No one",
                  "DRM",
                  "GM",
                  "Railway Board",
                ],
                correct: 0,
                explanation: "No one is the correct answer.",
              },
              {
                question: "Under which rule of Railway Service Conduct Rules is movable and immovable property mentioned?",
                options: [
                  "Rule-18",
                  "Rule-17",
                  "Rule-19",
                  "Rule-22A",
                ],
                correct: 0,
                explanation: "Rule-18 is the correct answer.",
              },
              {
                question: "What percentage of vacancies is reserved for ex-servicemen for the release of Group C?",
                options: [
                  "10%",
                  "15%",
                  "03%",
                  "02%",
                ],
                correct: 0,
                explanation: "10% is the correct answer.",
              },
              {
                question: "Railway Servants with not less than ……… years of service shall be eligible for assistance for the education of their children?",
                options: [
                  "01 Year",
                  "02 Years",
                  "03 Years",
                  "04 Years",
                ],
                correct: 2,
                explanation: "03 Years is the correct answer.",
              },
              {
                question: "What is the condition to be accepted by the applicant in case of own request transfer?",
                options: [
                  "Recruitment Grade",
                  "Bottom Seniority",
                  "Recruitment Grade & Bottom Seniority",
                  "None of the given options",
                ],
                correct: 2,
                explanation: "Recruitment Grade & Bottom Seniority is the correct answer.",
              },
              {
                question: "Sanction to the estimate is considered as ‘Technical sanction’ in case of?",
                options: [
                  "Abstract Estimate",
                  "Detailed Estimate",
                  "Revised Estimate",
                  "Completion Estimate",
                ],
                correct: 1,
                explanation: "Detailed Estimate is the correct answer.",
              },
              {
                question: "How much percentage of SC/ST candidates are reserved while recruitment?",
                options: [
                  "15% and 7.5% respectively",
                  "7.5% & 15% respectively",
                  "5% & 10% respectively",
                  "10% & 5% respectively",
                ],
                correct: 0,
                explanation: "15% and 7.5% respectively is the correct answer.",
              },
              {
                question: "Minimum notice period for quotations?",
                options: [
                  "7 days",
                  "10 days",
                  "12 days",
                  "None of the given options",
                ],
                correct: 0,
                explanation: "7 days is the correct answer.",
              },
              {
                question: "Cost of training is booked to Demand No. 12?",
                options: [
                  "True",
                  "False",
                  "Partly True",
                  "None of the given options",
                ],
                correct: 0,
                explanation: "True is the correct answer.",
              },
              {
                question: "How many sections are covered under RTI Act?",
                options: [
                  "31 sections",
                  "20 sections",
                  "40 sections",
                  "30 sections",
                ],
                correct: 0,
                explanation: "31 sections is the correct answer.",
              },
              {
                question: "The Disaster Recovery Site for IPAS is being planned at?",
                options: [
                  "Hyderabad",
                  "Mysore",
                  "Mumbai",
                  "Secunderabad",
                ],
                correct: 3,
                explanation: "Secunderabad is the correct answer.",
              },
              {
                question: "For monitoring of high value projects of all Government departments including IR through MOSPI, the following two systems are in place?",
                options: [
                  "UMID and SUVIDHA",
                  "OCMS and IPMD",
                  "eSAMIKSHA and ARPAN",
                  "CSP and PRAGATI",
                ],
                correct: 1,
                explanation: "OCMS and IPMD is the correct answer.",
              },
              {
                question: "Seniority is not affected due to transfer on Administrative grounds?",
                options: [
                  "True",
                  "False",
                  "Partly True",
                  "None of the given options",
                ],
                correct: 0,
                explanation: "True is the correct answer.",
              },
              {
                question: "Period for appeal under DAR rules is …. Days?",
                options: [
                  "45 days",
                  "30 days",
                  "15 days",
                  "35 days",
                ],
                correct: 0,
                explanation: "45 days is the correct answer.",
              },
              {
                question: "Retiring employee has to complete .... length of service for the issue of RELHS card (medical facilities)?",
                options: [
                  "33 years",
                  "10 years",
                  "20 years",
                  "None of the given options",
                ],
                correct: 3,
                explanation: "None of the given options is the correct answer.",
              },
              {
                question: "Expenditure under Staff Welfare & Amenities shall be charged to….?",
                options: [
                  "Demand No. 9",
                  "Demand No. 11",
                  "Demand No. 8",
                  "Demand No. 10",
                ],
                correct: 1,
                explanation: "Demand No. 11 is the correct answer.",
              },
              {
                question: "Members in selection board should be atleast?",
                options: [
                  "03",
                  "05",
                  "02",
                  "04",
                ],
                correct: 0,
                explanation: "03 is the correct answer.",
              },
              {
                question: "Railway Budget was merged with General Budget from which Financial Year?",
                options: [
                  "2017-18",
                  "2016-17",
                  "2015-16",
                  "None of the given options",
                ],
                correct: 0,
                explanation: "2017-18 is the correct answer.",
              },
              {
                question: "The following is not shown in the Balance Sheet?",
                options: [
                  "Fixed deposit",
                  "Opening stock",
                  "Mortgage on land",
                  "Bank overdraft",
                ],
                correct: 2,
                explanation: "Mortgage on land is the correct answer.",
              },
              {
                question: "For better monitoring of big Railway projects, they have been categorized as?",
                options: [
                  "Super critical, critical and throughput enhancement projects",
                  "High speed, safety and heavy haul projects",
                  "Projects with Rs.500 crores each and Rs.1000 crore each",
                  "Out of turn projects, Urgency based projects and Safety works projects",
                ],
                correct: 0,
                explanation: "Super critical, critical and throughput enhancement projects is the correct answer.",
              },
              {
                question: "Validity of half set Complimentary Pass is ….. Months?",
                options: [
                  "05 months",
                  "04 months",
                  "03 months",
                  "06 months",
                ],
                correct: 0,
                explanation: "05 months is the correct answer.",
              },
              {
                question: "Who is the supreme disciplinary authority?",
                options: [
                  "President of India",
                  "Chief Minister",
                  "Prime Minister of India",
                  "Chief Justice of India",
                ],
                correct: 0,
                explanation: "President of India is the correct answer.",
              },
              {
                question: "Hiding original data with modified content to protect sensitive personal or commercial data is?",
                options: [
                  "Data Encapsulation",
                  "Information Hiding",
                  "Data Masking",
                  "Data Sanitization",
                ],
                correct: 2,
                explanation: "Data Masking is the correct answer.",
              },
              {
                question: "All of the following items are classified as fundamental accounting assumptions except?",
                options: [
                  "Consistency",
                  "Business Entity",
                  "Going concern",
                  "Accrual",
                ],
                correct: 1,
                explanation: "Business Entity is the correct answer.",
              },
              {
                question: "Monetary limit of direct acceptance without Tender committee in open e-tendering?",
                options: [
                  "Up to Rs. 20 lakhs",
                  "Up to Rs. 50 lakhs",
                  "Up to Rs. 1 crore",
                  "None of the given options",
                ],
                correct: 1,
                explanation: "Up to Rs. 50 lakhs is the correct answer.",
              },
              {
                question: "How much employee contribution goes to NPS?",
                options: [
                  "10% of Basic Pay+DA",
                  "20%+DA",
                  "14%+DA",
                  "15%+DA",
                ],
                correct: 0,
                explanation: "10% of Basic Pay+DA is the correct answer.",
              },
              {
                question: "In case of death of Group A & B officers after completion of 20 years of service, how many sets of passes per year is permissible to the widow?",
                options: [
                  "One & Half set per year",
                  "02 sets",
                  "04 sets",
                  "01 set",
                ],
                correct: 0,
                explanation: "One & Half set per year is the correct answer.",
              },
              {
                question: "Total HLAP credited for six months working?",
                options: [
                  "10 Days",
                  "15 Days",
                  "20 Days",
                  "30 Days",
                ],
                correct: 0,
                explanation: "10 Days is the correct answer.",
              },
              {
                question: "The Railway Service (Conduct) Rule 1966, Rule 3A is related to?",
                options: [
                  "Taking part in politics",
                  "Promptness and courtesy",
                  "Observance of Govt. Policies",
                  "None of the given options",
                ],
                correct: 1,
                explanation: "Promptness and courtesy is the correct answer.",
              },
              {
                question: "Railway quarter can be retained for …. on normal rent on transfer?",
                options: [
                  "01 month",
                  "02 months",
                  "03 months",
                  "04 months",
                ],
                correct: 1,
                explanation: "02 months is the correct answer.",
              },
              {
                question: "All types of fines are deposited in which fund?",
                options: [
                  "Staff Benefit Fund",
                  "Revenue Reserve Fund",
                  "Railway Pension Fund",
                  "Development Fund",
                ],
                correct: 0,
                explanation: "Staff Benefit Fund is the correct answer.",
              },
      ],
  },
};