const QUIZ_TITLES: Record<string, string> = {
  'aom-previous-paper-2022': 'AOM Previous Paper 2022',
  'aom-previous-papers-2026': 'AOM Previous Papers 2026',
  'professional-subject': 'AOM Previous Papers 2026 — Professional Subject',
  'aom-professional-subject-test-01': 'AOM Professional Subject Test 01',
  'aom-professional-subject-test-02': 'AOM Professional Subject Test 02',
  'aom-professional-subject-test-03': 'AOM Professional Subject Test 03',
  'aom-professional-subject-test-04': 'AOM Professional Subject Test 04',
  'aom-professional-subject-test-05': 'AOM Professional Subject Test 05',
  'aom-professional-subject-test-06': 'AOM Professional Subject Test 06',
  'aom-finance-establishment-rules-test-01': 'AOM Finance & Establishment Rules Test 01',
  'aom-finance-establishment-rules-test-02': 'AOM Finance & Establishment Rules Test 02',
  'gk-rajabhasha': 'AOM Previous Papers 2026 — GK & Rajabhasha',
  'establishment-finance-rules': 'AOM Previous Papers 2026 — Establishment & Financial Rules',
  'accident-manual': 'Accident Manual',
  'accident-manual:chapter-1': 'Accident Manual Chapter 1',
  'accident-manual:chapter-2': 'Accident Manual Chapter 2',
  'accident-manual:chapter-3': 'Accident Manual Chapter 3',
  'accident-manual:chapter-4': 'Accident Manual Chapter 4',
  'accident-manual:chapter-5': 'Accident Manual Chapter 5',
  'accident-manual:chapter-6': 'Accident Manual Chapter 6',
  'accident-manual:chapter-7': 'Accident Manual Chapter 7',
  'accident-manual:chapter-8': 'Accident Manual Chapter 8',
  'accident-manual:chapter-9': 'Accident Manual Chapter 9',
  'accident-manual:AM Appendix V': 'Accident Manual Appendix V',
  'chapter-1': 'Accident Manual Chapter 1',
  'chapter-2': 'Accident Manual Chapter 2',
  'chapter-3': 'Accident Manual Chapter 3',
  'chapter-4': 'Accident Manual Chapter 4',
  'chapter-5': 'Accident Manual Chapter 5',
  'chapter-6': 'Accident Manual Chapter 6',
  'chapter-7': 'Accident Manual Chapter 7',
  'chapter-8': 'Accident Manual Chapter 8',
  'chapter-9': 'Accident Manual Chapter 9',
  'AM Appendix V': 'Accident Manual Appendix V',
  'block-working-manual': 'Block Working Manual',
  'block-working-manual:chapter-1': 'Block Working Manual Chapter 1',
  'block-working-manual:chapter-2': 'Block Working Manual Chapter 2',
  'commercial-department': 'Commercial Department',
  'commercial-department:chapter-1': 'Commercial Department Chapter 1',
  'commercial-department:chapter-2': 'Commercial Department Chapter 2',
  'disaster-management': 'Disaster Management',
  'disaster-management:chapter-1': 'Disaster Management Chapter 1',
  'disaster-management:chapter-2': 'Disaster Management Chapter 2',
  'disaster-management:chapter-3': 'Disaster Management Chapter 3',
  'disaster-management:chapter-4': 'Disaster Management Chapter 4',
  'disaster-management:chapter-5': 'Disaster Management Chapter 5',
  'disaster-management:chapter-6': 'Disaster Management Chapter 6',
  'disaster-management:chapter-7': 'Disaster Management Chapter 7',
  'disaster-management:chapter-8': 'Disaster Management Chapter 8',
  'disaster-management:chapter-9': 'Disaster Management Chapter 9',
  'disaster-management:chapter-10': 'Disaster Management Chapter 10',
  'disaster-management:chapter-11': 'Disaster Management Chapter 11',
  'disaster-management:chapter-12': 'Disaster Management Chapter 12',
  'disaster-management:chapter-13': 'Disaster Management Chapter 13',
  'general-subsidiary-rules': 'General & Subsidiary Rules',
  'general-subsidiary-rules:chapter-1': 'General & Subsidiary Rules Chapter 1',
  'general-subsidiary-rules:chapter-2': 'General & Subsidiary Rules Chapter 2',
  'general-subsidiary-rules:chapter-3': 'General & Subsidiary Rules Chapter 3',
  'general-subsidiary-rules:chapter-4': 'General & Subsidiary Rules Chapter 4',
  'general-subsidiary-rules:chapter-5': 'General & Subsidiary Rules Chapter 5',
  'general-subsidiary-rules:chapter-6': 'General & Subsidiary Rules Chapter 6',
  'general-subsidiary-rules:chapter-7': 'General & Subsidiary Rules Chapter 7',
  'general-subsidiary-rules:chapter-8': 'General & Subsidiary Rules Chapter 8',
  'general-subsidiary-rules:chapter-9': 'General & Subsidiary Rules Chapter 9',
  'general-subsidiary-rules:chapter-10': 'General & Subsidiary Rules Chapter 10',
  'general-subsidiary-rules:chapter-11': 'General & Subsidiary Rules Chapter 11',
  'general-subsidiary-rules:chapter-12': 'General & Subsidiary Rules Chapter 12',
  'general-subsidiary-rules:chapter-13': 'General & Subsidiary Rules Chapter 13',
  'general-subsidiary-rules:chapter-14': 'General & Subsidiary Rules Chapter 14',
  'general-subsidiary-rules:chapter-15': 'General & Subsidiary Rules Chapter 15',
  'general-subsidiary-rules:chapter-16': 'General & Subsidiary Rules Chapter 16',
  apar: 'Annual Performance Appraisal Report (APAR)',
  'annual-performance-appraisal-report': 'Annual Performance Appraisal Report (APAR)',
  cga: 'Compassionate Grounds Appointment (CGA)',
  'compassionate-grounds-appointment': 'Compassionate Grounds Appointment (CGA)',
  'conduct-rules': 'Railway Servants (Conduct) Rules 1966',
  cpc: 'Central Pay Commission (CPC)',
  'central-pay-commission': 'Central Pay Commission (CPC)',
  'centralised-public-grievance-redress-monitoring-system':
    'Centralised Public Grievance Redress Monitoring System',
  'discipline-appeal-rules': 'Railway Servants (Discipline & Appeal) Rules 1968',
  'railway-servants-discipline-appeal-rules-1968':
    'Railway Servants (Discipline & Appeal) Rules 1968',
  'employees-compensation-act-1923': 'Employees Compensation Act 1923',
  'indian-railway-establishment-code': 'Indian Railway Establishment Code',
  'indian-railway-establishment-manual': 'Indian Railway Establishment Manual',
  'modified-assured-career-progression': 'Modified Assured Career Progression',
  'permanent-negotiating-machinery': 'Permanent Negotiating Machinery',
  'railway-allowances': 'Railway Allowances',
  'railway-online-services': 'Railway Online Services',
  'railway-quarters': 'Railway Quarters',
  'railway-recruitment-posting-promotion': 'Railway Recruitment Posting Promotion',
  'railway-services-pension-rules-1993': 'Railway Services Pension Rules 1993',
  'staff-benefit-fund': 'Staff Benefit Fund',
  'trade-union-act-1926': 'Trade Union Act 1926',
  hrms: 'Human Resource Management System (HRMS)',
  'human-resource-management-system': 'Human Resource Management System (HRMS)',
  'leave-rules': 'Railway Servants (Leave) Rules 1949',
  'railway-servants-leave-rules-1949': 'Railway Servants (Leave) Rules 1949',
  lhb: 'Linke Hofmann Busch (LHB)',
  'linke-holfmann-busch': 'Linke Hofmann Busch (LHB)',
  miscelaneous: 'Miscellaneous',
  nps: 'National Pension System (NPS)',
  'national-pension-system': 'National Pension System (NPS)',
  ops: 'Old Pension Scheme (OPS)',
  'old-pension-system': 'Old Pension Scheme (OPS)',
  'pass-rules': 'Railway Servants (Pass) Rules 1986',
  'railway-servants-pass-rules-1986': 'Railway Servants (Pass) Rules 1986',
  'rest-rules': 'Railway Servants (Rest) Rules 2005',
  'railway-servants-rest-rules-2005': 'Railway Servants (Rest) Rules 2005',
  'railway-services-conduct-rules-1966': 'Railway Servants (Conduct) Rules 1966',
  'rti-act-2005': 'Right to Information Act 2005',
  'right-to-information-act-2005': 'Right to Information Act 2005',
  ups: 'Unified Pension System (UPS)',
  'unified-pension-system': 'Unified Pension System (UPS)',
  accounts: 'Accounts',
  finance: 'Finance',
  tenders: 'Tenders',
  kavach: 'Kavach',
  'kavach:kavach': 'Kavach',
  'operating-department': 'Operating Department',
  'operating-department:chapter-1': 'Operating Department Chapter 1',
  'operating-department:chapter-2': 'Operating Department Chapter 2',
  'operating-department:chapter-3': 'Operating Department Chapter 3',
  'operating-department:chapter-4': 'Operating Department Chapter 4',
  'operating-department:chapter-5': 'Operating Department Chapter 5',
  'operating-department:chapter-6': 'Operating Department Chapter 6',
  'operating-department:chapter-7': 'Operating Department Chapter 7',
  'operating-department:chapter-8': 'Operating Department Chapter 8',
  'operating-manual': 'Operating Manual',
  'operating-manual:chapter-1': 'Operating Manual Chapter 1',
  'operating-manual:chapter-2': 'Operating Manual Chapter 2',
  'operating-manual:chapter-3': 'Operating Manual Chapter 3',
  'operating-manual:chapter-4': 'Operating Manual Chapter 4',
  'operating-manual:chapter-5': 'Operating Manual Chapter 5',
  'operating-manual:chapter-6': 'Operating Manual Chapter 6',
  'operating-manual:chapter-7': 'Operating Manual Chapter 7',
  'operating-manual:chapter-8': 'Operating Manual Chapter 8',
  'operating-manual:chapter-9': 'Operating Manual Chapter 9',
  'operating-manual:chapter-10': 'Operating Manual Chapter 10',
  'operating-manual:chapter-11': 'Operating Manual Chapter 11',
  'operating-manual:chapter-12': 'Operating Manual Chapter 12',
  'operating-manual:chapter-13': 'Operating Manual Chapter 13',
  'operating-manual:chapter-14': 'Operating Manual Chapter 14',
  'operating-manual:chapter-15': 'Operating Manual Chapter 15',
  'operating-manual:chapter-16': 'Operating Manual Chapter 16',
  'operating-manual:chapter-17': 'Operating Manual Chapter 17',
  'operating-manual:chapter-18': 'Operating Manual Chapter 18',
  'operating-manual:chapter-19': 'Operating Manual Chapter 19',
  'operating-manual:chapter-20': 'Operating Manual Chapter 20',
  'operating-manual:chapter-21': 'Operating Manual Chapter 21',
  'operating-manual:chapter-22': 'Operating Manual Chapter 22',
  'operating-manual:chapter-23': 'Operating Manual Chapter 23',
  'operating-manual:chapter-24': 'Operating Manual Chapter 24',
  'operating-manual:chapter-25': 'Operating Manual Chapter 25',
  'railway-gk': 'Railway GK',
  'railway-gk:chapter-1': 'Railway GK Chapter 1',
  'railway-gk:chapter-2': 'Railway GK Chapter 2',
  'railway-gk:chapter-3': 'Railway GK Chapter 3',
  'railway-gk:chapter-4': 'Railway GK Chapter 4',
  'railway-gk:chapter-5': 'Railway GK Chapter 5',
  'railway-gk:chapter-6': 'Railway GK Chapter 6',
  'railway-gk:chapter-7': 'Railway GK Chapter 7',
  'railway-statistics': 'Railway Statistics',
  'railway-statistics:chapter-1': 'Railway Statistics Chapter 1',
  'railway-statistics:chapter-2': 'Railway Statistics Chapter 2',
  'national-rail-plan': 'National Rail Plan',
  'national-rail-plan:chapter-1': 'National Rail Plan Chapter 1',
  'national-rail-plan:chapter-2': 'National Rail Plan Chapter 2',
  rajabhasha: 'Rajabhasha',
  'rajabhasha:chapter-1': 'Rajabhasha Chapter 1',
  'rajabhasha:chapter-2': 'Rajabhasha Chapter 2',
  'rajabhasha:chapter-3': 'Rajabhasha Chapter 3',
  'rajabhasha:chapter-4': 'Rajabhasha Chapter 4',
  'general-awareness-art-culture': 'Art & Culture',
  'general-awareness-biology': 'Biology',
  'general-awareness-botany': 'Botany',
  'general-awareness-chemistry': 'Chemistry',
  'general-awareness-current-affairs': 'Current Affairs',
  'general-awareness-geography': 'Geography',
  'general-awareness-history': 'History',
  'general-awareness-physics': 'Physics',
  'general-awareness-polity': 'Indian Polity',
  'general-awareness-zoology': 'Zoology',
  'general-awareness-art-culture:quiz-1': 'Art & Culture — Quiz 1',
  'general-awareness-art-culture:quiz-2': 'Art & Culture — Quiz 2',
  'general-awareness-biology:quiz-1': 'Biology — Quiz 1',
  'general-awareness-biology:quiz-2': 'Biology — Quiz 2',
  'general-awareness-botany:quiz-1': 'Botany — Quiz 1',
  'general-awareness-botany:quiz-2': 'Botany — Quiz 2',
  'general-awareness-chemistry:quiz-1': 'Chemistry — Quiz 1',
  'general-awareness-chemistry:quiz-2': 'Chemistry — Quiz 2',
  'general-awareness-current-affairs:quiz-1': 'Current Affairs — Quiz 1',
  'general-awareness-geography:quiz-1': 'Geography — Quiz 1',
  'general-awareness-geography:quiz-2': 'Geography — Quiz 2',
  'general-awareness-history:quiz-1': 'History — Quiz 1',
  'general-awareness-history:quiz-2': 'History — Quiz 2',
  'general-awareness-history:quiz-3': 'History — Quiz 3',
  'general-awareness-history:quiz-4': 'History — Quiz 4',
  'general-awareness-history:quiz-5': 'History — Quiz 5',
  'general-awareness-history:quiz-6': 'History — Quiz 6',
  'general-awareness-history:quiz-7': 'History — Quiz 7',
  'general-awareness-history:quiz-8': 'History — Quiz 8',
  'general-awareness-history:quiz-9': 'History — Quiz 9',
  'general-awareness-history:quiz-10': 'History — Quiz 10',
  'general-awareness-history:quiz-11': 'History — Quiz 11',
  'general-awareness-history:quiz-12': 'History — Quiz 12',
  'general-awareness-history:quiz-13': 'History — Quiz 13',
  'general-awareness-physics:quiz-1': 'Physics — Quiz 1',
  'general-awareness-physics:quiz-2': 'Physics — Quiz 2',
  'general-awareness-physics:quiz-3': 'Physics — Quiz 3',
  'general-awareness-polity:quiz-1': 'Indian Polity — Quiz 1',
  'general-awareness-polity:quiz-2': 'Indian Polity — Quiz 2',
  'general-awareness-polity:quiz-3': 'Indian Polity — Quiz 3',
  'general-awareness-polity:quiz-4': 'Indian Polity — Quiz 4',
  'general-awareness-polity:quiz-5': 'Indian Polity — Quiz 5',
  'general-awareness-polity:quiz-6': 'Indian Polity — Quiz 6',
  'general-awareness-polity:quiz-7': 'Indian Polity — Quiz 7',
  'general-awareness-polity:quiz-8': 'Indian Polity — Quiz 8',
  'general-awareness-polity:quiz-9': 'Indian Polity — Quiz 9',
  'general-awareness-polity:quiz-10': 'Indian Polity — Quiz 10',
  'general-awareness-zoology:quiz-1': 'Zoology — Quiz 1',
}

export function getQuizTitle(quizId: string, categoryId?: string) {
  if (categoryId && QUIZ_TITLES[`${categoryId}:${quizId}`]) {
    return QUIZ_TITLES[`${categoryId}:${quizId}`]
  }
  if (QUIZ_TITLES[quizId]) return QUIZ_TITLES[quizId]
  if (categoryId && QUIZ_TITLES[categoryId]) return QUIZ_TITLES[categoryId]
  return quizId
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')
}
