export type SearchTopic = {
  href: string
  title: string
  category: string
  parent: string
  keywords: string
}

export const searchTopics: SearchTopic[] = [
  {
    href: "/abbreviations",
    title: "Abbreviations",
    category: "Reference",
    parent: "Reference",
    keywords: "abbreviations Abbreviations",
  },
  {
    href: "/general-awareness/abbreviations",
    title: "Abbreviations",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness abbreviations Abbreviations",
  },
  {
    href: "/manuals/accident-manual",
    title: "Accident Manual",
    category: "Manuals",
    parent: "Manuals",
    keywords: "manuals accident manual Accident Manual",
  },
  {
    href: "/quizzes/accident-manual",
    title: "Accident Manual",
    category: "Quizzes",
    parent: "Quizzes",
    keywords: "quizzes accident manual Accident Manual",
  },
  {
    href: "/pdfs/accident-manual-amendments",
    title: "Accident Manual Amendments",
    category: "PDFs",
    parent: "PDFs",
    keywords: "pdfs accident manual amendments Accident Manual Amendments",
  },
  {
    href: "/quizzes/aom-previous-paper-2022",
    title: "AOM Previous Paper 2022",
    category: "Quizzes",
    parent: "Quizzes",
    keywords:
      "quizzes aom previous paper 2022 AOM Previous Paper 2022 exam practice 175 questions",
  },
  {
    href: "/quizzes/aom-previous-papers",
    title: "AOM Previous Papers",
    category: "Quizzes",
    parent: "Quizzes",
    keywords:
      "quizzes aom previous papers AOM Previous Papers Professional Subject GK Rajabhasha Establishment Financial Rules",
  },
  {
    href: "/quizzes/financial-rules/accounts",
    title: "Accounts",
    category: "Quizzes",
    parent: "Quizzes › Financial Rules",
    keywords: "quizzes financial rules accounts Accounts",
  },
  {
    href: "/acts",
    title: "Acts & Rules",
    category: "Acts & Rules",
    parent: "Acts & Rules",
    keywords: "acts Acts & Rules",
  },
  {
    href: "/topics/operating-material/absolute-block-system",
    title: "Absolute Block System",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material absolute block system Absolute Block System essentials G.R. 8.01 line clear class B station TALQ MAS",
  },
  {
    href: "/topics/operating-material/adequate-distance",
    title: "Adequate Distance",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material adequate distance Adequate Distance block overlap signal overlap G.R. 1.02(2) G.R. 8.01 3.40",
  },
  {
    href: "/topics/operating-material/advanced-starter",
    title: "Advanced Starter",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material advanced starter Advanced Starter LSS ATP MAS IB",
  },
  {
    href: "/general-awareness/world-information/africa-countries",
    title: "African Countries",
    category: "General Awareness",

    parent: "General Awareness › World Information",
    keywords: "general awareness world information africa countries African Countries",
  },
  {
    href: "/general-awareness/states-information/andaman-nicobar",
    title: "Andaman Nicobar",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information andaman nicobar Andaman Nicobar",
  },
  {
    href: "/general-awareness/states-information/andhra-pradesh",
    title: "Andhra Pradesh",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information andhra pradesh Andhra Pradesh",
  },
  {
    href: "/quizzes/establishment-rules/apar",
    title: "APAR",
    category: "Quizzes",
    parent: "Quizzes › Establishment Rules",
    keywords: "quizzes establishment rules apar APAR",
  },
  {
    href: "/topics/apar",
    title: "APAR",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics apar APAR",
  },
  {
    href: "/general-awareness/important-days/april",
    title: "April",
    category: "General Awareness",
    parent: "General Awareness › Important Days",
    keywords: "general awareness important days april April",
  },
  {
    href: "/general-awareness/sports/archery",
    title: "Archery",
    category: "General Awareness",
    parent: "General Awareness › Sports",
    keywords: "general awareness sports archery Archery",
  },
  {
    href: "/general-awareness/states-information/arunachal-pradesh",
    title: "Arunachal Pradesh",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information arunachal pradesh Arunachal Pradesh",
  },
  {
    href: "/general-awareness/world-information/asian-countries",
    title: "Asian Countries",
    category: "General Awareness",
    parent: "General Awareness › World Information",
    keywords: "general awareness world information asian countries Asian Countries",
  },
  {
    href: "/general-awareness/sports/asian-games",
    title: "Asian Games",
    category: "General Awareness",
    parent: "General Awareness › Sports",
    keywords: "general awareness sports asian games Asian Games",
  },
  {
    href: "/general-awareness/states-information/assam",
    title: "Assam",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information assam Assam",
  },
  {
    href: "/general-awareness/important-days/august",
    title: "August",
    category: "General Awareness",
    parent: "General Awareness › Important Days",
    keywords: "general awareness important days august August",
  },
  {
    href: "/general-awareness/world-information/australian-countries",
    title: "Australian Countries",
    category: "General Awareness",
    parent: "General Awareness › World Information",
    keywords: "general awareness world information australian countries Australian Countries",
  },
  {
    href: "/topics/operating-material/authorised-officer",
    title: "Authorised Officer",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material authorised officer Authorised Officer authorized officer PCOM G.R. 1.02",
  },
  {
    href: "/pdfs/authorities",
    title: "Authorities",
    category: "PDFs",
    parent: "PDFs",
    keywords: "pdfs authorities Authorities",
  },
  {
    href: "/topics/operating-material/authority-to-proceed",
    title: "Authority to Proceed",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material authority to proceed Authority to Proceed ATP G.R. 1.02(6)",
  },
  {
    href: "/topics/operating-material/automatic-block-system",
    title: "Automatic Block System",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material automatic block system Automatic Block System semi-automatic T/B.912 T/E.912 TSL LSS defective absolute comparison",
  },
  {
    href: "/general-awareness/awards",
    title: "Awards",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness awards Awards",
  },

  {
    href: "/general-awareness/sports/badminton",
    title: "Badminton",
    category: "General Awareness",
    parent: "General Awareness › Sports",
    keywords: "general awareness sports badminton Badminton",
  },
  {
    href: "/general-awareness/banking-finance",
    title: "Banking Finance",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness banking finance Banking Finance",
  },
  {
    href: "/general-awareness/sports/basket-ball",
    title: "Basket Ball",
    category: "General Awareness",
    parent: "General Awareness › Sports",
    keywords: "general awareness sports basket ball Basket Ball",
  },
  {
    href: "/general-awareness/beauty-pageant",
    title: "Beauty Pageant",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness beauty pageant Beauty Pageant",
  },
  {
    href: "/general-awareness/states-information/bihar",
    title: "Bihar",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information bihar Bihar",
  },
  {
    href: "/general-awareness/biology",
    title: "Biology",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness biology Biology",
  },
  {
    href: "/quizzes/general-awareness/biology",
    title: "Biology",
    category: "Quizzes",
    parent: "Quizzes › General Awareness",
    keywords: "quizzes general awareness biology Biology",
  },
  {
    href: "/general-awareness/biosphere-reserves",
    title: "Biosphere Reserves",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness biosphere reserves Biosphere Reserves",
  },
  {
    href: "/topics/operating-material/block-forward",
    title: "Block Forward",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material block forward Block Forward G.R. 1.02(9) shunting double line",
  },
  {
    href: "/topics/operating-material/block-overlap",
    title: "Block Overlap",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material block overlap Block Overlap FSS MAS BSLB SLB adequate distance",
  },
  {
    href: "/topics/operating-material/block-section",
    title: "Block Section",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material block section Block Section G.R. 1.02(10) line clear",
  },
  {
    href: "/topics/operating-material/block-ticket",
    title: "Block Ticket",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material block ticket Block Ticket S.R. 6.02.5 T/J.602 TSL against traffic",
  },
  {
    href: "/topics/operating-material/block-working",
    title: "Block Working",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material block working Block Working line block power block integrated block shadow block TTM OHE",
  },
  {
    href: "/manuals/block-working-manual",
    title: "Block Working Manual",
    category: "Manuals",
    parent: "Manuals",
    keywords: "manuals block working manual Block Working Manual",
  },

  {
    href: "/quizzes/block-working-manual",
    title: "Block Working Manual",
    category: "Quizzes",
    parent: "Quizzes",
    keywords: "quizzes block working manual Block Working Manual",
  },
  {
    href: "/pdfs/block-working-manual-amendments",
    title: "Block Working Manual Amendments",
    category: "PDFs",
    parent: "PDFs",
    keywords: "pdfs block working manual amendments Block Working Manual Amendments",
  },
  {
    href: "/general-awareness/books-authors",
    title: "Books Authors",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness books authors Books Authors",
  },


  {
    href: "/quizzes/general-awareness/botany",
    title: "Botany",
    category: "Quizzes",
    parent: "Quizzes › General Awareness",
    keywords: "quizzes general awareness botany Botany",
  },
  {
    href: "/topics/operating-material/brake-power-certificate",
    title: "Brake Power Certificate",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material brake power certificate Brake Power Certificate BPC freight CC rake premium end-to-end TXR",
  },
  {
    href: "/topics/operating-material/brake-van",
    title: "Brake Van",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material brake van Brake Van G.R. 4.19.6 S.R. 4.19.4.1 BV equipment OTL SLR",
  },
  {
    href: "/general-awareness/sports/boxing",
    title: "Boxing",
    category: "General Awareness",
    parent: "General Awareness › Sports",
    keywords: "general awareness sports boxing Boxing",
  },
  {
    href: "/topics/cat",
    title: "CAT",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics cat CAT",
  },
  {
    href: "/quizzes/establishment-rules/cga",
    title: "CGA",
    category: "Quizzes",
    parent: "Quizzes › Establishment Rules",
    keywords: "quizzes establishment rules cga CGA",
  },
  {
    href: "/general-awareness/states-information/chandigarh",
    title: "Chandigarh",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information chandigarh Chandigarh",
  },
  {
    href: "/general-awareness/chemistry",
    title: "Chemistry",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness chemistry Chemistry",
  },
  {
    href: "/quizzes/general-awareness/chemistry",
    title: "Chemistry",
    category: "Quizzes",
    parent: "Quizzes › General Awareness",
    keywords: "quizzes general awareness chemistry Chemistry",
  },
  {
    href: "/general-awareness/sports/chess",
    title: "Chess",
    category: "General Awareness",
    parent: "General Awareness › Sports",
    keywords: "general awareness sports chess Chess",
  },
  {
    href: "/general-awareness/states-information/chhattisgarh",
    title: "Chhattisgarh",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information chhattisgarh Chhattisgarh",
  },
  {
    href: "/topics/chief-controller",
    title: "Chief Controller",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics chief controller Chief Controller",
  },
  {
    href: "/topics/operating-material/calling-on-signal",
    title: "Calling On Signal",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material calling on signal Calling On Signal G.R. 3.13 COGGN Podanur VDU",
  },
  {
    href: "/topics/operating-material/catch-slip-siding",
    title: "Catch / Slip Siding",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material catch slip siding Catch Slip Siding G.R. S.R. 3.50",
  },
  {
    href: "/general-awareness/awards/cinema-awards",
    title: "Cinema Awards",
    category: "General Awareness",
    parent: "General Awareness › Awards",
    keywords: "general awareness awards cinema awards Cinema Awards",
  },
  {
    href: "/pdfs/circulars",
    title: "Circulars",
    category: "PDFs",
    parent: "PDFs",
    keywords: "pdfs circulars Circulars",
  },
  {
    href: "/topics/information-technology-apps/cms",
    title: "CMS",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps cms CMS",
  },
  {
    href: "/topics/information-technology-apps/coa",
    title: "COA",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps coa COA",
  },
  {
    href: "/topics/coaches-data",
    title: "Coaches Data",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics coaches data Coaches Data",
  },
  {
    href: "/topics/operating-material/coacting-signal",
    title: "Co-acting Signal",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material co-acting signal Co-acting Signal G.R. 3.15 duplicating",
  },
  {
    href: "/topics/information-technology-apps/cois",
    title: "COIS",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps cois COIS",
  },
  {
    href: "/quizzes/commercial-department",
    title: "Commercial Department",
    category: "Quizzes",
    parent: "Quizzes",
    keywords: "quizzes commercial department Commercial Department",
  },
  {
    href: "/quizzes/disaster-management",
    title: "Disaster Management",
    category: "Quizzes",
    parent: "Quizzes",
    keywords: "quizzes disaster management Disaster Management NDMA DM Act",
  },
  {
    href: "/general-awareness/committees",
    title: "Committees",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness committees Committees",
  },
  {
    href: "/general-awareness/sports/commonwealth-games",
    title: "Commonwealth Games",
    category: "General Awareness",
    parent: "General Awareness › Sports",
    keywords: "general awareness sports commonwealth games Commonwealth Games",
  },
  {
    href: "/quizzes/establishment-rules/conduct-rules",
    title: "Conduct Rules",
    category: "Quizzes",
    parent: "Quizzes › Establishment Rules",
    keywords: "quizzes establishment rules conduct rules Conduct Rules",
  },
  {
    href: "/topics/container-rail-terminals",
    title: "Container Rail Terminals",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics container rail terminals Container Rail Terminals",
  },
  {
    href: "/quizzes/establishment-rules/cpc",
    title: "CPC",
    category: "Quizzes",
    parent: "Quizzes › Establishment Rules",
    keywords: "quizzes establishment rules cpc CPC",
  },
  {
    href: "/general-awareness/sports/cricket",
    title: "Cricket",
    category: "General Awareness",
    parent: "General Awareness › Sports",
    keywords: "general awareness sports cricket Cricket",
  },
  {
    href: "/quizzes/general-awareness/current-affairs",
    title: "Current Affairs",
    category: "Quizzes",
    parent: "Quizzes › General Awareness",
    keywords: "quizzes general awareness current affairs Current Affairs",
  },
  {
    href: "/general-awareness/states-information/dadra-nagar-haveli",
    title: "Dadra Nagar Haveli",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information dadra nagar haveli Dadra Nagar Haveli",
  },
  {
    href: "/general-awareness/states-information/daman-diu",
    title: "Daman Diu",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information daman diu Daman Diu",
  },
  {
    href: "/general-awareness/important-days/december",
    title: "December",
    category: "General Awareness",
    parent: "General Awareness › Important Days",
    keywords: "general awareness important days december December",
  },
  {
    href: "/topics/operating-material/defective-signals",
    title: "Defective Signals",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material defective signals Defective Signals warn danger ahead G.R. 3.65 3.66 3.67",
  },
  {
    href: "/topics/operating-material/defective-vehicles",
    title: "Defective Vehicles",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material defective vehicles Defective Vehicles G.R. 4.29 hot axle hot box",
  },
  {
    href: "/definitions",
    title: "Definitions",
    category: "Reference",
    parent: "Reference",
    keywords: "definitions Definitions",
  },
  {
    href: "/general-awareness/states-information/delhi",
    title: "Delhi",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information delhi Delhi",
  },
  {
    href: "/topics/financial-rules/demands",
    title: "Demands",
    category: "Study Topics",
    parent: "Topics › Financial Rules",
    keywords: "topics financial rules demands Demands",
  },
  {
    href: "/topics/operating-material/despatch-signals",
    title: "Despatch Signals",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material despatch signals Despatch Signals Starter Advanced starter",
  },
  {
    href: "/topics/operating-material/detonating-signals",
    title: "Detonating Signals",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material detonating signals Detonating Signals Detonators",
  },
  {
    href: "/acts/disaster-management-act-2005",
    title: "Disaster Management Act 2005",
    category: "Acts & Rules",
    parent: "Acts",
    keywords: "acts disaster management act 2005 Disaster Management Act 2005",
  },
  {
    href: "/quizzes/establishment-rules/discipline-appeal-rules",
    title: "Discipline Appeal Rules",
    category: "Quizzes",
    parent: "Quizzes › Establishment Rules",
    keywords: "quizzes establishment rules discipline appeal rules Discipline Appeal Rules",
  },
  {
    href: "/topics/operating-material/disconnection-reconnection",
    title: "Disconnection and Reconnection",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material disconnection reconnection Disconnection and Reconnection SR 3.51.6 APP XIII T.351",
  },
  {
    href: "/topics/operating-material/distant-signal",
    title: "Distant Signal",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material distant signal Distant Signal G.R S.R. 3.07 P marker double distant",
  },
  {
    href: "/topics/information-technology-apps/e-drishti",
    title: "e-Drishti",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps e drishti e-Drishti",
  },
  {
    href: "/general-awareness/elephant-reserves",
    title: "Elephant Reserves",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness elephant reserves Elephant Reserves",
  },
  {
    href: "/topics/operating-material/emergency-crank-handle",
    title: "Emergency Crank Handle",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material emergency crank handle Emergency Crank Handle S.R. 3.38.7 App XI-6 HKT",
  },
  {
    href: "/acts/employees-compensation-act-2010",
    title: "Employees Compensation Act 2010",
    category: "Acts & Rules",
    parent: "Acts",
    keywords: "acts employees compensation act 2010 Employees Compensation Act 2010",
  },
  {
    href: "/topics/engine-on-load",
    title: "Engine On Load",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics engine on load Engine On Load",
  },
  {
    href: "/topics/operating-material/engine-pushing",
    title: "Engine Pushing",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material engine pushing Engine Pushing G.R. S.R. 4.12 push back",
  },
  {
    href: "/topics/operating-material/engine-unable-to-haul-the-load",
    title: "Engine Unable to Haul the Load",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material engine unable to haul the load Engine Unable to Haul the Load relief engine push back divided train working T/609 G.R. S.R. 6.09",
  },
  {
    href: "/topics/operating-material/Exchange-of-all-right-signals",
    title: "Exchange of All Right Signals",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material exchange of all right signals Exchange of All Right Signals G.R. 4.42 green flag walkie-talkie Vande Bharat",
  },
  {
    href: "/topics/information-technology-apps/ess",
    title: "ESS",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps ess ESS",
  },
  {
    href: "/quizzes/establishment-rules",
    title: "Establishment Rules",
    category: "Quizzes",
    parent: "Quizzes",
    keywords: "quizzes establishment rules Establishment Rules",
  },
  {
    href: "/topics/establishment-rules",
    title: "Establishment Rules",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics establishment rules Establishment Rules",
  },
  {
    href: "/general-awareness/world-information/europe-countries",
    title: "European Countries",
    category: "General Awareness",
    parent: "General Awareness › World Information",
    keywords: "general awareness world information europe countries European Countries",
  },
  {
    href: "/topics/information-technology-apps/ewss",
    title: "EWSS",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps ewss EWSS",
  },
  {
    href: "/acts/factories-act-1948",
    title: "Factories Act 1948",
    category: "Acts & Rules",
    parent: "Acts",
    keywords: "acts factories act 1948 Factories Act 1948",
  },
  {
    href: "/topics/operating-material/facing-trailing-points",
    title: "Facing and Trailing Points",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material facing trailing points Facing and Trailing Points G.R. 1.02(20)",
  },
  {
    href: "/topics/operating-material/Fire-on-train",
    title: "Fire on Train",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material fire on train Fire on Passenger Coach in Mid-Section G.R. S.R. 6.10 CBC extinguisher",
  },
  {
    href: "/general-awareness/important-days/february",
    title: "February",
    category: "General Awareness",
    parent: "General Awareness › Important Days",
    keywords: "general awareness important days february February",
  },

  {
    href: "/quizzes/financial-rules/finance",
    title: "Finance",
    category: "Quizzes",
    parent: "Quizzes › Financial Rules",
    keywords: "quizzes financial rules finance Finance",
  },
  {
    href: "/quizzes/financial-rules",
    title: "Financial Rules",
    category: "Quizzes",
    parent: "Quizzes",
    keywords: "quizzes financial rules Financial Rules",
  },
  {
    href: "/topics/financial-rules",
    title: "Financial Rules",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics financial rules Financial Rules",
  },
  {
    href: "/topics/operating-material/fixed-signal",
    title: "Fixed Signal",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material fixed signal Fixed Signal G.R. 1.02(21)",
  },
  {
    href: "/topics/operating-material/flare-signals",
    title: "Flare Signals",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material flare signals Flare Signals warning Red flag Red flashing lamp",
  },
  {
    href: "/topics/operating-material/flat-tyre",
    title: "Flat Tyre",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material flat tyre Flat Tyre TXR USFD SR 30 kmph",
  },
  {
    href: "/topics/information-technology-apps/fois",
    title: "FOIS",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps fois FOIS",
  },

  {
    href: "/general-awareness/sports/football",
    title: "Football",
    category: "General Awareness",
    parent: "General Awareness › Sports",
    keywords: "general awareness sports football Football",
  },
  {
    href: "/topics/operating-material/fouling-mark",
    title: "Fouling Mark",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material fouling mark Fouling Mark G.R. 1.02(22)",
  },
  {
    href: "/topics/operating-material/gate-signal",
    title: "Gate Signal",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material gate signal Gate Signal G.R. S.R. 3.34 3.73 LC G marker",
  },
  {
    href: "/topics/gati-shakti-terminals",
    title: "Gati Shakti Terminals",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics gati shakti terminals Gati Shakti Terminals",
  },
  {
    href: "/topics/operating-material/glp-check",
    title: "GLP Check",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material glp check GLP Check Guard Loco Pilot BPC revalidation PME TXR proforma",
  },

  {
    href: "/general-awareness",
    title: "General Awareness",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness General Awareness",
  },
  {
    href: "/quizzes/general-awareness",
    title: "General Awareness",
    category: "Quizzes",
    parent: "Quizzes",
    keywords: "quizzes general awareness General Awareness",
  },
  {
    href: "/topics/general-rules",
    title: "General Rules",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics general rules General Rules GR",
  },
  {
    href: "/manuals/general-subsidiary-rules",
    title: "General Subsidiary Rules",
    category: "Manuals",
    parent: "Manuals",
    keywords: "manuals general subsidiary rules General Subsidiary Rules",
  },
  {
    href: "/quizzes/general-subsidiary-rules",
    title: "General Subsidiary Rules",
    category: "Quizzes",
    parent: "Quizzes",
    keywords: "quizzes general subsidiary rules General Subsidiary Rules",
  },
  {
    href: "/pdfs/general-subsidiary-rules-amendments",
    title: "General Subsidiary Rules Amendments",
    category: "PDFs",
    parent: "PDFs",
    keywords: "pdfs general subsidiary rules amendments General Subsidiary Rules Amendments",
  },
  {
    href: "/general-awareness/geographical-indication",
    title: "Geographical Indication",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness geographical indication Geographical Indication",
  },
  {
    href: "/general-awareness/geography",
    title: "Geography",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness geography Geography",
  },
  {
    href: "/quizzes/general-awareness/geography",
    title: "Geography",
    category: "Quizzes",
    parent: "Quizzes › General Awareness",
    keywords: "quizzes general awareness geography Geography",
  },
  {
    href: "/general-awareness/states-information/goa",
    title: "Goa",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information goa Goa",
  },
  {
    href: "/general-awareness/sports/golf",
    title: "Golf",
    category: "General Awareness",
    parent: "General Awareness › Sports",
    keywords: "general awareness sports golf Golf",
  },
  {
    href: "/topics/government-e-market",
    title: "Government E Market",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics government e market Government E Market",
  },
  {
    href: "/topics/govt-pension",
    title: "Govt Pension",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics govt pension Govt Pension",
  },
  {
    href: "/general-awareness/states-information/gujarat",
    title: "Gujarat",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information gujarat Gujarat",
  },
  {
    href: "/topics/operating-material/hand-signals",
    title: "Hand Signals",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material hand signals Hand Signals flags lamp bare hands",
  },
  {
    href: "/general-awareness/states-information/haryana",
    title: "Haryana",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information haryana Haryana",
  },
  {
    href: "/general-awareness/states-information/himachal-pradesh",
    title: "Himachal Pradesh",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information himachal pradesh Himachal Pradesh",
  },
  {
    href: "/general-awareness/history",
    title: "History",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness history History",
  },
  {
    href: "/quizzes/general-awareness/history",
    title: "History",
    category: "Quizzes",
    parent: "Quizzes › General Awareness",
    keywords: "quizzes general awareness history History",
  },
  {
    href: "/general-awareness/sports/hockey",
    title: "Hockey",
    category: "General Awareness",
    parent: "General Awareness › Sports",
    keywords: "general awareness sports hockey Hockey",
  },
  {
    href: "/",
    title: "Home",
    category: "Home",
    parent: "Home",
    keywords: "Home",
  },
  {
    href: "/topics/operating-material/home-signal",
    title: "Home Signal",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material home signal Home Signal G.R. 3.09 MAS FSS LSS",
  },
  {
    href: "/quizzes/establishment-rules/hrms",
    title: "HRMS",
    category: "Quizzes",
    parent: "Quizzes › Establishment Rules",
    keywords: "quizzes establishment rules hrms HRMS",
  },
  {
    href: "/topics/hrms",
    title: "HRMS",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics hrms HRMS",
  },
  {
    href: "/topics/operating-material/intermediate-block-signal",
    title: "IB Signal",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material IB signal Intermediate Block Signal G.R. S.R. 3.75 14.13 14.14 axle counter",
  },
  {
    href: "/topics/information-technology-apps/icms",
    title: "ICMS",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps icms ICMS",
  },
  {
    href: "/topics/operating-material/integrated-block",
    title: "Integrated Block",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material integrated block Integrated Block caution order 150 mts 15/8 kmph units",
  },
  {
    href: "/general-awareness/important-days",
    title: "Important Days",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness important days Important Days",
  },
  {
    href: "/general-awareness/index-reports",
    title: "Index Reports",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness index reports Index Reports",
  },
  {
    href: "/general-awareness/awards/india-civil-awards",
    title: "India Civil Awards",
    category: "General Awareness",
    parent: "General Awareness › Awards",
    keywords: "general awareness awards india civil awards India Civil Awards",
  },
  {
    href: "/general-awareness/india-information",
    title: "India Information",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness india information India Information",
  },
  {
    href: "/general-awareness/indian-constitution",
    title: "Indian Constitution",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness indian constitution Indian Constitution",
  },
  {
    href: "/general-awareness/awards/indian-gallantary-awards",
    title: "Indian Gallantary Awards",
    category: "General Awareness",
    parent: "General Awareness › Awards",
    keywords: "general awareness awards indian gallantary awards Indian Gallantary Awards",
  },
  {
    href: "/general-awareness/indian-penal-code",
    title: "Indian Penal Code",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness indian penal code Indian Penal Code",
  },
  {
    href: "/acts/indian-railways-act-1989",
    title: "Indian Railways Act 1989",
    category: "Acts & Rules",
    parent: "Acts",
    keywords: "acts indian railways act 1989 Indian Railways Act 1989",
  },
  {
    href: "/manuals/indian-railways-operating-manual",
    title: "Indian Railways Operating Manual",
    category: "Manuals",
    parent: "Manuals",
    keywords: "manuals indian railways operating manual Indian Railways Operating Manual",
  },
  {
    href: "/acts/industrial-disputes-act-1947",
    title: "Industrial Disputes Act 1947",
    category: "Acts & Rules",
    parent: "Acts",
    keywords: "acts industrial disputes act 1947 Industrial Disputes Act 1947",
  },
  {
    href: "/acts/industrial-relations-code-2010",
    title: "Industrial Relations Code 2010",
    category: "Acts & Rules",
    parent: "Acts",
    keywords: "acts industrial relations code 2010 Industrial Relations Code 2010",
  },
  {
    href: "/topics/information-technology-apps",
    title: "Information Technology Apps",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics information technology apps Information Technology Apps",
  },
  {
    href: "/topics/operating-material/interlocking",
    title: "Interlocking",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material interlocking Interlocking G.R. 1.02(29)",
  },
  {
    href: "/general-awareness/international-airports",
    title: "International Airports",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness international airports International Airports",
  },

  {
    href: "/general-awareness/international-organization",
    title: "International Organization",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness international organization International Organization",
  },
  {
    href: "/topics/operating-material/isolation",
    title: "Isolation",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material isolation Isolation G.R. 1.02(32)",
  },
  {
    href: "/topics/irec",
    title: "IREC",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics irec IREC",
  },

  {
    href: "/topics/irem",
    title: "IREM",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics irem IREM",
  },
  {
    href: "/general-awareness/states-information/jammu-kashmir",
    title: "Jammu Kashmir",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information jammu kashmir Jammu Kashmir",
  },
  {
    href: "/general-awareness/important-days/january",
    title: "January",
    category: "General Awareness",
    parent: "General Awareness › Important Days",
    keywords: "general awareness important days january January",
  },
  {
    href: "/general-awareness/states-information/jharkhand",
    title: "Jharkhand",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information jharkhand Jharkhand",
  },
  {
    href: "/topics/joint-consultative-machinery",
    title: "Joint Consultative Machinery",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics joint consultative machinery Joint Consultative Machinery",
  },
  {
    href: "/general-awareness/awards/journalism-awards",
    title: "Journalism Awards",
    category: "General Awareness",
    parent: "General Awareness › Awards",
    keywords: "general awareness awards journalism awards Journalism Awards",
  },
  {
    href: "/general-awareness/important-days/july",
    title: "July",
    category: "General Awareness",
    parent: "General Awareness › Important Days",
    keywords: "general awareness important days july July",
  },
  {
    href: "/general-awareness/important-days/june",
    title: "June",
    category: "General Awareness",
    parent: "General Awareness › Important Days",
    keywords: "general awareness important days june June",
  },
  {
    href: "/general-awareness/states-information/karnataka",
    title: "Karnataka",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information karnataka Karnataka",
  },
  {
    href: "/quizzes/kavach",
    title: "Kavach",
    category: "Quizzes",
    parent: "Quizzes",
    keywords: "quizzes kavach Kavach",
  },
  {
    href: "/topics/operating-material/kavach",
    title: "Kavach",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material kavach Kavach IR-ATP Indian Railway Automatic Train Protection System AS 20",
  },
  {
    href: "/general-awareness/states-information/kerala",
    title: "Kerala",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information kerala Kerala",
  },

  {
    href: "/general-awareness/states-information/lakshadweep",
    title: "Lakshadweep",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information lakshadweep Lakshadweep",
  },
  {
    href: "/quizzes/establishment-rules/leave-rules",
    title: "Leave Rules",
    category: "Quizzes",
    parent: "Quizzes › Establishment Rules",
    keywords: "quizzes establishment rules leave rules Leave Rules",
  },
  {
    href: "/topics/leave-travel-concession",
    title: "Leave Travel Concession",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics leave travel concession Leave Travel Concession",
  },
  {
    href: "/quizzes/establishment-rules/lhb",
    title: "LHB",
    category: "Quizzes",
    parent: "Quizzes › Establishment Rules",
    keywords: "quizzes establishment rules lhb LHB",
  },
  {
    href: "/topics/operating-material/line-block",
    title: "Line Block",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material line block Line Block circular notice field telephone VHF PWI SCOR Category-I Category-II Category-III",
  },
  {
    href: "/topics/operating-material/line-clear",
    title: "Line Clear",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material line clear Line Clear G.R. 1.02(36)",
  },
  {
    href: "/topics/operating-material/loco-pilot-entered-without-atp",
    title: "Loco Pilot Entered Without ATP",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material loco pilot entered without atp Loco Pilot Entered Block Section Without ATP G.R. S.R. 6.06 PLCT",
  },
  {
    href: "/topics/operating-material/lorry",
    title: "Lorry",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material lorry Lorry G.R. S.R. 15.27 T.1518 trolley notice block protection banner flag",
  },
  {
    href: "/topics/operating-material/lurch",
    title: "Lurch",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material lurch Lurch S.R. 6.07 unsafe track conditions running trains flasher",
  },
  {
    href: "/topics/operating-material/material-train",
    title: "Material Train",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material material train Material Train S.R. 4.62 T/462 T/A.462 engineering BPC",
  },
  {
    href: "/topics/operating-material/motor-trolley",
    title: "Motor Trolley",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material motor trolley Motor Trolley G.R. S.R. 15.18 15.25 T/A.1525 T/1525 lorry push trolley",
  },
  {
    href: "/general-awareness/awards/literature-awards",
    title: "Literature Awards",
    category: "General Awareness",
    parent: "General Awareness › Awards",
    keywords: "general awareness awards literature awards Literature Awards",
  },

  {
    href: "/topics/schemes/lwis-scheme",
    title: "LWIS Scheme",
    category: "Study Topics",
    parent: "Topics › Schemes",
    keywords: "topics schemes lwis scheme LWIS Scheme",
  },
  {
    href: "/topics/macp",
    title: "MACP",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics macp MACP",
  },
  {
    href: "/general-awareness/states-information/madhya-pradesh",
    title: "Madhya Pradesh",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information madhya pradesh Madhya Pradesh",
  },
  {
    href: "/general-awareness/states-information/maharashtra",
    title: "Maharashtra",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information maharashtra Maharashtra",
  },
  {
    href: "/general-awareness/maharatna-companies",
    title: "Maharatna Companies",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness maharatna companies Maharatna Companies",
  },
  {
    href: "/topics/financial-rules/major-heads",
    title: "Major Heads",
    category: "Study Topics",
    parent: "Topics › Financial Rules",
    keywords: "topics financial rules major heads Major Heads",
  },
  {
    href: "/general-awareness/states-information/manipur",
    title: "Manipur",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information manipur Manipur",
  },
  {
    href: "/manuals",
    title: "Manuals",
    category: "Manuals",
    parent: "Manuals",
    keywords: "manuals Manuals",
  },
  {
    href: "/general-awareness/important-days/march",
    title: "March",
    category: "General Awareness",
    parent: "General Awareness › Important Days",
    keywords: "general awareness important days march March",
  },
  {
    href: "/topics/master-circulars",
    title: "Master Circulars",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics master circulars Master Circulars",
  },
  {
    href: "/general-awareness/important-days/may",
    title: "May",
    category: "General Awareness",
    parent: "General Awareness › Important Days",
    keywords: "general awareness important days may May",
  },
  {
    href: "/general-awareness/states-information/meghalaya",
    title: "Meghalaya",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information meghalaya Meghalaya",
  },
  {
    href: "/topics/merry-go-round",
    title: "Merry Go Round",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics merry go round Merry Go Round",
  },
  {
    href: "/quizzes/establishment-rules/miscelaneous",
    title: "Miscellaneous",
    category: "Quizzes",
    parent: "Quizzes › Establishment Rules",
    keywords: "quizzes establishment rules miscelaneous Miscellaneous",
  },
  {
    href: "/topics/mission-3000MT",
    title: "Mission 3000 MT",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics mission 3000MT Mission 3000 MT",
  },
  {
    href: "/general-awareness/states-information/mizoram",
    title: "Mizoram",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information mizoram Mizoram",
  },
  {
    href: "/topics/operating-material/multiple-aspect-signalling",
    title: "Multiple Aspect Signalling",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material multiple aspect signalling Multiple Aspect Signalling MAS G.R. 1.02(41)",
  },
  {
    href: "/general-awareness/states-information/nagaland",
    title: "Nagaland",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information nagaland Nagaland",
  },

  {
    href: "/topics/national-logistics-policy",
    title: "National Logistics Policy",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics national logistics policy National Logistics Policy",
  },
  {
    href: "/general-awareness/national-parks",
    title: "National Parks",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness national parks National Parks",
  },
  {
    href: "/topics/national-pension-scheme",
    title: "National Pension Scheme",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics national pension scheme National Pension Scheme",
  },
  {
    href: "/topics/national-rail-plan",
    title: "National Rail Plan",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics national rail plan National Rail Plan",
  },
  {
    href: "/general-awareness/world-information/north-american-countries",
    title: "North American Countries",
    category: "General Awareness",
    parent: "General Awareness › World Information",
    keywords: "general awareness world information north american countries North American Countries",
  },
  {
    href: "/general-awareness/important-days/november",
    title: "November",
    category: "General Awareness",
    parent: "General Awareness › Important Days",
    keywords: "general awareness important days november November",
  },
  {
    href: "/quizzes/establishment-rules/nps",
    title: "NPS",
    category: "Quizzes",
    parent: "Quizzes › Establishment Rules",
    keywords: "quizzes establishment rules nps NPS",
  },
  {
    href: "/topics/information-technology-apps/ntes",
    title: "NTES",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps ntes NTES",
  },
  {
    href: "/topics/operating-material/obstruction",
    title: "Obstruction",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material obstruction Obstruction G.R. 1.02(43)",
  },
  {
    href: "/general-awareness/important-days/october",
    title: "October",
    category: "General Awareness",
    parent: "General Awareness › Important Days",
    keywords: "general awareness important days october October",
  },

  {
    href: "/general-awareness/states-information/odisha",
    title: "Odisha",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information odisha Odisha",
  },
  {
    href: "/acts/official-language-act-1963",
    title: "Official Language Act 1963",
    category: "Acts & Rules",
    parent: "Acts",
    keywords: "acts official language act 1963 Official Language Act 1963",
  },
  {
    href: "/general-awareness/sports/olympic-games",
    title: "Olympic Games",
    category: "General Awareness",
    parent: "General Awareness › Sports",
    keywords: "general awareness sports olympic games Olympic Games",
  },
  {
    href: "/quizzes/operating-department",
    title: "Operating Department",
    category: "Quizzes",
    parent: "Quizzes",
    keywords: "quizzes operating department Operating Department",
  },
  {
    href: "/manuals/opertaing-manual",
    title: "Operating Manual",
    category: "Manuals",
    parent: "Manuals",
    keywords: "manuals opertaing manual Operating Manual",
  },
  {
    href: "/quizzes/operating-manual",
    title: "Operating Manual",
    category: "Quizzes",
    parent: "Quizzes",
    keywords: "quizzes operating manual Operating Manual",
  },
  {
    href: "/topics/operating-material",
    title: "Operating Material",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics operating material Operating Material authorised officer",
  },
  {
    href: "/quizzes/establishment-rules/ops",
    title: "OPS",
    category: "Quizzes",
    parent: "Quizzes › Establishment Rules",
    keywords: "quizzes establishment rules ops OPS",
  },

  {
    href: "/general-awareness/awards/other-awards",
    title: "Other Awards",
    category: "General Awareness",
    parent: "General Awareness › Awards",
    keywords: "general awareness awards other awards Other Awards",
  },
  {
    href: "/topics/operating-material/other-signals",
    title: "Other Signals",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material other signals Other Signals Gate IB Automatic",
  },
  {
    href: "/topics/operating-material/outer-signal",
    title: "Outer Signal",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material outer signal Outer Signal FSS TAS class B T/369",
  },
  {
    href: "/quizzes/establishment-rules/pass-rules",
    title: "Pass Rules",
    category: "Quizzes",
    parent: "Quizzes › Establishment Rules",
    keywords: "quizzes establishment rules pass rules Pass Rules",
  },
  {
    href: "/pdfs",
    title: "PDF Documents",
    category: "PDFs",
    parent: "PDFs",
    keywords: "pdfs PDF Documents",
  },
  {
    href: "/general-awareness/awards/peace-service-awards",
    title: "Peace Service Awards",
    category: "General Awareness",
    parent: "General Awareness › Awards",
    keywords: "general awareness awards peace service awards Peace Service Awards",
  },
  {
    href: "/topics/permanent-negotiating-machinery",
    title: "Permanent Negotiating Machinery",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics permanent negotiating machinery Permanent Negotiating Machinery",
  },
  {
    href: "/topics/operating-material/permissive-signals",
    title: "Permissive Signals",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material permissive signals Permissive Signals Warner Distant",
  },
  {
    href: "/general-awareness/physics",
    title: "Physics",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness physics Physics",
  },
  {
    href: "/quizzes/general-awareness/physics",
    title: "Physics",
    category: "Quizzes",
    parent: "Quizzes › General Awareness",
    keywords: "quizzes general awareness physics Physics",
  },
  {
    href: "/topics/financial-rules/plan-heads",
    title: "Plan Heads",
    category: "Study Topics",
    parent: "Topics › Financial Rules",
    keywords: "topics financial rules plan heads Plan Heads",
  },
  {
    href: "/topics/information-technology-apps/pms",
    title: "PMS",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps pms PMS",
  },
  {
    href: "/topics/operating-material/point-trap-indicator",
    title: "Point Trap Indicator",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material point trap indicator Point Trap Indicator S.R. 3.50.2 3.51.3.1",
  },
  {
    href: "/topics/operating-material/points",
    title: "Points Affecting the Movement",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material points affecting the movement Points Affecting the Movement G.R. 3.38 VDU line block power block",
  },
  {
    href: "/quizzes/general-awareness/polity",
    title: "Polity",
    category: "Quizzes",
    parent: "Quizzes › General Awareness",
    keywords: "quizzes general awareness polity Polity",
  },
  {
    href: "/topics/prem",
    title: "PREM",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics prem PREM",
  },
  {
    href: "/topics/financial-rules/primary-units",
    title: "Primary Units",
    category: "Study Topics",
    parent: "Topics › Financial Rules",
    keywords: "topics financial rules primary units Primary Units",
  },
  {
    href: "/topics/information-technology-apps/prs-application",
    title: "PRS Application",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps prs application PRS Application",
  },
  {
    href: "/topics/operating-material/protection-of-train",
    title: "Protection of Train",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material protection of train Protection of Train GR 6.03 detonator single line double line TSL automatic block",
  },
  {
    href: "/topics/public-complaints",
    title: "Public Complaints",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics public complaints Public Complaints",
  },
  {
    href: "/general-awareness/states-information/puducherry",
    title: "Puducherry",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information puducherry Puducherry",
  },
  {
    href: "/general-awareness/states-information/punjab",
    title: "Punjab",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information punjab Punjab",
  },
  {
    href: "/topics/quarters",
    title: "Quarters",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics quarters Quarters",
  },
  {
    href: "/quizzes",
    title: "Quizzes",
    category: "Quizzes",
    parent: "Quizzes",
    keywords: "quizzes Quizzes",
  },
  {
    href: "/topics/railway-acts",
    title: "Railway Acts",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics railway acts Railway Acts Indian Railway Act 1989",
  },
  {
    href: "/topics/financial-rules/railway-budget",
    title: "Railway Budget",
    category: "Study Topics",
    parent: "Topics › Financial Rules",
    keywords: "topics financial rules railway budget Railway Budget",
  },
  {
    href: "/quizzes/railway-gk",
    title: "Railway Gk",
    category: "Quizzes",
    parent: "Quizzes",
    keywords: "quizzes railway gk Railway Gk",
  },
  {
    href: "/acts/railway-servants-da-rules-1968",
    title: "Railway Servants Da Rules 1968",
    category: "Acts & Rules",
    parent: "Acts",
    keywords: "acts railway servants da rules 1968 Railway Servants Da Rules 1968",
  },
  {
    href: "/acts/railway-servants-leave-rules-1949",
    title: "Railway Servants Leave Rules 1949",
    category: "Acts & Rules",
    parent: "Acts",
    keywords: "acts railway servants leave rules 1949 Railway Servants Leave Rules 1949",
  },
  {
    href: "/acts/railway-servants-pass-rules-1986",
    title: "Railway Servants Pass Rules 1986",
    category: "Acts & Rules",
    parent: "Acts",
    keywords: "acts railway servants pass rules 1986 Railway Servants Pass Rules 1986",
  },
  {
    href: "/acts/railway-servants-rest-rules-2005",
    title: "Railway Servants Rest Rules 2005",
    category: "Acts & Rules",
    parent: "Acts",
    keywords: "acts railway servants rest rules 2005 Railway Servants Rest Rules 2005",
  },
  {
    href: "/acts/railway-services-conduct-rules-1966",
    title: "Railway Services Conduct Rules 1966",
    category: "Acts & Rules",
    parent: "Acts",
    keywords: "acts railway services conduct rules 1966 Railway Services Conduct Rules 1966",
  },
  {
    href: "/quizzes/rajabhasha",
    title: "Rajabhasha",
    category: "Quizzes",
    parent: "Quizzes",
    keywords: "quizzes rajabhasha Rajabhasha",
  },
  {
    href: "/general-awareness/states-information/rajasthan",
    title: "Rajasthan",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information rajasthan Rajasthan",
  },
  {
    href: "/general-awareness/ramsar-sites",
    title: "Ramsar Sites",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness ramsar sites Ramsar Sites",
  },
  {
    href: "/topics/operating-material/rail-dolly",
    title: "Rail Dolly",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material rail dolly Rail Dolly S.R. 15.27.8 keyman PWI sleeper block protection",
  },
  {
    href: "/topics/operating-material/rail-fracture",
    title: "Rail Fracture",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material rail fracture Rail Fracture S.R. 6.01 caution order Kavach SOS SMOCIP",
  },
  {
    href: "/topics/operating-material/rail-road-vehicle",
    title: "Rail Road Vehicle",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material rail road vehicle Rail Road Vehicle RRV Rail-cum-Road Vehicle S.R. 15.27.9 ON OFF tracking",
  },
  {
    href: "/topics/operating-material/reception-signals",
    title: "Reception Signals",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material reception signals Reception Signals Outer Home Routing",
  },
  {
    href: "/topics/operating-material/relay-room",
    title: "Relay Room",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material relay room Relay Room APP XIII locking double key EKT",
  },
  {
    href: "/topics/operating-material/relief-engine",
    title: "Relief Engine",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material relief engine Relief Engine SR 6.02.6 T/A.602 T/C.912 obstructed block section",
  },
  {
    href: "/topics/operating-material/repeating-signal",
    title: "Repeating Signal",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material repeating signal Repeating Signal G.R. 3.16 R marker",
  },
  {
    href: "/quizzes/establishment-rules/rest-rules",
    title: "Rest Rules",
    category: "Quizzes",
    parent: "Quizzes › Establishment Rules",
    keywords: "quizzes establishment rules rest rules Rest Rules",
  },
  {
    href: "/acts/right-to-information-act-2005",
    title: "Right To Information Act 2005",
    category: "Acts & Rules",
    parent: "Acts",
    keywords: "acts right to information act 2005 Right To Information Act 2005",
  },
  {
    href: "/topics/information-technology-apps/rms",
    title: "RMS",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps rms RMS",
  },
  {
    href: "/topics/information-technology-apps/rshc",
    title: "RSHC",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps rshc RSHC",
  },
  {
    href: "/topics/information-technology-apps/rsms",
    title: "RSMS",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps rsms RSMS",
  },
  {
    href: "/quizzes/establishment-rules/rti-act-2005",
    title: "RTI Act 2005",
    category: "Quizzes",
    parent: "Quizzes › Establishment Rules",
    keywords: "quizzes establishment rules rti act 2005 RTI Act 2005",
  },
  {
    href: "/topics/information-technology-apps/rtis",
    title: "RTIS",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps rtis RTIS",
  },
  {
    href: "/topics/operating-material/routing-signal",
    title: "Routing Signal",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material routing signal Routing Signal G.R. 3.09 route indicators SEM Electric Repeater",
  },
  {
    href: "/topics/operating-material/running-line",
    title: "Running Line",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material running line Running Line G.R. 1.02(47)",
  },
  {
    href: "/topics/operating-material/running-train",
    title: "Running Train",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material running train Running Train G.R. 1.02(48)",
  },
  {
    href: "/topics/information-technology-apps/satsang",
    title: "SATSANG",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps satsang SATSANG",
  },


  {
    href: "/general-awareness/schemes",
    title: "Schemes",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness schemes Schemes",
  },
  {
    href: "/topics/schemes",
    title: "Schemes",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics schemes Schemes",
  },
  {
    href: "/general-awareness/awards/science-technology-awards",
    title: "Science Technology Awards",
    category: "General Awareness",
    parent: "General Awareness › Awards",
    keywords: "general awareness awards science technology awards Science Technology Awards",
  },
  {
    href: "/general-awareness/science-technology-defence",
    title: "Science Technology Defence",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness science technology defence Science Technology Defence",
  },
  {
    href: "/general-awareness/important-days/september",
    title: "September",
    category: "General Awareness",
    parent: "General Awareness › Important Days",
    keywords: "general awareness important days september September",
  },
  {
    href: "/topics/service-rules",
    title: "Service Rules",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics service rules Service Rules",
  },
  {
    href: "/general-awareness/sports/shooting",
    title: "Shooting",
    category: "General Awareness",
    parent: "General Awareness › Sports",
    keywords: "general awareness sports shooting Shooting",
  },
  {
    href: "/topics/operating-material/shunt-signal",
    title: "Shunt Signal",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material shunt signal Shunt Signal G.R. 3.14 SPI position light T/369",
  },
  {
    href: "/topics/operating-material/shadow-block",
    title: "Shadow Block",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material shadow block Shadow Block caution order 150 mts both ends authorities",
  },
  {
    href: "/topics/operating-material/shunting",
    title: "Shunting",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material shunting Shunting G.R. 1.02(49)",
  },
  {
    href: "/topics/operating-material/shunting-limit-board",
    title: "Shunting Limit Board",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material shunting limit board SLB BSLB G.R. 3.32",
  },
  {
    href: "/topics/operating-material/signal-overlap",
    title: "Signal Overlap",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material signal overlap Signal Overlap MAS adequate distance SLB",
  },
  {
    href: "/topics/operating-material/signals",
    title: "Signals",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material signals Signals fixed hand detonating flare warning",
  },
  {
    href: "/topics/operating-material/stabling",
    title: "Stabling",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material stabling Stabling running lines G.R. S.R. 5.19 5.23 securing vehicles formation",
  },
  {
    href: "/general-awareness/states-information/sikkim",
    title: "Sikkim",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information sikkim Sikkim",
  },


  {
    href: "/general-awareness/sports/snooker",
    title: "Snooker",
    category: "General Awareness",
    parent: "General Awareness › Sports",
    keywords: "general awareness sports snooker Snooker",
  },
  {
    href: "/general-awareness/world-information/south-american-countries",
    title: "South American Countries",
    category: "General Awareness",
    parent: "General Awareness › World Information",
    keywords: "general awareness world information south american countries South American Countries",
  },
  {
    href: "/general-awareness/sports",
    title: "Sports",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness sports Sports",
  },
  {
    href: "/general-awareness/awards/sports-adventure-awards",
    title: "Sports Adventure Awards",
    category: "General Awareness",
    parent: "General Awareness › Awards",
    keywords: "general awareness awards sports adventure awards Sports Adventure Awards",
  },
  {
    href: "/general-awareness/sports/squash",
    title: "Squash",
    category: "General Awareness",
    parent: "General Awareness › Sports",
    keywords: "general awareness sports squash Squash",
  },
  {
    href: "/topics/staff-benefit-fund",
    title: "Staff Benefit Fund",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics staff benefit fund Staff Benefit Fund",
  },
  {
    href: "/general-awareness/states-information",
    title: "States Information",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness states information States Information",
  },
  {
    href: "/topics/operating-material/station",
    title: "Station",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material station Station G.R. 1.02(51)",
  },
  {
    href: "/topics/operating-material/station-master",
    title: "Station Master",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material station master Station Master G.R. 1.02(53)",
  },
  {
    href: "/topics/operating-material/station-working-rules",
    title: "Station Working Rules",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material station working rules Station Working Rules SWR G.R. 5.06 Appendix XIV chapters appendices",
  },
  {
    href: "/manuals/station-working-rules",
    title: "Station Working Rules",
    category: "Manuals",
    parent: "Manuals",
    keywords: "manuals station working rules Station Working Rules",
  },
  {
    href: "/topics/operating-material/starter-signal",
    title: "Starter Signal",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material starter signal Starter Signal LSS Common Intermediate Routing",
  },
  {
    href: "/topics/operating-material/stop-signals",
    title: "Stop Signals",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material stop signals Stop Signals Reception Despatch Other",
  },


  {
    href: "/topics",
    title: "Study Topics",
    category: "Study Topics",
    parent: "Study Topics",
    keywords: "topics Study Topics",
  },
  {
    href: "/topics/operating-material/subsidiary-signals",
    title: "Subsidiary Signals",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material subsidiary signals Subsidiary Signals Calling On Shunt Co-acting Repeating",
  },
  {
    href: "/general-awareness/summits",
    title: "Summits",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness summits Summits",
  },
  {
    href: "/syllabus",
    title: "Syllabus",
    category: "Syllabus",
    parent: "Syllabus",
    keywords: "syllabus Syllabus",
  },
  {
    href: "/topics/operating-material/system-of-working",
    title: "System of Working",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material system of working System of Working G.R. 1.02(56)",
  },
  {
    href: "/topics/operating-material/temporary-single-line",
    title: "Temporary Single Line",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material temporary single line Temporary Single Line TSL S.R. 6.02.1 T/D 602 obstructed double line",
  },
  {
    href: "/topics/operating-material/track-tamping-machine",
    title: "Track Tamping Machine",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material track tamping machine Track Tamping Machine TTM S.R. 4.65 T/465 T/A465 JSC",
  },
  {
    href: "/topics/operating-material/total-interruption-of-communication",
    title: "Total Interruption of Communication",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material total interruption of communication TIC S.R. 6.02.4 6.02.3 T/B 602 T/C.602 single double line",
  },
  {
    href: "/general-awareness/sports/table-tennis",
    title: "Table Tennis",
    category: "General Awareness",
    parent: "General Awareness › Sports",

    keywords: "general awareness sports table tennis Table Tennis",
  },
  {
    href: "/general-awareness/states-information/tamil-nadu",
    title: "Tamil Nadu",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information tamil nadu Tamil Nadu",
  },
  {
    href: "/topics/information-technology-apps/tdms",
    title: "TDMS",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps tdms TDMS",
  },
  {
    href: "/general-awareness/states-information/telangana",
    title: "Telangana",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information telangana Telangana",
  },
  {
    href: "/quizzes/financial-rules/tenders",
    title: "Tenders",
    category: "Quizzes",
    parent: "Quizzes › Financial Rules",
    keywords: "quizzes financial rules tenders Tenders",
  },
  {
    href: "/general-awareness/sports/tennis",
    title: "Tennis",
    category: "General Awareness",
    parent: "General Awareness › Sports",
    keywords: "general awareness sports tennis Tennis",
  },
  {
    href: "/general-awareness/tiger-reserves",
    title: "Tiger Reserves",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness tiger reserves Tiger Reserves",
  },
  {
    href: "/topics/information-technology-apps/tms",
    title: "TMS",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps tms TMS",
  },
  {
    href: "/acts/trade-union-act-1926",
    title: "Trade Union Act 1926",
    category: "Acts & Rules",
    parent: "Acts",
    keywords: "acts trade union act 1926 Trade Union Act 1926",
  },
  {
    href: "/topics/operating-material/train",
    title: "Train",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material train Train G.R. 1.02(58)",
  },
  {
    href: "/topics/operating-material/train-engine-disabled",
    title: "Train Engine Disabled",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material train engine disabled Train Engine Disabled S.R. 6.05 relief engine block section",
  },
  {
    href: "/topics/operating-material/train-manager",
    title: "Train Manager",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material train manager Train Manager without guard S.R. 4.25.4 ZRTI",
  },
  {
    href: "/topics/operating-material/train-parting",
    title: "Train Parting",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material train parting Train Parted in Block Section G.R. S.R. 6.08 T/609 whistle",
  },
  {
    href: "/topics/operating-material/trains-unusually-delayed",
    title: "Trains Unusually Delayed",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material trains unusually delayed Trains Unusually Delayed G.R. 6.04 ART MRT SCOR",
  },
  {
    href: "/topics/transfers",
    title: "Transfers",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics transfers Transfers",
  },

  {
    href: "/general-awareness/states-information/tripura",
    title: "Tripura",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information tripura Tripura",
  },
  {
    href: "/general-awareness/unesco-world-heritage-sites",
    title: "Unesco World Heritage Sites",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness unesco world heritage sites Unesco World Heritage Sites",
  },
  {
    href: "/general-awareness/united-nations-organization",
    title: "United Nations Organization",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness united nations organization United Nations Organization",
  },
  {
    href: "/quizzes/establishment-rules/ups",
    title: "UPS",
    category: "Quizzes",
    parent: "Quizzes › Establishment Rules",
    keywords: "quizzes establishment rules ups UPS",
  },
  {
    href: "/topics/information-technology-apps/uts-application",
    title: "UTS Application",
    category: "Study Topics",
    parent: "Topics › Information Technology Apps",
    keywords: "topics information technology apps uts application UTS Application",
  },
  {
    href: "/general-awareness/states-information/uttar-pradesh",
    title: "Uttar Pradesh",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information uttar pradesh Uttar Pradesh",
  },
  {
    href: "/general-awareness/states-information/uttarakhand",
    title: "Uttarakhand",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information uttarakhand Uttarakhand",
  },
  {
    href: "/topics/operating-material/vehicle-guidance",
    title: "Vehicle Guidance",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material vehicle guidance Vehicle Guidance VG S.R. 4.25.3 TNC handbook",
  },
  {
    href: "/topics/operating-material/visibility-test-object",
    title: "Visibility Test Object",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material visibility test object VTO VTP Fog signal post G.R S.R. 3.61",
  },
  {
    href: "/topics/wagons-data",
    title: "Wagons Data",
    category: "Study Topics",
    parent: "Topics",
    keywords: "topics wagons data Wagons Data",
  },
  {
    href: "/topics/operating-material/warner-signal",
    title: "Warner Signal",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material warner signal Warner Signal GR 3.06 semaphore fish-tailed",
  },
  {
    href: "/topics/operating-material/without-tail-lamp",
    title: "Without Tail Lamp",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords:
      "topics operating material without tail lamp Without Tail Lamp S.R. 4.17 tail board last vehicle indicator incomplete train",
  },
  {
    href: "/general-awareness/sports/weightlifting",
    title: "Weightlifting",
    category: "General Awareness",
    parent: "General Awareness › Sports",
    keywords: "general awareness sports weightlifting Weightlifting",
  },
  {
    href: "/general-awareness/states-information/west-bengal",
    title: "West Bengal",
    category: "General Awareness",
    parent: "General Awareness › States Information",
    keywords: "general awareness states information west bengal West Bengal",
  },
  {
    href: "/general-awareness/who-is-who",
    title: "Who Is Who",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness who is who Who Is Who",
  },
  {
    href: "/general-awareness/wildlife-sanctuaries",
    title: "Wildlife Sanctuaries",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness wildlife sanctuaries Wildlife Sanctuaries",
  },
  {
    href: "/topics/operating-material/working-time-table",
    title: "Working Time Table",
    category: "Study Topics",
    parent: "Topics › Operating Material",
    keywords: "topics operating material working time table Working Time Table WTT G.R. 4.07 PCOM",
  },
  {
    href: "/manuals/working-time-table",
    title: "Working Time Table",
    category: "Manuals",
    parent: "Manuals",
    keywords: "manuals working time table Working Time Table",
  },
  {
    href: "/acts/workmen-compensation-act-1923",
    title: "Workmen Compensation Act 1923",
    category: "Acts & Rules",
    parent: "Acts",
    keywords: "acts workmen compensation act 1923 Workmen Compensation Act 1923",
  },
  {
    href: "/general-awareness/world-information",
    title: "World Information",
    category: "General Awareness",
    parent: "General Awareness",
    keywords: "general awareness world information World Information",
  },
  {
    href: "/general-awareness/sports/wrestling",
    title: "Wrestling",
    category: "General Awareness",
    parent: "General Awareness › Sports",
    keywords: "general awareness sports wrestling Wrestling",
  },
  {
    href: "/quizzes/general-awareness/zoology",
    title: "Zoology",
    category: "Quizzes",
    parent: "Quizzes › General Awareness",
    keywords: "quizzes general awareness zoology Zoology",
  },
]
