export const aom70Ldce2024 = {
    quizzes: {
        'aom-70-ldce-2024': [
            {
                question: 'Who heads operating department at Railway Board level?',
                options: ['MI (Member Infrastructure', 'MOBD (Member Operation & Business Development)', 'MTRS (Member Traction Rolling Stock)', 'MF (Member Finance)'],
                correct: 1,
                explanation: 'MOBD (Member Operation & Business Development) is the correct answer.',
            },
            {
                question: 'What is the maximum additional free time that may be permitted for convering open wagons with tarpaulins during loading of loose/bulk commodity such as coal etc at EOL sidings?',
                options: ['30 minutes', '1 hour', '2 hours', 'None of the above'],
                correct: 1,
                explanation: '1 hour is the correct answer.',
            },
            {
                question: 'Should any portion of a train, while in motion, part, which of the following activities should NOT be done by the Loco Pilot?',
                options: ['Keep the front portion in motion', 'Apply Emergency brake', 'Sound the prescribed code of whistle', 'None of the above'],
                correct: 1,
                explanation: 'Apply Emergency brake should not be done by the Loco Pilot.',
            },
            {
                question: 'Throughput refers to ________ run over a section in 24 hours',
                options: ['Total quantum of traffic', 'Total number of trains', 'Total number of wagons', 'Total number of engines'],
                correct: 0,
                explanation: 'Total quantum of traffic is the correct answer.',
            },
            {
                question: 'Which control is responsible for arranging supply of wagons against pending registration?',
                options: ['C&W Control', 'Traffic Control', 'Traction power Control', 'Commercial Control'],
                correct: 1,
                explanation: 'Traffic Control is the correct answer.',
            },
           {
            question: 'Which of the following is true?',
            options: ['SIP is prepared on the basis of ESP', 'ESP is prepared on the basis of SIP', 'There is no relationship between ESP and SIP', 'None of the above'],
            correct: 0,
            explanation: 'SIP is prepared on the basis of ESP.',
           },
           {
            question: 'When the control is interrupted and no communication with the controller is possible ________ will be responsible for working and regulating of train',
            options: ['Station Master', 'Chief Controller', 'AOM/DOM', 'Sr.DOT'],
            correct: 0,
            explanation: 'Station Master is the correct answer.',
           },

           
            {
              question: 'Who is responsible for imposing and removing power blocks in consultation with the Traffic Section Controller?',
              options: ['Power Controller/Traction Loco Controller', 'Traction Power Controller', 'Engineering Controller', 'C & W Control'],
              correct: 1,
              explanation: 'Traction Power Controller is the correct answer.',
            },
            {
              question: 'Who is responsible for planning and directing engine movements so as to ensure efficient engine utilization?',
              options: ['Traffic Controller', 'Power Controller/Traction Controller', 'Traction Power Controller', 'Commercial Control'],
              correct: 0,
              explanation: 'Traffic Controller is the correct answer.',
            },
            {
              question: 'For data sanctity and better insights on maintenance blocks, which application has been linked with Control Office Application (COA)?',
              options: ['Chalak Dal', 'Crew Management System', 'Terminal Management System', 'Track Management System'],
              correct: 3,
              explanation: 'Track Management System is the correct answer.',
            },
            {
              question: '___________ is the head of the Divisional Control Organization.',
              options: ['AOM/DOM', 'Sr. DOM', 'Chief Controller', 'DRM'],
              correct: 2,
              explanation: 'Chief Controller is the correct answer.',
            },
            {
              question: 'Material trains, Track Maintenance Trains, Ballast trains and Relief Trains are classified under __________.',
              options: ['Special trains', 'Shunting trains', 'Departmental trains', 'Mixed trains'],
              correct: 2,
              explanation: 'Departmental trains are the correct answer.',
            },
            {
              question: 'Scott’s formula for calculating Line Capacity is 1440/(R+5) × (7/10). What does the R stand for?',
              options: [
                'Running time in minutes of fastest passenger train in critical section',
                'Radius of curvature of steepest curve in the section',
                'Running time in minutes of goods train in critical section',
                'Number of trains per hour in critical section'
              ],
              correct: 2,
              explanation: 'Running time in minutes of goods train in critical section is the correct answer.',
            },
            {
              question: 'For how many days is cancellation of indent not permitted after advance stacking permission is granted?',
              options: ['5 days', '10 days', '15 days', '20 days'],
              correct: 2,
              explanation: '15 days is the correct answer.',
            },
            {
              question: 'What represents the requirement of average number of Locos in a Division?',
              options: ['Power plan', 'Control chart', 'Engine utilization', 'Speed'],
              correct: 0,
              explanation: 'Power plan is the correct answer.',
            },
            {
              question: 'What is derived by dividing the total hours for which the various Locos were available for traffic use with 24?',
              options: ['Engine KM', 'Loco outage', 'Engine Utilization', 'Engine Hour'],
              correct: 3,
              explanation: 'Engine Hour is the correct answer.',
            },
            {
              question: 'Which is not a factor for improving engine utilization?',
              options: [
                'Reduction in terminal detention',
                'Increasing speed of Goods trains',
                'Increasing the Loco holding',
                'Minimizing detention of trains en-route'
              ],
              correct: 2,
              explanation: 'Increasing the Loco holding is the correct answer.',
            },
            {
              question: 'How are the goods running staff generally booked?',
              options: ['Randomly', 'First in and first out', 'As per convenience', 'As per service seniority'],
              correct: 1,
              explanation: 'First in and first out is the correct answer.',
            },
            {
              question: 'What is an integrated lobby?',
              options: [
                'Both Crew and Guards are booked',
                'Only Crew are booked',
                'Both Electrical and Diesel crew are booked',
                'None of the above'
              ],
              correct: 0,
              explanation: 'Both Crew and Guards are booked is the correct answer.',
            },
            {
              question: 'What is the unit of Wagon Turn Round?',
              options: ['Days', 'Hours', 'Months', 'Years'],
              correct: 0,
              explanation: 'Days is the correct answer.',
            },

            
                {
                  question: 'What is the adequate distance for taking off signal in double line automatic signalled territory?',
                  options: ['120 m', '180 m', '240 m', '300 m'],
                  correct: 0,
                  explanation: '120 m is the correct answer.',
                },
                {
                  question: 'What is the formation of more than one standard train known as __________?',
                  options: ['Long Haul Train Operation', 'CC Train Operation', 'MGR Train Operation', 'RO-RO Train Operation'],
                  correct: 0,
                  explanation: 'Long Haul Train Operation is the correct answer.',
                },
                {
                  question: 'Who is the competent authority to notify the Associate weighbridge?',
                  options: ['Sr. DOM', 'CFTM', 'PCOM', 'PCCM'],
                  correct: 2,
                  explanation: 'PCOM is the correct answer.',
                },
                {
                  question: 'Which of the following is not among the standard compositions prescribed by Railway Board for LHB rakes?',
                  options: ['16 LHB coaches', '18 LHB Coaches', '21 LHB Coaches', '22 LHB Coaches'],
                  correct: 2,
                  explanation: '21 LHB Coaches is the correct answer.',
                },
                {
                  question: 'Night running is suspended in case of __________ class of ODC.',
                  options: ['A', 'B', 'C', 'D'],
                  correct: 2,
                  explanation: 'C is the correct answer.',
                },
                {
                  question: 'Computerized booking and delivery of consignment is done through __________.',
                  options: ['RMS', 'TMS', 'COA', 'CMS'],
                  correct: 1,
                  explanation: 'TMS is the correct answer.',
                },
                {
                  question: 'Which is not a module in ICMS (Integrated Coaching Management System)?',
                  options: ['PAM', 'COIS', 'CMM', 'SASTANG'],
                  correct: 0,
                  explanation: 'SASTANG is the correct answer.',
                },
                {
                  question: '___________ is a fully integrated Electronic Control System designed to minimize collisions and increase safety on Railway Systems.',
                  options: ['SASTANG', 'ACD', 'ICMS', 'TMS'],
                  correct: 1,
                  explanation: 'ACD is the correct answer.',
                },
                {
                  question: 'Management of maintenance blocks is one of the core functionalities of __________.',
                  options: ['COA', 'NTES', 'COIS', 'RMS'],
                  correct: 0,
                  explanation: 'COA is the correct answer.',
                },
                {
                  question: 'In yard situated on gradients steeper than __________ no loose or hand shunting of any vehicle is to be permitted.',
                  options: ['1 in 100', '1 in 200', '1 in 400', '1 in 80'],
                  correct: 2,
                  explanation: '1 in 400 is the correct answer.',
                },
                {
                  question: 'In operating statistics, primary unit of quantity is expressed in terms of __________.',
                  options: ['Tonnes', 'Quintal', 'Kilograms', 'Gram'],
                  correct: 0,
                  explanation: 'Tonnes is the correct answer.',
                },
                {
                  question: 'Traffic facility work comes under which Plan Head?',
                  options: ['PH-16', 'PH-17', 'PH-53', 'PH-13'],
                  correct: 0,
                  explanation: 'PH-16 is the correct answer.',
                },
                {
                  question: 'What is the maximum speed at which a train is permitted to run from the defective weighbridge to next available weighbridge?',
                  options: ['40 kmph', '45 kmph', '50 kmph', 'Normal speed'],
                  correct: 0,
                  explanation: '40 kmph is the correct answer.',
                },
                {
                  question: 'WGSCN stands for __________ coaches.',
                  options: ['II Class Sleeper', 'AC Executive Chair Car', 'Second AC Sleeper', 'Second AC Chair Car'],
                  correct: 0,
                  explanation: 'II Class Sleeper is the correct answer.',
                },
                {
                  question: 'What is the full form of FIRR __________?',
                  options: ['Financial Internal Rate of Return', 'Freight Internal Rate of Return', 'Final Internal Rate of Return', 'Foreign Internal Rate of Return'],
                  correct: 0,
                  explanation: 'Financial Internal Rate of Return is the correct answer.',
                },
                {
                  question: 'In emergencies and under special restrictions, in each case __________ may be used in lieu of a tail board.',
                  options: ['Red flag', 'Green flag', 'Either Red flag or Green Flag', 'Neither Red flag nor Green flag'],
                  correct: 0,
                  explanation: 'Red flag is the correct answer.',
                },
                {
                  question: 'Before giving signal to material train to start __________ shall see that all the workers are on the train and warn them to sit down.',
                  options: ['Guard of the material train', 'Station master', 'Engineering Supervisors of the Material train', 'Loco pilot in the material train'],
                  correct: 0,
                  explanation: 'Guard of the material train is the correct answer.',
                },
                {
                  question: '___________ shall see that the working of the station is carried out in strict accordance with the rules and regulations for the time being in force.',
                  options: ['Station master', 'The Sectional Transportation Inspector', 'Sr. DOM of the concerned Division', 'Sr. DSO of the concerned Division'],
                  correct: 0,
                  explanation: 'Station master is the correct answer.',
                },
                {
                  question: 'A train can be admitted on an obstructed line on __________ signal.',
                  options: ['Home', 'Calling On', 'Shunt', 'Hand'],
                  correct: 1,
                  explanation: 'Calling On is the correct answer.',
                },
                {
                  question: 'On how many days in a week is supply of rakes against Premium indent done on priority?',
                  options: ['1', '2', '3', '4'],
                  correct: 1,
                  explanation: '2 is the correct answer.',
                },
              
                
                    {
                      question: 'For granting line clear at a B-class double line station with MACL signalling arrangement, the line shall remain clear up to __________.',
                      options: ['BSLB', 'Outermost facing point', 'Both BSLB and Outermost facing point', 'Neither BSLB nor Outermost facing point'],
                      correct: 2,
                      explanation: 'Both BSLB and Outermost facing point is the correct answer.',
                    },
                    {
                      question: 'Stations at which the Loco Pilot must obtain an authority to proceed to enter the block section with his train are called __________.',
                      options: ['Junction stations', 'Block stations', 'Non block stations', 'Special Class stations'],
                      correct: 1,
                      explanation: 'Block stations is the correct answer.',
                    },
                    {
                      question: 'Who is not a signatory to the Station Working Rules of a particular station?',
                      options: ['Sr. DEN/DEN', 'Sr. DSTE/DSTE', 'Sr. DOM/DOM', 'Sr. DCM/DCM'],
                      correct: 3,
                      explanation: 'Sr. DCM/DCM is the correct answer.',
                    },
                    {
                      question: 'What is the value of Detailed Estimate above which DPR is required to be submitted to Railway Board for sanction?',
                      options: ['25 crores', '50 crores', '100 crores', '500 crores'],
                      correct: 1,
                      explanation: '50 crores is the correct answer.',
                    },
                    {
                      question: 'In the context of Indian Railways, what is the full form of RTIS?',
                      options: ['Railway Train Indication System', 'Railway Traffic Interchange System', 'Realtime Train Information System', 'Radio Train Indication System'],
                      correct: 2,
                      explanation: 'Realtime Train Information System is the correct answer.',
                    },
                    {
                      question: 'A short section of insulated and dead overhead equipment which separates the area fed by adjacent sub-stations or feeding posts is known as __________.',
                      options: ['Neutral section', 'Feeding post', 'Joint section', 'None of the above'],
                      correct: 0,
                      explanation: 'Neutral section is the correct answer.',
                    },
                    {
                      question: 'The brake power of a CC Rake at the originating point should be __________.',
                      options: ['100%', '95%', '90%', '75%'],
                      correct: 0,
                      explanation: '100% is the correct answer.',
                    },
                    {
                      question: 'What does TVU stand for __________?',
                      options: ['Train Vehicle Unit', 'Ticket Vending Unit', 'Train Vending Unit', 'None of the above'],
                      correct: 0,
                      explanation: 'Train Vehicle Unit is the correct answer.',
                    },
                    {
                      question: 'A train entering a block section without any authority to proceed constitutes an accident under which of the following?',
                      options: ['Class A', 'Class B', 'Class D', 'Class G'],
                      correct: 3,
                      explanation: 'Class G is the correct answer.',
                    },
                    {
                      question: 'Which of the following two cities are going to be connected by India’s first bullet train project?',
                      options: ['Mumbai and Ahmedabad', 'Gandhinagar and Varanasi', 'Delhi and Ayodhya', 'Delhi and Ahmedabad'],
                      correct: 0,
                      explanation: 'Mumbai and Ahmedabad is the correct answer.',
                    },
                    {
                      question: 'Which of the following is not a reportable accident under Section 113 of the Railway Act?',
                      options: ['Any accident attended with loss of any human life', 'Any collision involving a passenger carrying train', 'Trespassing at Level Crossing Gate', 'Derailment of any passenger carrying train'],
                      correct: 2,
                      explanation: 'Trespassing at Level Crossing Gate is the correct answer.',
                    },
                    {
                      question: 'What is the target time for turning out the Accident Relief Train in the day and night respectively?',
                      options: ['15 minutes and 25 minutes', '30 minutes and 45 minutes', '45 minutes and 60 minutes', '20 minutes and 30 minutes'],
                      correct: 1,
                      explanation: '30 minutes and 45 minutes is the correct answer.',
                    },
                    {
                      question: 'In which of the following cases is ex-gratia payment not permissible?',
                      options: ['Railway servants killed or injured in a train accident', 'Passengers killed or injured in a train accident', 'Person getting run over at an unmanned level crossing', 'None of the above'],
                      correct: 2,
                      explanation: 'Person getting run over at an unmanned level crossing is the correct answer.',
                    },
                    {
                      question: 'Under which category of accident is "Fire in Trains" classified?',
                      options: ['Class A', 'Class B', 'Class D', 'Class G'],
                      correct: 1,
                      explanation: 'Class B is the correct answer.',
                    },
                    {
                      question: 'What is the maximum permitted speed of a train in foggy weather conditions, when the visibility is restricted?',
                      options: ['45 kmph', '50 kmph', '60 kmph', '75 kmph'],
                      correct: 2,
                      explanation: '60 kmph is the correct answer.',
                    },
                    {
                      question: 'Which of the following is known as electronic interlocking?',
                      options: ['Route Relay Interlocking', 'Panel Interlocking', 'Solid State Interlocking', 'None of the above'],
                      correct: 2,
                      explanation: 'Solid State Interlocking is the correct answer.',
                    },
                    {
                      question: 'Which of the following is plan head is covered in in the scheme of Amit Bharat Station Scheme?',
                      options: ['PH-16', 'PH-17', 'PH-53', 'PH-13'],
                      correct: 2,
                      explanation: 'PH-53 is the correct answer.',
                    },
                    {
                      question: 'Which of the following is provided to avoid surface crossing of trains?',
                      options: ['Y connection', 'Rail Flyover', 'Road under Rail Flyover', 'Road Over Bridge'],
                      correct: 1,
                      explanation: 'Rail Flyover is the correct answer.',
                    },
                    {
                      question: 'Which of the following contributes to enhancement of line capacity?',
                      options: ['Splitting Block section with provision of IBP', 'Introducing Automatic Block System of Working', 'Doubling the single section', 'All of the above'],
                      correct: 3,
                      explanation: 'All of the above is the correct answer.',
                    },
                    {
                      question: 'Which is not true regarding the Master Circular on Gati Shakti Cargo Terminal?',
                      options: ['It is applicable for all new goods terminals', 'It is applicable for existing private sidings/PFTs that may opt for this', 'The terminal can only be developed in private land', 'It supersedes all the earlier policies on private sidings'],
                      correct: 2,
                      explanation: 'The terminal can only be developed in private land is the correct answer.',
                    },
                    
                        {
                          question: 'Which of the following scheme is related to station redevelopment works?',
                          options: ['Amrit Bharat Station Scheme', 'Vande Bharat Station Scheme', 'Mahatma Gandhi Station Scheme', 'None of the above'],
                          correct: 0,
                          explanation: 'Amrit Bharat Station Scheme is the correct answer.',
                        },
                        {
                          question: 'In which of the following case is DPR required to be prepared?',
                          options: ['Construction of a new line', 'Construction of a bypass', 'Construction of Gati Shakti Cargo Terminal', 'All of the above'],
                          correct: 3,
                          explanation: 'All of the above is the correct answer.',
                        },
                        {
                          question: 'Which of the following is not the objective of marshalling a train?',
                          options: ['Safety', 'Operational expediency', 'Customer convenience', 'Operating efficiency'],
                          correct: 3,
                          explanation: 'Operating efficiency is the correct answer.',
                        },
                        {
                          question: 'Which of the organization is related to Bullet Train in India?',
                          options: ['NHSRC', 'DFCC', 'RVNL', 'RLDA'],
                          correct: 0,
                          explanation: 'NHSRC is the correct answer.',
                        },
                        {
                          question: 'When is "Green Notice" issued?',
                          options: ['Consequential train accident', 'Temporary single line working', 'Non-interlocked working', 'None of the above'],
                          correct: 2,
                          explanation: 'Non-interlocked working is the correct answer.',
                        },
                        {
                          question: 'Untoward incidents are covered under which section of Indian Railway Act?',
                          options: ['Section 113', 'Section 124 A', 'Section 154', 'Section 146'],
                          correct: 1,
                          explanation: 'Section 124 A is the correct answer.',
                        },
                        {
                          question: 'Which of the following is the first priority task of a Railway servant at the site of a serious accident?',
                          options: ['To attend the injured person', 'To protect the adjacent line in case of Double line section', 'To preserve the clues of accident', 'To report the accident to control'],
                          correct: 1,
                          explanation: 'To protect the adjacent line in case of Double line section is the correct answer.',
                        },
                        {
                          question: 'The operating ratio of Indian Railway in 2022-23 is __________.',
                          options: ['98.1%', '95%', '97.7%', '100%'],
                          correct: 0,
                          explanation: '98.1% is the correct answer.',
                        },
                        {
                          question: 'During 2022-23 Indian Railway transported __________ millions tonnes of freight.',
                          options: ['1418.1', '1298.5', '1509.1', '1360.5'],
                          correct: 2,
                          explanation: '1509.1 million tonnes is the correct answer.',
                        },
                        {
                          question: 'Which of the following commodity constitutes the highest share of freight in Indian Railway?',
                          options: ['Coal', 'Iron ore', 'Cement', 'Food Grains'],
                          correct: 0,
                          explanation: 'Coal is the correct answer.',
                        },
                        {
                          question: 'Which article of Indian Constitution declares Hindi in Devanagari script as the official language of the Union of India?',
                          options: ['Article 343 (1)', 'Article 345', 'Article 356', 'Article 370'],
                          correct: 0,
                          explanation: 'Article 343 (1) is the correct answer.',
                        },
                        {
                          question: 'Which of the following states of India does not come under "Region-A" regarding Official Language Rules?',
                          options: ['Bihar', 'Uttar Pradesh', 'Punjab', 'Madhya Pradesh'],
                          correct: 2,
                          explanation: 'Punjab is the correct answer.',
                        },
                        {
                          question: 'What is the prescribed in-service Hindi (middle school level) training course for the Railway Employees?',
                          options: ['Prabodh', 'Praveen', 'Pragya', 'None of the above'],
                          correct: 1,
                          explanation: 'Praveen is the correct answer.',
                        },
                        {
                          question: 'Which of the following incentives is given for using Rajbhasha?',
                          options: ['Individual Cash Award', 'Award for writing original standard books', 'Indira Gandhi Official Language Awards', 'All the above'],
                          correct: 3,
                          explanation: 'All the above is the correct answer.',
                        },
                        {
                          question: 'Hindi Day is observed every year on __________.',
                          options: ['September 14', 'April 14', 'May 1', 'None of the above'],
                          correct: 0,
                          explanation: 'September 14 is the correct answer.',
                        },
                        {
                          question: 'Which Ministry of Government of India deals with Official Language?',
                          options: ['Home', 'Finance', 'HRD', 'Culture'],
                          correct: 0,
                          explanation: 'Home is the correct answer.',
                        },
                        {
                          question: 'For appearing in Hindi examinations the absence of a Railway employee from duty may be treated as __________.',
                          options: ['Duty', 'Special casual leave', 'Casual leave', 'Leave on average pay'],
                          correct: 1,
                          explanation: 'Special casual leave is the correct answer.',
                        },
                        {
                          question: 'Which of the following is the official language of Arunachal Pradesh?',
                          options: ['Hindi', 'English', 'Bodo', 'Manipuri'],
                          correct: 1,
                          explanation: 'English is the correct answer.',
                        },
                        {
                          question: 'Periodical meeting of Rajbhasha Co-ordination Committee is conducted in every __________ months.',
                          options: ['monthly', '2 months', '3 months', '6 months'],
                          correct: 2,
                          explanation: '3 months is the correct answer.',
                        },
                        {
                          question: 'Who is the chairman of the Divisional Rajbhasha Co-ordination Committee?',
                          options: ['DRM', 'ADRM', 'Sr. DPO', 'Sr. DCM'],
                          correct: 0,
                          explanation: 'DRM is the correct answer.',
                        },
                      
                        
                            {
                              question: 'There are __________ Railway zones in Indian Railway including Metro Railway.',
                              options: ['15', '16', '17', '19'],
                              correct: 2,
                              explanation: '17 is the correct answer.',
                            },
                            {
                              question: 'NPS stands for __________.',
                              options: ['New Pension System', 'National Pension System', 'National Pension Service', 'None of the above'],
                              correct: 0,
                              explanation: 'New Pension System is the correct answer.',
                            },
                            {
                              question: 'How is Group "C" staff recruited in Indian Railway?',
                              options: ['Direct Recruitment', 'Promotion from Group - D', 'Transfer from other services', 'All the above'],
                              correct: 3,
                              explanation: 'All the above is the correct answer.',
                            },
                            {
                              question: 'In which of the following grounds Compassionate Appointment is not permissible?',
                              options: [
                                'When a railway servant dies or gets permanently crippled in the course of duty',
                                'When a railway servant dies as a result of railway accident',
                                'When a railway servant develops serious ailments like cancer, heart disease etc.',
                                'When a railway servant remains unauthorized absent'
                              ],
                              correct: 3,
                              explanation: 'When a railway servant remains unauthorized absent is the correct answer.',
                            },
                            {
                              question: 'Which of the following is not treated as leave for calculation of Dearness Allowance?',
                              options: ['LHAP', 'CL', 'Special Leave', 'LAP'],
                              correct: 2,
                              explanation: 'Special Leave is the correct answer.',
                            },
                            {
                              question: 'Children Education Allowance is admissible.',
                              options: [
                                'Up to maximum of two eldest surviving children only',
                                'For more than two children in case the number of children exceeds two as a result of multiple births',
                                'For expenditure on the education of school going children (Nursery to Class - XII)',
                                'All the above'
                              ],
                              correct: 3,
                              explanation: 'All the above is the correct answer.',
                            },
                            {
                              question: 'For performing duty between which of the following time slots, is night duty allowance paid to all Group - C & D staff?',
                              options: ['00.00 to 06.00', '00.00 to 04.00', '22.00 to 06.00', '22.00 to 04.00'],
                              correct: 2,
                              explanation: '22.00 to 06.00 is the correct answer.',
                            },
                            {
                              question: 'What is the rate of overtime allowance for duty between rostered hours of work and the statutory limit?',
                              options: ['2 times', '1 1/2 times', '2 1/2 times', '1 1/4 times'],
                              correct: 1,
                              explanation: '1 1/2 times is the correct answer.',
                            },
                            {
                              question: 'Which of the following is not true about Child Care Leave (CCL)?',
                              options: [
                                'Admissible only if the child is below eighteen years of age',
                                'For taking care of up to 2 children',
                                'Only women employees can avail',
                                'Can be availed for any number of days during the service'
                              ],
                              correct: 3,
                              explanation: 'Can be availed for any number of days during the service is the correct answer.',
                            },
                            {
                              question: 'In which of the following cases can special casual leave be granted?',
                              options: ['Attending trade union meetings', 'Participating in Scout camp', 'Donating blood voluntarily', 'All the above'],
                              correct: 3,
                              explanation: 'All the above is the correct answer.',
                            },
                            {
                              question: 'A senior supervisor-in-charge in Grade Pay of Rs. 4200/- and above may suspend any staff working under him, who is __________ grades (GP) lower than him.',
                              options: ['2', '3', '4', '5'],
                              correct: 1,
                              explanation: '3 is the correct answer.',
                            },
                            {
                              question: 'Which of the following does not constitute a major penalty?',
                              options: [
                                'Withholding promotion for a specific period',
                                'Compulsory Retirement',
                                'Removal from service',
                                'Reduction to a lower time scale of pay, grade, post or service'
                              ],
                              correct: 0,
                              explanation: 'Withholding promotion for a specific period is the correct answer.',
                            },
                            {
                              question: 'Under which Rule of Railway Servants (Discipline & Appeals) Rules 1968, can a Railway servant be dismissed from railway service without holding any inquiry?',
                              options: ['Rule 6', 'Rule 12', 'Rule 14', 'None of the above'],
                              correct: 2,
                              explanation: 'Rule 14 is the correct answer.',
                            },
                            {
                              question: 'Casual leave can be prefixed or suffixed with __________.',
                              options: ['LAP', 'LHAP', 'Restricted Holiday', 'None of the above'],
                              correct: 2,
                              explanation: 'Restricted Holiday is the correct answer.',
                            },
                            {
                              question: 'What is the full form of PPO?',
                              options: ['Pay Payment Order', 'Pension & Pay Order', 'Pension Payment Order', 'Principal Payment Order'],
                              correct: 2,
                              explanation: 'Pension Payment Order is the correct answer.',
                            },
                            {
                              question: 'Who is the Chairman of Staff Benefit Fund at the Zonal Railway level?',
                              options: ['Principal Chief Medical Director', 'General Manager', 'Principal Chief Personnel Officer', 'Additional General Manager'],
                              correct: 2,
                              explanation: 'Principal Chief Personnel Officer is the correct answer.',
                            },
                            {
                              question: 'The online platform available to the citizens to lodge their grievance to the public authorities on any subject related to service delivery is known as __________.',
                              options: ['CPGRAMS', 'ANUBHAV', 'RAILSATHI', 'LIMBS'],
                              correct: 0,
                              explanation: 'CPGRAMS is the correct answer.',
                            },
                            {
                              question: 'What is the full form of FAA in the context of RTI?',
                              options: ['First Appellate Authority', 'First Application Authority', 'Final Appeal Agency', 'None of the above'],
                              correct: 0,
                              explanation: 'First Appellate Authority is the correct answer.',
                            },
                            {
                              question: 'Railway budget was merged with the Union Budget in the year __________.',
                              options: ['2015-16', '2016-17', '2017-18', '2018-19'],
                              correct: 2,
                              explanation: '2017-18 is the correct answer.',
                            },
                            {
                              question: 'The expenditure incurred to acquire an asset is called __________.',
                              options: ['Capital expenditure', 'Revenue expenditure', 'Deferred Revenue expenditure', 'None of the above'],
                              correct: 0,
                              explanation: 'Capital expenditure is the correct answer.',
                            },
                            {
                              question: 'In case of which type of expenditure on Railway, the sanction of the President is conveyed without being submitted for the vote of Parliament?',
                              options: ['Voted', 'Charged', 'Both Voted and Charged', 'Neither Voted nor Charged'],
                              correct: 1,
                              explanation: 'Charged is the correct answer.',
                            },
                            {
                              question: 'Which of the following is not a source of earnings of the Railway?',
                              options: ['Coaching services', 'Transport of Goods service', 'Sundry earnings', 'Internal borrowings'],
                              correct: 3,
                              explanation: 'Internal borrowings is the correct answer.',
                            },
                            {
                              question: 'Name the dedicated e-market for different goods and services procured by Government Organizations/Departments/PSUs.',
                              options: ['GeM', 'e-RD', 'e-Rail', 'Flipkart'],
                              correct: 0,
                              explanation: 'GeM is the correct answer.',
                            },
                            {
                              question: 'Through which of the following are disputed/not admitted debits withdrawn?',
                              options: ['Remission order', 'Credit advice note', 'Refund order', 'Certified Over Charge sheet'],
                              correct: 1,
                              explanation: 'Credit advice note is the correct answer.',
                            },
                            {
                              question: '__________ is the supreme audit institution of India.',
                              options: [
                                'Controller General of Accounts (CGA)',
                                'Comptroller & Auditor General of India (CAG)',
                                'Standing Parliamentary Committee on Accounts',
                                'None of the above'
                              ],
                              correct: 1,
                              explanation: 'Comptroller & Auditor General of India (CAG) is the correct answer.',
                            },
                            {
                              question: 'Who is the Plan Head co-coordinator of PH-17?',
                              options: ['PCOM', 'PCCM', 'PCPO', 'PCE'],
                              correct: 1,
                              explanation: 'PCCM is the correct answer.',
                            },
                            {
                              question: 'What is the Depreciation Fund provided for?',
                              options: ['Repairs of assets', 'Replacement of assets', 'New Purchase of assets', 'None of the above'],
                              correct: 1,
                              explanation: 'Replacement of assets is the correct answer.',
                            },
                            {
                              question: 'Review of expenditure is undertaken by Railway authorities in the month of August every year in order to see whether any modifications in the allotments is necessary. What is it known as __________?',
                              options: ['Financial review', 'August review', 'Audit review', 'None of the above'],
                              correct: 1,
                              explanation: 'August review is the correct answer.',
                            },
                            {
                              question: 'The percentage of working expenses to gross earnings is represented by __________.',
                              options: ['Operating ratio', 'Fiscal Deficit', 'Earning performance', 'Efficiency ratio'],
                              correct: 3,
                              explanation: 'Efficiency ratio is the correct answer.',
                            },
                            {
                              question: 'Allowance granted to compensate high cost of living based on the rise of price index is called __________.',
                              options: ['Interim Relief', 'Dearness Pay', 'Dearness Allowance', 'Special Compensatory Allowance'],
                              correct: 2,
                              explanation: 'Dearness Allowance is the correct answer.',
                            },
                          
        ],
    },
};