export const aom30Ldce2023 = {
    quizzes: {
        'aom-30-ldce-2023': [
            {
                question: 'Which of the following is a primary unit as per railway statistics?',
                options: ['Tonne-kms', 'Kilometer', 'Wagn Km per wagon day track', 'None of the above'],
                correct: 1,
                explanation: 'Kilometer is the primary unit as per railway statistics.',
            },
            {
                question: 'Full form of PDD is?',
                options: ['Post Departutre Delay', 'Post Departure Detention', 'Pre Departure Detention', 'None of the above'],
                correct: 2,
                explanation: 'Pre Departure Detention is the correct answer.',
            },
            {
                question: 'Which type of unit is NTKM?',
                options: ['Primary', 'Fundamental', 'Derived', 'This is not a unit'],
                correct: 1,
                explanation: 'NTKM is a Fundamental unit.',
            },
            {
                question: 'When will the long haul not be operated from the next station during the journey?',
                options: ['Stop signal defective', 'Hand signal not seen', 'Walkie talkie defective', 'None of the above'],
                correct: 2,
                explanation: 'Walkie talkie defective is the correct answer.',
            },
            {
                question: 'During Long Haul working, if there is one rake loaded and other is empty, then?',
                options: ['Loaded rake will be in front', 'Empty rake will be in front', 'Any rake can be in front', 'None of the above'],
                correct: 0,
                explanation: 'Loaded rake will be in front.',
            },
            {
                question: 'How many systems are there for Freight train examination?',
                options: ['2', '3', '4', 'None of the above'],
                correct: 2,
                explanation: '3 systems are there for Freight train examination.',
            },
            {
                question: 'What is the target time for dispatching Accident Relief Train?',
                options: ['45 minutes in day & 30 minutes in night', '15 minutes in day & 20 minutes in night', '30 minutes in day & 45 minutes in night', 'None of the above'],
                correct: 2,
                explanation: '30 minutes in day & 45 minutes in night is the correct answer.',
            },
            {
                question: 'Within how many days after the date of accident, DAR action has to be completed?',
                options: ['30 days', '60 days', '90 days', 'None of the above'],
                correct: 2,
                explanation: '90 days is the correct answer.',
            },
            {
                question: 'Inquiry of railway accident by CRS is mentioned under which section of Railway Act 1989?',
                options: ['Section 114', 'Section 115', 'Section 116', 'None of the above'],
                correct: 0,
                explanation: 'Section 114 is the correct answer.',
            },
            {
                question: 'Which of the following rule book is not kept in Accident Relief Train?',
                options: ['G&SR', 'Accident Manual', 'Working Time Table', 'Block Working Manual'],
                correct: 3,
                explanation: 'Block Working Manual is not kept in Accident Relief Train.',
            },
            
                {
                  question: 'How much loss of Railway property will be considered as a serious accident?',
                  options: ['More than Rs. 25 lakhs', 'More than Rs. 20 crores', 'More than Rs. 2 crores', 'None of the above'],
                  correct: 0,
                  explanation: 'More than Rs. 2 crores is the correct answer.',
                },
                {
                  question: 'Train accidents have been classified into how many categories?',
                  options: ['A to R', 'A to I', 'A to O', 'None of the above'],
                  correct: 0,
                  explanation: 'A to R is the correct answer.',
                },
                {
                  question: 'The Section Controller can call at the same time __________.',
                  options: ['One station only', 'Two stations only', 'All stations', 'None of the above'],
                  correct: 0,
                  explanation: 'Two stations only is the correct answer.',
                },
                {
                  question: 'When the control is interrupted and no communication with the controller is possible, who will be responsible for the working and regulating of trains?',
                  options: ['Chief Controller', 'Station Masters', 'Traffic Inspector', 'Loco Pilots'],
                  correct: 0,
                  explanation: 'Station Masters is the correct answer.',
                },
                {
                  question: 'Which register is not maintained by Section Controllers?',
                  options: ['Train Ordering Book', 'Load Register', 'Interchange Register', 'Engine Book'],
                  correct: 0,
                  explanation: 'Engine Book is the correct answer.',
                },
                {
                  question: 'In case of a goods train accident, arrangement of road transport and labour for unloading the wagons involved in the accident is the duty of __________.',
                  options: ['Chief Controller/Dy. Chief Controller (Stock)', 'C & W Control', 'Commercial Control', 'Engineering Control'],
                  correct: 0,
                  explanation: 'Commercial Control is the correct answer.',
                },
                {
                  question: 'Freight train ordering message is called __________.',
                  options: ['Control order', 'Train notice', 'CC Message', 'None of the above'],
                  correct: 0,
                  explanation: 'CC Message is the correct answer.',
                },
                {
                  question: 'Power plan indicates the number of Locos required for __________.',
                  options: ['Coaching service', 'Freight service', 'Parcel express service', 'None of the above'],
                  correct: 0,
                  explanation: 'Freight service is the correct answer.',
                },
                {
                  question: 'Loco outage can be prepared __________.',
                  options: ['Service-wise', 'Shed-wise', 'Traction-wise', 'All the above'],
                  correct: 0,
                  explanation: 'All the above is the correct answer.',
                },
                {
                  question: 'Which statement is correct?',
                  options: [
                    'Freight train ordering cannot be cancelled',
                    'Freight train cannot be re-ordered',
                    'Freight train ordering can be rescheduled/put back',
                    'All the above'
                  ],
                  correct: 0,
                  explanation: 'Freight train ordering can be rescheduled/put back is the correct answer.',
                },
                {
                  question: 'Allotment despite restrictions is controlled at __________.',
                  options: ['Railway Board level', 'Zonal HQ level', 'Divisional level', 'Area control level'],
                  correct: 0,
                  explanation: 'Railway Board level is the correct answer.',
                },
                {
                  question: 'System of signalling, Interlocking & communication arrangements is mentioned in which appendix of Station Working Rule?',
                  options: ['Appendix "A"', 'Appendix "B"', 'Appendix "E"', 'None of the above'],
                  correct: 0,
                  explanation: 'Appendix "A" is the correct answer.',
                },
                {
                  question: 'Main body of Station Working Rule is signed by __________.',
                  options: [
                    'Officers of Operating & Signal Department',
                    'Officers of only Operating department',
                    'Officers of Operating & Engineering Department',
                    'None of the above'
                  ],
                  correct: 0,
                  explanation: 'Officers of Operating & Signal Department is the correct answer.',
                },
                {
                  question: 'The period for which Muster Roll should be preserved from the date of its completion?',
                  options: ['1 year', '2 years', '3 years', 'Permanent record'],
                  correct: 0,
                  explanation: '3 years is the correct answer.',
                },
                {
                  question: 'A substitute of Shunting Limit Board (SLB) is __________.',
                  options: ['Calling on signal', 'Starter', 'First stop signal', 'Last stop signal'],
                  correct: 0,
                  explanation: 'Calling on signal is the correct answer.',
                },
                {
                  question: 'When a shunt signal is placed below a stop signal, it shall show __________ light in the "ON" position.',
                  options: ['White', 'Yellow', 'Red', 'No light'],
                  correct: 0,
                  explanation: 'No light is the correct answer.',
                },
                {
                  question: 'A Loco Pilot/Assistant Loco Pilot should record in the register __________ days in advance that he is lapsing road learning in a section.',
                  options: ['7 days', '13 days', '15 days', 'None of the above'],
                  correct: 0,
                  explanation: '13 days is the correct answer.',
                },
                {
                  question: 'Continuous night duty for Running Staff should be limited to __________ nights with last night duty towards Headquarters.',
                  options: ['3 nights', '4 nights', '5 nights', 'None of the above'],
                  correct: 0,
                  explanation: '4 nights is the correct answer.',
                },
                {
                  question: 'The out station rest, in case of 8 hours or more duty from Sign ON to Sign OFF in the previous trip, should be __________ hours.',
                  options: ['4 hours', '6 hours', '8 hours', 'None of the above'],
                  correct: 0,
                  explanation: '8 hours is the correct answer.',
                },
                {
                  question: 'The permitted ineffective percentages for Maintenance & Traffic spares of AC coaches (other than Rajadhani/Shatabdi & similar premium trains) are __________.',
                  options: [
                    '6% Maintenance & 5% Traffic',
                    '5% Maintenance & 6% Traffic',
                    '9% Maintenance & 7% Traffic',
                    'None of the above'
                  ],
                  correct: 0,
                  explanation: '6% Maintenance & 5% Traffic is the correct answer.',
                },
                
                    {
                      question: 'What is the minimum Axle Load route prevailing in Indian Railways?',
                      options: ['20 tonne', '22 tonne', '22.4 tonne', '22.9 tonne'],
                      correct: 0,
                      explanation: '20 tonne is the correct answer.',
                    },
                    {
                      question: 'In which of the following Zone, 25 Tonne Axle Load Route is not available?',
                      options: ['SER', 'SCR', 'ECoR', 'None of the above'],
                      correct: 0,
                      explanation: 'SER is the correct answer.',
                    },
                    {
                      question: 'In case of emergency, CC+6 loaded wagons can be permitted on exceeded CC+6 routes. Permission can be given by __________.',
                      options: ['PCE', 'PCOM', 'CRS', 'None of the above'],
                      correct: 0,
                      explanation: 'PCOM is the correct answer.',
                    },
                    {
                      question: 'Which of the following statements are not correct about mini rake?',
                      options: [
                        'Mini rake can be loaded with iron ore',
                        'Mini rake is charged at Train Load Class',
                        'Mini rakes are permitted only in covered wagons',
                        'Free time for loading / unloading of mini rake will be 5 hours'
                      ],
                      correct: 0,
                      explanation: 'Mini rakes are permitted only in covered wagons is the correct answer.',
                    },
                    {
                      question: 'Explosives are divided into how many classes?',
                      options: ['3', '5', '7', 'None of the above'],
                      correct: 0,
                      explanation: '7 is the correct answer.',
                    },
                    {
                      question: 'Free time for unloading of BTPN type of wagon under Engine on Load Scheme is given as __________.',
                      options: ['5 hours', '6 hours', '9 hours', 'None of the above'],
                      correct: 0,
                      explanation: '6 hours is the correct answer.',
                    },
                    {
                      question: 'If passenger carrying train does not arrive within __________ minutes after allowing for its normal running time from the station in rear, the Station Master at the station in advance shall immediately advise the station in rear and the control of this fact.',
                      options: ['5', '10', '15', 'None of the above'],
                      correct: 0,
                      explanation: '5 minutes is the correct answer.',
                    },
                    {
                      question: 'The powers to grant traffic blocks upto __________ hours have been given to DRM.',
                      options: ['3', '4', 'Full powers', 'None of the above'],
                      correct: 0,
                      explanation: '4 hours is the correct answer.',
                    },
                    {
                      question: 'General Manager can sanction NI upto __________ days subject to certain conditions.',
                      options: ['1', '2', '3', 'None of the above'],
                      correct: 0,
                      explanation: '3 days is the correct answer.',
                    },
                    {
                      question: 'ETA @ __________ minute per 100 kms shall be provided in sections having speed of 130 kmph and above.',
                      options: ['4', '6', '8', 'None of the above'],
                      correct: 0,
                      explanation: '6 minutes per 100 kms is the correct answer.',
                    },
                    {
                      question: 'Which of the following is not a luxury tourist train?',
                      options: ['Royal Rajasthan on Wheels', 'Maharaja Express', 'Panj Takht', 'None of the above'],
                      correct: 0,
                      explanation: 'Panj Takht is the correct answer.',
                    },
                    {
                      question: 'In case of train running with LHB coaches with deflated air spring in secondary stage suspension, train is permitted to run at __________ kmph speed.',
                      options: ['50', '60', '90', 'None of the above'],
                      correct: 0,
                      explanation: '60 kmph is the correct answer.',
                    },
                    {
                      question: 'Formula for Loco outage is __________.',
                      options: [
                        'Total engine hours from shed/24',
                        'Engine hours for traffic use/12',
                        'Total engine hours from shed/12',
                        'Engine hours for traffic use/24'
                      ],
                      correct: 0,
                      explanation: 'Total engine hours from shed/24 is the correct answer.',
                    },
                    {
                      question: 'Loco/Power links are prepared by __________.',
                      options: ["HQ's office", "Divisions' office", 'Loco lobbies', 'None of the above'],
                      correct: 0,
                      explanation: "HQ's office is the correct answer.",
                    },
                    {
                      question: 'The periodicity of Loco maintenance schedule IB for coaching locos (conventional) is __________.',
                      options: ['40 +/- 3 days', '80 +/- 3 days', '60 +/- 3 days', 'None of the above'],
                      correct: 0,
                      explanation: '40 +/- 3 days is the correct answer.',
                    },
                    {
                      question: "Guard's rough journal is required to be preserved for the period of __________.",
                      options: ['2 years', '3 years', '5 years', 'None of the above'],
                      correct: 0,
                      explanation: '2 years is the correct answer.',
                    },
                    {
                      question: 'At what time intervals are the running staff reviewed?',
                      options: ['6 months', '1 year', '2 years', 'None of the above'],
                      correct: 0,
                      explanation: '6 months is the correct answer.',
                    },
                    {
                      question: 'How many dead engines can be attached to Mail/Express/Superfast trains?',
                      options: ['1', '2', 'Cannot be attached', 'None of the above'],
                      correct: 0,
                      explanation: '1 is the correct answer.',
                    },
                    {
                      question: 'What is the gross clearance of "B" class ODC?',
                      options: ['Less than 6 inches', '6 inches or more but less than 9 inches', '9 inches or more', 'None of the above'],
                      correct: 0,
                      explanation: '6 inches or more but less than 9 inches is the correct answer.',
                    },
                    {
                      question: 'The modified Semi-Automatic stop signal is controlled by __________.',
                      options: ['SM in rear', 'SM in advance', 'Either A or B', 'None of the above'],
                      correct: 0,
                      explanation: 'SM in advance is the correct answer.',
                    },
                  
                    
                        {
                          question: 'Who permits Inter Railway movement of A class ODC?',
                          options: ['CRS', 'PCOM of the same zone', 'Sr. DOM', 'PCOM of the same zone and PCOM of the Railway concerned'],
                          correct: 0,
                          explanation: 'PCOM of the same zone and PCOM of the Railway concerned is the correct answer.',
                        },
                        {
                          question: 'What is the maximum speed of A class ODC in BG?',
                          options: ['40 kmph', 'Sectional speed', '60 kmph', 'None of the above'],
                          correct: 0,
                          explanation: 'Sectional speed is the correct answer.',
                        },
                        {
                          question: 'The mid-section modified semi-automatic stop signal is interlocked with ________',
                          options: ['LSS of station in rear', 'FSS of station in advance', 'Both A & B', 'Either A or B'],
                          correct: 0,
                          explanation: 'Both A & B is the correct answer.',
                        },
                        {
                          question: 'Preferential Traffic Order (PTO) is issued under which section of Railway Act 1989?',
                          options: ['Section 70', 'Section 71', 'Section 72', 'None of the above'],
                          correct: 0,
                          explanation: 'Section 71 is the correct answer.',
                        },
                        {
                          question: 'Free time for unloading of BCN type of wagon under Engine on Load scheme is given as ________',
                          options: ['4 hours', '5 hours', '6 hours', 'None of the above'],
                          correct: 0,
                          explanation: '6 hours is the correct answer.',
                        },
                        {
                          question: 'Software Aided Train Schedule And Network Governance (SASTANG) program is used for ________',
                          options: ['Time tabling of passengers trains', 'Time tabling of freight trains', 'Effective utilization of wagons', 'Effective utilization of Crew'],
                          correct: 0,
                          explanation: 'Time tabling of passengers trains is the correct answer.',
                        },
                        {
                          question: 'Full form of CADAT is ________',
                          options: ['Computer Aided Drivers Awareness Test', 'Comprehensive Awareness of Drivers Ability Test', 'Computer Aided Drivers Aptitude Test', 'None of the above'],
                          correct: 0,
                          explanation: 'Computer Aided Drivers Aptitude Test is the correct answer.',
                        },
                        {
                          question: 'Full form of RFID is ________',
                          options: ['Rail Frequency Identity Device', 'Radio Forwarding Indentification Device', 'Rail Forwarding Intact Device', 'Radio Frequency Identification'],
                          correct: 0,
                          explanation: 'Radio Frequency Identification is the correct answer.',
                        },
                        {
                          question: 'Train Collision Avoidance System (TCAS) is an indigenously developed Automatic Protection System meant to provide protection to trains against ________',
                          options: ['Signal Passing At Danger (SPAD)', 'Over speeding', 'Collisions', 'All the above'],
                          correct: 0,
                          explanation: 'All the above is the correct answer.',
                        },
                        {
                          question: 'The maximum speed of a train in a double line section shall be restricted to ________ kmph during fog, in automatic area.',
                          options: ['10', '15', '30', 'None of the above'],
                          correct: 0,
                          explanation: '30 kmph is the correct answer.',
                        },
                        {
                          question: 'Every Loco pilot and ALP shall "Sing ON" ________ minutes in advance for examining and taking over the Multiple Unit Electric Engine in the shed.',
                          options: ['30', '45', '60', 'None of the above'],
                          correct: 0,
                          explanation: '45 minutes is the correct answer.',
                        },
                        {
                          question: 'Record foil of the Caution order shall be preserved for period of how many months?',
                          options: ['4', '6', '12', 'Permanently'],
                          correct: 0,
                          explanation: '6 months is the correct answer.',
                        },
                        {
                          question: 'If Loco pilot and/or the guard failed to exchange signal with the station staff and the same has been reported to the Station Master of the block station in advance, the Station Master of block station in advance shall ________',
                          options: ['Stop and examine the train', 'Stop the train and hand over a written warning to the defaulting staff', 'Ensure whether LP and Guard is available or not', 'None of the above'],
                          correct: 0,
                          explanation: 'Stop and examine the train is the correct answer.',
                        },
                        {
                          question: 'Section will be considered saturated when line capacity exceeds ________',
                          options: ['100% of charted capacity', '90% of charted capacity', '80% of charted capacity', 'None of the above'],
                          correct: 0,
                          explanation: '90% of charted capacity is the correct answer.',
                        },
                        {
                          question: 'W/L board is provided on the approach of all level crossing at a distance of ________ meters.',
                          options: ['400', '600', '800', 'None of the above'],
                          correct: 0,
                          explanation: '600 meters is the correct answer.',
                        },
                        {
                          question: 'When running through between block stations and when running with the engine leading, the speed of a material train shall not exceed ________',
                          options: ['25 kmph', '40 kmph', 'Speed prescribed for goods train of similar stock', 'None of the above'],
                          correct: 0,
                          explanation: 'Speed prescribed for goods train of similar stock is the correct answer.',
                        },
                        {
                          question: 'The brake feel test is done by Loco pilot at the speed of ________ kmph.',
                          options: ['15', '40', '50', 'None of the above'],
                          correct: 0,
                          explanation: '15 kmph is the correct answer.',
                        },
                        {
                          question: 'The correct sequence in which following plans/drawings are prepared?',
                          options: ['SIP, ESP, SWRD', 'ESP, SIP, SWRD', 'SIP, SWRD. ESP', 'SWRD, SIP, ESP'],
                          correct: 0,
                          explanation: 'SIP, ESP, SWRD is the correct answer.',
                        },
                        {
                          question: 'The code for AC Chair Car Second Class of broad gauge coaching stock is ________',
                          options: ['WGSCZAC', 'WSCZAC', 'WGFCZ', 'None of the above'],
                          correct: 0,
                          explanation: 'WGSCZAC is the correct answer.',
                        },
                        {
                          question: 'When IBS is at "ON" and if telephone is not provided or out of order at Intermediate Block Post, Loco pilot after waiting for ________ minutes at the signal shall pass it at "ON" proceeding cautiously.',
                          options: ['5', '7', '10', '15'],
                          correct: 0,
                          explanation: '5 minutes is the correct answer.',
                        },
                      
                        
                            {
                              question: 'Sand Hump is an extended portion of rail in sand with increasing gradient of ________',
                              options: ['1 in 60', '1 in 80', '1 in 100', 'None of the above'],
                              correct: 0,
                              explanation: '1 in 60 is the correct answer.',
                            },
                            {
                              question: 'TVU of special class LC gate shall be ________',
                              options: ['Greater than 40000', 'Greater than 45000', 'Greater than 50000', 'None of the above'],
                              correct: 0,
                              explanation: 'Greater than 50000 is the correct answer.',
                            },
                            {
                              question: 'The distance of derailing switch from the points is about ________ feet.',
                              options: ['10', '15', '20', 'None of the above'],
                              correct: 0,
                              explanation: '15 feet is the correct answer.',
                            },
                            {
                              question: 'The Certificate Competency for operation of Block Instrument shall be valid for a period of ________ years.',
                              options: ['2', '3', '4', 'None of the above'],
                              correct: 0,
                              explanation: '3 years is the correct answer.',
                            },
                            {
                              question: 'Brake power percentage of an ordinary "End to End" Air Brake rake other than premium rake at en-route station should be ________',
                              options: ['75%', '85%', '95%', 'None of the above'],
                              correct: 0,
                              explanation: '95% is the correct answer.',
                            },
                            {
                              question: 'Colour Light Distant Signal may be combined with LSS, Gate Stop Signal etc. under ________',
                              options: ['Approved Special Instruction', 'Special Instruction', 'Working Instruction', 'None of the above'],
                              correct: 0,
                              explanation: 'Approved Special Instruction is the correct answer.',
                            },
                            {
                              question: 'A Railway servant is debarred of taking any Alcoholic drink/Sedative/Narcotic/Stimulant drug or preparation within how many hours before the commencement of his duty or when on duty ________',
                              options: ['6 hours', '8 hours', '12 hours', 'None of the above'],
                              correct: 0,
                              explanation: '8 hours is the correct answer.',
                            },
                            {
                              question: 'At a "B" Class double line MACL station, rear block section terminates at ________',
                              options: ['Outermost facing point', 'BSLB', 'Either A or B', 'None of the above'],
                              correct: 0,
                              explanation: 'BSLB is the correct answer.',
                            },
                            {
                              question: 'At a "B" class double line MACL station, while performing shunting up to the First stop signal in rear i.e. up to the Home signal, Block Back is ________',
                              options: ['Necessary', 'Not Necessary', 'Depends on layout', 'None of the above'],
                              correct: 0,
                              explanation: 'Not Necessary is the correct answer.',
                            },
                            {
                              question: 'If outside station limits, distance between two trains is ________ meter or more, such occurrence may not be treated as averted collision.',
                              options: ['250', '400', '500', '600'],
                              correct: 0,
                              explanation: '500 meters is the correct answer.',
                            },
                            {
                              question: '"Smell of burning grease" is the symptom of ________',
                              options: ['Seizure of roller bearing', 'Brake binding', 'Flat tyre', 'None of the above'],
                              correct: 0,
                              explanation: 'Seizure of roller bearing is the correct answer.',
                            },
                            {
                              question: 'A decrease in net tonne kilometer per engine hours may be due to ________',
                              options: ['Increase in the proportion of unbalanced traffic', 'Increase in the average starting wagon load', 'Decrease in shunting engine hours', 'Decrease in light engine running'],
                              correct: 0,
                              explanation: 'Increase in the proportion of unbalanced traffic is the correct answer.',
                            },
                            {
                              question: 'Which among the following is not a means of isolation?',
                              options: ['Sand Hump', 'Derailing swich', 'Skid', 'Snag dead end'],
                              correct: 0,
                              explanation: 'Skid is the correct answer.',
                            },
                            {
                              question: 'Which light of hand signal will be used by guard in night to inform the loco pilot at the time of train parting?',
                              options: ['Red', 'Green', 'White', 'None of the above'],
                              correct: 0,
                              explanation: 'Red is the correct answer.',
                            },
                            {
                              question: 'Transportation of Coal for power houses is categorized under which category under priority schedule?',
                              options: ['Priority "A"', 'Priority "B"', 'Priority "C"', 'Priority "D"'],
                              correct: 0,
                              explanation: 'Priority "A" is the correct answer.',
                            },


{
  question: 'Which Tennis player has been on the top of the ATP rakings for maximum period?',
  options: ['Novak Djokovic', 'Roger Federer', 'Rafael Nadal', 'None of the above'],
  correct: 0,
  explanation: 'Novak Djokovic is the correct answer.',
},
{
  question: 'Which Indian athlete is also known as "Udan Pari"?',
  options: ['Hima Das', 'Dutee Chand', 'PT Usha', 'None of the above'],
  correct: 2,
  explanation: 'PT Usha is the correct answer.',
},
{
  question: 'Which Indian cricketer has also been President of BCCI?',
  options: ['Kapil Dev', 'Sunil Gavaskar', 'Sourav Ganguly', 'None of the above'],
  correct: 2,
  explanation: 'Sourav Ganguly is the correct answer.',
},
{
  question: 'Which country has won the most World cups in Football?',
  options: ['Brazil', 'Germany', 'Argentina', 'None of the above'],
  correct: 0,
  explanation: 'Brazil is the correct answer.',
},
{
  question: 'Who is the first Indian player to win an individual Gold in Olympics?',
  options: ['Abhinav Bindra', 'Neeraj Chopra', 'Sushil Kumar', 'None of the above'],
  correct: 0,
  explanation: 'Abhinav Bindra is the correct answer.',
},
{
  question: 'Vijender Signgh is associated with which sport?',
  options: ['Boxing', 'Archery', 'Wrestling', 'None of the above'],
  correct: 0,
  explanation: 'Boxing is the correct answer.',
},
{
  question: 'The number of centuries made by Sachin Tendulkar in International matches is ________',
  options: ['98', '99', '100', 'None of the above'],
  correct: 2,
  explanation: '100 is the correct answer.',
},
{
  question: 'Irani Trophy is associated with which sport?',
  options: ['Cricket', 'Football', 'Hockey', 'None of the above'],
  correct: 0,
  explanation: 'Cricket is the correct answer.',
},
{
  question: 'The number of Gold medals won by India in Olympics till now is ________',
  options: ['7', '8', '9', 'None of the above'],
  correct: 1,
  explanation: '8 is the correct answer.',
},
{
  question: 'The word "Butterfly" is associated with which sport?',
  options: ['Swimming', 'Football', 'Hockey', 'None of the above'],
  correct: 0,
  explanation: 'Swimming is the correct answer.',
},
{
  question: 'Which one of the following does NOT constitute the electoral college for electing the President of India?',
  options: ['Elected member of Lok Sabha', 'Elected member of Rajya Sabha', 'Elected member of State Legislative Assembly each state', 'None of the above'],
  correct: 3,
  explanation: 'None of the above is the correct answer.',
},
{
  question: 'A person who is not a member of Parliament can be appointed as a Minister by the President of India for a maximum period of ________',
  options: ['6 months', '1 year', '2 years', 'None of the above'],
  correct: 0,
  explanation: '6 months is the correct answer.',
},
{
  question: 'Who among the following can be attend meetings of the Union Cabinet?',
  options: ['Cabinet Ministers', 'Ministers of State', 'Deputy Ministers', 'None of the above'],
  correct: 0,
  explanation: 'Cabinet Ministers is the correct answer.',
},
{
  question: 'When was the Constitution of India implemented?',
  options: ['26th January 1950', '26th January 1951', '26th January 1952', 'None of the above'],
  correct: 0,
  explanation: '26th January 1950 is the correct answer.',
},
{
  question: 'What is the strength of the Public Accounts Committee?',
  options: ['10 from Lok Sabha and 5 from Rajya Sabha', '15 from Lok Sabha and 7 from Rajya Sabha', '15 from Lok Sabha and 10 from Rajya Sabha', 'None of the above'],
  correct: 1,
  explanation: '15 from Lok Sabha and 7 from Rajya Sabha is the correct answer.',
},
{
  question: 'Quit India Movement was launched in response to ________',
  options: ['The Rowlatt Act', 'The Simon Commission', 'Cripps Proposal', 'None of the above'],
  correct: 2,
  explanation: 'Cripps Proposal is the correct answer.',
},
{
  question: 'The state of Bengal was partitioned by Lord Curzon in the year ________',
  options: ['1905', '1906', '1907', 'None of the above'],
  correct: 0,
  explanation: '1905 is the correct answer.',
},
{
  question: 'Indian National Congress was founded in the year ________',
  options: ['1885', '1886', '1887', 'None of the above'],
  correct: 0,
  explanation: '1885 is the correct answer.',
},
{
  question: 'Who was the Gandhiji\'s nominee defeated by Subash Chandra Bose for the Presidentship of the Congress in 1939?',
  options: ['Pattabhi Sitaramayya', 'Sardar Vallabhbhai Patel', 'Srinivas Iyengar', 'None of the above'],
  correct: 0,
  explanation: 'Pattabhi Sitaramayya is the correct answer.',
},
{
  question: 'The battle of Plassey was fought in the year ________',
  options: ['1757', '1758', '1759', 'None of the above'],
  correct: 0,
  explanation: '1757 is the correct answer.',
},
{
  question: 'Tulasidas the author of Ramcharitmanas was a contemporary of which of the following Rulers?',
  options: ['Akbar', 'Shah Jahan', 'Aurangzeb', 'None of the above'],
  correct: 0,
  explanation: 'Akbar is the correct answer.',
},
{
  question: 'The Radcliffe line is a boundary between which two countries?',
  options: ['India and Pakistan', 'India and China', 'India and Myanmar', 'None of the above'],
  correct: 0,
  explanation: 'India and Pakistan is the correct answer.',
},
{
  question: 'The following monsoon contributes most of the rains in India?',
  options: ['North West Monsoon', 'South West Monsoon', 'North East Monsoon', 'None of the above'],
  correct: 1,
  explanation: 'South West Monsoon is the correct answer.',
},
{
  question: 'Which atomic power station in India is built completely indigenously?',
  options: ['Tarapur', 'Kalpakkam', 'Rajasthan', 'None of the above'],
  correct: 3,
  explanation: 'None of the above is the correct answer.',
},
{
  question: 'Which of the following important rivers of Indian does NOT originate in the Western Ghats?',
  options: ['Godavari', 'Kaveri', 'Krishna', 'None of the above'],
  correct: 3,
  explanation: 'None of the above is the correct answer.',
},
{
  question: 'When it is noon IST at Allahabad in India, the time at Greenwhich in London is ________',
  options: ['06:30 hours', '17:30 hours', 'Midnight, GMT', 'None of the above'],
  correct: 0,
  explanation: '06:30 hours is the correct answer.',
},
{
  question: 'Carbon, diamond and graphite are together called as ________',
  options: ['Allotropes', 'Isomers', 'Isomorphs', 'None of the above'],
  correct: 0,
  explanation: 'Allotropes is the correct answer.',
},
{
  question: 'The first chairman of Atomic Energy Commission was ________',
  options: ['Dr. Homi J Bhabha', 'Dr. Vikram Sarabhai', 'Chandrasekhara Venkata Raman', 'None of the above'],
  correct: 0,
  explanation: 'Dr. Homi J Bhabha is the correct answer.',
},
{
  question: 'Name the Governor General who abolished the Sati Pratha in 1829?',
  options: ['Lord William Bentinck', 'Lord William Mayo', 'Lord Cornwallis', 'None of the above'],
  correct: 0,
  explanation: 'Lord William Bentinck is the correct answer.',
},
{
  question: 'The Yellowstone National Park is located in which country?',
  options: ['Russia', 'Canada', 'USA', 'None of the above'],
  correct: 2,
  explanation: 'USA is the correct answer.',
},
{
  question: 'Who founded the Indian Statistical Institute on 17 December 1931?',
  options: ['R A Fisher', 'P C Mahalanobis', 'F Yates', 'None of the above'],
  correct: 1,
  explanation: 'P C Mahalanobis is the correct answer.',
},
{
  question: 'Who was the first Indian to win all England Badminton Championships?',
  options: ['Prakash Padukone', 'P. V. Sindhu', 'Saina Nehwal', 'None of the above'],
  correct: 0,
  explanation: 'Prakash Padukone is the correct answer.',
},
{
  question: 'Between whom did the third battle of Panipat was fought?',
  options: ['Akbar & Hemu', 'Ahmad Shah Abdali & Maratha', 'Babur and Ibrahim Lodi', 'None of the above'],
  correct: 1,
  explanation: 'Ahmad Shah Abdali and Maratha is the correct answer.',
},
{
  question: 'If the pH value of any type of soil is 10, then the soil will be considered as ________',
  options: ['Acidic', 'Basic', 'Alkaline', 'None of the above'],
  correct: 2,
  explanation: 'Alkaline is the correct answer.',
},
{
  question: 'Nanda Devi peak is located in which state?',
  options: ['Uttarakhand', 'Himachal Pradesh', 'Jammu and Kashmir', 'None of the above'],
  correct: 0,
  explanation: 'Uttarakhand is the correct answer.',
},
{
  question: 'Silent Valley National Park is located in which state?',
  options: ['Kerala', 'Tamil Nadu', 'Karnataka', 'None of the above'],
  correct: 0,
  explanation: 'Kerala is the correct answer.',
},
{
  question: 'What is the literacy rate in India as on 2011?',
  options: ['74.04%', '75.04%', '76.04%', 'None of the above'],
  correct: 0,
  explanation: '74.04% is the correct answer.',
},
{
  question: 'Coking Coil is a vital input in which of the folowing industries?',
  options: ['Sponge Iron', 'Steel', 'Copper', 'None of the above'],
  correct: 1,
  explanation: 'Steel is the correct answer.',
},
{
  question: 'Who is the Director of the RRR, whose song won the Oscar Award for Best Original Song in 2023?',
  options: ['S. S. Rajamouli', 'Rajkumar Hirani', 'Rajkumar Santoshi', 'None of the above'],
  correct: 0,
  explanation: 'S. S. Rajamouli is the correct answer.',
},
{
  question: 'Which country has recently banned domestic flights for journeys that are possible in less than two and half hours by Train?',
  options: ['India', 'France', 'Spain', 'None of the above'],
  correct: 1,
  explanation: 'France is the correct answer.',
},
{
  question: 'Who is called an employee proficient in Hindi?',
  options: ['Knowledge of Hindi at Primary level', 'Passed Primary level exam in Hindi medium', 'Knowledge of Hindi at Matriculation level', 'Matriculation level exam passed in Hindi medium'],
  correct: 3,
  explanation: 'Matriculation level exam passed in Hindi medium is the correct answer.',
},
{
  question: 'Which is the foreign language included in the Eight Schedule?',
  options: ['Nepali', 'Persian', 'English', 'None of the above'],
  correct: 0,
  explanation: 'Nepali is the correct answer.',
},
{
  question: 'Who is the Chairman of Railway Board Official Language Implementation Committee?',
  options: ['Minister of Railways', 'Prime Minister', 'Chairman and CEO, Railway Board', 'None of the above'],
  correct: 2,
  explanation: 'Chairman and CEO, Railway Board is the correct answer.',
},

{
                              question: 'Who is the Chairman of Central Hindi Committee?',
                              options: ['Home Minister', 'Prime Minister', 'Railway Minister', 'None of the above'],
                              correct: 0,
                              explanation: 'Prime Minister is the correct answer.',
                            },
                            {
                              question: 'For what purpose Lal Bahadur Shastri Takaniki Maulik Lekhan Award is given?',
                              options: ['To write books in Hindi literature', 'To write technical books in Hindi on Railway subjects', 'For story/story collection and novel writting', 'None of the above'],
                              correct: 0,
                              explanation: 'To write technical books in Hindi on Railway subjects is the correct answer.',
                            },
                            
                                {
                                  question: 'How many members of Rajya Sabha are there in Committee of Parliament on Official Language?',
                                  options: ['7', '10', '15', 'None of the above'],
                                  correct: 0,
                                  explanation: '10 is the correct answer.',
                                },
                                {
                                  question: 'How many sections are there in the Official Language Act, 1963?',
                                  options: ['8', '9', '10', 'None of the above'],
                                  correct: 0,
                                  explanation: '9 is the correct answer.',
                                },
                                {
                                  question: 'In which language is there a provision to give the documents related to disciplinary proceedings to the employee?',
                                  options: ['Regional language', 'Hindi', 'Hindi or English - in which the employee wants', 'None of the above'],
                                  correct: 0,
                                  explanation: 'Hindi or English - in which the employee wants is the correct answer.',
                                },
                                {
                                  question: 'Who is the Chairman of the Zonal Railway Official Language Implementation Committee?',
                                  options: ['General Manager', 'Additional General Manager', 'Chief Rajabhasha Officer', 'None of the above'],
                                  correct: 0,
                                  explanation: 'General Manager is the correct answer.',
                                },
                                {
                                  question: 'What is the introductory course for central government employees?',
                                  options: ['Praveen', 'Prabodh', 'Pragya', 'None of the above'],
                                  correct: 0,
                                  explanation: 'Prabodh is the correct answer.',
                                },
                                {
                                  question: 'In which language order are the announcements to be made at Railway stations?',
                                  options: ['Local, Hindi, English', 'Regional, English, Hindi', 'Regional, Hindi, English', 'None of the above'],
                                  correct: 0,
                                  explanation: 'Regional, Hindi, English is the correct answer.',
                                },
                                
                                  {
                                    question: 'Who does the translation of statutory rules, regulations and orders as per the constitution of India?',
                                    options: ['Home Ministry', 'Ministry of Law', 'Ministry of Railways', 'None of the above'],
                                    correct: 1,
                                    explanation: 'Ministry of Law is the correct answer.',
                                  },
                                
                                {
                                  question: 'For whom is the Rajabhasha Individual Cash Award Scheme prescribed?',
                                  options: ['For employees', 'For officers', 'For officers up to Junior Administrative Grade and non-gazetted categories', 'For Senior Administrative Grade Officers'],
                                  correct: 0,
                                  explanation: 'For officers up to Junior Administrative Grade and non-gazetted categories is the correct answer.',
                                },
                                {
                                  question: 'Hindi Salahkar Samithi is constituted in which ministry?',
                                  options: ['In all ministries', 'In the Ministry of Home Affairs', 'In the Ministry of Education', 'In the Ministry of Finance'],
                                  correct: 0,
                                  explanation: 'In all ministries is the correct answer.',
                                },
                                {
                                  question: 'What is the amount of the first prize under the Rail Travelogue Award Scheme?',
                                  options: ['6000/- and citation', '8000/- and citation', '10000/- and citation', 'None of the above'],
                                  correct: 0,
                                  explanation: '10000/- and citation is the correct answer.',
                                },
                                {
                                  question: 'What is the full form of PRAN? How many digits does a PRAN number have?',
                                  options: ['Permanent Retirement Account Number, 12', 'Provident Retirement Account Number, 12', 'Permanent Railway Account Number, 14', 'Permanent Railwaymen\'s Account Number, 12'],
                                  correct: 0,
                                  explanation: 'Permanent Retirement Account Number, 12 is the correct answer.',
                                },
                                {
                                  question: 'What is upper limit of Child Care Leave for Railway employees?',
                                  options: ['90 days', '365 days', '730 days', 'None of the above'],
                                  correct: 0,
                                  explanation: '730 days is the correct answer.',
                                },
                                {
                                  question: 'Which Authority is empowered to order for cut in Pension of Retired Railway Servant under DAR proceedings?',
                                  options: ['DRM', 'GM', 'President of India', 'None of the above'],
                                  correct: 0,
                                  explanation: 'President of India is the correct answer.',
                                },
                                {
                                  question: 'Who can allow for personal hearing in major penalty cases?',
                                  options: ['Appellate Authority', 'Appointing Authority', 'Disciplinary Authority', 'None of the above'],
                                  correct: 0,
                                  explanation: 'Disciplinary Authority is the correct answer.',
                                },
                                {
                                  question: 'What is the maximum period of suspension that can be extended at a time after review of the Competent Authority?',
                                  options: ['120 days', '150 days', '180 days', 'None of the above'],
                                  correct: 0,
                                  explanation: '180 days is the correct answer.',
                                },
                                {
                                  question: 'What is the minimum period of Child Care Leave to be considered for sanction to a female Government servant?',
                                  options: ['5 days', '10 days', '15 days', '20 days'],
                                  correct: 0,
                                  explanation: '5 days is the correct answer.',
                                },
                                {
                                  question: 'What is the penalty per day to be imposed against a Central Public Information Officer for giving misleading information?',
                                  options: ['100/- per day', '250/- per day', '500/- per day', 'None of the above'],
                                  correct: 0,
                                  explanation: '250/- per day is the correct answer.',
                                },
                                {
                                  question: 'What is the time period for transfer of application to other Public Authority for request of information under section 6(3) of the RTI Act?',
                                  options: ['7 days', '10 days', '15 days', '30 days'],
                                  correct: 1,
                                  explanation: '10 days is the correct answer.',
                                },
                                {
                                  question: 'In case of availing Child Care Leave, the age of dependent disabled children should be up to ________',
                                  options: ['18 years', '22 years', '25 years', 'No limit'],
                                  correct: 0,
                                  explanation: 'No limit is the correct answer.',
                                },
                                {
                                  question: 'Who is the custodian of listed documents in a Departmental Enquiry?',
                                  options: ['Disciplinary Authority', 'Inquiry Officer', 'Presenting Officer', 'None of the above'],
                                  correct: 2,
                                  explanation: 'Presenting Officer is the correct answer.',
                                },
                                {
                                  question: 'Who will take a decision whether the charges have been established before passing final orders?',
                                  options: ['Disciplinary Authority', 'Inquiry Officer', 'Presenting Officer', 'None of the above'],
                                  correct: 0,
                                  explanation: 'Disciplinary Authority is the correct answer.',
                                },
                                {
                                  question: 'Railway Services (Conduct) Rules were passed in ________',
                                  options: ['1961', '1966', '1987', '1989'],
                                  correct: 0,
                                  explanation: '1966 is the correct answer.',
                                },
                                {
                                  question: 'The period of maternity leave on account of miscarriage/abortion should be restricted to ________ days during the entire service.',
                                  options: ['30', '45', '180', 'None of the above'],
                                  correct: 0,
                                  explanation: '45 days is the correct answer.',
                                },
                              
                                
                                    {
                                      question: 'Which part of THE RAILWAY SERVANTS (DISCIPLINE & APPEAL) RULES, 1968 gives details of major and minor penalties?',
                                      options: ['Part I', 'Part II', 'Part III', 'Part IV'],
                                      correct: 0,
                                      explanation: 'Part III is the correct answer.',
                                    },
                                    {
                                      question: 'Where appointing authority is not available, who should be treated as Appointing Authority?',
                                      options: ['Controlling officer', 'DRM', 'GM', 'CPO'],
                                      correct: 0,
                                      explanation: 'Controlling officer is the correct answer.',
                                    },
                                    {
                                      question: 'Recognized Trade Union official can be allowed to act as defence counsel in DAR cases in ________ numbers of cases.',
                                      options: ['2', '3', '4', 'Any'],
                                      correct: 0,
                                      explanation: '4 is the correct answer.',
                                    },
                                    {
                                      question: 'What is a Budget?',
                                      options: ['A statement of receipts and payments incurred in a year', 'A statement of appropriation of funds', 'A record of all expenses made', 'A statement of estimated receipts and expenditure of the Government'],
                                      correct: 3,
                                      explanation: 'A statement of estimated receipts and expenditure of the Government is the correct answer.',
                                    },
                                    {
                                      question: 'From which financial year, was the Railway Budget merged with the General Budget?',
                                      options: ['2015-16', '2016-17', '2017-18', '2018-19'],
                                      correct: 2,
                                      explanation: '2017-18 is the correct answer.',
                                    },
                                    {
                                      question: 'What does QCBS stand for ________',
                                      options: ['Quality and Cost Based Selection', 'Qunitity Conscious Bid Selection', 'Quality Contract Bid Selection', 'None of the above'],
                                      correct: 0,
                                      explanation: 'Quality and Cost Based Selection is the correct answer.',
                                    },
                                    {
                                      question: 'The expenditure of the Railways is now covered in demand for grants number ________',
                                      options: ['81', '83', '85', 'None of the above'],
                                      correct: 0,
                                      explanation: '85 is the correct answer.',
                                    },
                                    {
                                      question: 'The full form of DRF is ________',
                                      options: ['Depreciation Reserve Fund', 'Depreciation Renewal Fund', 'Development Reserve Fund', 'None of the above'],
                                      correct: 0,
                                      explanation: 'Depreciation Reserve Fund is the correct answer.',
                                    },
                                    {
                                      question: 'The gross budgetary support towards capital expenditure of Indian Railways for the year 2023-24 is?',
                                      options: ['Less than 1 lakh crore', 'Between 1 and 2 lakh crores', 'More than 2 lakh crores', 'None of the above'],
                                      correct: 0,
                                      explanation: 'More than 2 lakh crores is the correct answer.',
                                    },
                                    {
                                      question: 'The Plan Head under which works for customer amenities are included?',
                                      options: ['51', '52', '53', 'None of the above'],
                                      correct: 0,
                                      explanation: '53 is the correct answer.',
                                    },
                                    {
                                      question: 'The powers of the General Manager for sanctioning works under Plan Head 16 up to ________',
                                      options: ['Rs. 2.5 crores', 'Rs. 5 crores', 'Rs. 50 crores', 'None of the above'],
                                      correct: 0,
                                      explanation: 'Rs. 50 crores is the correct answer.',
                                    },
                                    {
                                      question: 'After the merger of the Railway Budget, what has been the major implication?',
                                      options: [
                                        'Railways no longer has to prepare its Annual Statement of Receipts & Expenditure',
                                        'The Finance Minister prepares the Railway Budget',
                                        'Railways no longer has to pay dividend to the Government',
                                        'None of the above'
                                      ],
                                      correct: 0,
                                      explanation: 'Railways no longer has to pay dividend to the Government is the correct answer.',
                                    },
                                    {
                                      question: 'Which is not an example of EBR Funding in Indian Railways?',
                                      options: ['Leased assets from IRFC', 'LIC loan', 'RRSK Funds', 'None of the above'],
                                      correct: 0,
                                      explanation: 'RRSK Funds is the correct answer.',
                                    },
                                    {
                                      question: 'What is NOT a source of funding for Indian Railways to finance its capital expenditure projects?',
                                      options: ['Extra budgetary resources', 'Gross budgetary support', 'Internal resources of Indian Railways', 'None of the above'],
                                      correct: 0,
                                      explanation: 'None of the above is the correct answer.',
                                    },
                                    {
                                      question: 'Re-appropriation of funds from one Plan Head to another Plan Head is within the powers of ________',
                                      options: ['DRM', 'PHOD', 'GM', 'Railway Board'],
                                      correct: 0,
                                      explanation: 'Railway Board is the correct answer.',
                                    },
                                    {
                                      question: 'Percentage of working expenses to gross earnings is known ________',
                                      options: ['Inventory Turn Over Ratio', 'Operating Ratio', 'Liquidity Ratio', 'None of the above'],
                                      correct: 0,
                                      explanation: 'Operating Ratio is the correct answer.',
                                    },
                                    {
                                      question: 'Abstract "Y" in Earning classification is ________',
                                      options: ['Passenger Earning', 'Goods Earning', 'Sundry Earning', 'Other coaching earning'],
                                      correct: 0,
                                      explanation: 'Sundry Earning is the correct answer.',
                                    },
                                    {
                                      question: 'Administrative approval of competent authority for incurring expenditure is accorded at this stage?',
                                      options: ['Abstract Estimate', 'Detailed Estimate', 'Revised Estimate', 'Completion Estimate'],
                                      correct: 0,
                                      explanation: 'Abstract Estimate is the correct answer.',
                                    },
                                    {
                                      question: 'Minimum notice period for quotations is ________',
                                      options: ['7 days', '10 days', '12 days', 'None of the above'],
                                      correct: 0,
                                      explanation: '7 days is the correct answer.',
                                    },
                                    {
                                      question: 'Variation beyond 150% of the contract value requires the sanction of ________',
                                      options: ['Railway Board', 'GM', 'PHOD', 'Tender Accepting Authority'],
                                      correct: 0,
                                      explanation: 'Tender Accepting Authority is the correct answer.',
                                    },
                                    {
                                      question: 'Primary Unit of allocation denotes ________',
                                      options: ['Nature of expenditure', 'Object of expenditure', 'Authority who has incurred the expenditure', 'None of the above'],
                                      correct: 0,
                                      explanation: 'Object of expenditure is the correct answer.',
                                    },
                                    {
                                      question: 'Cash in Transit is ________',
                                      options: [
                                        'The cash taken by station in the balance sheet is accounted by cash office in the following month',
                                        'The cash accounted by station in a month',
                                        'The cash accounted by cash office in a month',
                                        'None of the above'
                                      ],
                                      correct: 0,
                                      explanation: 'The cash taken by station in the balance sheet is accounted by cash office in the following month is the correct answer.',
                                    },
                                  
        ],
    },
};