import { FileArchive, FileText } from "lucide-react";

export const gsrpdfFiles = [
  {
    name: "Digital SCR G&SR 2020 upto AS 21",
    filename: "Digital SCR G&SR 2020 upto AS 21.pdf",
    size: "13MB",
    description:
      "Complete Digital SCR G&SR 2020 with all amendments up to AS 21",
    icon: FileArchive,
  },
  {
    name: "AS 24 to SCR G&SR 2020",
    filename: "AS 24 to SCR G&SR 2020.pdf",
    size: "914KB",
    description: "Amendment Slip 24 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 23 to SCR G&SR 2020",
    filename: "AS 23 to SCR G&SR 2020.pdf",
    size: "914KB",
    description: "Amendment Slip 23 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 22 to SCR G&SR 2020",
    filename: "AS 22 to SCR G&SR 2020.pdf",
    size: "1257KB",
    description: "Amendment Slip 22 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 21 to SCR G&SR 2020",
    filename: "AS 21 to SCR G&SR 2020.pdf",
    size: "657KB",
    description: "Amendment Slip 21 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 20 to G&SR 2020",
    filename: "AS 20 to G&SR 2020.pdf",
    size: "546KB",
    description: "Amendment Slip 20 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 19 to G&SR 2020",
    filename: "AS 19 to G&SR 2020.pdf",
    size: "175KB",
    description: "Amendment Slip 19 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 18 to G&SR 2020",
    filename: "AS 18 to G&SR 2020.pdf",
    size: "2969KB",
    description: "Amendment Slip 18 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 17 to G&SR 2020",
    filename: "AS 17 to G&SR 2020.pdf",
    size: "667KB",
    description: "Amendment Slip 17 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 16 to G&SR 2020",
    filename: "AS 16 to G&SR 2020.pdf",
    size: "803KB",
    description: "Amendment Slip 16 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 15 to G&SR 2020",
    filename: "AS 15 to G&SR 2020.pdf",
    size: "491KB",
    description: "Amendment Slip 15 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 14 to G&SR 2020",
    filename: "AS 14 to G&SR 2020.pdf",
    size: "1293KB",
    description: "Amendment Slip 14 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 13 to G&SR 2020",
    filename: "AS 13 to G&SR 2020.pdf",
    size: "406KB",
    description: "Amendment Slip 13 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 12 to G&SR 2020",
    filename: "AS 12 to G&SR 2020.pdf",
    size: "699KB",
    description: "Amendment Slip 12 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 11 to G&SR 2020",
    filename: "AS 11 to G&SR 2020.pdf",
    size: "125KB",
    description: "Amendment Slip 11 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 10 to G&SR 2020",
    filename: "AS 10 to G&SR 2020.pdf",
    size: "776KB",
    description: "Amendment Slip 10 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 9 to G&SR 2020",
    filename: "AS 9 to G&SR 2020.pdf",
    size: "667KB",
    description: "Amendment Slip 9 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 8 to G&SR 2020",
    filename: "AS 8 to G&SR 2020.pdf",
    size: "2115KB",
    description: "Amendment Slip 8 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 7 to G&SR 2020",
    filename: "AS 7 to G&SR 2020.pdf",
    size: "4513KB",
    description: "Amendment Slip 7 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 6 to G&SR 2020",
    filename: "AS 6 to G&SR 2020.pdf",
    size: "705KB",
    description: "Amendment Slip 6 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 5 to G&SR 2020",
    filename: "AS 5 to G&SR 2020.pdf",
    size: "2048KB",
    description: "Amendment Slip 5 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 4 to G&SR 2020",
    filename: "AS 4 to G&SR 2020.pdf",
    size: "502KB",
    description: "Amendment Slip 4 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 3 to G&SR 2020",
    filename: "AS 3 to G&SR 2020.pdf",
    size: "2924KB",
    description: "Amendment Slip 3 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 2 to G&SR 2020",
    filename: "AS 2 to G&SR 2020.pdf",
    size: "6440KB",
    description: "Amendment Slip 2 to SCR G&SR 2020",
    icon: FileText,
  },
  {
    name: "AS 1 to G&SR 2020",
    filename: "AS 1 to G&SR 2020.pdf",
    size: "357KB",
    description: "Amendment Slip 1 to SCR G&SR 2020",
    icon: FileText,
  },
];

export const accidentPdfFiles = [
  {
    name: "Accident Manual 2012 Updated",
    filename: "Accident manual SCR 2012.pdf",
    size: "5074KB",
    description:
      "Accident Manual SCR 2012 Updated Up to AS 6",
    icon: FileArchive,
  },
  {
    name: "AS 6 to Accident Manual",
    filename: "Accident Manual AS -6.pdf",
    size: "9.8MB",
    description:
      "Accident Manual Amendment Slip 6 - Latest comprehensive update",
    icon: FileArchive,
  },
  {
    name: "AS 5 to Accident Manual",
    filename: "Accident Manual AS - 5.pdf",
    size: "232KB",
    description:
      "Accident Manual Amendment Slip 5 - Safety procedures and protocols",
    icon: FileText,
  },
  {
    name: "AS 4 to Accident Manual",
    filename: "Accident Manual AS - 4.pdf",
    size: "180KB",
    description: "Accident Manual Amendment Slip 4 - Updated safety guidelines",
    icon: FileText,
  },
  {
    name: "AS 3 to Accident Manual",
    filename: "Accident Manual AS - 3.pdf",
    size: "208KB",
    description:
      "Accident Manual Amendment Slip 3 - Revised accident procedures",
    icon: FileText,
  },
  {
    name: "AS 2 to Accident Manual",
    filename: "Accident Manual AS - 2.pdf",
    size: "116KB",
    description: "Accident Manual Amendment Slip 2 - Safety protocol updates",
    icon: FileText,
  },
];

