export const aomProfessionalSubjectTest48 = {
    tests: {
        'aom-professional-subject-test-48': [
            {
                question: `The shortest section OHE that can be isolated is _______`,
                options: ['Sector', 'Sub sector', 'Elementary section', 'Neutral section'],
                correct: 2,
                explanation: `Elementary section.
                The shortest section of OHE that can be isolated remotely is Sub sector.`,
            },
            {
                question: `What is the full form of CGEGIS?`,
                options: ['Central Government Employees Group Insurance Scheme', 'Central Goverment Employees Group Increment Scheme', 'Central Government Employees Group Insurance System', 'None of the above'],
                correct: 0,
                explanation: `Central Goverment Employees Group Insurance Scheme.`,
            },
            {
                question: `How many Divisions are there in the Indian Railways?`,
                options: ['70', '72', '75', '80'],
                correct: 0,
                explanation: `70.`,
            },
            {
                question: `Which of the following zone, 25 Tonne Axle Load route is not available?`,
                options: ['ECoR', 'NWR', 'SCR', 'SER'],
                correct: 1,
                explanation: `NWR.`,
            },
            {
                question: `The thickness of wheel flange in mm is _______`,
                options: ['25.3 mm', '26.3 mm', '27.6 mm', '28.5 mm'],
                correct: 3,
                explanation: `28.5 mm.`,
            },
            {
                question: `DFC routes have upgraded design features of ________ axle load for bridges and formation.`,
                options: ['32.5 Tonne', '33.2 Tonne', '34.8 Tonne', '35 Tonne'],
                correct: 0,
                explanation: `32.5 Tonne.`,
            },
            {
                question: `Over Dimensional Consignment Movement approval and Linking is done with ______`,
                options: ['COA', 'ICMS', 'RMS', 'TMS'],
                correct: 3,
                explanation: `TMS.`,
            },
            {
                question: `The limit of over speeding by the Loco pilot which shall not cause Disciplinary action against the Loco pilot is _______`,
                options: ['3 km/h', '5 km/h', '8 km/h', '10 km/h'],
                correct: 1,
                explanation: `5 km/h.`,
            },
            {
                question: `The number of items in TMLP (GDR) check is ______`,
                options: ['7', '8', '9', '10'],
                correct: 1,
                explanation: `8.`,
            },
            {
                question: `The Grace Period for Premium BPC is ______`,
                options: ['3 days', '5 days', '7 days', '10 days'],
                correct: 1,
                explanation: `5 days.`,
            },
            {
                question: `The permissible limit of flat tyre in the locomotive of a goods train is ______`,
                options: ['40 mm', '50 mm', '60 mm', '70 mm'],
                correct: 1,
                explanation: `50 mm.`,
            },
            {
                question: `In the five digit numbering system of Coaching trains, Suvidha Train number starts with ______`,
                options: ['5', '6', '7', '8'],
                correct: 3,
                explanation: `8.`,
            },
            {
                question: `A decrease in net tonne kilometer per engine hours may be due to ______`,
                options: ['Increase in the proportion of unbalanced traffic', 'Increase in the average starting wagon load', 'Decrease in shunting engine hours', 'Decrease in light engine hours'],
                correct: 0,
                explanation: `Increase in the proportion of unbalanced traffic.`,
            },
            {
                question: `In coaching operations, which is not true about HOG technology?`,
                options: ['It increases passenger carrying capacity of a train', 'It reduces consumption of diesel for electricity generation', 'It improves braking characteristics of loco', 'It reduces requirement of power car'],
                correct: 2,
                explanation: `It improves braking characteristics of loco.`,
            },
            {
                question: `Which of the following is not developed by CRIS?`,
                options: ['ICMS', 'KAVACH', 'SATSANG', 'SFOORTI'],
                correct: 1,
                explanation: `KAVACH.`,
            },
            {
                question: `A railway station shall be categorized as NSG-4 if the passenger earnings per year is ______`,
                options: ['More than 20 crore, less than or equal to 50 crore', 'More than 10 crore, less than or equal to 50 crore', 'More than 10 crore, less than or equal to 20 crore', 'None of the above'],
                correct: 2,
                explanation: `More than 10 crore, less than or equal to 20 crore.`,
            },
            {
                question: `In planning process, what is eDAS portal used for?`,
                options: ['Approval of ESP', 'Scrutiny of estimates', 'Uploading DPRs', 'Executing siding agreements'],
                correct: 0,
                explanation: `Approval of ESP.`,
            },
            {
                question: `The height of the centre line of the red signal should be ______ above rail level`,
                options: ['3 m', '3.5 m', '3.65 m', '3.85 m'],
                correct: 2,
                explanation: `3.65 m.`,
            },
            {
                question: `What is the duration of concession agreement between private container train operators and Indian Railways/`,
                options: ['10 years', '15 years', '20 years', '25 years'],
                correct: 2,
                explanation: `20 years.`,
            },
            {
                question: `The period of agreement for new GCT on non-railway land is ______`,
                options: ['30 years', '35 years', '45 years', '50 years'],
                correct: 3,
                explanation: `50 years.`,
            },
            {
                question: `What is the maximum speed allowed for hand shunting of wagons?`,
                options: ['3 km/h', '5 km/h', '8 km/h', '10 km/h'],
                correct: 1,
                explanation: `5 km/h.`,
            },
            {
                question: `Which of these is a "Non-Signalling" based feature of Kavach that works regardless of the interlocking system?`,
                options: ['Displaying the current location in the passenger coach', 'Protection against train rollback', 'Enabling WIFI for passenger use', 'Alarm chain pulling'],
                correct: 1,
                explanation: `Protection against train rollback.`,
            },
            {
                question: `What is the minimum land area required for a facility to be officially classified as a Multi-Modal Logistics Park (MMLP) in India?`,
                options: ['50 acres', '100 acres', '150 acres', '200 acres'],
                correct: 1,
                explanation: `100 acres.`,
            },
            {
                question: `The predecessor to Kavach, known as the Anti-Collision Device (ACD), faced limitations in multi-line territory primarily because it relied on which technology?`,
                options: ['Steam-based communication signals', 'GPS for location determination', 'Optical cameras for track scanning', 'Fibre-optic cables exclusively'],
                correct: 1,
                explanation: `GPS for location determination.`,
            },
            {
                question: `If a GCTO disputes charges levied by the Divisional Railway and the DRM rules in favor of the GCTO, within how many days must the exces amount be refunded?`,
                options: ['15 days', '20 days', '30 days', '45 days'],
                correct: 0,
                explanation: `15 days.`,
            },
            {
                question: `CAMTECH is situated at ______`,
                options: ['Gwalior', 'Allahabad', 'Chennai', 'Mumbai'],
                correct: 0,
                explanation: `Gwalior.`,
            },
            {
                question: `The prima facie evidence of the weight and the number of packages is ______`,
                options: ['FNR', 'Forwarding note', 'Railway Receipt', 'Consignment Note'],
                correct: 2,
                explanation: `Railway Receipt. Railway Receipt is the prima facie evidence of the weight and the number of packages.`,
            },
            {
                question: `An application before the Claims Tribunal compensation for the loss of life or personal injury to a passenger, may be instituted against-
                (A) The railway administration from which the passenger obtained his pass or purchased ticket, or
                (B) The railway administration on whose railway the destination station lies or the loss or personal injury occurred`,
                options: ['A', 'B', 'A and B', 'None of the above'],
                correct: 2,
                explanation: `A and B.`,
            },
            {
                question: `The frequency of monitoring employees having grade "B" is ______`,
                options: ['Mothly', 'Quarterly', 'Half-yearly', 'Yearly'],
                correct: 2,
                explanation: `Half-yearly.`,
            },
            {
                question: `The power supply between two adjacent Traction substations feeding the OHE in TRD is separated by ______`,
                options: ['SP', 'SSP', 'FP', 'RCC'],
                correct: 0,
                explanation: `SP.`,
            },
            {
                question: `Taking OFF two reception signals at a time for different trains is called ______ of trains.`,
                options: ['Simultaneous dispatch', 'Sequential reception', 'Concurrent reception', 'Simultaneous reception'],
                correct: 3,
                explanation: `Simultaneous reception.`,
            },
            {
                question: `For post facto analysis of punctuality loss and its causes, _________ module captures train running at the Originating/Terminating and interchange points and the causes of detention, data input predominantly at Divisional and Headquarter level.`,
                options: ['COA', 'ICMS', 'CMS', 'PAM'],
                correct: 3,
                explanation: `PAM.`,
            },
            {
                question: `A single rail cut provided to isolate running line from non running line and when vehicle moves over it if it is open the vehicle derails is known as ______`,
                options: ['Snag dead end', 'Sand hump', 'Scotch block', 'Trap points'],
                correct: 3,
                explanation: `Trap points.`,
            },
            {
                question: `When will the long haul not be operated from the next station during the journey?`,
                options: ['Stop signal defective', 'Hand signal not seen', 'Walkie talkie defective', 'None of the above'],
                correct: 2,
                explanation: `Walkie talkie defective.`,
            },
            {
                question: `In MSDAC, when automatic reset with supervisory track section is done, corresponding signal will show ______`,
                options: ['ON aspect', 'OFF aspect', 'ON aspect with preparatory reset', 'OFF aspect with preparatory reset'],
                correct: 0,
                explanation: `ON aspect.`,
            },
            {
                question: `POET means _______`,
                options: ['Public Operated Enquiry Terminal', 'Passenger Order Enquiry Terminal', 'Passenger Operated Enquiry Terminal', 'Public Operated Enhancement Tool'],
                correct: 2,
                explanation: `Passenger Operated Enquiry Terminal.`,
            },
            {
                question: `Percentage of spare coaches for Mechanical requirement that must be kept at a depots for AC coaches on BG (Other than Rajadhani/Shatabdi and other premium trains) is ______`,
                options: ['5%', '6%', '8.5%', '10%'],
                correct: 2,
                explanation: `8.5%.`,
            },
            {
                question: `Which of the following is used to convert pneumatic force into mechanical force?`,
                options: ['Brake valve', 'Brake cylinder', 'Brake pipe', 'Hand brake'],
                correct: 1,
                explanation: `Brake cylinder.`,
            },
            {
                question: `Advance planning of traffic blocks or disconnections in Rolling block is made for ______`,
                options: ['26 weeks', '35 weeks', '45 weeks', '52 weeks'],
                correct: 3,
                explanation: `52 weeks.`,
            },
            {
                question: `The minimum number of portable train lighting equipment required in each Brake van of a coaching train is ______`,
                options: ['1', '2', '3', '4'],
                correct: 0,
                explanation: `1.`,
            },
            {
                question: `The Last stop signal-cum distant signal of LC gate will display ______ aspect when the Line clear has not been obtained from the station in advance.`,
                options: ['Red', 'Green', 'Yellow', 'White'],
                correct: 0,
                explanation: `Red.`,
            },
            {
                question: `Instructions in regard to handling of explosive and other dangerous goods are laid down in ______`,
                options: ['IRCA Red Tariff', 'IRCA Coaching tariff', 'RCT Act', 'None of the above'],
                correct: 0,
                explanation: `IRCA Red Tariff.`,
            },
            {
                question: `What is the full form of BDU _______`,
                options: ['Business Department Unit', 'Block Department Unit', 'Business Development Unit', 'None of the above'],
                correct: 2,
                explanation: `Business Development Unit.`,
            },
            {
                question: `What does IRPSM stands for?`,
                options: ['Integrated Railway Performance System Module', 'Integrated Railway Planning System Module', 'Integrated Railway Project System Management', 'Indian Railway Project Sanctions and Management'],
                correct: 3,
                explanation: `Indian Railway Project Sanctions and Management.`,
            },
            {
                question: `What is the tenure for new cargo terminals, siding, goods shed, and other cargo related facilities (as per the Master Circular on "Policy for Management of Railway Land")?`,
                options: ['30 years', '35 years', '45 years', '50 years'],
                correct: 1,
                explanation: `35 years.`,
            },
            {
                question: `Under General Purpose Wagon Investment Scheme (GPWIS), which of the following is General Purpose Wagon?`,
                options: ['BCFCM', 'BCNAHSM2', 'BOXN', 'BLSSA'],
                correct: 2,
                explanation: `BOXN.`,
            },
            {
                question: `Who is the competent authority to a approve change in the name of the Railway Stations?`,
                options: ['CRS', 'Ministry of Home Affairs', 'Railway Board', 'Ministry of Railways'],
                correct: 1,
                explanation: `Ministry of Home Affairs.`,
            },
            {
                question: `In case of Gati Shakti Cargo Terminal (GCT) on non-railway land, who is responsible for maintenance of Common user traffic facilities at the station?`,
                options: ['GCTO', 'GCTO & Railway', 'Railway', 'None of the above'],
                correct: 2,
                explanation: `Railway.`,
            },
            {
                question: `To whom should the request be submitted by existing Sidings/Terminals to migrate to the "Gati Shakti Multi-Modal Cargo Terminal (GCT) Policy"?`,
                options: ['Division', 'Zone', 'Railway Board', 'None of the above'],
                correct: 0,
                explanation: `Division.`,
            },
            {
                question: `During monsoon season, the premissible carrying capacity of which of the following commodities, when loaded on CC+8 routes, shall remain same as applicable on universalized CC+6 routes?`,
                options: ['Chrome ore', 'Iron ore', 'Gypsum', 'Bauxite'],
                correct: 2,
                explanation: `Gypsum.`,
            },
            {
                question: `Maintenance and operation of assets of common user traffic facility created at the serving station at the cost of the Gati Shakti Cargo Terminal Operator (GCTO) shall the responsibility of ______`,
                options: ['GCTO', 'Will be equally shared by GCTO and Railway', 'Railway', 'Railway subject to fulfulmentof guaranteed traffic by GCTO else by Railway'],
                correct: 2,
                explanation: `Railway.`,
            },
            {
                question: `For setting up and/or operation of a Gati Shakti Cargo Terminal (GCT), the nodal officer is ________`,
                options: ['DRM', 'GM', 'Railway Board', 'PCOM'],
                correct: 0,
                explanation: `DRM.`,
            },
            {
                question: `In which of the following wagons, Automobile traffic cannot be moved?`,
                options: ['BCCNM', 'BCCNR', 'BCACM', 'NMG'],
                correct: 0,
                explanation: `BCCNM.`,
            },
            {
                question: `Who is empowered to approve running of CC+8 routes operation in Railway`,
                options: ['DRM', 'GM', 'Railway Board', 'PCOM'],
                correct: 1,
                explanation: `GM.`,
            },
            {
                question: `What is the minimum composition of Mini Rakes?`,
                options: ['20 wagons', '23 wagons', '27 wagons', '30 wagons'],
                correct: 0,
                explanation: `20 wagons.`,
            },
            {
                question: `Who is authorized to permit to installation of Private Weighbridge on Railway Land?`,
                options: ['DRM', 'GM', 'Railway Board', 'PCOM'],
                correct: 0,
                explanation: `DRM.`,
            },
            {
                question: `Full form of CPGRAMS is ______`,
                options: ['Central Public Grievance Report and Monitoring Service', 'Common Public Grievance Report and Monitoring System', 'Centralized Public Grievance Redress and Monitoring System', 'Centralized Passenger Grievance Redress and Monitoring System'],
                correct: 2,
                explanation: `Centralized Public Grievance Redress and Monitoring System.`,
            },
            {
                question: `For open rake (BOXN etc.), free time for loading under EOL scheme is ______`,
                options: ['2 hours', '3 hours', '4 hours', '5 hours'],
                correct: 1,
                explanation: `3 hours.`,
            },
            {
                question: `Who is the Plan Head coordinator for works under PH-53 at Zonal level?`,
                options: ['PCCM', 'GM', 'PCPO', 'PCOM'],
                correct: 0,
                explanation: `PCCM.`,
            },
            {
                question: `Full form of ICMS is ______`,
                options: ['Integrated Cargo Management System', 'Indian Coaching Management System', 'Integrated Coaching Monitoring System', 'Integrated Coaching Management System'],
                correct: 3,
                explanation: `Integrated Coaching Management System.`,
            },
            {
                question: `What is the full fomr of SFOORTI portal which can also be accessed through BDU portal?`,
                options: ['Smart Freight Operation and Real Time Information', 'Smart Fare Operational Optimization and Real Time Information', 'Smart Freight Operation and Reliability Tracking Information', 'Smart Freight Operation Optimization and Real Technology Information'],
                correct: 0,
                explanation: `Smart Freight Operation and Real Time Information.`,
            },
            {
                question: `A GCT shall not be permitted to book and handle the following commodities?`,
                options: ['Coal', 'Coke', 'Piecemeal Parcel traffic', 'Full parcel rakes'],
                correct: 3,
                explanation: `Full parcel rakes.`,
            },
            {
                question: `Who is the nodal agency at National level for Coordination of response & relief in the wake of Natural Disasters?`,
                options: ['Ministry of Home Affairs', 'Ministry of Railways', 'Ministry of Civil Aviation', 'Ministry of Defence'],
                correct: 0,
                explanation: `Ministry of Home Affairs.`,
            },
            {
                question: `What does EnHM stands for?`,
                options: ['Environmental and Housekeepting Ministry', 'Environment and Hospitality Management', 'Environment and Housekeeping Management', 'None of the above'],
                correct: 2,
                explanation: `Environment and Housekeeping Management.`,
            },
            {
                question: `Which one of the following statement is NOT correct for digital signature?`,
                options: ['It is a mechanism for authentication', 'It cannot be duplicated', 'It is created by encrypting information', 'It is scanned image of one signature'],
                correct: 3,
                explanation: `It is scanned image of one signature.`,
            },
            {
                question: `Maximum permissible speed of empty BLC wagon is ______`,
                options: ['100 km/h', '110 km/h', '120 km/h', '130 km/h'],
                correct: 0,
                explanation: `100 km/h.`,
            },
            {
                question: `The time interval method of train working is not practicable due to ______`,
                options: ['Terrain is not same throughout the country', 'Hauling capacity, load of train and brake power is not same for all trains', 'Speed of trains vary', 'All of the above'],
                correct: 2,
                explanation: `Speed of trains vary.`,
            },
            {
                question: `Which of the following signal never placed alone on a post?`,
                options: ['Calling-on signal', 'Shunt signal', 'Repeating signal', 'Warner signal'],
                correct: 0,
                explanation: `Calling-on signal.`,
            },
            {
                question: `Which of the following parameter best captures the freight operation performance?`,
                options: ['Tonne-kilometer', 'Tonne-kilometer per engine hour', 'Tonne-kilometer per day', 'NTKM per Wagon Day'],
                correct: 3,
                explanation: `NTKM per Wagon Day.`,
            },
            {
                question: `When the gate is closed to road traffic, clearance between the road surface level and the boom shall be ______`,
                options: ['0.5 m to 0.8 m', '0.8 m to 1.0 m', '1.0 m to 1.2 m', '1.2 m to 1.5 m'],
                correct: 1,
                explanation: `0.8 m to 1.0 m.`,
            },   
            
        ]
    }
}