export const aomProfessionalSubjectTest45 = {
    tests: {
        'aom-professional-subject-test-45': [
            {
                question: `Before giving signal to a material train to start, _______ shall see that all the workers are on the train and warn them to sit down.`,
                options: ['Loco pilot', 'Station Master', 'TMR or material train', 'PWI or material train'],
                correct: 2,
                explanation: `TMR or material train.`,
            },
            {
                question: `Lumpsum deposit for Government Department as Wagon Registration Fee shall be ______`,
                options: ['5 lakhs', '10 lakhs', '15 lakhs', '20 lakhs'],
                correct: 0,
                explanation: `5 lakhs.`,
            },
            {
                question: `After the introduction of electronic registration of demand, the Wagon Demand/Priority Register shall be maintained by the ________`,
                options: ['COIS', 'RMS', 'SFOORTI', 'TMS'],
                correct: 3,
                explanation: `TMS.`,
            },
            {
                question: `How many copies of the Vehicle Guidance shall be prepared by the Loading point?`,
                options: ['1', '2', '3', '4'],
                correct: 1,
                explanation: `2.`,
            },
            {
                question: `All consignments loaded in the standard bags of uniform size is exempted from mandatory weighment at the weighbridges with a proviso that at least _______ percent of rakes should be subjected to weighment at the weighbridges.`,
                options: ['5', '6', '7', '8'],
                correct: 0,
                explanation: `5.`,
            },
            {
                question: `During thick or foggy weather, the speed of the train after passing Automatic signal at attention aspect shall not exceed ________`,
                options: ['30 km/h', '40 km/h', '50 km/h', '60 km/h'],
                correct: 0,
                explanation: `30 km/h.`,
            },
            {
                question: `The minimum number of wooden wedges/skids required in the Brake van of coaching train is ________`,
                options: ['2', '3', '4', '5'],
                correct: 0,
                explanation: `2.`,
            },
            {
                question: `The minimum number of portable train lighting equipment required in each Brake van of a coaching train is ________`,
                options: ['1', '2', '3', '4'],
                correct: 0,
                explanation: `1.`,
            },
            {
                question: `The condition for taking OFF the Home signal in the Automatic block system single line section is-
                (A) When a train is approaching a Home signal, other wise than at a terminal station, the signal shall not be taken OFF unless the line is clear not only upto the Starter but also for an adequate distance beyond it.
                (B) The direction of the block section ahead is not set in opposite.`,
                options: ['Only (A)', 'Only (B)', 'Both (A) and (B)', 'Neither (A) nor (B)'],
                correct: 3,
                explanation: `Neither (A) nor (B).`,
            },
            {
                question: `Voluntary Safety Reporting can be done through ________`,
                options: ['COA', 'ICMS', 'PAM', 'SIMS'],
                correct: 3,
                explanation: `SIMS.`,
            },
            {
                question: `One of the Automatic stop signal between two stations in the Automatic block signalling territory in each direction may be made as Modified Semi-automatic stop signal under ________`,
                options: ['Special instructions', 'Approved special instructions', 'Station Working Rules', 'Engineering signal manual'],
                correct: 0,
                explanation: `Special instructions.`,
            },
            {
                question: `One of the Automatic stop signal between two stations in the Automatic block signalling territory in each direction may be made as Modified Semi-automatic stop signal under ________`,
                options: ['Special instructions', 'Approved special instructions', 'Station Working Rules', 'Engineering signal manual'],
                correct: 0,
                explanation: `Special instructions.`,
            },
            {
                question: `For wagons ohter than 25 T axle load trains, in CC+8+2 routes, if the Gross weight of the wagon is more than 91.6 T but less than 92.1 T, and unable to adjust/unloading the loading, the speed of the train shall be ______`,
                options: ['Restricted to 40 kmph', 'Restricted to 50 kmph', 'Restricted to 60 kmph', 'Normal speed'],
                correct: 3,
                explanation: `Normal speed.`,
            },
            {
                question: `Functioning of the Weighbrdige in the division should be reported ________`,
                options: ['Daily', 'Weekly', 'Monthly', 'Quarterly'],
                correct: 0,
                explanation: `Daily.`,
            },
            {
                question: `Additional free time per rake for cleaning activities to tank wagons in private siding and goods sheds in case of edible oil when there is change of product is ________`,
                options: ['4 hours', '5 hours', '6 hours', '7 hours'],
                correct: 0,
                explanation: `4 hours.`,
            },
            {
                question: `The standard rake size of BAFRDR wagons including End Articulated Bogie (EAB) is ________`,
                options: ['50', '51', '52', '53'],
                correct: 1,
                explanation: `51.`,
            },
            {
                question: `What is the free time for loading of bagged consignment in block rakes (open wagons) in the case of freight terminals worked on the EOL basis?`,
                options: ['4 hours', '5 hours', '6 hours', '7 hours'],
                correct: 2,
                explanation: `6 hours.`,
            },
            {
                question: `The activities of publication of Tariff books and allotment of station codes is done by ________`,
                options: ['IRCA', 'Railway Ministry', 'Commercial Directorates of Railway Board', 'Central Government'],
                correct: 2,
                explanation: `Commercial Directorates of Railway Board.`,
            },
            {
                question: `The number of the existing coach when converted as RA/Inspection carriage shall be prefixed with ________`,
                options: ['RX', 'RZ', 'XR', 'ZR'],
                correct: 2,
                explanation: `XR.`,
            },
            {
                question: `Minimum penalty for Train passing signal at danger due to contributory factors like loss of brake power on run?`,
                options: ['Removal', 'Compulsory retirement', 'Reduction to lower grade', 'None of the above'],
                correct: 2,
                explanation: `Reduction to lower grade.`,
            },
            {
                question: `What is the maximum permitted speed of LHB coach in case of enroute breakage of primary springs?`,
                options: ['100 km/h', '110 km/h', '95 km/h', '90 km/h'],
                correct: 2,
                explanation: `95 km/h.`,
            },
            {
                question: `The schedule of IC maintenance of WAG-7 locomotives is ________`,
                options: ['180 days + 3 days', '180 days + 5 days', '240 days + 3 days', '240 days + 5 days'],
                correct: 2,
                explanation: `240 days + 3 days.`,
            },
            {
                question: `Minimum penalty for staff who are found to have secondary responsibility for the accident in collisions involving a train resulting in loss of human life is ________`,
                options: ['Removal', 'Compulsory retirement', 'Reduction to lower grade', 'Major penalties'],
                correct: 3,
                explanation: `Major penalties.`,
            },  
            {
                question: `Minimum penalty for staff who are found to have secondary responsibility for the accident in collisions involving a train resulting in loss of human life is ________`,
                options: ['Removal', 'Compulsory retirement', 'Reduction to lower grade', 'Major penalties'],
                correct: 3,
                explanation: `Major penalties.`,
            },
            {
                question: `Minimum penalty for over speeding by drivers resulting in derailment of goods train in station yard on ohter than main line if working substantively in C grade?`,
                options: ['Reduction to C grade for 3 years with loss of seniority', 'Reduction to C grade for 3 years without loss of seniority', 'Reduction to Shunter for 1 to 3 years with loss of seniority', 'Reduction to Shunter for 1 to 3 years without loss of seniority'],
                correct: 3,
                explanation: `Reduction to Shunter for 1 to 3 years without loss of seniority.`,
            },
            {
                question: `What is the full form of SPART?`,
                options: ['Self Promoted Account Review Team', 'Self Profelled Accident Relief Train', 'Self Profelled Accident Rsecue Team', 'Specially Powered Accident Relief Train'],
                correct: 1,
                explanation: `Self Profelled Accident Relief Train.`,
            },
            {
                question: `In which of the following cases, ex-gratia payment is not permissible?`,
                options: ['Railway servant killed or injured in a train accident', 'Passenger killed or injured in a train accident', 'Persons gettin run over at unmanned level crossing', 'None of the above'],
                correct: 2,
                explanation: `Persons getting run over at unmanned level crossing.`,
            },
            {
                question: `Minimum penalty for staff who are found to have primary responsibility for the accident in collisions involving a train resulting in no loss of human life is ________`,
                options: ['Removal from service', 'Compulsory retirement', 'Reduction to lower grade', 'Major penalties'],
                correct: 0,
                explanation: `Removal from service.`,
            },
            {
                question: `Full form of eTRR is ________`,
                options: ['Electronic Transmission of Railway Receipt', 'Electronic Transfer of Railway Receipts', 'Electrical Transmission of Railway Receipt', 'None of the above'],
                correct: 0,
                explanation: `Electronic Transmission of Railway Receipt.`,
            },
            {
                question: `Online caution order is generated through ________`,
                options: ['ICMS', 'FOIS', 'FMM', 'TMS'],
                correct: 0,
                explanation: `ICMS.`,
            },
            {
                question: `Every Railway servant is bound by the General Rules, the subsidiary rules and special instructions under section ______ of the Railway Act, 1989?`,
                options: ['175', '176', '177', '178'],
                correct: 0,
                explanation: `175.`,
            },
            {
                question: `Whenever Loco Pilot report about slack or rough running or heavy lurch or any abnormal condition in the track over which his train has passed, the speed of the first train during day shall not exceed ________`,
                options: ['10 km/h', '15 km/h', '20 km/h', '25 km/h'],
                correct: 0,
                explanation: `10 km/h.`,
            },
            {
                question: `In how many categories the Goods trains are classified?`,
                options: ['1', '2', '3', '4'],
                correct: 2,
                explanation: `3.`,
            },
            {
                question: `UDM stands for ________`,
                options: ['User Depot Module', 'Unique Digial Machine', 'Unique Digital Modem', 'User-friendly Digital Module'],
                correct: 0,
                explanation: `User Depot Module.`,
            },
            {
                question: `Which one of the following is NOT correct about Shunting`,
                options: ['For the purpose of shunting, steep gradient is 1 in 260 or steeper for Roller bearing vehicles', 'Shunting operations shall be controlled by Fixed signals or Hand signals or verbal directions', 'Shunting is permitted for passenger trains', 'The Outer, Home, and the LSS shall not be used for shunting'],
                correct: 0,
                explanation: `For the purpose of shunting, steep gradient is 1 in 260 or steeper for Roller bearing vehicles.`,
            },
            {
                question: `Which one of the following is NOT correct?`,
                options: ['Co-acting signals are placed in rear of a fixed signals', 'Repeating signals repeats the aspects of the fixed signal in advance', 'Co-acting signals are provided to have continuous visibility', 'Electric repeater is provided to have visibility of the signal from the place where signal is worked'],
                correct: 0,
                explanation: `Co-acting signals are placed in rear of a fixed signals.`,
            },
            {
                question: `The minimum distance between the Shunting Limit Board and the Opposing First stop signal on a class B single line two aspect signalling territory in Absolute block system is ________`,
                options: ['300 metres', '400 metres', '500 metres', '600 metres'],
                correct: 1,
                explanation: `400 metres.`,
            },
            {
                question: `The schedule of TOH maintenance of WAP-5 Locomotives is ________`,
                options: ['12 months', '18 months', '24 months', '30 months'],
                correct: 2,
                explanation: `24 months.`,
            },
            {
                question: `The schedule of IB maintenance of WAP-5 Locomotives is ________`,
                options: ['90 days', '120 days', '150 days', '180 days'],
                correct: 3,
                explanation: `180 days.`,
            },
            {
                question: `The schedule of IA maintenance of WAP-7 Locomotives is ________`,
                options: ['60 days', '90 days', '120 days', '150 days'],
                correct: 1,
                explanation: `90 days.`,
            },
            {
                question: `Minimum penalty for over speeding by drivers without any contributory factors resulting in derailment of passenger train involving loss of human life is ________`,
                options: ['Removal from service', 'Compulsory retirement', 'Dismissal', 'Major penalties'],
                correct: 2,
                explanation: `Dismissal.`,
            },
            {
                question: `When was the Metro Railway, Kolkata became a Zone Railway?`,
                options: ['2010', '2011', '2012', '2013'],
                correct: 0,
                explanation: `2010.`,
            },
            {
                question: `South Central Railway was established on ________`,
                options: ['1965', '1966', '1967', '1968'],
                correct: 1,
                explanation: `1966.`,
            },
            {
                question: `Wheels of LHB coaches are provided with what type bearing?`,
                options: ['Cylinderical roller bearing', 'Catridge tapered roller bearing', 'Plane bearing', 'Spherical roller bearing'],
                correct: 1,
                explanation: `Catridge tapered roller bearing.`,
            },
            {
                question: `TRI-NETRA is a project related to ________`,
                options: ['Introduction of CCTV camera in Railway platform to monitor passenger activities', 'Introduction of CCTV camera in Diesel shed to monitor workment activities', 'Terrain imaging of locomotive driver', 'All of the above'],
                correct: 2,
                explanation: `Terrain imaging of locomotive driver.`,
            },
            {
                question: `As per the new wagon numbering scheme, what is indicated by the first two digits?`,
                options: ['Owning railway', 'Wagon type', 'Year of manufacturing', 'Check digit'],
                correct: 1,
                explanation: `Wagon type.`,
            },
            {
                question: `Which form is issued by the TXR staff to report fit wagons?`,
                options: ['RS-15', 'RS-16', 'RS-17', 'RS-18'],
                correct: 2,
                explanation: `RS-17.`,
            },
            {
                question: `Which form is issued by the TXR staff to report sick wagons?`,
                options: ['RS-15', 'RS-16', 'RS-17', 'RS-18'],
                correct: 1,
                explanation: `RS-16.`,
            },
            {
                question: `Which department is responsible for supply of wooden wedges/skids in the Brake van of a coaching train?`,
                options: ['C&W', 'Mechanical', 'Engineering', 'Traffic'],
                correct: 1,
                explanation: `Mechanical.`,
            },
        ]
    }
}