export const aomProfessionalSubjectTest47 = {
    tests: {
        'aom-professional-subject-test-47': [
            {
                question: `During failure of MSDAC, for initiating the Prepartory reset, line verification is done by ______`,
                options: ['Train despatching station', 'Train receiving station', 'Both', 'Any station'],
                correct: 1,
                explanation: `Train receiving station.`,
            },
            {
                question: `POET means ______`,
                options: ['Public Operated Enquiry Terminal', 'Passenger Order Enquiry Terminal', 'Passenger Operated Enquiry Terminal', 'Public Operated Enhancement Terminal'],
                correct: 2,
                explanation: `Passenger Operated Enquiry Terminal.`,
            },
            {
                question: `POMKA means ______`,
                options: ['Permanent Officers Medical Kit for Accidents', 'Periodical Officers Monitoring of Accidents', 'Portable Medical for Accidents', 'Permanent Official Medical Kit for Assistance'],
                correct: 2,
                explanation: `Portable Medical for Accidents.`,
            },
            {
                question: `Whenever train stopped without clearing fouling mark, to prevent any movement on the fouled line the Train Manager shall inform the Station master at once by ________`,
                options: ['Exchange of Private Number', 'Exhibiting Stop hand signal', 'Showing green flag', 'Waving white light'],
                correct: 1,
                explanation: `Exhibiting Stop hand signal.`,
            },
            {
                question: `Whenever train engine is to be detached outside station limits on a gradient, the Train Manager shall not give such permission unless _______`,
                options: ['Hand brakes of the Brake van and six vehicles have been applied', 'Exhibiting Stop hand signal', 'Showing green flag', 'Waving white light'],
                correct: 1,
                explanation: `Exhibiting Stop hand signal.`,
            },
            {
                question: `Which form is used to display the list of Railway personnel at at station qualified to render first aid?`,
                options: ['ACC 8', 'ACC 9', 'ACC 10', 'ACC 11'],
                correct: 0,
                explanation: `ACC 8.`,
            },
            {
                question: `Detaching of engines from trains outside station limits or anywhere on a gradient may be prohibited altogether under ______ wherever considered necessary in the interest of safety`,
                options: ['Special instructions', 'Approved special instructions', 'Station working rules', 'Accident manual'],
                correct: 0,
                explanation: `Special instructions.`,
            },
            {
                question: `How much clear Maintenance Time should be given at Primary End for trains running under Round Trip Pattern?`,
                options: ['4 hours', '6 hours', '8 hours', '10 hours'],
                correct: 1,
                explanation: `6 hours.`,
            },
            {
                question: `Choosing the rolling stock having lowest numerical value of ride index amongst given options?`,
                options: ['ICF Coach', 'LHB Coach', 'Sleeper Coach', 'AC 3-Tier Coach'],
                correct: 1,
                explanation: `LHB Coach.`,
            },
            {
                question: `What is indicated by 7th to 10th digit in 11 digit wagon numbering scheme followed in Indian Railways?`,
                options: ['Wagon Type', 'Owning railway', 'Year of manufacture', 'Individual wagon number'],
                correct: 3,
                explanation: `Individual wagon number.`,
            },
            {
                question: `With reference to Air brake system of ICF coaches, which amongst the following is the correct full form of PEASD?`,
                options: ['Passenger Emergency Alarm Signal Device', 'Proper Emergency Alarm Signal Device', 'Pipe Exhaust Air Supply Device', 'Pipe Exhaust Air Supply Device'],
                correct: 0,
                explanation: `Passenger Emergency Alarm Signal Device.`,
            },
            {
                question: `Which of the following is NOT an essential condition for carrying out rolling in/rolling out examination of coaching train?`,
                options: ['Speed of train should not be more than 30 kmph at rolling in point', 'There should be adequate arrangement of lights rolling in point', 'Site of rolling in point shall provide unobstructed view of undergear from both side', 'Speed of train should be more than 30 kmph at rolling in point'],
                correct: 3,
                explanation: `Speed of train should be more than 30 kmph at rolling in point.`,
            },
            {
                question: `The height of the ISO Containers for international movement is ______`,
                options: [`9'6"`, `9'0"`, `8'6"`, `8'0"`],
                correct: 0,
                explanation: `9'6".`,
            },
            {
                question: `With the increase in numerical value of ride index, passenger comfort will ______`,
                options: ['increase', 'decrease', 'remain the same', 'None of the above'],
                correct: 1,
                explanation: `decrease.`,
            },
            {
                question: `Permissible maximum limit of flat surface on tread in BG wagon is ______`,
                options: ['40 mm', '50 mm', '60 mm', '70 mm'],
                correct: 2,
                explanation: `60 mm.`,
            },
            {
                question: `Between a loaded rake and empty rake on the same route, which one is at greater risk of derailment provided all other things being equal?`,
                options: ['Loaded rake', 'Empty rake', 'No difference, equal risk', 'None of the above'],
                correct: 1,
                explanation: `Empty rake.`,
            },
            {
                question: `Which of the following class of ART must have 140T crane in its composition?`,
                options: ['Class A', 'Class B', 'Class C', 'Class D'],
                correct: 0,
                explanation: `Class A.`,
            },
            {
                question: `With reference to derailment investigation, Nadal\'s formula dictates that the Derailment coefficient is depndent upon ______`,
                options: ['Train speed and radius of curvature', 'Flange angle and coefficent of friction', 'Wheel gauge and total play', 'Radius of curvature and height of train\'s center of gravity'],
                correct: 1,
                explanation: `Flange angle and coefficent of friction.`,
            },
            {
                question: `Which of the following is a passenger grievance redressal portal in Indian Railways?`,
                options: ['IREPS', 'HRMS', 'RESS', 'Rail Madad'],
                correct: 3,
                explanation: `Rail Madad.`,
            },
            {
                question: `Allowance for Engineering restrictions in train running is mentioned in ______`,
                options: ['Station working rules', 'Train working rules', 'Working time table', 'P Way manual'],
                correct: 2,
                explanation: `Working time table.`,
            },
            {
                question: `ICM stands for ______`,
                options: ['Integral Coach Miantenance System', 'Integral Coaching Monitoring System', 'Internal Coaching Management System', 'Integrated Coaching Management System'],
                correct: 3,
                explanation: `Integrated Coaching Management System.`,
            },
            {
                question: `For which type of services Engine/Loco link is associated with?`,
                options: ['Passenger train services', 'Goods train services', 'Departmental train services', 'All of the above'],
                correct: 0,
                explanation: `Passenger train services.`,
            },
            {
                question: `Movement of which traffic is not regulated by Preferential Traffic Order?`,
                options: ['Passenger traffic', 'Programmed traffic', 'Military traffic', 'Goods for emergency relief work for victims of natural disaster'],
                correct: 0,
                explanation: `Passenger traffic.`,
            },
            {
                question: `CMS has been introduced in the crew lobbies to provide ______`,
                options: ['Optimum and effective utilization of crew', 'Monitoring of training of staff', 'Monitoring of 10 hours duty & HOER', 'All of the above'],
                correct: 0,
                explanation: `All of the above.`,
            },
            {
                question: `The running duty at a stretch for the running staff should not ordinarily exceed ______ hours`,
                options: ['9', '10', '11', '12'],
                correct: 0,
                explanation: `9.`,
            },
            {
                question: `Logn haul train will be run in which of the following condition?`,
                options: ['Both rakes empty', 'Both rakes loaded', 'One rake empty and one rake loaded', 'All of the above'],
                correct: 3,
                explanation: `All of the above.`,
            },
            {
                question: `Simultaneous reception of two or more trains is permitted by _______`,
                options: ['Special instructions', 'Approved special instructions', 'Station working rules', 'Signal Engineering Manual'],
                correct: 0,
                explanation: `Special instructions.`,
            },
            {
                question: `The lump sum amount of ex-gratia for hospitalization of grievously injured paseenger in train accident upto first 30 days is ______`,
                options: ['50,000/-', '1,00,000/-', '1,50,000/-', '2,50,000/-'],
                correct: 3,
                explanation: `2,50,000/-.`,
            },
            {
                question: `The amount of ex-gratia relief to be paid to the dependents of a passenger due to death in a Untoward incident (As defined under section 124-A of the Railway Act, 1989) is ______`,
                options: ['50,000/-', '1,00,000/-', '1,50,000/-', '2,00,000/-'],
                correct: 2,
                explanation: `1,50,000/-.`,
            },
            {
                question: `Allotment despite restrictions is controlled at _______`,
                options: ['Rly head office', 'Rly divisional head office', 'Rly zone head office', 'Rly regional head office'],
                correct: 2,
                explanation: `Rly zone head office.`,
            },
            {
                question: `In case of goods train accident, arrangement of road transport and labor for unloading of wagons involved in the accident si the duty of ______`,
                options: ['C&W Contorl', 'Commercial Control', 'Engineering Control', 'Safety Control'],
                correct: 1,
                explanation: `Commercial Control.`,
            },
            {
                question: `Which type of unit is NTKM?`,
                options: ['Derived', 'Fundamental', 'Primary', 'Secondary'],
                correct: 1,
                explanation: `Fundamental.`,
            },
            {
                question: `Which of the following is a Primary Unit as per Railway statistics?`,
                options: ['Kilometer', 'Tonne kilometer', 'Wagon kilometer per wagon day', 'None of the above'],
                correct: 0,
                explanation: `Kilometer.`,
            },
            {
                question: `If the Loco pilot has not operated on an Automatic section for more than 24 months, she/he should be given road learning for ______ trips in each direction`,
                options: ['4', '5', '3', '6'],
                correct: 2,
                explanation: `6.`,
            },
            {
                question: `RFMS stands for ______`,
                options: ['Railway Freight Management System', 'Referrential File Management System', 'Railway Fare Management System', 'Railway Failure Management System'],
                correct: 1,
                explanation: `Referrential File Management System.`,
            },
            {
                question: `Security Deposit to be deposited within one month from the approval of Deptailed Project Report (DPR) for setting up a Private Freight Terminal (PFT) is ______`,
                options: ['10 Lakh', '20 Lakh', '30 Lakh', '40 Lakh'],
                correct: 0,
                explanation: `10 Lakh.`,
            },
            {
                question: `Applicant shall submit a Detailed Project Report (DPR) to Sr.DOM within ______ days of receiving in principle approval for setting up a Private Freight Terminal (PFT)`,
                options: ['30', '45', '60', '90'],
                correct: 1,
                explanation: `45.`,
            },
            {
                question: `In principle approval for setting up a PFT will be communicated to the applicant by the Sr.DOM within ______ days of application for the same.`,
                options: ['45', '46', '47', '48'],
                correct: 2,
                explanation: `47.`,
            },
            {
                question: `The Railway administration shall not be responsible in any case for the loss, destruction or damage or deterioration, non delivery of any consignment arising after the ________`,
                options: ['Expiry of a period of 7 days after termination of transit', 'Expiry of a period of 14 days after termination of transit', 'Expiry of a period of 21 days after termination of transit', 'Expiry of a period of 28 days after termination of transit'],
                correct: 0,
                explanation: `Expiry of a period of 7 days after termination of transit.`,
            },
            {
                question: `As per the "Scheme of best among failed candidates" in selections, the promotion of SC/ST candidates should be reviewed after ________ months`,
                options: ['3', '6', '9', '12'],
                correct: 1,
                explanation: `6.`,
            },
            {
                question: `Point indicator shows ______ light at night when point is set for the straight line`,
                options: ['Green', 'Red', 'Yellow', 'White'],
                correct: 3,
                explanation: `White.`,
            },
            {
                question: `Which of the following is NOT correct about Brake Power Certificate?`,
                options: ['The color of BPC of CC rake will be white', 'The minimum originating brake power for air braked goods trains, running on End to End pattern of examination, shall be 90% except wherever local instructions have specified higher level of brake power to meet specific requirements', 'The originating brake power for air braked goods trains, running in CC rakes shall be 100%', 'The originating brake power for air braked goods trains, running in Premium rakes shall be 95%'],
                correct: 0,
                explanation: `The color of BPC of CC rake will be white.`,
            },
            {
                question: `To test the Visibility of signals, the Visibility Test Object shall be seen from a distance not less than 180 meters or lesser distance if sanctioned by _______`,
                options: ['CRS', 'PCOM or PCSTE', 'GM', 'Railway Board'],
                correct: 3,
                explanation: `Railway Board.`,
            },
            {
                question: `Which one of the following is CORRECT about Semaphore arm type calling-on signals?`,
                options: ['It is painted white with red bar', 'It is painted red with white bar', 'It is painted green with red bar', 'It is painted blue with white bar'],
                correct: 0,
                explanation: `It is painted white with red bar.`,
            },
            {
                question: `Which of the following is NOT correct about Semaphore distant signal?`,
                options: ['It is painted yellow with white fish tail in the side facing train', 'It has a fish tailed arm', 'It is painted yellow with black fish tain in the side facing train', 'It is painted white with black fish tain on the reverse side'],
                correct: 0,
                explanation: `It is painted yellow with black fish tail in the side facing train.`,
            },
            {
                question: `The report prepared by the Police containing details of incident.`,
                options: ['FIR', 'Inquest report', 'Jama Talashi', 'Survey'],
                correct: 1,
                explanation: `Inquest report.`,
            },
            {
                question: `The headquarters of Institute of Rail Transport is at ______`,
                options: ['Mumbai', 'Delhi', 'Chennai', 'Kolkata'],
                correct: 1,
                explanation: `Delhi.`,
            },
            {
                question: `Obstruction Test of Point Machine is done at ______`,
                options: ['100 mm from toe', '125 mm from toe', '150 mm from toe', '175 mm from toe'],
                correct: 2,
                explanation: `150 mm from toe.`,
            },
            {
                question: `The length of the chord to measure versine of a curve is ______`,
                options: ['10 meters', '20 meters', '30 meters', '40 meters'],
                correct: 1,
                explanation: `20 meters.`,
            },
            {
                question: `Minimum lead restriction under Freight Forwarded Scheme is ______`,
                options: ['500 km', '600 km', '700 km', '800 km'],
                correct: 2,
                explanation: `700 km.`,
            },
            {
                question: `A green light held above the head and moved by twisting the wrist indicates ______`,
                options: ['Move slowly for coupling', 'Move towards the person signalling', 'Move away from the person signalling', 'Already signal'],
                correct: 0,
                explanation: `Move slowly for coupling.`,
            },
            {
                question: `A "G" marker shall be provided on a Gate stop signal except where otherwise prohibited under ______`,
                options: ['Special instructions', 'Approved special instructions', 'Station working rules', 'Signal Engineering Manual'],
                correct: 0,
                explanation: `Special instructions.`,
            },
            {
                question: `Which of the following app is NOT developed by CRIS?`,
                options: ['IREPS', 'Rail Sugam', 'Rail Yatri', 'TDMS'],
                correct: 2,
                explanation: `Rail Yatri.`,
            },
            {
                question: `To measure the versine of a curve, stations are marked at a distance of ______`,
                options: ['10 meters', '20 meters', '30 meters', '40 meters'],
                correct: 0,
                explanation: `10 meters.`,
            },
            {
                question: `Provision of minimum equipment of fixed signals may be exempted under ______`,
                options: ['Special instructions', 'Approved special instructions', 'Station working rules', 'Signal Engineering Manual'],
                correct: 1,
                explanation: `Approved special instructions.`,
            },
            {
                question: `Freight Name Record (FNR) contains ______`,
                options: ['10 digits', '11 digits', '12 digits', '13 digits'],
                correct: 1,
                explanation: `11 digits.`,
            },
            {
                question: `Stretcher in the Brake van of passenger train shall be supplied by ______`,
                options: ['Commercial department', 'Mechanical department', 'Medical department', 'Traffic department'],
                correct: 3,
                explanation: `Traffic department.`,
            },
            {
                question: `Breach of block rules comes under which class of accident?`,
                options: ['Class E', 'Class F', 'Class G', 'Class H'],
                correct: 2,
                explanation: `Class G.`,
            },
            {
                question: `Which of the following conditions is necessary to permit the speed of 30 kmph over turnout?`,
                options: ['Higher speed turnouts are provided on a reasonable long section in a continuous stretch', 'On such sections higher speed turnouts are provided on all running lines', 'Turn in curves and running loops on which higher speed is permitted are suitably strengthened', 'All of the above'],
                correct: 3,
                explanation: `All of the above.`,
            },
            {
                question: `Derailment of a train not carrying passengers resulting in loss of human life and/or damage to Railway property of the value exceeding 2 crore rupees and/or interruption of any important through line of communication for atleast 24 hours comes under ______`,
                options: ['D1', 'D2', 'D3', 'D4'],
                correct: 1,
                explanation: `D2.
                D-1 = Derailment of a train carrying passengers resulting in loss of human life and/or grievious hurt and/or damage to Railway property of the value exceeding 2 crore rupees and/or interruption of any important through line of communication for atleast 24 hours.
                D-2 = Derailment of a train not carrying passengers resulting in loss of human life and/or damage to Railway property of the value exceeding 2 crore rupees and/or interruption of any important through line of communication for atleast 24 hours.
                D-3 = Derailment of a train carrying passengers not falling under D-A above.
                D-4 = Derailment of a train not carrying passengers not falling under D-2 above but loss to Railway property and/or interruption to traffic is more than threashold value.
                D-5 = Derailment of a train not carrying passengers not falling either D-2 or D-4 above.
                D-6 = Other derailments, i.e derailments occuring in shunting, marshalling yards, loco yards and siding etc, but not involving a train.`,
            },
            {
                question: `Who is the co-ordinating officer after commissioning of GCT?`,
                options: ['CFTM', 'DRM', 'Sr.DOM', 'Sr.DCM'],
                correct: 3,
                explanation: `Sr.DCM.`,
            },
            {
                question: `When should a Warner signal to be provided at a class B station (both in single and double line sections)?`,
                options: ['If trains run through at a speed exceeding 50 kmph without stopping', 'If trains run through at a speed exceeding 40 kmph with stopping', 'If trains run through at a speed exceeding 45 kmph with stopping', 'Warner signals are not required at class B station'],
                correct: 0,
                explanation: `If trains run through at a speed exceeding 50 kmph without stopping.`,
            },
            {
                question: `PRAVAS means ______`,
                options: ['Portal for Rail Adhikari Vishramalaya Awantan System', 'Portal for Railway Aawas and Vishramalaya Awantan System', 'Portal for Railway Aawas and Vishramalaya Allotment System', 'None of the above'],
                correct: 0,
                explanation: `Portal for Rail Adhikari Vishramalaya Awantan System.`,
            },
            {
                question: `The coordinating officer throughout the construction stage of a PFT at headquarter level shall be ______`,
                options: ['CPTM', 'CTPM', 'CCM/FM', 'CFTM'],
                correct: 1,
                explanation: `CTPM.`,
            },
            {
                question: `Full form of CADAT is _______`,
                options: ['Computer Aided Drivers Awareness Test', 'Comprehensive Awareness of Drivers Ability Test', 'Computer Aided Drivers Aptitude Test', 'None of the above'],
                correct: 2,
                explanation: `Computer Aided Drivers Aptitude Test.`,
            },
            {
                question: `What is the value of Detailed Estimate above which DPR is required to be submitted to Railway Board for sanction?`,
                options: ['50 Crore', '75 Crore', '80 Crore', '100 Crore'],
                correct: 0,
                explanation: `50 Crore.`,
            },
            {
                question: `Ghum, the highest station in India and the second highest in the world is located in ______`,
                options: ['Darjeeling Himalayan Railway', 'Kalka Shimla Railway', 'Nilgiri Mountain Railway', 'None of the above'],
                correct: 0,
                explanation: `Darjeeling Himalayan Railway.`,
            },
            {
                question: `Which of the following is NOT correct regarding Learning Road by Loco Pilots?`,
                options: ['Every LP/ALP should be given three trips (Up & Down direction separately) for learning road out of which one must be night', 'On Ghat section and automati territories maxumu six trips of road learning shall be provided in both directions', 'If LP/ALP has not operated on section for 8 months, three trips in Ghat section should be given for road learning', 'Any additional trip/s considered necessary should be provided with the approval of the controlling branch officer of the division'],
                correct: 1,
                explanation: `On Ghat section and automatic territories maximum six trips of road learning shall be provided in both directions (Minimum).`,
            },
            {
                question: `GCT fesibility report to DRM may be submitted within ______`,
                options: ['7 days', '10 days', '15 days', '20 days'],
                correct: 2,
                explanation: `15 days.`,
            },
            {
                question: `Existing siding may also migrate to GCT policy by the ______`,
                options: ['Request to CTPM', 'Request to CCM/FM', 'Request to DRM', 'Request to Railway Board'],
                correct: 2,
                explanation: `Request to DRM.`,
            },
            {
                question: `When does a goods train considered "Over Due Train"?`,
                options: ['If does not arrive within 5 minutes after allowing for its normal running time', 'If does not arrive within 10 minutes after allowing for its normal running time', 'If does not arrive within 15 minutes after allowing for its normal running time', 'If does not arrive within 20 minutes after allowing for its normal running time'],
                correct: 3,
                explanation: `If does not arrive within 20 minutes after allowing for its normal running time.`,
            },
            {
                question: `(A) The intelocking of Catch/Slip siding points shall be such taht the key required to set the siding points is released fro the instruments in the "Train Going To"/"Train Coming From" position.
                (B) Where Slip siding is located at the departure end of a double line station, the interlocking shall be such that the points can be set towards the block section only when the block instrument is set to "Line clear" position.` ,
                options: ['Only A is correct', 'Only B is correct', 'Both A and B are correct', 'Both A and B are incorrect'],
                correct: 0,
                explanation: `Both A and B are correct.`,
            },
            
        ]
    }
}