export const railwayStatistics = {
  columns: ['Unit', '2023-24', '2024-25'] as const,
  notes: [
    '@ Includes investment (`53,449.91crore) from Capital Fund.',
    '# includes investment (`53,449.91crore) from Capital Fund.',
    '$ Excluding Konkan Railway.',
    '* revised',
    '** No dividend was payable since 2017-18.',
  ],
  sections: [
    {
      title: 'PLANT & EQUIPMENT',
      rows: [
        {
          item: 'Capital Investment (incl. capital Fund)',
          unit: '` in crore',
          year2023_24: '@7,47,592.53',
          year2024_25: '#9,28,193.72',
        },
        {
          item: 'Total Investment',
          unit: '”',
          year2023_24: '12,18,258.82',
          year2024_25: '14,72,668.33',
        },
        {
          item: 'Route Length',
          unit: 'Kms.',
          year2023_24: '69,181',
          year2024_25: '69,439',
        },
        {
          item: 'Locomotives',
          unit: 'Nos.',
          year2023_24: '*15,114',
          year2024_25: '16,092',
        },
        {
          item: 'Passenger Service Vehicles',
          unit: '”',
          year2023_24: '*80,838',
          year2024_25: '84,238',
        },
        {
          item: 'Other Coaching Vehicles',
          unit: '”',
          year2023_24: '*13,111',
          year2024_25: '13,935',
        },
        {
          item: 'Wagons',
          unit: '”',
          year2023_24: '*3,28,559',
          year2024_25: '3,46,366',
        },
        {
          item: 'Railway Stations',
          unit: '”',
          year2023_24: '7,461',
          year2024_25: '7,469',
        },
      ],
    },
    {
      title: 'OPERATION',
      groups: [
        {
          title: 'Passenger',
          rows: [
            {
              item: 'Train Kms.',
              unit: 'Millions',
              year2023_24: '800',
              year2024_25: '835',
            },
            {
              item: 'Vehicle Kms.',
              unit: '”',
              year2023_24: '*26,506',
              year2024_25: '27,437',
            },
          ],
        },
        {
          title: 'Freight',
          rows: [
            {
              item: 'Train Kms.',
              unit: '”',
              year2023_24: '513',
              year2024_25: '520',
            },
            {
              item: 'Wagon Kms.',
              unit: '”',
              year2023_24: '23,977',
              year2024_25: '22,841',
            },
          ],
        },
      ],
    },
    {
      title: 'VOLUME OF TRAFFIC',
      rows: [
        {
          item: 'Passengers Originating',
          unit: 'Millions',
          year2023_24: '6,905',
          year2024_25: '7,293',
        },
        {
          item: 'Passenger Kms.',
          unit: '”',
          year2023_24: '1,064,700',
          year2024_25: '1,132,500',
        },
      ],
      groups: [
        {
          title: 'Tonnes Originating:$',
          rows: [
            {
              item: 'Revenue Earning Traffic',
              unit: '”',
              year2023_24: '1,588.06',
              year2024_25: '1,614.91',
            },
            {
              item: 'Total Traffic (incl. non-revenue)',
              unit: '”',
              year2023_24: '1,589.95',
              year2024_25: '1,617.30',
            },
          ],
        },
        {
          title: 'Net Tonne Kms.$',
          rows: [
            {
              item: 'Revenue Earning Traffic',
              unit: '”',
              year2023_24: '973,968',
              year2024_25: '971,085',
            },
            {
              item: 'Total Traffic (incl. non-revenue)',
              unit: '”',
              year2023_24: '974,469',
              year2024_25: '971,460',
            },
          ],
        },
      ],
    },
    {
      title: 'EMPLOYMENT AND WAGES',
      rows: [
        {
          item: 'Regular Employees',
          unit: 'Thousands',
          year2023_24: '1,252',
          year2024_25: '1,229',
        },
        {
          item: 'Wage Bill of Regular Employees',
          unit: '` in crore',
          year2023_24: '1,73,640',
          year2024_25: '1,85,218',
        },
        {
          item: 'Average Annual Wage Per Regular Employee',
          unit: '` in units',
          year2023_24: '13,86,702',
          year2024_25: '15,07,075',
        },
      ],
    },
    {
      title: 'FINANCIAL RESULTS',
      rows: [
        {
          item: 'Revenue',
          unit: '` in crore',
          year2023_24: '2,55,272.63',
          year2024_25: '2,65,113.61',
        },
        {
          item: 'Expenses',
          unit: '”',
          year2023_24: '2,50,893.61',
          year2024_25: '2,60,768.89',
        },
        {
          item: 'Miscellaneous Transactions',
          unit: '”',
          year2023_24: '(-)1,119.34',
          year2024_25: '(-)1,684.44',
        },
        {
          item: 'Net Revenue (before dividend)',
          unit: '”',
          year2023_24: '3,259.68',
          year2024_25: '2,660.28',
        },
        {
          item: 'Rate of Return on Capital',
          unit: 'Percent',
          year2023_24: '0.44',
          year2024_25: '0.29',
        },
        {
          item: 'Dividend on Capital **',
          unit: '` in crore',
          year2023_24: '0.00',
          year2024_25: '0.00',
        },
        {
          item: 'Shortfall (-)/Excess (+)',
          unit: '”',
          year2023_24: '3,259.68',
          year2024_25: '2,660.28',
        },
      ],
    },
    {
      title: 'I. Rail Network',
      numberedHeaders: ['S.No.', 'Item', 'Unit', '2023-24', '2024-25'] as const,
      entries: [
        {
          sno: '1',
          item: 'Route Kilometres',
          children: [
            {
              sno: '(i)',
              item: 'BG',
              unit: 'Kms.',
              year2023_24: '66,820',
              year2024_25: '67,372',
            },
            {
              sno: '(ii)',
              item: 'MG',
              unit: '"',
              year2023_24: '1,159',
              year2024_25: '894',
            },
            {
              sno: '(iii)',
              item: 'NG',
              unit: '"',
              year2023_24: '1,202',
              year2024_25: '1,173',
            },
            {
              sno: '',
              item: 'Total (all gauges)',
              unit: '"',
              year2023_24: '69,181',
              year2024_25: '69,439',
            },
          ],
        },
        {
          sno: '2',
          item: 'Running Track Kilometres (Total all gauges)',
          unit: '"',
          year2023_24: '1,09,748',
          year2024_25: '1,11,641',
        },
        {
          sno: '3',
          item: 'Total Track Kilometres (Total all gauges)',
          unit: '"',
          year2023_24: '1,35,207',
          year2024_25: '1,37,522',
        },
        {
          sno: '4',
          item: 'Electrified Route Kilometre (Total all gauges)',
          unit: '"',
          year2023_24: '62,253',
          year2024_25: '65,510',
        },
      ],
    },
    {
      title: 'II. Rolling stock',
      numberedHeaders: ['S.No.', 'Item', 'Unit', '2023-24', '2024-25'] as const,
      entries: [
        {
          sno: '1',
          item: 'Number of Locomotives (in units)',
          children: [
            {
              sno: '(i)',
              item: 'Steam',
              unit: '"',
              year2023_24: '38',
              year2024_25: '34',
            },
            {
              sno: '(ii)',
              item: 'Diesel',
              unit: '"',
              year2023_24: '*4,401',
              year2024_25: '4,296',
            },
            {
              sno: '(iii)',
              item: 'Electric',
              unit: '"',
              year2023_24: '10,675',
              year2024_25: '11,762',
            },
            {
              sno: '',
              item: 'Total',
              unit: '"',
              year2023_24: '*15,114',
              year2024_25: '16,092',
            },
          ],
        },
        {
          sno: '2',
          item: 'Number of Wagons',
          unit: '"',
          year2023_24: '*3,28,559',
          year2024_25: '3,46,366',
        },
        {
          sno: '3',
          item: 'Number of Coaches-(in units)',
          children: [
            {
              sno: '(i)',
              item: 'Passenger Carriages (including DEMU/  DHMU)',
              unit: '"',
              year2023_24: '*68,031',
              year2024_25: '70,969',
            },
            {
              sno: '(ii)',
              item: 'Other Coaching Vehicles',
              unit: '"',
              year2023_24: '*13,111',
              year2024_25: '13,935',
            },
            {
              sno: '(iii)',
              item: 'EMU and MEMU Coaches',
              unit: '"',
              year2023_24: '*12,798',
              year2024_25: '13,263',
            },
            {
              sno: '(iv)',
              item: 'Rail Cars',
              unit: '"',
              year2023_24: '*9',
              year2024_25: '6',
            },
            {
              sno: '',
              item: 'Total',
              unit: '"',
              year2023_24: '*93,949',
              year2024_25: '98,173',
            },
          ],
        },
      ],
    },
    {
      title: 'III. Loco Utilisation',
      numberedHeaders: ['S.No.', 'Item', 'Unit', '2023-24', '2024-25'] as const,
      entries: [
        {
          sno: '1',
          item: 'Tractive effort per loco',
          children: [
            {
              sno: '(i)',
              item: 'BG',
              unit: 'Kgs.',
              year2023_24: '43,380',
              year2024_25: '44,418',
            },
            {
              sno: '(ii)',
              item: 'MG',
              unit: '"',
              year2023_24: '15,987',
              year2024_25: '15,804',
            },
          ],
        },
        {
          sno: '2',
          item: 'GTKMs (excl. wt. of engine & dept.) per kg. of tractive effort.',
          children: [
            {
              sno: '(i)',
              item: 'BG',
              unit: 'Kms.',
              year2023_24: '3,551',
              year2024_25: '3,196',
            },
            {
              sno: '(ii)',
              item: 'MG',
              unit: '"',
              year2023_24: '168',
              year2024_25: '142',
            },
          ],
        },
        {
          sno: '3',
          item: 'Engine kilometres per day per engine in use (Pass.) (B.G)',
          children: [
            {
              sno: '(i)',
              item: 'Diesel',
              unit: 'Kms.',
              year2023_24: '768',
              year2024_25: '759',
            },
            {
              sno: '(ii)',
              item: 'Electric',
              unit: '"',
              year2023_24: '823',
              year2024_25: '756',
            },
          ],
        },
        {
          sno: '4',
          item: 'Engine kilometres per day per engine in use (Goods) (B.G)',
          children: [
            {
              sno: '(i)',
              item: 'Diesel',
              unit: 'Kms.',
              year2023_24: '450',
              year2024_25: '475',
            },
            {
              sno: '(ii)',
              item: 'Electric',
              unit: '"',
              year2023_24: '309',
              year2024_25: '282',
            },
          ],
        },
        {
          sno: '5',
          item: 'NTKMs per engine hour (BG) All traction',
          unit: '',
          year2023_24: '*14,007',
          year2024_25: '12,779',
        },
        {
          sno: '6',
          item: 'Ineffective percentage of locomotives (B.G)',
          unit: '% age',
          children: [
            {
              sno: '(i)',
              item: 'Diesel',
              unit: '"',
              year2023_24: '*11.90',
              year2024_25: '10.32',
            },
            {
              sno: '(ii)',
              item: 'Electric',
              unit: '"',
              year2023_24: '*5.34',
              year2024_25: '5.99',
            },
          ],
        },
      ],
    },
    {
      title: 'IV. Wagon Utilisation',
      numberedHeaders: ['S.No.', 'Item', 'Unit', '2023-24', '2024-25'] as const,
      entries: [
        {
          sno: '1',
          item: 'Wagon KMs in terms of 8 wheelers',
          unit: 'Million',
          year2023_24: '23,977',
          year2024_25: '22,841',
        },
        {
          sno: '2',
          item: 'Total Carrying Capacity (All Gauges)',
          unit: 'Million Tonnes',
          year2023_24: '*19.65',
          year2024_25: '21.05',
        },
        {
          sno: '3',
          item: 'Average carrying capacity - wagon',
          unit: 'Tonnes',
          children: [
            {
              sno: '(i)',
              item: 'BG',
              unit: '"',
              year2023_24: '62.9',
              year2024_25: '63.9',
            },
            {
              sno: '(ii)',
              item: 'MG',
              unit: '"',
              year2023_24: '*32.3',
              year2024_25: '40.4',
            },
          ],
        },
        {
          sno: '4',
          item: 'Wagon Turn Round (in days) (BG)',
          unit: 'Days',
          year2023_24: '5.11',
          year2024_25: '5.48',
        },
        {
          sno: '5',
          item: 'Wagon Kms. per wagon per day (BG)',
          unit: 'Kms',
          year2023_24: '192.0',
          year2024_25: '176.0',
        },
        {
          sno: '6',
          item: 'NTKMs per wagon per day (BG)',
          unit: 'Kms',
          year2023_24: '7,851',
          year2024_25: '7,292',
        },
        {
          sno: '7',
          item: 'Ineffective percentage of wagons (B.G)',
          unit: '% age',
          year2023_24: '*2.45',
          year2024_25: '2.88',
        },
      ],
    },


    {
      title: 'V. Coach Utilisation',
      numberedHeaders: ['S.No.', 'Item', 'Unit', '2023-24', '2024-25'] as const,
      entries: [
        {
          sno: '1',
          item: 'Vehicle Kms.(Excluding Deptt../Rail Car etc.)',
          unit: 'Millions',
          children: [
            {
              sno: '(i)',
              item: 'Suburban (EMU)',
              unit: '"',
              year2023_24: '2,234',
              year2024_25: '2,272',
            },
            {
              sno: '(ii)',
              item: 'Non Suburban',
              unit: '"',
              year2023_24: '*24,272',
              year2024_25: '25,165',
            },
            {
              sno: '',
              item: 'Total',
              unit: '"',
              year2023_24: '26,506',
              year2024_25: '27,437',
            },
          ],
        },
        {
          sno: '2',
          item: 'Vehicle Kms per vehicle day (B.G)',
          unit: 'Kms.',
          year2023_24: '*493',
          year2024_25: '488',
        },
        {
          sno: '3',
          item: 'Ineffective percentage of coaches (B.G) (Passenger Carriage)',
          unit: '% age',
          year2023_24: '*5.11',
          year2024_25: '5.42',
        },
      ],
    },
    {
      title: 'VI. Train Utilisation',
      numberedHeaders: ['S.No.', 'Item', 'Unit', '2023-24', '2024-25'] as const,
      groups: [
        {
          title: 'a. Passenger Train Performance',
          entries: [
            {
              sno: '1',
              item: 'Number of Passenger trains runs daily',
              unit: 'Nos.',
              year2023_24: '13,198',
              year2024_25: '13,940',
            },
            {
              sno: '2',
              item: 'Passenger Train Kms',
              unit: 'Millions',
              year2023_24: '800',
              year2024_25: '835',
            },
          ],
        },
        {
          title: 'b. Goods Train Performance',
          entries: [
            {
              sno: '1',
              item: 'Number of Goods trains runs daily',
              unit: 'Nos.',
              year2023_24: '11,724',
              year2024_25: '11,631',
            },
            {
              sno: '2',
              item: 'Goods Train Kms.',
              unit: 'Millions',
              year2023_24: '513',
              year2024_25: '520',
            },
            {
              sno: '3',
              item: 'Average Speed of All Goods Train (B.G.)',
              children: [
                {
                  sno: '(i)',
                  item: 'Diesel',
                  unit: 'Kms./Hour',
                  year2023_24: '27.3',
                  year2024_25: '26.4',
                },
                {
                  sno: '(ii)',
                  item: 'Electric',
                  unit: '"',
                  year2023_24: '24.1',
                  year2024_25: '23.1',
                },
                {
                  sno: '(iii)',
                  item: 'All Traction',
                  unit: '"',
                  year2023_24: '25.0',
                  year2024_25: '23.4',
                },
              ],
            },
            {
              sno: '4',
              item: 'Average Net load of Goods train (B.G)  (All traction)',
              unit: 'Tonnes',
              year2023_24: '1,899',
              year2024_25: '1,869',
            },
            {
              sno: '5',
              item: 'Average Gross load of Goods train (B.G.)  (All traction)',
              unit: 'Tonnes',
              year2023_24: '*3,160',
              year2024_25: '3,031',
            },
          ],
        },
      ],
    },
    {
      title: 'VII Volume of traffic',
      numberedHeaders: ['S.No.', 'Item', 'Unit', '2023-24', '2024-25'] as const,
      groups: [
        {
          title: 'a. Passenger Traffic (Suburban + Non-Suburban)',
          entries: [
            {
              sno: '1',
              item: 'Passenger Originating',
              unit: 'Millions',
              year2023_24: '6,905',
              year2024_25: '7,293',
            },
            {
              sno: '2',
              item: 'Passenger Kilometres',
              unit: 'Millions',
              year2023_24: '1,064,700',
              year2024_25: '1,132,500',
            },
            {
              sno: '3',
              item: 'Average Lead',
              unit: 'Kms.',
              year2023_24: '154.20',
              year2024_25: '155.30',
            },
            {
              sno: '4',
              item: 'Passenger Earnings',
              unit: '` in crore',
              year2023_24: '70,693.32',
              year2024_25: '75,367.52',
            },
            {
              sno: '5',
              item: 'Average rate per PKMs',
              unit: 'Paise',
              year2023_24: '66.40',
              year2024_25: '66.55',
            },
            {
              sno: '6',
              item: 'Number of Passenger carried per day',
              unit: 'Millions',
              year2023_24: '18.87',
              year2024_25: '19.98',
            },
          ],
        },
        {
          title: 'b. Freight Traffic (Revenue)',
          entries: [
            {
              sno: '1',
              item: 'Tonnes originating',
              unit: 'Millions',
              year2023_24: '1,588.06',
              year2024_25: '1,614.91',
            },
            {
              sno: '2',
              item: 'Lead (originating)',
              unit: 'Kms.',
              year2023_24: '613',
              year2024_25: '601',
            },
            {
              sno: '3',
              item: 'Freight Earnings excl. Demurrage/Wharfage',
              unit: '` in crore',
              year2023_24: '1,65,880.58',
              year2024_25: '1,68,323.61',
            },
            {
              sno: '4',
              item: 'Freight NTKMs',
              unit: 'Millions',
              year2023_24: '973,968',
              year2024_25: '971,085',
            },
            {
              sno: '5',
              item: 'Average rate per NTKMs',
              unit: 'Paise',
              year2023_24: '170.31',
              year2024_25: '173.34',
            },
            {
              sno: '6',
              item: 'Earnings per million tonne',
              unit: '` in crore',
              year2023_24: '104.45',
              year2024_25: '104.23',
            },
            {
              sno: '7',
              item: 'Freight carried per day (including non-revenue)',
              unit: 'Millions Tonnes',
              year2023_24: '4.34',
              year2024_25: '4.43',
            },
          ],
        },
      ],
    },

    {
      title: 'VIII Train Accidents (Excl. KRCL)',
      unit: 'Nos.',
      year2023_24: '40',
      year2024_25: '31',
      numberedHeaders: ['S.No.', 'Item', 'Unit', '2023-24', '2024-25'] as const,
      entries: [
        {
          sno: '1',
          item: 'Collisions',
          unit: '"',
          year2023_24: '6',
          year2024_25: '3',
        },
        {
          sno: '2',
          item: 'Derailment',
          unit: '"',
          year2023_24: '25',
          year2024_25: '24',
        },
        {
          sno: '3',
          item: 'Level Crossing',
          unit: '"',
          year2023_24: '0',
          year2024_25: '1',
        },
        {
          sno: '4',
          item: 'Fire in trains',
          unit: '"',
          year2023_24: '9',
          year2024_25: '3',
        },
        {
          sno: '5',
          item: 'Miscellaneous',
          year2023_24: '0',
          year2024_25: '0',
        },
        {
          sno: '6',
          item: 'Accident per million train Kms',
          year2023_24: '0.03',
          year2024_25: '0.03',
        },
      ],
    },
    {
      title: 'IX Density',
      numberedHeaders: ['S.No.', 'Item', 'Unit', '2023-24', '2024-25'] as const,
      entries: [
        {
          sno: '1',
          item: 'Net Tonne Kms per route Km. (BG)',
          unit: 'Km.',
          year2023_24: '14.58',
          year2024_25: '14.41',
        },
        {
          sno: '2',
          item: 'Passenger Kms per route Km. (BG)',
          unit: '"',
          year2023_24: '15.93',
          year2024_25: '16.80',
        },
        {
          sno: '3',
          item: 'Gross Tonne Kms per route Km. (BG)',
          unit: '"',
          year2023_24: '*38.84',
          year2024_25: '38.26',
        },
      ],
    },
    {
      title: 'X Consumption of Fuel/Energy by Locomotive',
      numberedHeaders: ['S.No.', 'Item', 'Unit', '2023-24', '2024-25'] as const,
      entries: [
        {
          sno: '(i)',
          item: 'Diesel',
          unit: 'Million litres',
          year2023_24: '*1,212.65',
          year2024_25: '977.11',
        },
        {
          sno: '(ii)',
          item: 'Electric',
          unit: 'Million KWH',
          year2023_24: '*23,310.74',
          year2024_25: '25,385.86',
        },
      ],
    },
    {
      title: '(A) Financial Ratios',
      numberedHeaders: ['S.No.', 'Item', 'Unit', '2023-24', '2024-25'] as const,
      entries: [
        {
          sno: '1.',
          item: 'Operating ratio',
          unit: '% age',
          year2023_24: '98.43',
          year2024_25: '98.22',
        },
        {
          sno: '2.',
          item: 'Rate of return on Capital',
          unit: '% age',
          year2023_24: '0.44',
          year2024_25: '0.29',
        },
        {
          sno: '3.',
          item: 'Working ratio of IR',
          unit: '% age',
          year2023_24: '91.31',
          year2024_25: '91.60',
        },
        {
          sno: '4.',
          item: 'Operating ratio with subsidy (Cost recovery)',
          unit: '% age',
          year2023_24: '81.10',
          year2024_25: '81.70',
        },
        {
          sno: '5.',
          item: 'Operating ratio for Coaching (Passenger) and Goods (Freight)',
          children: [
            {
              sno: 'i.',
              item: 'Goods',
              unit: '% age',
              year2023_24: '67.55',
              year2024_25: '71.29',
            },
            {
              sno: 'ii.',
              item: 'Coaching',
              unit: '% age',
              year2023_24: '177.69',
              year2024_25: '171.53',
            },
          ],
        },
        {
          sno: '6.',
          item: 'Debt Servicing as percentage of OWE and as a percentage of Gross receipts.',
          children: [
            {
              sno: 'i.',
              item: 'Debt servicing as percentage of OWE',
              unit: '% age',
              year2023_24: '19.70',
              year2024_25: '20.40',
            },
            {
              sno: 'ii.',
              item: 'Debt servicing as percentage of Gross receipts',
              unit: '% age',
              year2023_24: '14.70',
              year2024_25: '15.40',
            },
          ],
        },
        {
          sno: '7.',
          item: 'Capex to Revenue ratio - Capex (from internal  generation ) /Revenue',
          unit: '% age',
          year2023_24: '1.20',
          year2024_25: '0.80',
        },
      ],
    },
    {
      title: '(B) Earning/Yield Ratios (Based on Apportion Earning)',
      numberedHeaders: ['S.No.', 'Item', 'Unit', '2023-24', '2024-25'] as const,
      entries: [
        {
          sno: '1.',
          item: 'Passenger yield/ PKMs',
          unit: 'In Paise',
          year2023_24: '66.40',
          year2024_25: '66.55',
        },
        {
          sno: '2.',
          item: 'Freight yield/NTKMs',
          unit: 'In Paise',
          year2023_24: '170.31',
          year2024_25: '173.34',
        },
      ],
    },
    {
      title: '(C) Productivity Index',
      numberedHeaders: ['S.No.', 'Item', 'Unit', '2023-24', '2024-25'] as const,
      entries: [
        {
          sno: '1.',
          item: 'Employee Productivity',
          year2023_24: '8,48,391',
          year2024_25: '8,66,631',
        },
        {
          sno: '2.',
          item: 'Infrastructure Productivity',
          year2023_24: '78,57,124',
          year2024_25: '77,44,801',
        },
      ],
    },
    {
      title: '(D) Asset Utilization',
      numberedHeaders: ['S.No.', 'Item', 'Unit', '2023-24', '2024-25'] as const,
      entries: [
        {
          sno: '1.',
          item: 'Utilization of Assets',
          children: [
            {
              sno: 'i.',
              item: 'NTKMs per wagon per day -(BG)',
              unit: 'KMs',
              year2023_24: '7,851',
              year2024_25: '7,292',
            },
            {
              sno: 'ii.',
              item: 'Wagon KMs per Wagon day -(BG)',
              unit: 'KMs',
              year2023_24: '192.00',
              year2024_25: '176.0',
            },
            {
              sno: 'iii.',
              item: 'Wagon turn around - BG',
              unit: 'In days',
              year2023_24: '5.11',
              year2024_25: '5.48',
            },
            {
              sno: 'iv.',
              item: 'Average Load per Wagon - BG',
              unit: 'Tonnes',
              year2023_24: '65.00',
              year2024_25: '68.00',
            },
          ],
        },
      ],
    },
    {
      title: '(E) Operating Indices',
      numberedHeaders: ['S.No.', 'Item', 'Unit', '2023-24', '2024-25'] as const,
      entries: [
        {
          sno: '1.',
          item: 'Average speed of Goods Train – (BG) – All traction',
          unit: 'KM/hour',
          year2023_24: '25.00',
          year2024_25: '23.4',
        },
        {
          sno: '2.',
          item: 'Ineffective percentage of Rolling Stock – (BG)',
          children: [
            {
              sno: 'i.',
              item: 'Diesel Locos',
              unit: '% age',
              year2023_24: '*11.90',
              year2024_25: '10.32',
            },
            {
              sno: 'ii.',
              item: 'Electric Locos',
              unit: '% age',
              year2023_24: '*5.34',
              year2024_25: '5.99',
            },
            {
              sno: 'iii.',
              item: 'EMU Coaches',
              unit: '% age',
              year2023_24: '8.48',
              year2024_25: '9.37',
            },
            {
              sno: 'iv.',
              item: 'Passenger Carriages',
              unit: '% age',
              year2023_24: '*5.11',
              year2024_25: '5.42',
            },
            {
              sno: 'v.',
              item: 'Other Coaching Vehicles',
              unit: '% age',
              year2023_24: '*7.47',
              year2024_25: '7.94',
            },
            {
              sno: 'vi.',
              item: 'Wagons',
              unit: '% age',
              year2023_24: '*2.45',
              year2024_25: '2.88',
            },
          ],
        },
        {
          sno: '3.',
          item: 'Specific Fuel Consumption  (Consumption per 1000 GTKMs) – (BG)',
          children: [
            {
              sno: 'i.',
              item: 'Passenger service Diesel',
              unit: 'Litres',
              year2023_24: '3.42',
              year2024_25: '1.88',
            },
            {
              sno: 'ii.',
              item: 'Goods services Diesel',
              unit: 'Litres',
              year2023_24: '1.98',
              year2024_25: '1.46',
            },
          ],
        },
        {
          sno: '4.',
          item: 'Specific Energy Consumption  (Consumption per 1000 GTKMs) – (BG)',
          children: [
            {
              sno: 'i.',
              item: 'Passenger service- Electricity',
              unit: 'K.Wt. Hrs.',
              year2023_24: '*18.80',
              year2024_25: '18.70',
            },
            {
              sno: 'ii.',
              item: 'Goods services -Electricity',
              unit: 'K.Wt. Hrs.',
              year2023_24: '*6.22',
              year2024_25: '6.50',
            },
          ],
        },
        {
          sno: '5.',
          item: 'Punctuality Index – Punctuality (M/Exp. Trains) – (BG)',
          unit: '% age',
          year2023_24: '73.62',
          year2024_25: '77.12',
        },
        {
          sno: '6.',
          item: 'Accident per Million Train Kilometers',
          year2023_24: '0.03',
          year2024_25: '0.03',
        },
      ],
    },
  ],
}
