export const aomPreviousPapersQuizzes = {
  quizzes: {
    'professional-subject': [
      {
        question: "Which of the given option modules is NOT part of the ICMS (Integrated Coaching Management System)?",
        options: [
          "COIS",
          "TMS",
          "PAM",
          "Time Tabling Module",
        ],
        correct: 1,
        explanation: "TMS is the correct answer.",
      },
      {
        question: "Which of the given commodities has the highest share in the total freight loading of Indian Railways?",
        options: [
          "Cement",
          "Iron Ore",
          "Coal",
          "Foodgrains",
        ],
        correct: 2,
        explanation: "Coal is the correct answer.",
      },
      {
        question: "In an Automatic Signaling section during foggy weather, what is the maximum permissible speed of a train when the signal aspect is Green, if the locomotive is: (i) equipped with a functional Fog Safe Device, and (ii) not equipped with it?",
        options: [
          "(i) 75 kmph, (ii) 45 kmph",
          "(i) 60 kmph, (ii) 30 kmph",
          "(i) 75 kmph, (ii) 60 kmph",
          "(i) 90 kmph, (ii) 75 kmph",
        ],
        correct: 2,
        explanation: "(i) 75 kmph, (ii) 60 kmph is the correct answer.",
      },
      {
        question: "Material trains, Track Maintenance Trains, Ballast Trains and Relief Trains are classified under which of the given categories?",
        options: [
          "Departmental Trains",
          "Shunting Trains",
          "Mixed Trains",
          "Special Trains",
        ],
        correct: 0,
        explanation: "Departmental Trains is the correct answer.",
      },
      {
        question: "Between which locations has the construction of a new Dedicated Freight Corridor been announced in the Budget?",
        options: [
          "Delhi–Varanasi",
          "Pune–Hyderabad",
          "Dankuni–Surat",
          "None of the options",
        ],
        correct: 2,
        explanation: "Dankuni–Surat is the correct answer.",
      },
      {
        question: "Which organization is developing India's first indigenous hydrogen-powered train?",
        options: [
          "BHEL",
          "Siemens",
          "Modern Coach Factory (MCF)",
          "Integral Coach Factory (ICF)",
        ],
        correct: 3,
        explanation: "Integral Coach Factory (ICF) is the correct answer.",
      },
      {
        question: "Which portal is used for uploading accident-related information on Indian Railways?",
        options: [
          "ICMS",
          "CMS",
          "FOIS",
          "SIMS",
        ],
        correct: 3,
        explanation: "SIMS is the correct answer.",
      },
      {
        question: "What is the total length of the Udhampur–Srinagar–Baramulla Railway Link inaugurated by the Prime Minister on 06 June 2025?",
        options: [
          "225 km",
          "272 km",
          "325 km",
          "172 km",
        ],
        correct: 1,
        explanation: "272 km is the correct answer.",
      },
      {
        question: "Train collisions are classified as \"Consequential Train Accidents\" under which of the given categories?",
        options: [
          "A1 to A2",
          "A1 to A3",
          "A1 to A4",
          "None of the given options",
        ],
        correct: 2,
        explanation: "A1 to A4 is the correct answer.",
      },
      {
        question: "A Combined Crew Lobby is classified as a Category \"A\" lobby if it serves how many users per day?",
        options: [
          "21 to 50 users",
          "50 or more users",
          "Up to 20 users",
          "51 or more users",
        ],
        correct: 3,
        explanation: "51 or more users is the correct answer.",
      },
      {
        question: "Which of the following loco failures is not categorized as a Non-Statistical Loco Failure?",
        options: [
          "Failure of departmental service loco",
          "Failure of trial loco after heavy repair schedule",
          "Failure of shunting service loco",
          "Failure of loco overdue for schedule by more than 12 hours",
        ],
        correct: 3,
        explanation: "Failure of loco overdue for schedule by more than 12 hours is the correct answer.",
      },
      {
        question: "The spacing of Automatic Block Signalling (ABS) signals for lines exclusively used for freight traffic may normally be kept at:",
        options: [
          "1 km",
          "2 km",
          "1.5 km",
          "3 km",
        ],
        correct: 1,
        explanation: "2 km is the correct answer.",
      },
      {
        question: "What is the minimum safety radius to be observed when testing detonators?",
        options: [
          "100 metres",
          "200 metres",
          "50 metres",
          "40 metres",
        ],
        correct: 2,
        explanation: "50 metres is the correct answer.",
      },
      {
        question: "Which of the following is NOT classified as a \"Consequential Train Accident\" in the Accident Manual?",
        options: [
          "Collision",
          "Derailment",
          "Fire",
          "Averted Collision",
        ],
        correct: 3,
        explanation: "Averted Collision is the correct answer.",
      },
      {
        question: "What is the full form of DPWCS in Indian Railways?",
        options: [
          "Distributed Power With Control System",
          "Digital Power Wireless Control System",
          "Diesel Power Wireless Communication System",
          "Distributed Power Wireless Control System",
        ],
        correct: 3,
        explanation: "Distributed Power Wireless Control System is the correct answer.",
      },
      {
        question: "What does the engine whistle code \"two short and one long\" (OO –) indicate in railway operations?",
        options: [
          "Guard to apply brakes",
          "Alarm chain has been pulled",
          "Train is starting",
          "Defective signal",
        ],
        correct: 1,
        explanation: "Alarm chain has been pulled is the correct answer.",
      },
      {
        question: "What is the standard minimum length of a Sand Hump when used as a substitute for adequate distance?",
        options: [
          "60 metres",
          "120 metres",
          "180 metres",
          "250 metres",
        ],
        correct: 0,
        explanation: "60 metres is the correct answer.",
      },
      {
        question: "What is the prescribed preservation period for Caution Order registers and books?",
        options: [
          "3 years",
          "2 years",
          "1 year",
          "Permanent record",
        ],
        correct: 2,
        explanation: "1 year is the correct answer.",
      },
      {
        question: "How does the ACD system interact with road users at level crossings?",
        options: [
          "By physically blocking the level crossing with barriers",
          "By providing audio-visual warnings to road users",
          "By controlling the traffic signals at level crossings",
          "By decreasing the train's speed through level crossings",
        ],
        correct: 1,
        explanation: "By providing audio-visual warnings to road users is the correct answer.",
      },
      {
        question: "No Non-Interlocking (NI) work should last for more than:",
        options: [
          "14 days",
          "10 days",
          "7 days",
          "21 days",
        ],
        correct: 0,
        explanation: "14 days is the correct answer.",
      },
      {
        question: "The SWR of a Special Class station requires the sanction of:",
        options: [
          "GM",
          "CRS",
          "PCOM",
          "Railway Board",
        ],
        correct: 1,
        explanation: "CRS is the correct answer.",
      },
      {
        question: "After passing an Automatic Stop signal at 'ON', the Loco Pilot must maintain a minimum distance of how many metres or OHE spans from the preceding train?",
        options: [
          "100 metres or 1 clear OHE span",
          "120 metres or 2 clear OHE spans",
          "200 metres or 3 clear OHE spans",
          "150 metres or 2 clear OHE spans",
        ],
        correct: 3,
        explanation: "150 metres or 2 clear OHE spans is the correct answer.",
      },
      {
        question: "For Trolley / Motor Trolley / Lorry on a single line section, the night signal shall show which colour lights?",
        options: [
          "White light in both directions",
          "Red lights on both sides",
          "Red light in one direction and white light in the other",
          "Green light in both directions",
        ],
        correct: 2,
        explanation: "Red light in one direction and white light in the other is the correct answer.",
      },
      {
        question: "When charge of a Diesel/Electric engine is taken over outside a shed, how much time is allowed before the scheduled departure of the train and after the arrival of the locomotive at the handing-over point?",
        options: [
          "15 minutes before and 15 minutes after",
          "20 minutes before and 10 minutes after",
          "30 minutes before and 15 minutes after",
          "10 minutes before and 10 minutes after",
        ],
        correct: 0,
        explanation: "15 minutes before and 15 minutes after is the correct answer.",
      },
      {
        question: "Rail dolley shall not be worked on sections having gradients steeper than:",
        options: [
          "1 in 100",
          "1 in 150",
          "1 in 250",
          "1 in 200",
        ],
        correct: 3,
        explanation: "1 in 200 is the correct answer.",
      },
      {
        question: "In case of pushing of Material Trains, on which gradient is pushing not permitted?",
        options: [
          "On up gradient steeper than 1 in 100",
          "On gradients easier than 1 in 200",
          "On level track",
          "On down gradient steeper than 1 in 100",
        ],
        correct: 3,
        explanation: "On down gradient steeper than 1 in 100 is the correct answer.",
      },
      {
        question: "Who is responsible for planning and directing engine movements so as to ensure efficient engine utilization?",
        options: [
          "Traction Power Controller",
          "Power Controller / Traction Controller",
          "Traffic Controller",
          "Commercial Control",
        ],
        correct: 2,
        explanation: "Traffic Controller is the correct answer.",
      },
      {
        question: "To minimize Pre-Departure Detention (PDD), what is the maximum time generally allowed for \"Train Pulling\" across Zonal Railways?",
        options: [
          "15 minutes",
          "25 minutes",
          "20 minutes",
          "10 minutes",
        ],
        correct: 0,
        explanation: "15 minutes is the correct answer.",
      },
      {
        question: "Arrange the following trains in the correct general order of precedence: I. Mail/Express Train II. Passenger Train III. Super-fast Train (Rajdhani/Shatabdi) IV. Through Goods Train",
        options: [
          "I, III, II, IV",
          "III, I, II, IV",
          "III, II, I, IV",
          "II, I, III, IV",
        ],
        correct: 1,
        explanation: "III, I, II, IV is the correct answer.",
      },
      {
        question: "After exploding a detonator, if no obstruction is encountered, the Loco Pilot may resume normal speed only after proceeding cautiously for a distance of:",
        options: [
          "1200 metres",
          "1220 metres",
          "1500 metres",
          "600 metres",
        ],
        correct: 2,
        explanation: "1500 metres is the correct answer.",
      },
      {
        question: "At what time intervals are the running staff reviewed?",
        options: [
          "2 years",
          "3 years",
          "1 year",
          "6 months",
        ],
        correct: 2,
        explanation: "1 year is the correct answer.",
      },
      {
        question: "Which document is automatically generated by SigDATE software using the Signal Interlocking Plan (SIP)?",
        options: [
          "Route Control Chart (RCC)",
          "Train Timetable",
          "Crew Duty Roster",
          "Track Maintenance Schedule",
        ],
        correct: 0,
        explanation: "Route Control Chart (RCC) is the correct answer.",
      },
      {
        question: "What is the maximum speed limit up to which the FogPASS device is suitable for providing assistance to Loco Pilots?",
        options: [
          "100 kmph",
          "160 kmph",
          "140 kmph",
          "120 kmph",
        ],
        correct: 1,
        explanation: "160 kmph is the correct answer.",
      },
      {
        question: "In Indian Railways' freight statistics, which of the following is included under \"Non-Revenue Traffic\"?",
        options: [
          "Military Equipment",
          "Coal for Export",
          "Railway's own Ballast and Fuel",
          "Relief material during disasters",
        ],
        correct: 2,
        explanation: "Railway's own Ballast and Fuel is the correct answer.",
      },
      {
        question: "A lorry shall ordinarily be run only by day and when the weather is sufficiently clear for a signal to be distinctly seen from a minimum distance of:",
        options: [
          "400 metres",
          "1200 metres",
          "800 metres",
          "600 metres",
        ],
        correct: 2,
        explanation: "800 metres is the correct answer.",
      },
      {
        question: "The Anti Collision Device (ACD) communicates with each other through radio communication when they are within a radial range of at least:",
        options: [
          "4 km",
          "1 km",
          "2 km",
          "3 km",
        ],
        correct: 3,
        explanation: "3 km is the correct answer.",
      },
      {
        question: "When a train stops due to an accident in an Automatic section, the first detonator to protect the same line must be placed at a distance of:",
        options: [
          "250 metres",
          "90 metres",
          "150 metres",
          "400 metres",
        ],
        correct: 1,
        explanation: "90 metres is the correct answer.",
      },
      {
        question: "A Gate Stop Signal in Automatic territory is identified by:",
        options: [
          "'G' marker only",
          "'G' marker and an illuminated 'A' marker",
          "White disc",
          "Red light only",
        ],
        correct: 1,
        explanation: "'G' marker and an illuminated 'A' marker is the correct answer.",
      },
      {
        question: "What is the primary purpose of the Punctuality Module (PAM) within the Integrated Coaching Management System (ICMS)?",
        options: [
          "Simulating suitable timings for train schedules",
          "Generating reports for the management of coaching stock",
          "Real-time monitoring of train punctuality",
          "Post facto analysis of punctuality loss and its causes",
        ],
        correct: 3,
        explanation: "Post facto analysis of punctuality loss and its causes is the correct answer.",
      },
      {
        question: "At what distance is the Caution Indicator Board placed from the site of obstruction on Broad Gauge (BG)?",
        options: [
          "800 metres",
          "1200 metres",
          "1000 metres",
          "600 metres",
        ],
        correct: 1,
        explanation: "1200 metres is the correct answer.",
      },
      {
        question: "What are the three aspects shown by signals in a 3-aspect signaling territory?",
        options: [
          "None of the above options",
          "Stop, Attention, Proceed",
          "Stop, Caution, Proceed",
          "Attention, Caution, Proceed",
        ],
        correct: 2,
        explanation: "Stop, Caution, Proceed is the correct answer.",
      },
      {
        question: "What is the index of growth for Passenger Traffic (Non-Suburban Passenger Kilometres) in the year 2024–25, considering 1950–51 as the base year (1950–51 = 100)?",
        options: [
          "1578",
          "2202",
          "1686",
          "522",
        ],
        correct: 2,
        explanation: "1686 is the correct answer.",
      },
      {
        question: "What is the full form of WILD in the Indian Railways system?",
        options: [
          "Wheel Indicator Load Device",
          "Wheel Impact Load Detector",
          "Wireless Impact Load Detector",
          "Wagon Impact Level Detector",
        ],
        correct: 1,
        explanation: "Wheel Impact Load Detector is the correct answer.",
      },
      {
        question: "The vehicle code/transport code for a Dining Car is:",
        options: [
          "CK",
          "DC",
          "CD",
          "DK",
        ],
        correct: 2,
        explanation: "CD is the correct answer.",
      },
      {
        question: "When the control is interrupted and no communication with the Controller is possible, who will be responsible for the working and regulating of trains?",
        options: [
          "Chief Controller",
          "Loco Pilots",
          "Traffic Inspector",
          "Station Masters",
        ],
        correct: 3,
        explanation: "Station Masters is the correct answer.",
      },
      {
        question: "In consequential and indicative accident cases, entry into SIMS shall be made on a real-time basis, but not later than ______ after the occurrence of the event.",
        options: [
          "1 hour",
          "2 hours",
          "4 hours",
          "30 minutes",
        ],
        correct: 1,
        explanation: "2 hours is the correct answer.",
      },
      {
        question: "For how many days is cancellation of indent not permitted after Advance Stacking Permission is granted?",
        options: [
          "None of the given options",
          "5 days",
          "6 days",
          "4 days",
        ],
        correct: 0,
        explanation: "None of the given options is the correct answer.",
      },
      {
        question: "Which rule mandates that the Railway Administration shall supply a copy of the rules to every station?",
        options: [
          "Rule 2.03",
          "Rule 2.01",
          "Rule 2.04",
          "Rule 2.02",
        ],
        correct: 1,
        explanation: "Rule 2.01 is the correct answer.",
      },
      {
        question: "What is the total route length of the Eastern Dedicated Freight Corridor?",
        options: [
          "1100 km",
          "1506 km",
          "1337 km",
          "2020 km",
        ],
        correct: 1,
        explanation: "1506 km is the correct answer.",
      },
      {
        question: "How many litres of diesel are being saved annually due to electrification in Indian Railways?",
        options: [
          "320 crore litres",
          "50 crore litres",
          "180 crore litres",
          "100 crore litres",
        ],
        correct: 2,
        explanation: "180 crore litres is the correct answer.",
      },
      {
        question: "According to safety regulations, what is the minimum electrical clearance to be maintained from live 25 kV OHE equipment?",
        options: [
          "1.5 metres",
          "2.0 metres",
          "1.0 metre",
          "3.0 metres",
        ],
        correct: 1,
        explanation: "2.0 metres is the correct answer.",
      },
      {
        question: "What is India's global rank in freight transportation by rail?",
        options: [
          "Seventh",
          "Second",
          "Fifth",
          "Twelfth",
        ],
        correct: 1,
        explanation: "Second is the correct answer.",
      },
      {
        question: "What is the immediate first action a Loco Pilot must take upon the occurrence of an accident or an unusual occurrence that may obstruct the adjacent track?",
        options: [
          "Switch on the flasher light of the locomotive",
          "Check the extent of damage to the coaches",
          "Protect the track with detonators",
          "Inform the Guard via walkie-talkie",
        ],
        correct: 0,
        explanation: "Switch on the flasher light of the locomotive is the correct answer.",
      },
      {
        question: "Which of the following is NOT considered an essential item to be maintained at a Crew Lobby?",
        options: [
          "Gradient Chart",
          "Abnormality Register",
          "Accident Chart",
          "Breathalyzer",
        ],
        correct: 2,
        explanation: "Accident Chart is the correct answer.",
      },
      {
        question: "What is the prescribed standard suitcase size for storing POMKA (Portable Medical Kit for Accidents) contents?",
        options: [
          "18 inches",
          "15 inches",
          "21 inches",
          "25 inches",
        ],
        correct: 2,
        explanation: "21 inches is the correct answer.",
      },
      {
        question: "In a division with both diesel and electric operations, the Control Office prepares Loco Outage based on:",
        options: [
          "Type of traction",
          "All of the given options",
          "Home shed",
          "Type of service",
        ],
        correct: 1,
        explanation: "All of the given options is the correct answer.",
      },
      {
        question: "Which of the following equipment is NOT associated with the handling of coal in BOXN wagons?",
        options: [
          "Pay Loader",
          "Wagon Tippler",
          "Silo",
          "Reach Stacker",
        ],
        correct: 3,
        explanation: "Reach Stacker is the correct answer.",
      },
      {
        question: "When is a Green Notice issued?",
        options: [
          "Temporary Single Line Working",
          "PQRS Work",
          "Consequential Train Accident",
          "None of the above options",
        ],
        correct: 3,
        explanation: "None of the above options is the correct answer.",
      },
      {
        question: "During pushing, a Patrol or Search Light Special with one or more vehicles in front of the engine may be permitted to run at a maximum speed of:",
        options: [
          "40 kmph",
          "30 kmph",
          "60 kmph",
          "25 kmph",
        ],
        correct: 0,
        explanation: "40 kmph is the correct answer.",
      },
      {
        question: "During an emergency at a Level Crossing, at what minimum distance from the obstruction should a Danger Signal be immediately exhibited?",
        options: [
          "2 metres",
          "15 metres",
          "5 metres",
          "10 metres",
        ],
        correct: 2,
        explanation: "5 metres is the correct answer.",
      },
      {
        question: "A loco failure causing a delay of ______ or more to a freight train due to loco problems or enginemanship of the crew is categorized as a Statistical Loco Failure.",
        options: [
          "60 minutes",
          "90 minutes",
          "30 minutes",
          "45 minutes",
        ],
        correct: 0,
        explanation: "60 minutes is the correct answer.",
      },
      {
        question: "What is the standard Adequate Distance (Signal Overlap) in the Automatic Block System on Broad Gauge?",
        options: [
          "100 metres",
          "400 metres",
          "120 metres",
          "180 metres",
        ],
        correct: 2,
        explanation: "120 metres is the correct answer.",
      },
      {
        question: "A Neutral Section lies between two consecutive:",
        options: [
          "Block Stations",
          "OHE Depots",
          "Section Insulators",
          "Sub-stations",
        ],
        correct: 3,
        explanation: "Sub-stations is the correct answer.",
      },
      {
        question: "In case of ACP, which whistle code shall the Loco Pilot sound?",
        options: [
          "Three Long",
          "One Short, One Long",
          "Two Short, One Long",
          "Two Long, One Short",
        ],
        correct: 2,
        explanation: "Two Short, One Long is the correct answer.",
      },
      {
        question: "Which accident classification covers the failure of an engine hauling a goods train or a light engine?",
        options: [
          "Class L-2",
          "Class J-2",
          "Class J-1",
          "Class K-1",
        ],
        correct: 1,
        explanation: "Class J-2 is the correct answer.",
      },
      {
        question: "What is the full form of MSDAC in Indian Railways?",
        options: [
          "Multiple System Detection and Control",
          "Multi Signal Digital Axle Counter",
          "Main Section Data Axle Counter",
          "Multi Section Digital Axle Counter",
        ],
        correct: 3,
        explanation: "Multi Section Digital Axle Counter is the correct answer.",
      },
      {
        question: "The census for calculating Train Vehicle Units (TVU) at a Level Crossing is normally conducted once every:",
        options: [
          "3 years",
          "1 year",
          "10 years",
          "5 years",
        ],
        correct: 0,
        explanation: "3 years is the correct answer.",
      },
      {
        question: "As per Railway Board guidelines, what percentage of Leave Reserve and Trainee Reserve should be incorporated while assessing crew requirements?",
        options: [
          "30% Leave Reserve and 10% Trainee Reserve",
          "20% Leave Reserve and 5% Trainee Reserve",
          "25% Leave Reserve and 10% Trainee Reserve",
          "30% Leave Reserve and 15% Trainee Reserve",
        ],
        correct: 0,
        explanation: "30% Leave Reserve and 10% Trainee Reserve is the correct answer.",
      },
      {
        question: "When a train stops between stations in an Automatic Block section, the Guard must protect the train from the:",
        options: [
          "Front",
          "Both sides",
          "Not required",
          "Rear",
        ],
        correct: 3,
        explanation: "Rear is the correct answer.",
      },
      {
        question: "The types of shunt signals are:",
        options: [
          "All of the given options",
          "Miniature Semaphore",
          "Position Type",
          "Disc Type",
        ],
        correct: 0,
        explanation: "All of the given options is the correct answer.",
      },
      {
        question: "A section is considered saturated when sectional utilisation exceeds:",
        options: [
          "70% of charted capacity",
          "90% of charted capacity",
          "80% of charted capacity",
          "100% of charted capacity",
        ],
        correct: 1,
        explanation: "90% of charted capacity is the correct answer.",
      },
      {
        question: "Which of the following is considered a better Operating Ratio for a railway?",
        options: [
          "90%",
          "80%",
          "100%",
          "75%",
        ],
        correct: 3,
        explanation: "75% is the correct answer.",
      },
      {
        question: "Which set of conditions strictly determines the number of trains permitted to run simultaneously in a block section under the Following Train System?",
        options: [
          "Maximum 2 trains and 1 train per 2 km",
          "Maximum 4 trains and 1 train per 10 km",
          "Maximum 5 trains and 1 train per 4 km",
          "Maximum 4 trains and 1 train per 5 km",
        ],
        correct: 3,
        explanation: "Maximum 4 trains and 1 train per 5 km is the correct answer.",
      },
      {
        question: "Which type of Brake Power Certificate (BPC) has the longest validity period?",
        options: [
          "Intensive",
          "All of the options have the same validity",
          "CC",
          "Premium",
        ],
        correct: 2,
        explanation: "CC is the correct answer.",
      },
      {
        question: "IBS (Intermediate Block Signalling) shall not be provided on sections with heavy and continuous falling gradients steeper than ______ unless the brake power of trains is adequate to stop the train at the IBS.",
        options: [
          "1 in 80",
          "1 in 60",
          "1 in 120",
          "1 in 100",
        ],
        correct: 0,
        explanation: "1 in 80 is the correct answer.",
      },
      {
        question: "Catch siding is intended to protect which of the following?",
        options: [
          "Station Section",
          "Block Section",
          "Outlying Siding",
          "Station Limits",
        ],
        correct: 0,
        explanation: "Station Section is the correct answer.",
      },
      {
        question: "Which of the following is NOT among the standard compositions prescribed by the Railway Board for LHB coaches?",
        options: [
          "22 Coaches",
          "18 Coaches",
          "16 Coaches",
          "21 Coaches",
        ],
        correct: 3,
        explanation: "21 Coaches is the correct answer.",
      },
      {
        question: "The normal aspect of an Automatic Stop Signal is:",
        options: [
          "Stop",
          "Attention",
          "Proceed",
          "Caution",
        ],
        correct: 3,
        explanation: "Caution is the correct answer.",
      },
      {
        question: "An EMU train uses which type of coupling?",
        options: [
          "CBC",
          "Screw Coupling",
          "Schaku Coupler",
          "Buffer and Chain",
        ],
        correct: 2,
        explanation: "Schaku Coupler is the correct answer.",
      },
      {
        question: "Suvidha Special trains generally start with the digit:",
        options: [
          "5",
          "7",
          "6",
          "8",
        ],
        correct: 3,
        explanation: "8 is the correct answer.",
      },
      {
        question: "For the Financial Year 2024–25, what was the total Revenue Earning Freight Traffic handled by Indian Railways?",
        options: [
          "1,614.91 MT",
          "2,625.50 MT",
          "1,188.20 MT",
          "3,650.00 MT",
        ],
        correct: 0,
        explanation: "1,614.91 MT is the correct answer.",
      },
      {
        question: "Indian Railways' first Gati Shakti Cargo Terminal was commissioned in which division?",
        options: [
          "Mumbai Division",
          "Prayagraj Division",
          "Asansol Division",
          "Lucknow Division",
        ],
        correct: 2,
        explanation: "Asansol Division is the correct answer.",
      },
      {
        question: "Which device is used at stations to selectively shut down the OHE supply over a specific part or sub-part of an elementary section?",
        options: [
          "Tripping Switch",
          "Isolator",
          "Insulator",
          "Circuit Breaker",
        ],
        correct: 1,
        explanation: "Isolator is the correct answer.",
      },
      {
        question: "What is the codal life of LHB design stainless steel coaches in Indian Railways?",
        options: [
          "30 years",
          "35 years",
          "25 years",
          "40 years",
        ],
        correct: 1,
        explanation: "35 years is the correct answer.",
      },
      {
        question: "A VDU (Visual Display Unit) is the standard operating interface available in which interlocking system?",
        options: [
          "M.I.",
          "P.I.",
          "SSI",
          "RRI",
        ],
        correct: 2,
        explanation: "SSI is the correct answer.",
      },
    ],
    'gk-rajabhasha': [
      {
        question: "How many States and UTs/NCT fall under Region 'A' as per the Official Language Rules?",
        options: [
          "8 States and 2 UTs",
          "7 States and 1 UT",
          "None of the given options",
          "9 States and 2 (UT + NCT)",
        ],
        correct: 3,
        explanation: "9 States and 2 (UT + NCT) is the correct answer.",
      },
      {
        question: "How many sections are there in the Official Language Act?",
        options: [
          "10",
          "7",
          "9",
          "8",
        ],
        correct: 2,
        explanation: "9 is the correct answer.",
      },
      {
        question: "Who among the following was one of the Navratnas of Akbar?",
        options: [
          "Amir Khusro",
          "Swami Haridas",
          "Abul Fazl",
          "Purandar Das",
        ],
        correct: 2,
        explanation: "Abul Fazl is the correct answer.",
      },
      {
        question: "Which country officially changed its capital's name from Nur-Sultan back to Astana?",
        options: [
          "Kyrgyzstan",
          "Uzbekistan",
          "Turkmenistan",
          "Kazakhstan",
        ],
        correct: 3,
        explanation: "Kazakhstan is the correct answer.",
      },
      {
        question: "Under which Official Language Rule are the names of Central Government offices, where 80% of employees have acquired working knowledge of Hindi, notified in the Gazette?",
        options: [
          "Rule 10(3)",
          "Rule 10(4)",
          "Rule 10",
          "Rule 10(2)",
        ],
        correct: 1,
        explanation: "Rule 10(4) is the correct answer.",
      },
      {
        question: "Which team secured the Ranji Trophy title in the 2025–26 season?",
        options: [
          "Jammu & Kashmir",
          "Vidarbha",
          "Mumbai",
          "Karnataka",
        ],
        correct: 0,
        explanation: "Jammu & Kashmir is the correct answer.",
      },
      {
        question: "Which committee recommended the inclusion of Fundamental Duties in the Constitution?",
        options: [
          "Balwant Rai Mehta Committee",
          "Swaran Singh Committee",
          "Verma Committee",
          "Sarkaria Commission",
        ],
        correct: 1,
        explanation: "Swaran Singh Committee is the correct answer.",
      },
      {
        question: "In which of the following games is the Baulk Line used?",
        options: [
          "Kho-Kho",
          "Badminton",
          "Kabaddi",
          "Tennis",
        ],
        correct: 2,
        explanation: "Kabaddi is the correct answer.",
      },
      {
        question: "As of early 2026, which Indian state holds the record for the highest number of designated Ramsar Sites?",
        options: [
          "Uttar Pradesh",
          "Tamil Nadu",
          "West Bengal",
          "Punjab",
        ],
        correct: 1,
        explanation: "Tamil Nadu is the correct answer.",
      },
      {
        question: "Maithili, Bodo, Dogri, and Santhali were added to the Eighth Schedule of the Constitution in the year:",
        options: [
          "2002",
          "2003",
          "2004",
          "1992",
        ],
        correct: 2,
        explanation: "2004 is the correct answer.",
      },
      {
        question: "Which Indian state became the first to establish a national-level Artificial Intelligence (AI) research institution?",
        options: [
          "Gujarat",
          "Maharashtra",
          "Karnataka",
          "Telangana",
        ],
        correct: 0,
        explanation: "Gujarat is the correct answer.",
      },
      {
        question: "Where is the Debrigarh Wildlife Sanctuary, which recently hosted the Indian Bison Fest, located?",
        options: [
          "Chhattisgarh",
          "Jharkhand",
          "Odisha",
          "Madhya Pradesh",
        ],
        correct: 2,
        explanation: "Odisha is the correct answer.",
      },
      {
        question: "In which layer of the Earth's atmosphere is the ozone layer primarily located?",
        options: [
          "Troposphere",
          "Stratosphere",
          "Exosphere",
          "Mesosphere",
        ],
        correct: 1,
        explanation: "Stratosphere is the correct answer.",
      },
      {
        question: "Sadbhavana Diwas is celebrated every year on:",
        options: [
          "20 August",
          "14 November",
          "15 August",
          "2 October",
        ],
        correct: 0,
        explanation: "20 August is the correct answer.",
      },
      {
        question: "The Environment (Protection) Act, 1986 empowers the ________ to establish authorities charged with preventing environmental pollution in all its forms.",
        options: [
          "Central Government",
          "Supreme Court",
          "State Government",
          "Local Municipalities",
        ],
        correct: 0,
        explanation: "Central Government is the correct answer.",
      },
      {
        question: "Which clinical test is specifically used to confirm the diagnosis of Typhoid fever?",
        options: [
          "ELISA Test",
          "Widal Test",
          "CT Scan",
          "MRI Scan",
        ],
        correct: 1,
        explanation: "Widal Test is the correct answer.",
      },
      {
        question: "The organization that Comptroller and Auditor General heads is known as",
        options: [
          "Institute of Chartered Accountants of India",
          "Indian Audit and Accounts Department",
          "Indian Civil Accounts Organisation",
          "Controller General of Accounts",
        ],
        correct: 1,
        explanation: "Indian Audit and Accounts Department is the correct answer.",
      },
      {
        question: "The 'Republic' feature of the Indian Constitution was inspired by the Constitution of which country?",
        options: [
          "Australian Constitution",
          "British Constitution",
          "Irish Constitution",
          "French Constitution",
        ],
        correct: 3,
        explanation: "French Constitution is the correct answer.",
      },
      {
        question: "Which constitutional body has the exclusive power to initiate the creation of a new All India Service under Article 312?",
        options: [
          "Rajya Sabha",
          "UPSC",
          "Lok Sabha",
          "President of India",
        ],
        correct: 0,
        explanation: "Rajya Sabha is the correct answer.",
      },
      {
        question: "Who was the First Chairman of the Parliamentary Committee on Official Language constituted in 1976?",
        options: [
          "Lalit Narayan Mishra",
          "Bal Gangadhar Kher",
          "Om Mehta",
          "Kamlapati Tripathi",
        ],
        correct: 2,
        explanation: "Om Mehta is the correct answer.",
      },
      {
        question: "Mangal Pandey belonged to which infantry regiment?",
        options: [
          "7th Awadh Regiment",
          "34th Native Infantry",
          "19th Native Infantry",
          "20th Native Infantry",
        ],
        correct: 1,
        explanation: "34th Native Infantry is the correct answer.",
      },
      {
        question: "Gautamiputra Satakarni titled Rajaraja and Maharaja is related to which dynasty?",
        options: [
          "Shunga",
          "Satavahana",
          "Pandya",
          "Shaka",
        ],
        correct: 1,
        explanation: "Satavahana is the correct answer.",
      },
      {
        question: "Which traveller recorded his experiences in the book \"Kitab-i-Rehla\"?",
        options: [
          "Al-Beruni",
          "Marco Polo",
          "Francois Bernier",
          "Ibn Battuta",
        ],
        correct: 3,
        explanation: "Ibn Battuta is the correct answer.",
      },
      {
        question: "Who is known as the 'Father of Indian Supercomputing'?",
        options: [
          "A.P.J. Abdul Kalam",
          "Vijay P. Bhatkar",
          "Homi J. Bhabha",
          "Raghunath Mashelkar",
        ],
        correct: 1,
        explanation: "Vijay P. Bhatkar is the correct answer.",
      },
      {
        question: "What is the main objective of the Montreal Protocol?",
        options: [
          "Biodiversity Conservation",
          "Protection of Ozone Layer",
          "Global Warming",
          "Forest Conservation",
        ],
        correct: 1,
        explanation: "Protection of Ozone Layer is the correct answer.",
      },
      {
        question: "What is the target year set by India to achieve 'Net Zero' carbon emissions?",
        options: [
          "2070",
          "2030",
          "2047",
          "2050",
        ],
        correct: 0,
        explanation: "2070 is the correct answer.",
      },
      {
        question: "Mohiniyattam is primarily associated with which traditional dance element?",
        options: [
          "Chowk Style",
          "Tribhanga Style",
          "Lasya Style",
          "Samapadam Style",
        ],
        correct: 2,
        explanation: "Lasya Style is the correct answer.",
      },
      {
        question: "Who was the Chairman of the First Official Language Commission?",
        options: [
          "Bal Gangadhar Kher",
          "Bal Gangadhar Tilak",
          "Govind Ballabh Pant",
          "Kamlapati Tripathi",
        ],
        correct: 0,
        explanation: "Bal Gangadhar Kher is the correct answer.",
      },
      {
        question: "Syndicate Bank was merged into which Public Sector Bank?",
        options: [
          "Canara Bank",
          "Indian Bank",
          "Bank of India",
          "Union Bank of India",
        ],
        correct: 0,
        explanation: "Canara Bank is the correct answer.",
      },
      {
        question: "What kind of solar radiation is primarily absorbed by the Ozone layer?",
        options: [
          "Ultraviolet Radiation",
          "Green Radiation",
          "Visible Radiation",
          "Infrared Radiation",
        ],
        correct: 0,
        explanation: "Ultraviolet Radiation is the correct answer.",
      },
      {
        question: "Raja Ram Mohan Roy published the Persian-language journal in India titled:",
        options: [
          "Mirat-ul-Akhbar",
          "The Brahmanical Magazine",
          "Tuhfat-ul-Muwahhidin",
          "Sambad Kaumudi",
        ],
        correct: 0,
        explanation: "Mirat-ul-Akhbar is the correct answer.",
      },
      {
        question: "By which Constitutional Amendment was Sikkim established as a full-fledged state of the Indian Union?",
        options: [
          "34th Amendment",
          "35th Amendment",
          "36th Amendment",
          "38th Amendment",
        ],
        correct: 2,
        explanation: "36th Amendment is the correct answer.",
      },
      {
        question: "The \"South High-Speed Diamond\" network announced in February 2026 primarily interlinks how many southern states?",
        options: [
          "4",
          "3",
          "5",
          "6",
        ],
        correct: 2,
        explanation: "5 is the correct answer.",
      },
      {
        question: "Which of the following pairs of books and authors is incorrectly matched?",
        options: [
          "Hind Swaraj — Mahatma Gandhi",
          "Why I am an Atheist — Bhagat Singh",
          "Raghuvaṃśam — Ramdhari Singh Dinkar",
          "Gitanjali — Rabindranath Tagore",
        ],
        correct: 2,
        explanation: "Raghuvaṃśam — Ramdhari Singh Dinkar is the correct answer.",
      },
      {
        question: "Which Part of the Constitution contains provisions regarding Official Language?",
        options: [
          "Part XVI",
          "Part XVII",
          "Part XV",
          "None of the given options",
        ],
        correct: 1,
        explanation: "Part XVII is the correct answer.",
      },
      {
        question: "Who was the First Chairman of the Committee formed on the recommendation of the Official Language Commission?",
        options: [
          "Bal Gangadhar Tilak",
          "Kamlapati Tripathi",
          "Govind Ballabh Pant",
          "Lalit Narayan Mishra",
        ],
        correct: 2,
        explanation: "Govind Ballabh Pant is the correct answer.",
      },
      {
        question: "Which of the following pairs do NOT share any borders?",
        options: [
          "Bhutan and West Bengal",
          "Bhutan and Arunachal Pradesh",
          "Bhutan and Assam",
          "Bhutan and Meghalaya",
        ],
        correct: 3,
        explanation: "Bhutan and Meghalaya is the correct answer.",
      },
      {
        question: "In which Part and Article of the Constitution is the provision regarding the language to be used for transaction of business in Parliament?",
        options: [
          "All of the given options",
          "Article 341",
          "Article 210 of Part VI",
          "Article 120 of Part V",
        ],
        correct: 3,
        explanation: "Article 120 of Part V is the correct answer.",
      },
      {
        question: "Who chaired the First Railway Hindi Salahakaar Samiti constituted in 1973?",
        options: [
          "Lalit Narayan Mishra",
          "Bal Gangadhar Kher",
          "Kamlapati Tripathi",
          "Om Mehta",
        ],
        correct: 0,
        explanation: "Lalit Narayan Mishra is the correct answer.",
      },
      {
        question: "In which Articles of the Constitution is the Official Language mentioned?",
        options: [
          "Article 120",
          "Article 210",
          "Articles 343–351",
          "All of the given options",
        ],
        correct: 3,
        explanation: "All of the given options is the correct answer.",
      },
      {
        question: "Which is the Official Language of Arunachal Pradesh?",
        options: [
          "None of the given options",
          "English",
          "Tai",
          "Arunachali Hindi",
        ],
        correct: 1,
        explanation: "English is the correct answer.",
      },
      {
        question: "Which party formed the government in Britain in the year 1945?",
        options: [
          "Labour Party",
          "Democratic Party",
          "Socialist Party",
          "Liberal Party",
        ],
        correct: 0,
        explanation: "Labour Party is the correct answer.",
      },
      {
        question: "Where was the maiden test of the Pinaka LRGR-120 system conducted?",
        options: [
          "Balasore",
          "Pokhran",
          "Sriharikota",
          "ITR Chandipur",
        ],
        correct: 3,
        explanation: "ITR Chandipur is the correct answer.",
      },
      {
        question: "Which international organization is responsible for organizing the Conference of the Parties (COP) summits?",
        options: [
          "UNFCCC",
          "WTO",
          "UNESCO",
          "WHO",
        ],
        correct: 0,
        explanation: "UNFCCC is the correct answer.",
      },
      {
        question: "Which of the following Upanishads, primarily written in prose, is considered the oldest and largest?",
        options: [
          "Chandogya Upanishad",
          "Brihadaranyaka Upanishad",
          "Isha Upanishad",
          "Shvetashvatara Upanishad",
        ],
        correct: 1,
        explanation: "Brihadaranyaka Upanishad is the correct answer.",
      },
      {
        question: "Which of the given elements is classified as a metalloid?",
        options: [
          "Sodium",
          "Silicon",
          "Iron",
          "Oxygen",
        ],
        correct: 1,
        explanation: "Silicon is the correct answer.",
      },
      {
        question: "How long is the Prabodh course conducted under Intensive Training?",
        options: [
          "15 Working Days",
          "20 Working Days",
          "25 Working Days",
          "30 Working Days",
        ],
        correct: 2,
        explanation: "25 Working Days is the correct answer.",
      },
      {
        question: "Which file extension is most commonly used for executable installation files on a Windows system?",
        options: [
          ".jpg",
          ".txt",
          ".mp3",
          ".exe",
        ],
        correct: 3,
        explanation: ".exe is the correct answer.",
      },
      {
        question: "What type of media is commonly used for WAN communication?",
        options: [
          "Coaxial Cable",
          "Fiber Optic Cable",
          "HDMI Cable",
          "Twisted Pair Cable",
        ],
        correct: 1,
        explanation: "Fiber Optic Cable is the correct answer.",
      },
      {
        question: "Wainganga and Painganga are part of which major river system?",
        options: [
          "Narmada",
          "Tapti",
          "Ganga",
          "Godavari",
        ],
        correct: 3,
        explanation: "Godavari is the correct answer.",
      },
      {
        question: "Who was the British Governor-General of India at the time of the 'Deepavali Declaration' in 1929?",
        options: [
          "Lord Mountbatten",
          "Lord Reading",
          "Lord Chelmsford",
          "Lord Irwin",
        ],
        correct: 3,
        explanation: "Lord Irwin is the correct answer.",
      },
      {
        question: "In which Part and Article of the Constitution is the provision regarding the language to be used for transaction of business in State Legislatures?",
        options: [
          "Article 341",
          "All of the given options",
          "Article 120 of Part V",
          "Article 210 of Part VI",
        ],
        correct: 3,
        explanation: "Article 210 of Part VI is the correct answer.",
      },
      {
        question: "Which Article of the Constitution contains provisions regarding the language to be used in courts, etc.?",
        options: [
          "Articles 341 & 342",
          "Article 348",
          "Article 120",
          "Article 351",
        ],
        correct: 1,
        explanation: "Article 348 is the correct answer.",
      },
      {
        question: "When electricity is passed through water, it results in which type of chemical reaction?",
        options: [
          "Double Displacement",
          "Decomposition",
          "Displacement",
          "Combination",
        ],
        correct: 1,
        explanation: "Decomposition is the correct answer.",
      },
      {
        question: "The ________ method is commonly used to verify the integrity of data.",
        options: [
          "Compression",
          "Caching",
          "Hashing",
          "Duplication",
        ],
        correct: 2,
        explanation: "Hashing is the correct answer.",
      },
    ],
    'establishment-finance-rules': [
      {
        question: "After the conclusion of a disciplinary inquiry, no penalty can be imposed on the charged official before:",
        options: [
          "Issuing of speaking orders",
          "Inspection of official records",
          "Cross-examination of witnesses",
          "Issuing notice of imposition of penalty",
        ],
        correct: 0,
        explanation: "Issuing of speaking orders is the correct answer.",
      },
      {
        question: "What is the maximum number of incentive increments that can be granted to a Railway servant during their entire career on sports account as per the 2009 policy?",
        options: [
          "5",
          "3",
          "10",
          "7",
        ],
        correct: 0,
        explanation: "5 is the correct answer.",
      },
      {
        question: "Which Standard Form is used to nominate an Inquiry Officer?",
        options: [
          "SF-9",
          "SF-4",
          "None of the given options",
          "SF-7",
        ],
        correct: 3,
        explanation: "SF-7 is the correct answer.",
      },
      {
        question: "Transfer without financial adjustment is done by:",
        options: [
          "Both of these options",
          "None of the given options",
          "By altering balances in the ledger",
          "Preparing JV",
        ],
        correct: 2,
        explanation: "By altering balances in the ledger is the correct answer.",
      },
      {
        question: "Which of the following forms is used for revocation of suspension orders?",
        options: [
          "SF No. 4",
          "SF No. 1",
          "SF No. 7",
          "SF No. 2",
        ],
        correct: 0,
        explanation: "SF No. 4 is the correct answer.",
      },
      {
        question: "What works are carried out under Plan Head-51?",
        options: [
          "Staff Quarters",
          "Gauge Conversion",
          "Electrification",
          "Passenger Amenities",
        ],
        correct: 0,
        explanation: "Staff Quarters is the correct answer.",
      },
      {
        question: "The additional pension added after completion of 87 years of age is ______ of the basic pension.",
        options: [
          "20%",
          "30%",
          "40%",
          "25%",
        ],
        correct: 1,
        explanation: "30% is the correct answer.",
      },
      {
        question: "From which source is the Funeral Advance recovered?",
        options: [
          "From pension",
          "It is not recovered",
          "From monthly salary",
          "From settlement dues",
        ],
        correct: 3,
        explanation: "From settlement dues is the correct answer.",
      },
      {
        question: "Suspense Grant of Railways includes:",
        options: [
          "Manufacture Suspense",
          "All of the given options",
          "Miscellaneous Advance (Capital)",
          "Stores Suspense",
        ],
        correct: 1,
        explanation: "All of the given options is the correct answer.",
      },
      {
        question: "Psychological Aptitude Tests are used for recruitment of:",
        options: [
          "Assistant Loco Pilot and Station Master",
          "Goods Guard and Station Master",
          "All of the given options",
          "Goods Guard and Assistant Loco Pilot",
        ],
        correct: 0,
        explanation: "Assistant Loco Pilot and Station Master is the correct answer.",
      },
      {
        question: "Family Pension for Central Government employees was introduced in the year:",
        options: [
          "1980",
          "1964",
          "1986",
          "1975",
        ],
        correct: 1,
        explanation: "1964 is the correct answer.",
      },
      {
        question: "When does the probation period commence for a newly recruited Group 'C' employee whose initial training is prescribed?",
        options: [
          "Date of reporting to Railways",
          "Date of reporting for training",
          "None of the above",
          "On absorption to the working post after successful completion of training",
        ],
        correct: 3,
        explanation: "On absorption to the working post after successful completion of training is the correct answer.",
      },
      {
        question: "When a railway employee is transferred to a station more than 2000 km away, what is the joining time? Statements: (A) 15 days joining time if transferred beyond 2000 km. (B) 12 days joining time if travelling by flight. ---",
        options: [
          "Only (B) is correct",
          "Both are incorrect",
          "Only (A) is correct",
          "Both are correct",
        ],
        correct: 3,
        explanation: "Both are correct is the correct answer.",
      },
      {
        question: "In case of confirmed reservation, a Pass/PTO holder can make a maximum of ______ reservations, provided the earlier one is cancelled before preparation of the first reservation chart.",
        options: [
          "3",
          "2",
          "No limit",
          "4",
        ],
        correct: 0,
        explanation: "3 is the correct answer.",
      },
      {
        question: "Who collects the IGST?",
        options: [
          "Central Government",
          "Both State and Centre equally",
          "Local Municipality",
          "State Government",
        ],
        correct: 0,
        explanation: "Central Government is the correct answer.",
      },
      {
        question: "Leave encashment to serving railway servants is booked to which Primary Unit?",
        options: [
          "PU-20 of respective Abstracts",
          "PU-25 of Abstract L",
          "PU-02 of Abstract L",
          "PU-25 of respective Abstracts",
        ],
        correct: 0,
        explanation: "PU-20 of respective Abstracts is the correct answer.",
      },
      {
        question: "Reimbursement of medical expenses in Indian Railways is now booked under which Revenue Primary Unit (PU)?",
        options: [
          "PU-12",
          "PU-32",
          "PU-26",
          "PU-22",
        ],
        correct: 2,
        explanation: "PU-26 is the correct answer.",
      },
      {
        question: "What is the revised duration for the Induction Training of ALPs in Dual Traction?",
        options: [
          "122 days",
          "151 days",
          "90 days",
          "109 days",
        ],
        correct: 3  ,
        explanation: "109 days is the correct answer.",
      },
      {
        question: "As per extant policy instructions, the codal life of a laptop provided to Gazetted Officers is:",
        options: [
          "5 years",
          "4 years",
          "2 years",
          "3 years",
        ],
        correct: 1,
        explanation: "4 years is the correct answer.",
      },
      {
        question: "The Report of the Comptroller and Auditor General of India is considered by which Parliamentary Committee?",
        options: [
          "Estimates Committee",
          "Public Accounts Committee",
          "Business Advisory Committee",
          "Committee on Public Undertakings",
        ],
        correct: 1,
        explanation: "Public Accounts Committee is the correct answer.",
      },
      {
        question: "(A) A school pass issued for a son above 18 years can include parents/guardians if the son is a Person with Disability (PwD). (B) A school pass issued for an unmarried daughter above 25 years cannot include her parents/guardians.",
        options: [
          "Only (B) is correct",
          "Both (A) & (B) are incorrect",
          "Only (A) is correct",
          "Both (A) & (B) are correct",
        ],
        correct: 2,
        explanation: "Only (A) is correct is the correct answer.",
      },
      {
        question: "Who is responsible for the custody of the Bank Guarantee submitted by contractors to Railways?",
        options: [
          "Executive Officer",
          "Engineering Officer",
          "Accounts Officer",
          "Audit Officer",
        ],
        correct: 2,
        explanation: "Accounts Officer is the correct answer.",
      },
      {
        question: "The performance of SC/ST employees promoted under the \"best amongst failed\" scheme is reviewed after:",
        options: [
          "15 months",
          "3 months",
          "One year",
          "Six months",
        ],
        correct: 3,
        explanation: "Six months is the correct answer.",
      },
      {
        question: "For granting Study Leave to a Railway Employee (except Railway Medical Service Officers), the employee should have completed at least:",
        options: [
          "5 years",
          "7 years",
          "3 years",
          "2 years",
        ],
        correct: 0,
        explanation: "5 years is the correct answer.",
      },
      {
        question: "An officer must submit representation against APAR within ______ days from the date it is communicated/disclosed through SPARROW Portal.",
        options: [
          "45 days",
          "15 days",
          "30 days",
          "60 days",
        ],
        correct: 1,
        explanation: "15 days is the correct answer.",
      },
      {
        question: "Pick the correct order in accounting classification for works.",
        options: [
          "Plan Head → Source → Sub Head → Primary Unit",
          "Plan Head → Sub Head → Source → Primary Unit",
          "Source → Plan Head → Sub Head → Primary Unit",
          "Source → Sub Head → Plan Head → Primary Unit",
        ],
        correct: 2,
        explanation: "Source → Plan Head → Sub Head → Primary Unit is the correct answer.",
      },
      {
        question: "Quarter retention on transfer is permitted till ______ when the child is studying in 11th standard.",
        options: [
          "None of the given options",
          "Two months",
          "End of academic year for 11th standard",
          "End of academic year for 12th standard",
        ],
        correct: 2,
        explanation: "End of academic year for 11th standard is the correct answer.",
      },
      {
        question: "What does Rule 25 of the Railway Servants (D&A) Rules, 1968 deal with?",
        options: [
          "Revision",
          "Inquiry",
          "Penalties",
          "Appeal",
        ],
        correct: 0,
        explanation: "Revision is the correct answer.",
      },
      {
        question: "In Revenue Allocation, the last two digits represent:",
        options: [
          "Primary Unit",
          "Year",
          "Month",
          "Demand Number",
        ],
        correct: 0,
        explanation: "Primary Unit is the correct answer.",
      },
      {
        question: "What is the full form of ENPV in the context of Railway project appraisal?",
        options: [
          "Economic Net Present Value",
          "Estimated Net Present Value",
          "Essential Net Present Value",
          "Expected Net Present Value",
        ],
        correct: 0,
        explanation: "Economic Net Present Value is the correct answer.",
      },
      {
        question: "(A) Transport Allowance is a part of the taxable income of an employee. (B) Transport Allowance is not admissible to a Railway official who is away from Headquarters on duty from 2 January 2026 to 2 February 2026.",
        options: [
          "Both are correct",
          "Only (B) is correct",
          "Both are incorrect",
          "Only (A) is correct",
        ],
        correct: 3,
        explanation: "Only (A) is correct is the correct answer.",
      },
      {
        question: "Which of the following is not defined as a penalty under the Railway Servants (D&A) Rules, 1968?",
        options: [
          "Censure",
          "Transfer to outstation",
          "Stoppage of Pass/PTO",
          "Withholding of promotion",
        ],
        correct: 1,
        explanation: "Transfer to outstation is the correct answer.",
      },
      {
        question: "(A) A censure and a written warning are both minor penalties under the D&A Rules. (B) An employee dismissed from service is ineligible for all future employment under the Government.",
        options: [
          "Both are incorrect",
          "Only (B) is correct",
          "Only (A) is correct",
          "Both are correct",
        ],
        correct: 1,
        explanation: "Only (B) is correct is the correct answer.",
      },
      {
        question: "Master Circular Number dealing with deputation is:",
        options: [
          "65",
          "57",
          "38",
          "42",
        ],
        correct: 1,
        explanation: "57 is the correct answer.",
      },
      {
        question: "Exchequer Control is:",
        options: [
          "None of the given options",
          "Self-imposed expenditure discipline against the cash content of budget allotment",
          "Imposing restrictions on drawing limits on banks",
          "Self-imposed expenditure discipline against budget allotment ], } }",
        ],
        correct: 1,
        explanation: "Self-imposed expenditure discipline against the cash content of budget allotment is the correct answer.",
      },
    ],
  },
}
